// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/stu3/resources.proto

package com.google.fhir.stu3.proto;

public interface AccountOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:google.fhir.stu3.proto.Account)
    com.google.protobuf.MessageOrBuilder {

  /**
   *
   *
   * <pre>
   * Logical id of this artifact
   * </pre>
   *
   * <code>.google.fhir.stu3.proto.Id id = 1;</code>
   *
   * @return Whether the id field is set.
   */
  boolean hasId();
  /**
   *
   *
   * <pre>
   * Logical id of this artifact
   * </pre>
   *
   * <code>.google.fhir.stu3.proto.Id id = 1;</code>
   *
   * @return The id.
   */
  com.google.fhir.stu3.proto.Id getId();
  /**
   *
   *
   * <pre>
   * Logical id of this artifact
   * </pre>
   *
   * <code>.google.fhir.stu3.proto.Id id = 1;</code>
   */
  com.google.fhir.stu3.proto.IdOrBuilder getIdOrBuilder();

  /**
   *
   *
   * <pre>
   * Metadata about the resource
   * </pre>
   *
   * <code>.google.fhir.stu3.proto.Meta meta = 2;</code>
   *
   * @return Whether the meta field is set.
   */
  boolean hasMeta();
  /**
   *
   *
   * <pre>
   * Metadata about the resource
   * </pre>
   *
   * <code>.google.fhir.stu3.proto.Meta meta = 2;</code>
   *
   * @return The meta.
   */
  com.google.fhir.stu3.proto.Meta getMeta();
  /**
   *
   *
   * <pre>
   * Metadata about the resource
   * </pre>
   *
   * <code>.google.fhir.stu3.proto.Meta meta = 2;</code>
   */
  com.google.fhir.stu3.proto.MetaOrBuilder getMetaOrBuilder();

  /**
   *
   *
   * <pre>
   * A set of rules under which this content was created
   * </pre>
   *
   * <code>.google.fhir.stu3.proto.Uri implicit_rules = 3;</code>
   *
   * @return Whether the implicitRules field is set.
   */
  boolean hasImplicitRules();
  /**
   *
   *
   * <pre>
   * A set of rules under which this content was created
   * </pre>
   *
   * <code>.google.fhir.stu3.proto.Uri implicit_rules = 3;</code>
   *
   * @return The implicitRules.
   */
  com.google.fhir.stu3.proto.Uri getImplicitRules();
  /**
   *
   *
   * <pre>
   * A set of rules under which this content was created
   * </pre>
   *
   * <code>.google.fhir.stu3.proto.Uri implicit_rules = 3;</code>
   */
  com.google.fhir.stu3.proto.UriOrBuilder getImplicitRulesOrBuilder();

  /**
   *
   *
   * <pre>
   * Language of the resource content
   * </pre>
   *
   * <code>.google.fhir.stu3.proto.LanguageCode language = 4;</code>
   *
   * @return Whether the language field is set.
   */
  boolean hasLanguage();
  /**
   *
   *
   * <pre>
   * Language of the resource content
   * </pre>
   *
   * <code>.google.fhir.stu3.proto.LanguageCode language = 4;</code>
   *
   * @return The language.
   */
  com.google.fhir.stu3.proto.LanguageCode getLanguage();
  /**
   *
   *
   * <pre>
   * Language of the resource content
   * </pre>
   *
   * <code>.google.fhir.stu3.proto.LanguageCode language = 4;</code>
   */
  com.google.fhir.stu3.proto.LanguageCodeOrBuilder getLanguageOrBuilder();

  /**
   *
   *
   * <pre>
   * Text summary of the resource, for human interpretation
   * </pre>
   *
   * <code>.google.fhir.stu3.proto.Narrative text = 5;</code>
   *
   * @return Whether the text field is set.
   */
  boolean hasText();
  /**
   *
   *
   * <pre>
   * Text summary of the resource, for human interpretation
   * </pre>
   *
   * <code>.google.fhir.stu3.proto.Narrative text = 5;</code>
   *
   * @return The text.
   */
  com.google.fhir.stu3.proto.Narrative getText();
  /**
   *
   *
   * <pre>
   * Text summary of the resource, for human interpretation
   * </pre>
   *
   * <code>.google.fhir.stu3.proto.Narrative text = 5;</code>
   */
  com.google.fhir.stu3.proto.NarrativeOrBuilder getTextOrBuilder();

  /**
   *
   *
   * <pre>
   * Contained, inline Resources
   * </pre>
   *
   * <code>repeated .google.fhir.stu3.proto.ContainedResource contained = 6;</code>
   */
  java.util.List<com.google.fhir.stu3.proto.ContainedResource> getContainedList();
  /**
   *
   *
   * <pre>
   * Contained, inline Resources
   * </pre>
   *
   * <code>repeated .google.fhir.stu3.proto.ContainedResource contained = 6;</code>
   */
  com.google.fhir.stu3.proto.ContainedResource getContained(int index);
  /**
   *
   *
   * <pre>
   * Contained, inline Resources
   * </pre>
   *
   * <code>repeated .google.fhir.stu3.proto.ContainedResource contained = 6;</code>
   */
  int getContainedCount();
  /**
   *
   *
   * <pre>
   * Contained, inline Resources
   * </pre>
   *
   * <code>repeated .google.fhir.stu3.proto.ContainedResource contained = 6;</code>
   */
  java.util.List<? extends com.google.fhir.stu3.proto.ContainedResourceOrBuilder>
      getContainedOrBuilderList();
  /**
   *
   *
   * <pre>
   * Contained, inline Resources
   * </pre>
   *
   * <code>repeated .google.fhir.stu3.proto.ContainedResource contained = 6;</code>
   */
  com.google.fhir.stu3.proto.ContainedResourceOrBuilder getContainedOrBuilder(int index);

  /**
   *
   *
   * <pre>
   * Additional Content defined by implementations
   * </pre>
   *
   * <code>repeated .google.fhir.stu3.proto.Extension extension = 7;</code>
   */
  java.util.List<com.google.fhir.stu3.proto.Extension> getExtensionList();
  /**
   *
   *
   * <pre>
   * Additional Content defined by implementations
   * </pre>
   *
   * <code>repeated .google.fhir.stu3.proto.Extension extension = 7;</code>
   */
  com.google.fhir.stu3.proto.Extension getExtension(int index);
  /**
   *
   *
   * <pre>
   * Additional Content defined by implementations
   * </pre>
   *
   * <code>repeated .google.fhir.stu3.proto.Extension extension = 7;</code>
   */
  int getExtensionCount();
  /**
   *
   *
   * <pre>
   * Additional Content defined by implementations
   * </pre>
   *
   * <code>repeated .google.fhir.stu3.proto.Extension extension = 7;</code>
   */
  java.util.List<? extends com.google.fhir.stu3.proto.ExtensionOrBuilder>
      getExtensionOrBuilderList();
  /**
   *
   *
   * <pre>
   * Additional Content defined by implementations
   * </pre>
   *
   * <code>repeated .google.fhir.stu3.proto.Extension extension = 7;</code>
   */
  com.google.fhir.stu3.proto.ExtensionOrBuilder getExtensionOrBuilder(int index);

  /**
   *
   *
   * <pre>
   * Extensions that cannot be ignored
   * </pre>
   *
   * <code>repeated .google.fhir.stu3.proto.Extension modifier_extension = 8;</code>
   */
  java.util.List<com.google.fhir.stu3.proto.Extension> getModifierExtensionList();
  /**
   *
   *
   * <pre>
   * Extensions that cannot be ignored
   * </pre>
   *
   * <code>repeated .google.fhir.stu3.proto.Extension modifier_extension = 8;</code>
   */
  com.google.fhir.stu3.proto.Extension getModifierExtension(int index);
  /**
   *
   *
   * <pre>
   * Extensions that cannot be ignored
   * </pre>
   *
   * <code>repeated .google.fhir.stu3.proto.Extension modifier_extension = 8;</code>
   */
  int getModifierExtensionCount();
  /**
   *
   *
   * <pre>
   * Extensions that cannot be ignored
   * </pre>
   *
   * <code>repeated .google.fhir.stu3.proto.Extension modifier_extension = 8;</code>
   */
  java.util.List<? extends com.google.fhir.stu3.proto.ExtensionOrBuilder>
      getModifierExtensionOrBuilderList();
  /**
   *
   *
   * <pre>
   * Extensions that cannot be ignored
   * </pre>
   *
   * <code>repeated .google.fhir.stu3.proto.Extension modifier_extension = 8;</code>
   */
  com.google.fhir.stu3.proto.ExtensionOrBuilder getModifierExtensionOrBuilder(int index);

  /**
   *
   *
   * <pre>
   * Account number
   * </pre>
   *
   * <code>repeated .google.fhir.stu3.proto.Identifier identifier = 9;</code>
   */
  java.util.List<com.google.fhir.stu3.proto.Identifier> getIdentifierList();
  /**
   *
   *
   * <pre>
   * Account number
   * </pre>
   *
   * <code>repeated .google.fhir.stu3.proto.Identifier identifier = 9;</code>
   */
  com.google.fhir.stu3.proto.Identifier getIdentifier(int index);
  /**
   *
   *
   * <pre>
   * Account number
   * </pre>
   *
   * <code>repeated .google.fhir.stu3.proto.Identifier identifier = 9;</code>
   */
  int getIdentifierCount();
  /**
   *
   *
   * <pre>
   * Account number
   * </pre>
   *
   * <code>repeated .google.fhir.stu3.proto.Identifier identifier = 9;</code>
   */
  java.util.List<? extends com.google.fhir.stu3.proto.IdentifierOrBuilder>
      getIdentifierOrBuilderList();
  /**
   *
   *
   * <pre>
   * Account number
   * </pre>
   *
   * <code>repeated .google.fhir.stu3.proto.Identifier identifier = 9;</code>
   */
  com.google.fhir.stu3.proto.IdentifierOrBuilder getIdentifierOrBuilder(int index);

  /**
   *
   *
   * <pre>
   * active | inactive | entered-in-error
   * </pre>
   *
   * <code>.google.fhir.stu3.proto.AccountStatusCode status = 10;</code>
   *
   * @return Whether the status field is set.
   */
  boolean hasStatus();
  /**
   *
   *
   * <pre>
   * active | inactive | entered-in-error
   * </pre>
   *
   * <code>.google.fhir.stu3.proto.AccountStatusCode status = 10;</code>
   *
   * @return The status.
   */
  com.google.fhir.stu3.proto.AccountStatusCode getStatus();
  /**
   *
   *
   * <pre>
   * active | inactive | entered-in-error
   * </pre>
   *
   * <code>.google.fhir.stu3.proto.AccountStatusCode status = 10;</code>
   */
  com.google.fhir.stu3.proto.AccountStatusCodeOrBuilder getStatusOrBuilder();

  /**
   *
   *
   * <pre>
   * E.g. patient, expense, depreciation
   * </pre>
   *
   * <code>.google.fhir.stu3.proto.CodeableConcept type = 11;</code>
   *
   * @return Whether the type field is set.
   */
  boolean hasType();
  /**
   *
   *
   * <pre>
   * E.g. patient, expense, depreciation
   * </pre>
   *
   * <code>.google.fhir.stu3.proto.CodeableConcept type = 11;</code>
   *
   * @return The type.
   */
  com.google.fhir.stu3.proto.CodeableConcept getType();
  /**
   *
   *
   * <pre>
   * E.g. patient, expense, depreciation
   * </pre>
   *
   * <code>.google.fhir.stu3.proto.CodeableConcept type = 11;</code>
   */
  com.google.fhir.stu3.proto.CodeableConceptOrBuilder getTypeOrBuilder();

  /**
   *
   *
   * <pre>
   * Human-readable label
   * </pre>
   *
   * <code>.google.fhir.stu3.proto.String name = 12;</code>
   *
   * @return Whether the name field is set.
   */
  boolean hasName();
  /**
   *
   *
   * <pre>
   * Human-readable label
   * </pre>
   *
   * <code>.google.fhir.stu3.proto.String name = 12;</code>
   *
   * @return The name.
   */
  com.google.fhir.stu3.proto.String getName();
  /**
   *
   *
   * <pre>
   * Human-readable label
   * </pre>
   *
   * <code>.google.fhir.stu3.proto.String name = 12;</code>
   */
  com.google.fhir.stu3.proto.StringOrBuilder getNameOrBuilder();

  /**
   *
   *
   * <pre>
   * What is account tied to?
   * </pre>
   *
   * <code>
   * .google.fhir.stu3.proto.Reference subject = 13 [(.google.fhir.proto.valid_reference_type) = "Patient", (.google.fhir.proto.valid_reference_type) = "Device", (.google.fhir.proto.valid_reference_type) = "Practitioner", (.google.fhir.proto.valid_reference_type) = "Location", (.google.fhir.proto.valid_reference_type) = "HealthcareService", (.google.fhir.proto.valid_reference_type) = "Organization"];
   * </code>
   *
   * @return Whether the subject field is set.
   */
  boolean hasSubject();
  /**
   *
   *
   * <pre>
   * What is account tied to?
   * </pre>
   *
   * <code>
   * .google.fhir.stu3.proto.Reference subject = 13 [(.google.fhir.proto.valid_reference_type) = "Patient", (.google.fhir.proto.valid_reference_type) = "Device", (.google.fhir.proto.valid_reference_type) = "Practitioner", (.google.fhir.proto.valid_reference_type) = "Location", (.google.fhir.proto.valid_reference_type) = "HealthcareService", (.google.fhir.proto.valid_reference_type) = "Organization"];
   * </code>
   *
   * @return The subject.
   */
  com.google.fhir.stu3.proto.Reference getSubject();
  /**
   *
   *
   * <pre>
   * What is account tied to?
   * </pre>
   *
   * <code>
   * .google.fhir.stu3.proto.Reference subject = 13 [(.google.fhir.proto.valid_reference_type) = "Patient", (.google.fhir.proto.valid_reference_type) = "Device", (.google.fhir.proto.valid_reference_type) = "Practitioner", (.google.fhir.proto.valid_reference_type) = "Location", (.google.fhir.proto.valid_reference_type) = "HealthcareService", (.google.fhir.proto.valid_reference_type) = "Organization"];
   * </code>
   */
  com.google.fhir.stu3.proto.ReferenceOrBuilder getSubjectOrBuilder();

  /**
   *
   *
   * <pre>
   * Transaction window
   * </pre>
   *
   * <code>.google.fhir.stu3.proto.Period period = 14;</code>
   *
   * @return Whether the period field is set.
   */
  boolean hasPeriod();
  /**
   *
   *
   * <pre>
   * Transaction window
   * </pre>
   *
   * <code>.google.fhir.stu3.proto.Period period = 14;</code>
   *
   * @return The period.
   */
  com.google.fhir.stu3.proto.Period getPeriod();
  /**
   *
   *
   * <pre>
   * Transaction window
   * </pre>
   *
   * <code>.google.fhir.stu3.proto.Period period = 14;</code>
   */
  com.google.fhir.stu3.proto.PeriodOrBuilder getPeriodOrBuilder();

  /**
   *
   *
   * <pre>
   * Time window that transactions may be posted to this account
   * </pre>
   *
   * <code>.google.fhir.stu3.proto.Period active = 15;</code>
   *
   * @return Whether the active field is set.
   */
  boolean hasActive();
  /**
   *
   *
   * <pre>
   * Time window that transactions may be posted to this account
   * </pre>
   *
   * <code>.google.fhir.stu3.proto.Period active = 15;</code>
   *
   * @return The active.
   */
  com.google.fhir.stu3.proto.Period getActive();
  /**
   *
   *
   * <pre>
   * Time window that transactions may be posted to this account
   * </pre>
   *
   * <code>.google.fhir.stu3.proto.Period active = 15;</code>
   */
  com.google.fhir.stu3.proto.PeriodOrBuilder getActiveOrBuilder();

  /**
   *
   *
   * <pre>
   * How much is in account?
   * </pre>
   *
   * <code>.google.fhir.stu3.proto.Money balance = 16;</code>
   *
   * @return Whether the balance field is set.
   */
  boolean hasBalance();
  /**
   *
   *
   * <pre>
   * How much is in account?
   * </pre>
   *
   * <code>.google.fhir.stu3.proto.Money balance = 16;</code>
   *
   * @return The balance.
   */
  com.google.fhir.stu3.proto.Money getBalance();
  /**
   *
   *
   * <pre>
   * How much is in account?
   * </pre>
   *
   * <code>.google.fhir.stu3.proto.Money balance = 16;</code>
   */
  com.google.fhir.stu3.proto.MoneyOrBuilder getBalanceOrBuilder();

  /** <code>repeated .google.fhir.stu3.proto.Account.Coverage coverage = 17;</code> */
  java.util.List<com.google.fhir.stu3.proto.Account.Coverage> getCoverageList();
  /** <code>repeated .google.fhir.stu3.proto.Account.Coverage coverage = 17;</code> */
  com.google.fhir.stu3.proto.Account.Coverage getCoverage(int index);
  /** <code>repeated .google.fhir.stu3.proto.Account.Coverage coverage = 17;</code> */
  int getCoverageCount();
  /** <code>repeated .google.fhir.stu3.proto.Account.Coverage coverage = 17;</code> */
  java.util.List<? extends com.google.fhir.stu3.proto.Account.CoverageOrBuilder>
      getCoverageOrBuilderList();
  /** <code>repeated .google.fhir.stu3.proto.Account.Coverage coverage = 17;</code> */
  com.google.fhir.stu3.proto.Account.CoverageOrBuilder getCoverageOrBuilder(int index);

  /**
   *
   *
   * <pre>
   * Who is responsible?
   * </pre>
   *
   * <code>
   * .google.fhir.stu3.proto.Reference owner = 18 [(.google.fhir.proto.valid_reference_type) = "Organization"];
   * </code>
   *
   * @return Whether the owner field is set.
   */
  boolean hasOwner();
  /**
   *
   *
   * <pre>
   * Who is responsible?
   * </pre>
   *
   * <code>
   * .google.fhir.stu3.proto.Reference owner = 18 [(.google.fhir.proto.valid_reference_type) = "Organization"];
   * </code>
   *
   * @return The owner.
   */
  com.google.fhir.stu3.proto.Reference getOwner();
  /**
   *
   *
   * <pre>
   * Who is responsible?
   * </pre>
   *
   * <code>
   * .google.fhir.stu3.proto.Reference owner = 18 [(.google.fhir.proto.valid_reference_type) = "Organization"];
   * </code>
   */
  com.google.fhir.stu3.proto.ReferenceOrBuilder getOwnerOrBuilder();

  /**
   *
   *
   * <pre>
   * Explanation of purpose/use
   * </pre>
   *
   * <code>.google.fhir.stu3.proto.String description = 19;</code>
   *
   * @return Whether the description field is set.
   */
  boolean hasDescription();
  /**
   *
   *
   * <pre>
   * Explanation of purpose/use
   * </pre>
   *
   * <code>.google.fhir.stu3.proto.String description = 19;</code>
   *
   * @return The description.
   */
  com.google.fhir.stu3.proto.String getDescription();
  /**
   *
   *
   * <pre>
   * Explanation of purpose/use
   * </pre>
   *
   * <code>.google.fhir.stu3.proto.String description = 19;</code>
   */
  com.google.fhir.stu3.proto.StringOrBuilder getDescriptionOrBuilder();

  /** <code>repeated .google.fhir.stu3.proto.Account.Guarantor guarantor = 20;</code> */
  java.util.List<com.google.fhir.stu3.proto.Account.Guarantor> getGuarantorList();
  /** <code>repeated .google.fhir.stu3.proto.Account.Guarantor guarantor = 20;</code> */
  com.google.fhir.stu3.proto.Account.Guarantor getGuarantor(int index);
  /** <code>repeated .google.fhir.stu3.proto.Account.Guarantor guarantor = 20;</code> */
  int getGuarantorCount();
  /** <code>repeated .google.fhir.stu3.proto.Account.Guarantor guarantor = 20;</code> */
  java.util.List<? extends com.google.fhir.stu3.proto.Account.GuarantorOrBuilder>
      getGuarantorOrBuilderList();
  /** <code>repeated .google.fhir.stu3.proto.Account.Guarantor guarantor = 20;</code> */
  com.google.fhir.stu3.proto.Account.GuarantorOrBuilder getGuarantorOrBuilder(int index);
}
