// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/google/fhir/proto/stu3/extensions.proto

package com.google.fhir.stu3.proto;

/**
 * <pre>
 * Auto-generated from StructureDefinition for minValue.
 * Must be &gt;= this value.
 * See http://hl7.org/fhir/StructureDefinition/minValue
 * </pre>
 *
 * Protobuf type {@code google.fhir.stu3.proto.QuestionnaireMinValue}
 */
public final class QuestionnaireMinValue extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:google.fhir.stu3.proto.QuestionnaireMinValue)
    QuestionnaireMinValueOrBuilder {
private static final long serialVersionUID = 0L;
  // Use QuestionnaireMinValue.newBuilder() to construct.
  private QuestionnaireMinValue(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private QuestionnaireMinValue() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new QuestionnaireMinValue();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private QuestionnaireMinValue(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.google.fhir.stu3.proto.String.Builder subBuilder = null;
            if (id_ != null) {
              subBuilder = id_.toBuilder();
            }
            id_ = input.readMessage(com.google.fhir.stu3.proto.String.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(id_);
              id_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            com.google.fhir.stu3.proto.QuestionnaireMinValue.Value.Builder subBuilder = null;
            if (value_ != null) {
              subBuilder = value_.toBuilder();
            }
            value_ = input.readMessage(com.google.fhir.stu3.proto.QuestionnaireMinValue.Value.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(value_);
              value_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.fhir.stu3.proto.Extensions.internal_static_google_fhir_stu3_proto_QuestionnaireMinValue_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.fhir.stu3.proto.Extensions.internal_static_google_fhir_stu3_proto_QuestionnaireMinValue_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.fhir.stu3.proto.QuestionnaireMinValue.class, com.google.fhir.stu3.proto.QuestionnaireMinValue.Builder.class);
  }

  public interface ValueOrBuilder extends
      // @@protoc_insertion_point(interface_extends:google.fhir.stu3.proto.QuestionnaireMinValue.Value)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.google.fhir.stu3.proto.Date date = 1;</code>
     * @return Whether the date field is set.
     */
    boolean hasDate();
    /**
     * <code>.google.fhir.stu3.proto.Date date = 1;</code>
     * @return The date.
     */
    com.google.fhir.stu3.proto.Date getDate();
    /**
     * <code>.google.fhir.stu3.proto.Date date = 1;</code>
     */
    com.google.fhir.stu3.proto.DateOrBuilder getDateOrBuilder();

    /**
     * <code>.google.fhir.stu3.proto.DateTime date_time = 2;</code>
     * @return Whether the dateTime field is set.
     */
    boolean hasDateTime();
    /**
     * <code>.google.fhir.stu3.proto.DateTime date_time = 2;</code>
     * @return The dateTime.
     */
    com.google.fhir.stu3.proto.DateTime getDateTime();
    /**
     * <code>.google.fhir.stu3.proto.DateTime date_time = 2;</code>
     */
    com.google.fhir.stu3.proto.DateTimeOrBuilder getDateTimeOrBuilder();

    /**
     * <code>.google.fhir.stu3.proto.Time time = 3;</code>
     * @return Whether the time field is set.
     */
    boolean hasTime();
    /**
     * <code>.google.fhir.stu3.proto.Time time = 3;</code>
     * @return The time.
     */
    com.google.fhir.stu3.proto.Time getTime();
    /**
     * <code>.google.fhir.stu3.proto.Time time = 3;</code>
     */
    com.google.fhir.stu3.proto.TimeOrBuilder getTimeOrBuilder();

    /**
     * <code>.google.fhir.stu3.proto.Instant instant = 4;</code>
     * @return Whether the instant field is set.
     */
    boolean hasInstant();
    /**
     * <code>.google.fhir.stu3.proto.Instant instant = 4;</code>
     * @return The instant.
     */
    com.google.fhir.stu3.proto.Instant getInstant();
    /**
     * <code>.google.fhir.stu3.proto.Instant instant = 4;</code>
     */
    com.google.fhir.stu3.proto.InstantOrBuilder getInstantOrBuilder();

    /**
     * <code>.google.fhir.stu3.proto.Decimal decimal = 5;</code>
     * @return Whether the decimal field is set.
     */
    boolean hasDecimal();
    /**
     * <code>.google.fhir.stu3.proto.Decimal decimal = 5;</code>
     * @return The decimal.
     */
    com.google.fhir.stu3.proto.Decimal getDecimal();
    /**
     * <code>.google.fhir.stu3.proto.Decimal decimal = 5;</code>
     */
    com.google.fhir.stu3.proto.DecimalOrBuilder getDecimalOrBuilder();

    /**
     * <code>.google.fhir.stu3.proto.Integer integer = 6;</code>
     * @return Whether the integer field is set.
     */
    boolean hasInteger();
    /**
     * <code>.google.fhir.stu3.proto.Integer integer = 6;</code>
     * @return The integer.
     */
    com.google.fhir.stu3.proto.Integer getInteger();
    /**
     * <code>.google.fhir.stu3.proto.Integer integer = 6;</code>
     */
    com.google.fhir.stu3.proto.IntegerOrBuilder getIntegerOrBuilder();

    public com.google.fhir.stu3.proto.QuestionnaireMinValue.Value.ValueCase getValueCase();
  }
  /**
   * <pre>
   * Value of extension
   * </pre>
   *
   * Protobuf type {@code google.fhir.stu3.proto.QuestionnaireMinValue.Value}
   */
  public static final class Value extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:google.fhir.stu3.proto.QuestionnaireMinValue.Value)
      ValueOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Value.newBuilder() to construct.
    private Value(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Value() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Value();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Value(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.fhir.stu3.proto.Date.Builder subBuilder = null;
              if (valueCase_ == 1) {
                subBuilder = ((com.google.fhir.stu3.proto.Date) value_).toBuilder();
              }
              value_ =
                  input.readMessage(com.google.fhir.stu3.proto.Date.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.google.fhir.stu3.proto.Date) value_);
                value_ = subBuilder.buildPartial();
              }
              valueCase_ = 1;
              break;
            }
            case 18: {
              com.google.fhir.stu3.proto.DateTime.Builder subBuilder = null;
              if (valueCase_ == 2) {
                subBuilder = ((com.google.fhir.stu3.proto.DateTime) value_).toBuilder();
              }
              value_ =
                  input.readMessage(com.google.fhir.stu3.proto.DateTime.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.google.fhir.stu3.proto.DateTime) value_);
                value_ = subBuilder.buildPartial();
              }
              valueCase_ = 2;
              break;
            }
            case 26: {
              com.google.fhir.stu3.proto.Time.Builder subBuilder = null;
              if (valueCase_ == 3) {
                subBuilder = ((com.google.fhir.stu3.proto.Time) value_).toBuilder();
              }
              value_ =
                  input.readMessage(com.google.fhir.stu3.proto.Time.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.google.fhir.stu3.proto.Time) value_);
                value_ = subBuilder.buildPartial();
              }
              valueCase_ = 3;
              break;
            }
            case 34: {
              com.google.fhir.stu3.proto.Instant.Builder subBuilder = null;
              if (valueCase_ == 4) {
                subBuilder = ((com.google.fhir.stu3.proto.Instant) value_).toBuilder();
              }
              value_ =
                  input.readMessage(com.google.fhir.stu3.proto.Instant.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.google.fhir.stu3.proto.Instant) value_);
                value_ = subBuilder.buildPartial();
              }
              valueCase_ = 4;
              break;
            }
            case 42: {
              com.google.fhir.stu3.proto.Decimal.Builder subBuilder = null;
              if (valueCase_ == 5) {
                subBuilder = ((com.google.fhir.stu3.proto.Decimal) value_).toBuilder();
              }
              value_ =
                  input.readMessage(com.google.fhir.stu3.proto.Decimal.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.google.fhir.stu3.proto.Decimal) value_);
                value_ = subBuilder.buildPartial();
              }
              valueCase_ = 5;
              break;
            }
            case 50: {
              com.google.fhir.stu3.proto.Integer.Builder subBuilder = null;
              if (valueCase_ == 6) {
                subBuilder = ((com.google.fhir.stu3.proto.Integer) value_).toBuilder();
              }
              value_ =
                  input.readMessage(com.google.fhir.stu3.proto.Integer.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.google.fhir.stu3.proto.Integer) value_);
                value_ = subBuilder.buildPartial();
              }
              valueCase_ = 6;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.fhir.stu3.proto.Extensions.internal_static_google_fhir_stu3_proto_QuestionnaireMinValue_Value_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.fhir.stu3.proto.Extensions.internal_static_google_fhir_stu3_proto_QuestionnaireMinValue_Value_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.fhir.stu3.proto.QuestionnaireMinValue.Value.class, com.google.fhir.stu3.proto.QuestionnaireMinValue.Value.Builder.class);
    }

    private int valueCase_ = 0;
    private java.lang.Object value_;
    public enum ValueCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      DATE(1),
      DATE_TIME(2),
      TIME(3),
      INSTANT(4),
      DECIMAL(5),
      INTEGER(6),
      VALUE_NOT_SET(0);
      private final int value;
      private ValueCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static ValueCase valueOf(int value) {
        return forNumber(value);
      }

      public static ValueCase forNumber(int value) {
        switch (value) {
          case 1: return DATE;
          case 2: return DATE_TIME;
          case 3: return TIME;
          case 4: return INSTANT;
          case 5: return DECIMAL;
          case 6: return INTEGER;
          case 0: return VALUE_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public ValueCase
    getValueCase() {
      return ValueCase.forNumber(
          valueCase_);
    }

    public static final int DATE_FIELD_NUMBER = 1;
    /**
     * <code>.google.fhir.stu3.proto.Date date = 1;</code>
     * @return Whether the date field is set.
     */
    @java.lang.Override
    public boolean hasDate() {
      return valueCase_ == 1;
    }
    /**
     * <code>.google.fhir.stu3.proto.Date date = 1;</code>
     * @return The date.
     */
    @java.lang.Override
    public com.google.fhir.stu3.proto.Date getDate() {
      if (valueCase_ == 1) {
         return (com.google.fhir.stu3.proto.Date) value_;
      }
      return com.google.fhir.stu3.proto.Date.getDefaultInstance();
    }
    /**
     * <code>.google.fhir.stu3.proto.Date date = 1;</code>
     */
    @java.lang.Override
    public com.google.fhir.stu3.proto.DateOrBuilder getDateOrBuilder() {
      if (valueCase_ == 1) {
         return (com.google.fhir.stu3.proto.Date) value_;
      }
      return com.google.fhir.stu3.proto.Date.getDefaultInstance();
    }

    public static final int DATE_TIME_FIELD_NUMBER = 2;
    /**
     * <code>.google.fhir.stu3.proto.DateTime date_time = 2;</code>
     * @return Whether the dateTime field is set.
     */
    @java.lang.Override
    public boolean hasDateTime() {
      return valueCase_ == 2;
    }
    /**
     * <code>.google.fhir.stu3.proto.DateTime date_time = 2;</code>
     * @return The dateTime.
     */
    @java.lang.Override
    public com.google.fhir.stu3.proto.DateTime getDateTime() {
      if (valueCase_ == 2) {
         return (com.google.fhir.stu3.proto.DateTime) value_;
      }
      return com.google.fhir.stu3.proto.DateTime.getDefaultInstance();
    }
    /**
     * <code>.google.fhir.stu3.proto.DateTime date_time = 2;</code>
     */
    @java.lang.Override
    public com.google.fhir.stu3.proto.DateTimeOrBuilder getDateTimeOrBuilder() {
      if (valueCase_ == 2) {
         return (com.google.fhir.stu3.proto.DateTime) value_;
      }
      return com.google.fhir.stu3.proto.DateTime.getDefaultInstance();
    }

    public static final int TIME_FIELD_NUMBER = 3;
    /**
     * <code>.google.fhir.stu3.proto.Time time = 3;</code>
     * @return Whether the time field is set.
     */
    @java.lang.Override
    public boolean hasTime() {
      return valueCase_ == 3;
    }
    /**
     * <code>.google.fhir.stu3.proto.Time time = 3;</code>
     * @return The time.
     */
    @java.lang.Override
    public com.google.fhir.stu3.proto.Time getTime() {
      if (valueCase_ == 3) {
         return (com.google.fhir.stu3.proto.Time) value_;
      }
      return com.google.fhir.stu3.proto.Time.getDefaultInstance();
    }
    /**
     * <code>.google.fhir.stu3.proto.Time time = 3;</code>
     */
    @java.lang.Override
    public com.google.fhir.stu3.proto.TimeOrBuilder getTimeOrBuilder() {
      if (valueCase_ == 3) {
         return (com.google.fhir.stu3.proto.Time) value_;
      }
      return com.google.fhir.stu3.proto.Time.getDefaultInstance();
    }

    public static final int INSTANT_FIELD_NUMBER = 4;
    /**
     * <code>.google.fhir.stu3.proto.Instant instant = 4;</code>
     * @return Whether the instant field is set.
     */
    @java.lang.Override
    public boolean hasInstant() {
      return valueCase_ == 4;
    }
    /**
     * <code>.google.fhir.stu3.proto.Instant instant = 4;</code>
     * @return The instant.
     */
    @java.lang.Override
    public com.google.fhir.stu3.proto.Instant getInstant() {
      if (valueCase_ == 4) {
         return (com.google.fhir.stu3.proto.Instant) value_;
      }
      return com.google.fhir.stu3.proto.Instant.getDefaultInstance();
    }
    /**
     * <code>.google.fhir.stu3.proto.Instant instant = 4;</code>
     */
    @java.lang.Override
    public com.google.fhir.stu3.proto.InstantOrBuilder getInstantOrBuilder() {
      if (valueCase_ == 4) {
         return (com.google.fhir.stu3.proto.Instant) value_;
      }
      return com.google.fhir.stu3.proto.Instant.getDefaultInstance();
    }

    public static final int DECIMAL_FIELD_NUMBER = 5;
    /**
     * <code>.google.fhir.stu3.proto.Decimal decimal = 5;</code>
     * @return Whether the decimal field is set.
     */
    @java.lang.Override
    public boolean hasDecimal() {
      return valueCase_ == 5;
    }
    /**
     * <code>.google.fhir.stu3.proto.Decimal decimal = 5;</code>
     * @return The decimal.
     */
    @java.lang.Override
    public com.google.fhir.stu3.proto.Decimal getDecimal() {
      if (valueCase_ == 5) {
         return (com.google.fhir.stu3.proto.Decimal) value_;
      }
      return com.google.fhir.stu3.proto.Decimal.getDefaultInstance();
    }
    /**
     * <code>.google.fhir.stu3.proto.Decimal decimal = 5;</code>
     */
    @java.lang.Override
    public com.google.fhir.stu3.proto.DecimalOrBuilder getDecimalOrBuilder() {
      if (valueCase_ == 5) {
         return (com.google.fhir.stu3.proto.Decimal) value_;
      }
      return com.google.fhir.stu3.proto.Decimal.getDefaultInstance();
    }

    public static final int INTEGER_FIELD_NUMBER = 6;
    /**
     * <code>.google.fhir.stu3.proto.Integer integer = 6;</code>
     * @return Whether the integer field is set.
     */
    @java.lang.Override
    public boolean hasInteger() {
      return valueCase_ == 6;
    }
    /**
     * <code>.google.fhir.stu3.proto.Integer integer = 6;</code>
     * @return The integer.
     */
    @java.lang.Override
    public com.google.fhir.stu3.proto.Integer getInteger() {
      if (valueCase_ == 6) {
         return (com.google.fhir.stu3.proto.Integer) value_;
      }
      return com.google.fhir.stu3.proto.Integer.getDefaultInstance();
    }
    /**
     * <code>.google.fhir.stu3.proto.Integer integer = 6;</code>
     */
    @java.lang.Override
    public com.google.fhir.stu3.proto.IntegerOrBuilder getIntegerOrBuilder() {
      if (valueCase_ == 6) {
         return (com.google.fhir.stu3.proto.Integer) value_;
      }
      return com.google.fhir.stu3.proto.Integer.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (valueCase_ == 1) {
        output.writeMessage(1, (com.google.fhir.stu3.proto.Date) value_);
      }
      if (valueCase_ == 2) {
        output.writeMessage(2, (com.google.fhir.stu3.proto.DateTime) value_);
      }
      if (valueCase_ == 3) {
        output.writeMessage(3, (com.google.fhir.stu3.proto.Time) value_);
      }
      if (valueCase_ == 4) {
        output.writeMessage(4, (com.google.fhir.stu3.proto.Instant) value_);
      }
      if (valueCase_ == 5) {
        output.writeMessage(5, (com.google.fhir.stu3.proto.Decimal) value_);
      }
      if (valueCase_ == 6) {
        output.writeMessage(6, (com.google.fhir.stu3.proto.Integer) value_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (valueCase_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, (com.google.fhir.stu3.proto.Date) value_);
      }
      if (valueCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (com.google.fhir.stu3.proto.DateTime) value_);
      }
      if (valueCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (com.google.fhir.stu3.proto.Time) value_);
      }
      if (valueCase_ == 4) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, (com.google.fhir.stu3.proto.Instant) value_);
      }
      if (valueCase_ == 5) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, (com.google.fhir.stu3.proto.Decimal) value_);
      }
      if (valueCase_ == 6) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, (com.google.fhir.stu3.proto.Integer) value_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.google.fhir.stu3.proto.QuestionnaireMinValue.Value)) {
        return super.equals(obj);
      }
      com.google.fhir.stu3.proto.QuestionnaireMinValue.Value other = (com.google.fhir.stu3.proto.QuestionnaireMinValue.Value) obj;

      if (!getValueCase().equals(other.getValueCase())) return false;
      switch (valueCase_) {
        case 1:
          if (!getDate()
              .equals(other.getDate())) return false;
          break;
        case 2:
          if (!getDateTime()
              .equals(other.getDateTime())) return false;
          break;
        case 3:
          if (!getTime()
              .equals(other.getTime())) return false;
          break;
        case 4:
          if (!getInstant()
              .equals(other.getInstant())) return false;
          break;
        case 5:
          if (!getDecimal()
              .equals(other.getDecimal())) return false;
          break;
        case 6:
          if (!getInteger()
              .equals(other.getInteger())) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      switch (valueCase_) {
        case 1:
          hash = (37 * hash) + DATE_FIELD_NUMBER;
          hash = (53 * hash) + getDate().hashCode();
          break;
        case 2:
          hash = (37 * hash) + DATE_TIME_FIELD_NUMBER;
          hash = (53 * hash) + getDateTime().hashCode();
          break;
        case 3:
          hash = (37 * hash) + TIME_FIELD_NUMBER;
          hash = (53 * hash) + getTime().hashCode();
          break;
        case 4:
          hash = (37 * hash) + INSTANT_FIELD_NUMBER;
          hash = (53 * hash) + getInstant().hashCode();
          break;
        case 5:
          hash = (37 * hash) + DECIMAL_FIELD_NUMBER;
          hash = (53 * hash) + getDecimal().hashCode();
          break;
        case 6:
          hash = (37 * hash) + INTEGER_FIELD_NUMBER;
          hash = (53 * hash) + getInteger().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.google.fhir.stu3.proto.QuestionnaireMinValue.Value parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.fhir.stu3.proto.QuestionnaireMinValue.Value parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.fhir.stu3.proto.QuestionnaireMinValue.Value parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.fhir.stu3.proto.QuestionnaireMinValue.Value parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.fhir.stu3.proto.QuestionnaireMinValue.Value parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.fhir.stu3.proto.QuestionnaireMinValue.Value parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.fhir.stu3.proto.QuestionnaireMinValue.Value parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.google.fhir.stu3.proto.QuestionnaireMinValue.Value parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.google.fhir.stu3.proto.QuestionnaireMinValue.Value parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.google.fhir.stu3.proto.QuestionnaireMinValue.Value parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.google.fhir.stu3.proto.QuestionnaireMinValue.Value parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.google.fhir.stu3.proto.QuestionnaireMinValue.Value parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.google.fhir.stu3.proto.QuestionnaireMinValue.Value prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Value of extension
     * </pre>
     *
     * Protobuf type {@code google.fhir.stu3.proto.QuestionnaireMinValue.Value}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:google.fhir.stu3.proto.QuestionnaireMinValue.Value)
        com.google.fhir.stu3.proto.QuestionnaireMinValue.ValueOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.google.fhir.stu3.proto.Extensions.internal_static_google_fhir_stu3_proto_QuestionnaireMinValue_Value_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.google.fhir.stu3.proto.Extensions.internal_static_google_fhir_stu3_proto_QuestionnaireMinValue_Value_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.google.fhir.stu3.proto.QuestionnaireMinValue.Value.class, com.google.fhir.stu3.proto.QuestionnaireMinValue.Value.Builder.class);
      }

      // Construct using com.google.fhir.stu3.proto.QuestionnaireMinValue.Value.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        valueCase_ = 0;
        value_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.google.fhir.stu3.proto.Extensions.internal_static_google_fhir_stu3_proto_QuestionnaireMinValue_Value_descriptor;
      }

      @java.lang.Override
      public com.google.fhir.stu3.proto.QuestionnaireMinValue.Value getDefaultInstanceForType() {
        return com.google.fhir.stu3.proto.QuestionnaireMinValue.Value.getDefaultInstance();
      }

      @java.lang.Override
      public com.google.fhir.stu3.proto.QuestionnaireMinValue.Value build() {
        com.google.fhir.stu3.proto.QuestionnaireMinValue.Value result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.google.fhir.stu3.proto.QuestionnaireMinValue.Value buildPartial() {
        com.google.fhir.stu3.proto.QuestionnaireMinValue.Value result = new com.google.fhir.stu3.proto.QuestionnaireMinValue.Value(this);
        if (valueCase_ == 1) {
          if (dateBuilder_ == null) {
            result.value_ = value_;
          } else {
            result.value_ = dateBuilder_.build();
          }
        }
        if (valueCase_ == 2) {
          if (dateTimeBuilder_ == null) {
            result.value_ = value_;
          } else {
            result.value_ = dateTimeBuilder_.build();
          }
        }
        if (valueCase_ == 3) {
          if (timeBuilder_ == null) {
            result.value_ = value_;
          } else {
            result.value_ = timeBuilder_.build();
          }
        }
        if (valueCase_ == 4) {
          if (instantBuilder_ == null) {
            result.value_ = value_;
          } else {
            result.value_ = instantBuilder_.build();
          }
        }
        if (valueCase_ == 5) {
          if (decimalBuilder_ == null) {
            result.value_ = value_;
          } else {
            result.value_ = decimalBuilder_.build();
          }
        }
        if (valueCase_ == 6) {
          if (integerBuilder_ == null) {
            result.value_ = value_;
          } else {
            result.value_ = integerBuilder_.build();
          }
        }
        result.valueCase_ = valueCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.google.fhir.stu3.proto.QuestionnaireMinValue.Value) {
          return mergeFrom((com.google.fhir.stu3.proto.QuestionnaireMinValue.Value)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.google.fhir.stu3.proto.QuestionnaireMinValue.Value other) {
        if (other == com.google.fhir.stu3.proto.QuestionnaireMinValue.Value.getDefaultInstance()) return this;
        switch (other.getValueCase()) {
          case DATE: {
            mergeDate(other.getDate());
            break;
          }
          case DATE_TIME: {
            mergeDateTime(other.getDateTime());
            break;
          }
          case TIME: {
            mergeTime(other.getTime());
            break;
          }
          case INSTANT: {
            mergeInstant(other.getInstant());
            break;
          }
          case DECIMAL: {
            mergeDecimal(other.getDecimal());
            break;
          }
          case INTEGER: {
            mergeInteger(other.getInteger());
            break;
          }
          case VALUE_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.fhir.stu3.proto.QuestionnaireMinValue.Value parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.google.fhir.stu3.proto.QuestionnaireMinValue.Value) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int valueCase_ = 0;
      private java.lang.Object value_;
      public ValueCase
          getValueCase() {
        return ValueCase.forNumber(
            valueCase_);
      }

      public Builder clearValue() {
        valueCase_ = 0;
        value_ = null;
        onChanged();
        return this;
      }


      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.fhir.stu3.proto.Date, com.google.fhir.stu3.proto.Date.Builder, com.google.fhir.stu3.proto.DateOrBuilder> dateBuilder_;
      /**
       * <code>.google.fhir.stu3.proto.Date date = 1;</code>
       * @return Whether the date field is set.
       */
      @java.lang.Override
      public boolean hasDate() {
        return valueCase_ == 1;
      }
      /**
       * <code>.google.fhir.stu3.proto.Date date = 1;</code>
       * @return The date.
       */
      @java.lang.Override
      public com.google.fhir.stu3.proto.Date getDate() {
        if (dateBuilder_ == null) {
          if (valueCase_ == 1) {
            return (com.google.fhir.stu3.proto.Date) value_;
          }
          return com.google.fhir.stu3.proto.Date.getDefaultInstance();
        } else {
          if (valueCase_ == 1) {
            return dateBuilder_.getMessage();
          }
          return com.google.fhir.stu3.proto.Date.getDefaultInstance();
        }
      }
      /**
       * <code>.google.fhir.stu3.proto.Date date = 1;</code>
       */
      public Builder setDate(com.google.fhir.stu3.proto.Date value) {
        if (dateBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          value_ = value;
          onChanged();
        } else {
          dateBuilder_.setMessage(value);
        }
        valueCase_ = 1;
        return this;
      }
      /**
       * <code>.google.fhir.stu3.proto.Date date = 1;</code>
       */
      public Builder setDate(
          com.google.fhir.stu3.proto.Date.Builder builderForValue) {
        if (dateBuilder_ == null) {
          value_ = builderForValue.build();
          onChanged();
        } else {
          dateBuilder_.setMessage(builderForValue.build());
        }
        valueCase_ = 1;
        return this;
      }
      /**
       * <code>.google.fhir.stu3.proto.Date date = 1;</code>
       */
      public Builder mergeDate(com.google.fhir.stu3.proto.Date value) {
        if (dateBuilder_ == null) {
          if (valueCase_ == 1 &&
              value_ != com.google.fhir.stu3.proto.Date.getDefaultInstance()) {
            value_ = com.google.fhir.stu3.proto.Date.newBuilder((com.google.fhir.stu3.proto.Date) value_)
                .mergeFrom(value).buildPartial();
          } else {
            value_ = value;
          }
          onChanged();
        } else {
          if (valueCase_ == 1) {
            dateBuilder_.mergeFrom(value);
          }
          dateBuilder_.setMessage(value);
        }
        valueCase_ = 1;
        return this;
      }
      /**
       * <code>.google.fhir.stu3.proto.Date date = 1;</code>
       */
      public Builder clearDate() {
        if (dateBuilder_ == null) {
          if (valueCase_ == 1) {
            valueCase_ = 0;
            value_ = null;
            onChanged();
          }
        } else {
          if (valueCase_ == 1) {
            valueCase_ = 0;
            value_ = null;
          }
          dateBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.google.fhir.stu3.proto.Date date = 1;</code>
       */
      public com.google.fhir.stu3.proto.Date.Builder getDateBuilder() {
        return getDateFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.fhir.stu3.proto.Date date = 1;</code>
       */
      @java.lang.Override
      public com.google.fhir.stu3.proto.DateOrBuilder getDateOrBuilder() {
        if ((valueCase_ == 1) && (dateBuilder_ != null)) {
          return dateBuilder_.getMessageOrBuilder();
        } else {
          if (valueCase_ == 1) {
            return (com.google.fhir.stu3.proto.Date) value_;
          }
          return com.google.fhir.stu3.proto.Date.getDefaultInstance();
        }
      }
      /**
       * <code>.google.fhir.stu3.proto.Date date = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.fhir.stu3.proto.Date, com.google.fhir.stu3.proto.Date.Builder, com.google.fhir.stu3.proto.DateOrBuilder> 
          getDateFieldBuilder() {
        if (dateBuilder_ == null) {
          if (!(valueCase_ == 1)) {
            value_ = com.google.fhir.stu3.proto.Date.getDefaultInstance();
          }
          dateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.fhir.stu3.proto.Date, com.google.fhir.stu3.proto.Date.Builder, com.google.fhir.stu3.proto.DateOrBuilder>(
                  (com.google.fhir.stu3.proto.Date) value_,
                  getParentForChildren(),
                  isClean());
          value_ = null;
        }
        valueCase_ = 1;
        onChanged();;
        return dateBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.fhir.stu3.proto.DateTime, com.google.fhir.stu3.proto.DateTime.Builder, com.google.fhir.stu3.proto.DateTimeOrBuilder> dateTimeBuilder_;
      /**
       * <code>.google.fhir.stu3.proto.DateTime date_time = 2;</code>
       * @return Whether the dateTime field is set.
       */
      @java.lang.Override
      public boolean hasDateTime() {
        return valueCase_ == 2;
      }
      /**
       * <code>.google.fhir.stu3.proto.DateTime date_time = 2;</code>
       * @return The dateTime.
       */
      @java.lang.Override
      public com.google.fhir.stu3.proto.DateTime getDateTime() {
        if (dateTimeBuilder_ == null) {
          if (valueCase_ == 2) {
            return (com.google.fhir.stu3.proto.DateTime) value_;
          }
          return com.google.fhir.stu3.proto.DateTime.getDefaultInstance();
        } else {
          if (valueCase_ == 2) {
            return dateTimeBuilder_.getMessage();
          }
          return com.google.fhir.stu3.proto.DateTime.getDefaultInstance();
        }
      }
      /**
       * <code>.google.fhir.stu3.proto.DateTime date_time = 2;</code>
       */
      public Builder setDateTime(com.google.fhir.stu3.proto.DateTime value) {
        if (dateTimeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          value_ = value;
          onChanged();
        } else {
          dateTimeBuilder_.setMessage(value);
        }
        valueCase_ = 2;
        return this;
      }
      /**
       * <code>.google.fhir.stu3.proto.DateTime date_time = 2;</code>
       */
      public Builder setDateTime(
          com.google.fhir.stu3.proto.DateTime.Builder builderForValue) {
        if (dateTimeBuilder_ == null) {
          value_ = builderForValue.build();
          onChanged();
        } else {
          dateTimeBuilder_.setMessage(builderForValue.build());
        }
        valueCase_ = 2;
        return this;
      }
      /**
       * <code>.google.fhir.stu3.proto.DateTime date_time = 2;</code>
       */
      public Builder mergeDateTime(com.google.fhir.stu3.proto.DateTime value) {
        if (dateTimeBuilder_ == null) {
          if (valueCase_ == 2 &&
              value_ != com.google.fhir.stu3.proto.DateTime.getDefaultInstance()) {
            value_ = com.google.fhir.stu3.proto.DateTime.newBuilder((com.google.fhir.stu3.proto.DateTime) value_)
                .mergeFrom(value).buildPartial();
          } else {
            value_ = value;
          }
          onChanged();
        } else {
          if (valueCase_ == 2) {
            dateTimeBuilder_.mergeFrom(value);
          }
          dateTimeBuilder_.setMessage(value);
        }
        valueCase_ = 2;
        return this;
      }
      /**
       * <code>.google.fhir.stu3.proto.DateTime date_time = 2;</code>
       */
      public Builder clearDateTime() {
        if (dateTimeBuilder_ == null) {
          if (valueCase_ == 2) {
            valueCase_ = 0;
            value_ = null;
            onChanged();
          }
        } else {
          if (valueCase_ == 2) {
            valueCase_ = 0;
            value_ = null;
          }
          dateTimeBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.google.fhir.stu3.proto.DateTime date_time = 2;</code>
       */
      public com.google.fhir.stu3.proto.DateTime.Builder getDateTimeBuilder() {
        return getDateTimeFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.fhir.stu3.proto.DateTime date_time = 2;</code>
       */
      @java.lang.Override
      public com.google.fhir.stu3.proto.DateTimeOrBuilder getDateTimeOrBuilder() {
        if ((valueCase_ == 2) && (dateTimeBuilder_ != null)) {
          return dateTimeBuilder_.getMessageOrBuilder();
        } else {
          if (valueCase_ == 2) {
            return (com.google.fhir.stu3.proto.DateTime) value_;
          }
          return com.google.fhir.stu3.proto.DateTime.getDefaultInstance();
        }
      }
      /**
       * <code>.google.fhir.stu3.proto.DateTime date_time = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.fhir.stu3.proto.DateTime, com.google.fhir.stu3.proto.DateTime.Builder, com.google.fhir.stu3.proto.DateTimeOrBuilder> 
          getDateTimeFieldBuilder() {
        if (dateTimeBuilder_ == null) {
          if (!(valueCase_ == 2)) {
            value_ = com.google.fhir.stu3.proto.DateTime.getDefaultInstance();
          }
          dateTimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.fhir.stu3.proto.DateTime, com.google.fhir.stu3.proto.DateTime.Builder, com.google.fhir.stu3.proto.DateTimeOrBuilder>(
                  (com.google.fhir.stu3.proto.DateTime) value_,
                  getParentForChildren(),
                  isClean());
          value_ = null;
        }
        valueCase_ = 2;
        onChanged();;
        return dateTimeBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.fhir.stu3.proto.Time, com.google.fhir.stu3.proto.Time.Builder, com.google.fhir.stu3.proto.TimeOrBuilder> timeBuilder_;
      /**
       * <code>.google.fhir.stu3.proto.Time time = 3;</code>
       * @return Whether the time field is set.
       */
      @java.lang.Override
      public boolean hasTime() {
        return valueCase_ == 3;
      }
      /**
       * <code>.google.fhir.stu3.proto.Time time = 3;</code>
       * @return The time.
       */
      @java.lang.Override
      public com.google.fhir.stu3.proto.Time getTime() {
        if (timeBuilder_ == null) {
          if (valueCase_ == 3) {
            return (com.google.fhir.stu3.proto.Time) value_;
          }
          return com.google.fhir.stu3.proto.Time.getDefaultInstance();
        } else {
          if (valueCase_ == 3) {
            return timeBuilder_.getMessage();
          }
          return com.google.fhir.stu3.proto.Time.getDefaultInstance();
        }
      }
      /**
       * <code>.google.fhir.stu3.proto.Time time = 3;</code>
       */
      public Builder setTime(com.google.fhir.stu3.proto.Time value) {
        if (timeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          value_ = value;
          onChanged();
        } else {
          timeBuilder_.setMessage(value);
        }
        valueCase_ = 3;
        return this;
      }
      /**
       * <code>.google.fhir.stu3.proto.Time time = 3;</code>
       */
      public Builder setTime(
          com.google.fhir.stu3.proto.Time.Builder builderForValue) {
        if (timeBuilder_ == null) {
          value_ = builderForValue.build();
          onChanged();
        } else {
          timeBuilder_.setMessage(builderForValue.build());
        }
        valueCase_ = 3;
        return this;
      }
      /**
       * <code>.google.fhir.stu3.proto.Time time = 3;</code>
       */
      public Builder mergeTime(com.google.fhir.stu3.proto.Time value) {
        if (timeBuilder_ == null) {
          if (valueCase_ == 3 &&
              value_ != com.google.fhir.stu3.proto.Time.getDefaultInstance()) {
            value_ = com.google.fhir.stu3.proto.Time.newBuilder((com.google.fhir.stu3.proto.Time) value_)
                .mergeFrom(value).buildPartial();
          } else {
            value_ = value;
          }
          onChanged();
        } else {
          if (valueCase_ == 3) {
            timeBuilder_.mergeFrom(value);
          }
          timeBuilder_.setMessage(value);
        }
        valueCase_ = 3;
        return this;
      }
      /**
       * <code>.google.fhir.stu3.proto.Time time = 3;</code>
       */
      public Builder clearTime() {
        if (timeBuilder_ == null) {
          if (valueCase_ == 3) {
            valueCase_ = 0;
            value_ = null;
            onChanged();
          }
        } else {
          if (valueCase_ == 3) {
            valueCase_ = 0;
            value_ = null;
          }
          timeBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.google.fhir.stu3.proto.Time time = 3;</code>
       */
      public com.google.fhir.stu3.proto.Time.Builder getTimeBuilder() {
        return getTimeFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.fhir.stu3.proto.Time time = 3;</code>
       */
      @java.lang.Override
      public com.google.fhir.stu3.proto.TimeOrBuilder getTimeOrBuilder() {
        if ((valueCase_ == 3) && (timeBuilder_ != null)) {
          return timeBuilder_.getMessageOrBuilder();
        } else {
          if (valueCase_ == 3) {
            return (com.google.fhir.stu3.proto.Time) value_;
          }
          return com.google.fhir.stu3.proto.Time.getDefaultInstance();
        }
      }
      /**
       * <code>.google.fhir.stu3.proto.Time time = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.fhir.stu3.proto.Time, com.google.fhir.stu3.proto.Time.Builder, com.google.fhir.stu3.proto.TimeOrBuilder> 
          getTimeFieldBuilder() {
        if (timeBuilder_ == null) {
          if (!(valueCase_ == 3)) {
            value_ = com.google.fhir.stu3.proto.Time.getDefaultInstance();
          }
          timeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.fhir.stu3.proto.Time, com.google.fhir.stu3.proto.Time.Builder, com.google.fhir.stu3.proto.TimeOrBuilder>(
                  (com.google.fhir.stu3.proto.Time) value_,
                  getParentForChildren(),
                  isClean());
          value_ = null;
        }
        valueCase_ = 3;
        onChanged();;
        return timeBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.fhir.stu3.proto.Instant, com.google.fhir.stu3.proto.Instant.Builder, com.google.fhir.stu3.proto.InstantOrBuilder> instantBuilder_;
      /**
       * <code>.google.fhir.stu3.proto.Instant instant = 4;</code>
       * @return Whether the instant field is set.
       */
      @java.lang.Override
      public boolean hasInstant() {
        return valueCase_ == 4;
      }
      /**
       * <code>.google.fhir.stu3.proto.Instant instant = 4;</code>
       * @return The instant.
       */
      @java.lang.Override
      public com.google.fhir.stu3.proto.Instant getInstant() {
        if (instantBuilder_ == null) {
          if (valueCase_ == 4) {
            return (com.google.fhir.stu3.proto.Instant) value_;
          }
          return com.google.fhir.stu3.proto.Instant.getDefaultInstance();
        } else {
          if (valueCase_ == 4) {
            return instantBuilder_.getMessage();
          }
          return com.google.fhir.stu3.proto.Instant.getDefaultInstance();
        }
      }
      /**
       * <code>.google.fhir.stu3.proto.Instant instant = 4;</code>
       */
      public Builder setInstant(com.google.fhir.stu3.proto.Instant value) {
        if (instantBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          value_ = value;
          onChanged();
        } else {
          instantBuilder_.setMessage(value);
        }
        valueCase_ = 4;
        return this;
      }
      /**
       * <code>.google.fhir.stu3.proto.Instant instant = 4;</code>
       */
      public Builder setInstant(
          com.google.fhir.stu3.proto.Instant.Builder builderForValue) {
        if (instantBuilder_ == null) {
          value_ = builderForValue.build();
          onChanged();
        } else {
          instantBuilder_.setMessage(builderForValue.build());
        }
        valueCase_ = 4;
        return this;
      }
      /**
       * <code>.google.fhir.stu3.proto.Instant instant = 4;</code>
       */
      public Builder mergeInstant(com.google.fhir.stu3.proto.Instant value) {
        if (instantBuilder_ == null) {
          if (valueCase_ == 4 &&
              value_ != com.google.fhir.stu3.proto.Instant.getDefaultInstance()) {
            value_ = com.google.fhir.stu3.proto.Instant.newBuilder((com.google.fhir.stu3.proto.Instant) value_)
                .mergeFrom(value).buildPartial();
          } else {
            value_ = value;
          }
          onChanged();
        } else {
          if (valueCase_ == 4) {
            instantBuilder_.mergeFrom(value);
          }
          instantBuilder_.setMessage(value);
        }
        valueCase_ = 4;
        return this;
      }
      /**
       * <code>.google.fhir.stu3.proto.Instant instant = 4;</code>
       */
      public Builder clearInstant() {
        if (instantBuilder_ == null) {
          if (valueCase_ == 4) {
            valueCase_ = 0;
            value_ = null;
            onChanged();
          }
        } else {
          if (valueCase_ == 4) {
            valueCase_ = 0;
            value_ = null;
          }
          instantBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.google.fhir.stu3.proto.Instant instant = 4;</code>
       */
      public com.google.fhir.stu3.proto.Instant.Builder getInstantBuilder() {
        return getInstantFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.fhir.stu3.proto.Instant instant = 4;</code>
       */
      @java.lang.Override
      public com.google.fhir.stu3.proto.InstantOrBuilder getInstantOrBuilder() {
        if ((valueCase_ == 4) && (instantBuilder_ != null)) {
          return instantBuilder_.getMessageOrBuilder();
        } else {
          if (valueCase_ == 4) {
            return (com.google.fhir.stu3.proto.Instant) value_;
          }
          return com.google.fhir.stu3.proto.Instant.getDefaultInstance();
        }
      }
      /**
       * <code>.google.fhir.stu3.proto.Instant instant = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.fhir.stu3.proto.Instant, com.google.fhir.stu3.proto.Instant.Builder, com.google.fhir.stu3.proto.InstantOrBuilder> 
          getInstantFieldBuilder() {
        if (instantBuilder_ == null) {
          if (!(valueCase_ == 4)) {
            value_ = com.google.fhir.stu3.proto.Instant.getDefaultInstance();
          }
          instantBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.fhir.stu3.proto.Instant, com.google.fhir.stu3.proto.Instant.Builder, com.google.fhir.stu3.proto.InstantOrBuilder>(
                  (com.google.fhir.stu3.proto.Instant) value_,
                  getParentForChildren(),
                  isClean());
          value_ = null;
        }
        valueCase_ = 4;
        onChanged();;
        return instantBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.fhir.stu3.proto.Decimal, com.google.fhir.stu3.proto.Decimal.Builder, com.google.fhir.stu3.proto.DecimalOrBuilder> decimalBuilder_;
      /**
       * <code>.google.fhir.stu3.proto.Decimal decimal = 5;</code>
       * @return Whether the decimal field is set.
       */
      @java.lang.Override
      public boolean hasDecimal() {
        return valueCase_ == 5;
      }
      /**
       * <code>.google.fhir.stu3.proto.Decimal decimal = 5;</code>
       * @return The decimal.
       */
      @java.lang.Override
      public com.google.fhir.stu3.proto.Decimal getDecimal() {
        if (decimalBuilder_ == null) {
          if (valueCase_ == 5) {
            return (com.google.fhir.stu3.proto.Decimal) value_;
          }
          return com.google.fhir.stu3.proto.Decimal.getDefaultInstance();
        } else {
          if (valueCase_ == 5) {
            return decimalBuilder_.getMessage();
          }
          return com.google.fhir.stu3.proto.Decimal.getDefaultInstance();
        }
      }
      /**
       * <code>.google.fhir.stu3.proto.Decimal decimal = 5;</code>
       */
      public Builder setDecimal(com.google.fhir.stu3.proto.Decimal value) {
        if (decimalBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          value_ = value;
          onChanged();
        } else {
          decimalBuilder_.setMessage(value);
        }
        valueCase_ = 5;
        return this;
      }
      /**
       * <code>.google.fhir.stu3.proto.Decimal decimal = 5;</code>
       */
      public Builder setDecimal(
          com.google.fhir.stu3.proto.Decimal.Builder builderForValue) {
        if (decimalBuilder_ == null) {
          value_ = builderForValue.build();
          onChanged();
        } else {
          decimalBuilder_.setMessage(builderForValue.build());
        }
        valueCase_ = 5;
        return this;
      }
      /**
       * <code>.google.fhir.stu3.proto.Decimal decimal = 5;</code>
       */
      public Builder mergeDecimal(com.google.fhir.stu3.proto.Decimal value) {
        if (decimalBuilder_ == null) {
          if (valueCase_ == 5 &&
              value_ != com.google.fhir.stu3.proto.Decimal.getDefaultInstance()) {
            value_ = com.google.fhir.stu3.proto.Decimal.newBuilder((com.google.fhir.stu3.proto.Decimal) value_)
                .mergeFrom(value).buildPartial();
          } else {
            value_ = value;
          }
          onChanged();
        } else {
          if (valueCase_ == 5) {
            decimalBuilder_.mergeFrom(value);
          }
          decimalBuilder_.setMessage(value);
        }
        valueCase_ = 5;
        return this;
      }
      /**
       * <code>.google.fhir.stu3.proto.Decimal decimal = 5;</code>
       */
      public Builder clearDecimal() {
        if (decimalBuilder_ == null) {
          if (valueCase_ == 5) {
            valueCase_ = 0;
            value_ = null;
            onChanged();
          }
        } else {
          if (valueCase_ == 5) {
            valueCase_ = 0;
            value_ = null;
          }
          decimalBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.google.fhir.stu3.proto.Decimal decimal = 5;</code>
       */
      public com.google.fhir.stu3.proto.Decimal.Builder getDecimalBuilder() {
        return getDecimalFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.fhir.stu3.proto.Decimal decimal = 5;</code>
       */
      @java.lang.Override
      public com.google.fhir.stu3.proto.DecimalOrBuilder getDecimalOrBuilder() {
        if ((valueCase_ == 5) && (decimalBuilder_ != null)) {
          return decimalBuilder_.getMessageOrBuilder();
        } else {
          if (valueCase_ == 5) {
            return (com.google.fhir.stu3.proto.Decimal) value_;
          }
          return com.google.fhir.stu3.proto.Decimal.getDefaultInstance();
        }
      }
      /**
       * <code>.google.fhir.stu3.proto.Decimal decimal = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.fhir.stu3.proto.Decimal, com.google.fhir.stu3.proto.Decimal.Builder, com.google.fhir.stu3.proto.DecimalOrBuilder> 
          getDecimalFieldBuilder() {
        if (decimalBuilder_ == null) {
          if (!(valueCase_ == 5)) {
            value_ = com.google.fhir.stu3.proto.Decimal.getDefaultInstance();
          }
          decimalBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.fhir.stu3.proto.Decimal, com.google.fhir.stu3.proto.Decimal.Builder, com.google.fhir.stu3.proto.DecimalOrBuilder>(
                  (com.google.fhir.stu3.proto.Decimal) value_,
                  getParentForChildren(),
                  isClean());
          value_ = null;
        }
        valueCase_ = 5;
        onChanged();;
        return decimalBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.fhir.stu3.proto.Integer, com.google.fhir.stu3.proto.Integer.Builder, com.google.fhir.stu3.proto.IntegerOrBuilder> integerBuilder_;
      /**
       * <code>.google.fhir.stu3.proto.Integer integer = 6;</code>
       * @return Whether the integer field is set.
       */
      @java.lang.Override
      public boolean hasInteger() {
        return valueCase_ == 6;
      }
      /**
       * <code>.google.fhir.stu3.proto.Integer integer = 6;</code>
       * @return The integer.
       */
      @java.lang.Override
      public com.google.fhir.stu3.proto.Integer getInteger() {
        if (integerBuilder_ == null) {
          if (valueCase_ == 6) {
            return (com.google.fhir.stu3.proto.Integer) value_;
          }
          return com.google.fhir.stu3.proto.Integer.getDefaultInstance();
        } else {
          if (valueCase_ == 6) {
            return integerBuilder_.getMessage();
          }
          return com.google.fhir.stu3.proto.Integer.getDefaultInstance();
        }
      }
      /**
       * <code>.google.fhir.stu3.proto.Integer integer = 6;</code>
       */
      public Builder setInteger(com.google.fhir.stu3.proto.Integer value) {
        if (integerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          value_ = value;
          onChanged();
        } else {
          integerBuilder_.setMessage(value);
        }
        valueCase_ = 6;
        return this;
      }
      /**
       * <code>.google.fhir.stu3.proto.Integer integer = 6;</code>
       */
      public Builder setInteger(
          com.google.fhir.stu3.proto.Integer.Builder builderForValue) {
        if (integerBuilder_ == null) {
          value_ = builderForValue.build();
          onChanged();
        } else {
          integerBuilder_.setMessage(builderForValue.build());
        }
        valueCase_ = 6;
        return this;
      }
      /**
       * <code>.google.fhir.stu3.proto.Integer integer = 6;</code>
       */
      public Builder mergeInteger(com.google.fhir.stu3.proto.Integer value) {
        if (integerBuilder_ == null) {
          if (valueCase_ == 6 &&
              value_ != com.google.fhir.stu3.proto.Integer.getDefaultInstance()) {
            value_ = com.google.fhir.stu3.proto.Integer.newBuilder((com.google.fhir.stu3.proto.Integer) value_)
                .mergeFrom(value).buildPartial();
          } else {
            value_ = value;
          }
          onChanged();
        } else {
          if (valueCase_ == 6) {
            integerBuilder_.mergeFrom(value);
          }
          integerBuilder_.setMessage(value);
        }
        valueCase_ = 6;
        return this;
      }
      /**
       * <code>.google.fhir.stu3.proto.Integer integer = 6;</code>
       */
      public Builder clearInteger() {
        if (integerBuilder_ == null) {
          if (valueCase_ == 6) {
            valueCase_ = 0;
            value_ = null;
            onChanged();
          }
        } else {
          if (valueCase_ == 6) {
            valueCase_ = 0;
            value_ = null;
          }
          integerBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.google.fhir.stu3.proto.Integer integer = 6;</code>
       */
      public com.google.fhir.stu3.proto.Integer.Builder getIntegerBuilder() {
        return getIntegerFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.fhir.stu3.proto.Integer integer = 6;</code>
       */
      @java.lang.Override
      public com.google.fhir.stu3.proto.IntegerOrBuilder getIntegerOrBuilder() {
        if ((valueCase_ == 6) && (integerBuilder_ != null)) {
          return integerBuilder_.getMessageOrBuilder();
        } else {
          if (valueCase_ == 6) {
            return (com.google.fhir.stu3.proto.Integer) value_;
          }
          return com.google.fhir.stu3.proto.Integer.getDefaultInstance();
        }
      }
      /**
       * <code>.google.fhir.stu3.proto.Integer integer = 6;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.fhir.stu3.proto.Integer, com.google.fhir.stu3.proto.Integer.Builder, com.google.fhir.stu3.proto.IntegerOrBuilder> 
          getIntegerFieldBuilder() {
        if (integerBuilder_ == null) {
          if (!(valueCase_ == 6)) {
            value_ = com.google.fhir.stu3.proto.Integer.getDefaultInstance();
          }
          integerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.fhir.stu3.proto.Integer, com.google.fhir.stu3.proto.Integer.Builder, com.google.fhir.stu3.proto.IntegerOrBuilder>(
                  (com.google.fhir.stu3.proto.Integer) value_,
                  getParentForChildren(),
                  isClean());
          value_ = null;
        }
        valueCase_ = 6;
        onChanged();;
        return integerBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:google.fhir.stu3.proto.QuestionnaireMinValue.Value)
    }

    // @@protoc_insertion_point(class_scope:google.fhir.stu3.proto.QuestionnaireMinValue.Value)
    private static final com.google.fhir.stu3.proto.QuestionnaireMinValue.Value DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.google.fhir.stu3.proto.QuestionnaireMinValue.Value();
    }

    public static com.google.fhir.stu3.proto.QuestionnaireMinValue.Value getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Value>
        PARSER = new com.google.protobuf.AbstractParser<Value>() {
      @java.lang.Override
      public Value parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Value(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Value> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Value> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.fhir.stu3.proto.QuestionnaireMinValue.Value getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int ID_FIELD_NUMBER = 1;
  private com.google.fhir.stu3.proto.String id_;
  /**
   * <pre>
   * xml:id (or equivalent in JSON)
   * </pre>
   *
   * <code>.google.fhir.stu3.proto.String id = 1;</code>
   * @return Whether the id field is set.
   */
  @java.lang.Override
  public boolean hasId() {
    return id_ != null;
  }
  /**
   * <pre>
   * xml:id (or equivalent in JSON)
   * </pre>
   *
   * <code>.google.fhir.stu3.proto.String id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public com.google.fhir.stu3.proto.String getId() {
    return id_ == null ? com.google.fhir.stu3.proto.String.getDefaultInstance() : id_;
  }
  /**
   * <pre>
   * xml:id (or equivalent in JSON)
   * </pre>
   *
   * <code>.google.fhir.stu3.proto.String id = 1;</code>
   */
  @java.lang.Override
  public com.google.fhir.stu3.proto.StringOrBuilder getIdOrBuilder() {
    return getId();
  }

  public static final int VALUE_FIELD_NUMBER = 3;
  private com.google.fhir.stu3.proto.QuestionnaireMinValue.Value value_;
  /**
   * <code>.google.fhir.stu3.proto.QuestionnaireMinValue.Value value = 3 [(.google.fhir.proto.validation_requirement) = REQUIRED_BY_FHIR];</code>
   * @return Whether the value field is set.
   */
  @java.lang.Override
  public boolean hasValue() {
    return value_ != null;
  }
  /**
   * <code>.google.fhir.stu3.proto.QuestionnaireMinValue.Value value = 3 [(.google.fhir.proto.validation_requirement) = REQUIRED_BY_FHIR];</code>
   * @return The value.
   */
  @java.lang.Override
  public com.google.fhir.stu3.proto.QuestionnaireMinValue.Value getValue() {
    return value_ == null ? com.google.fhir.stu3.proto.QuestionnaireMinValue.Value.getDefaultInstance() : value_;
  }
  /**
   * <code>.google.fhir.stu3.proto.QuestionnaireMinValue.Value value = 3 [(.google.fhir.proto.validation_requirement) = REQUIRED_BY_FHIR];</code>
   */
  @java.lang.Override
  public com.google.fhir.stu3.proto.QuestionnaireMinValue.ValueOrBuilder getValueOrBuilder() {
    return getValue();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != null) {
      output.writeMessage(1, getId());
    }
    if (value_ != null) {
      output.writeMessage(3, getValue());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getId());
    }
    if (value_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getValue());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.fhir.stu3.proto.QuestionnaireMinValue)) {
      return super.equals(obj);
    }
    com.google.fhir.stu3.proto.QuestionnaireMinValue other = (com.google.fhir.stu3.proto.QuestionnaireMinValue) obj;

    if (hasId() != other.hasId()) return false;
    if (hasId()) {
      if (!getId()
          .equals(other.getId())) return false;
    }
    if (hasValue() != other.hasValue()) return false;
    if (hasValue()) {
      if (!getValue()
          .equals(other.getValue())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasId()) {
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
    }
    if (hasValue()) {
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getValue().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.fhir.stu3.proto.QuestionnaireMinValue parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.fhir.stu3.proto.QuestionnaireMinValue parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.fhir.stu3.proto.QuestionnaireMinValue parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.fhir.stu3.proto.QuestionnaireMinValue parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.fhir.stu3.proto.QuestionnaireMinValue parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.fhir.stu3.proto.QuestionnaireMinValue parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.fhir.stu3.proto.QuestionnaireMinValue parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.fhir.stu3.proto.QuestionnaireMinValue parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.fhir.stu3.proto.QuestionnaireMinValue parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.google.fhir.stu3.proto.QuestionnaireMinValue parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.fhir.stu3.proto.QuestionnaireMinValue parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.fhir.stu3.proto.QuestionnaireMinValue parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.fhir.stu3.proto.QuestionnaireMinValue prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Auto-generated from StructureDefinition for minValue.
   * Must be &gt;= this value.
   * See http://hl7.org/fhir/StructureDefinition/minValue
   * </pre>
   *
   * Protobuf type {@code google.fhir.stu3.proto.QuestionnaireMinValue}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:google.fhir.stu3.proto.QuestionnaireMinValue)
      com.google.fhir.stu3.proto.QuestionnaireMinValueOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.fhir.stu3.proto.Extensions.internal_static_google_fhir_stu3_proto_QuestionnaireMinValue_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.fhir.stu3.proto.Extensions.internal_static_google_fhir_stu3_proto_QuestionnaireMinValue_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.fhir.stu3.proto.QuestionnaireMinValue.class, com.google.fhir.stu3.proto.QuestionnaireMinValue.Builder.class);
    }

    // Construct using com.google.fhir.stu3.proto.QuestionnaireMinValue.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (idBuilder_ == null) {
        id_ = null;
      } else {
        id_ = null;
        idBuilder_ = null;
      }
      if (valueBuilder_ == null) {
        value_ = null;
      } else {
        value_ = null;
        valueBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.fhir.stu3.proto.Extensions.internal_static_google_fhir_stu3_proto_QuestionnaireMinValue_descriptor;
    }

    @java.lang.Override
    public com.google.fhir.stu3.proto.QuestionnaireMinValue getDefaultInstanceForType() {
      return com.google.fhir.stu3.proto.QuestionnaireMinValue.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.fhir.stu3.proto.QuestionnaireMinValue build() {
      com.google.fhir.stu3.proto.QuestionnaireMinValue result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.fhir.stu3.proto.QuestionnaireMinValue buildPartial() {
      com.google.fhir.stu3.proto.QuestionnaireMinValue result = new com.google.fhir.stu3.proto.QuestionnaireMinValue(this);
      if (idBuilder_ == null) {
        result.id_ = id_;
      } else {
        result.id_ = idBuilder_.build();
      }
      if (valueBuilder_ == null) {
        result.value_ = value_;
      } else {
        result.value_ = valueBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.fhir.stu3.proto.QuestionnaireMinValue) {
        return mergeFrom((com.google.fhir.stu3.proto.QuestionnaireMinValue)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.fhir.stu3.proto.QuestionnaireMinValue other) {
      if (other == com.google.fhir.stu3.proto.QuestionnaireMinValue.getDefaultInstance()) return this;
      if (other.hasId()) {
        mergeId(other.getId());
      }
      if (other.hasValue()) {
        mergeValue(other.getValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.google.fhir.stu3.proto.QuestionnaireMinValue parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.google.fhir.stu3.proto.QuestionnaireMinValue) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.google.fhir.stu3.proto.String id_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.fhir.stu3.proto.String, com.google.fhir.stu3.proto.String.Builder, com.google.fhir.stu3.proto.StringOrBuilder> idBuilder_;
    /**
     * <pre>
     * xml:id (or equivalent in JSON)
     * </pre>
     *
     * <code>.google.fhir.stu3.proto.String id = 1;</code>
     * @return Whether the id field is set.
     */
    public boolean hasId() {
      return idBuilder_ != null || id_ != null;
    }
    /**
     * <pre>
     * xml:id (or equivalent in JSON)
     * </pre>
     *
     * <code>.google.fhir.stu3.proto.String id = 1;</code>
     * @return The id.
     */
    public com.google.fhir.stu3.proto.String getId() {
      if (idBuilder_ == null) {
        return id_ == null ? com.google.fhir.stu3.proto.String.getDefaultInstance() : id_;
      } else {
        return idBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * xml:id (or equivalent in JSON)
     * </pre>
     *
     * <code>.google.fhir.stu3.proto.String id = 1;</code>
     */
    public Builder setId(com.google.fhir.stu3.proto.String value) {
      if (idBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        id_ = value;
        onChanged();
      } else {
        idBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * xml:id (or equivalent in JSON)
     * </pre>
     *
     * <code>.google.fhir.stu3.proto.String id = 1;</code>
     */
    public Builder setId(
        com.google.fhir.stu3.proto.String.Builder builderForValue) {
      if (idBuilder_ == null) {
        id_ = builderForValue.build();
        onChanged();
      } else {
        idBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * xml:id (or equivalent in JSON)
     * </pre>
     *
     * <code>.google.fhir.stu3.proto.String id = 1;</code>
     */
    public Builder mergeId(com.google.fhir.stu3.proto.String value) {
      if (idBuilder_ == null) {
        if (id_ != null) {
          id_ =
            com.google.fhir.stu3.proto.String.newBuilder(id_).mergeFrom(value).buildPartial();
        } else {
          id_ = value;
        }
        onChanged();
      } else {
        idBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * xml:id (or equivalent in JSON)
     * </pre>
     *
     * <code>.google.fhir.stu3.proto.String id = 1;</code>
     */
    public Builder clearId() {
      if (idBuilder_ == null) {
        id_ = null;
        onChanged();
      } else {
        id_ = null;
        idBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * xml:id (or equivalent in JSON)
     * </pre>
     *
     * <code>.google.fhir.stu3.proto.String id = 1;</code>
     */
    public com.google.fhir.stu3.proto.String.Builder getIdBuilder() {
      
      onChanged();
      return getIdFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * xml:id (or equivalent in JSON)
     * </pre>
     *
     * <code>.google.fhir.stu3.proto.String id = 1;</code>
     */
    public com.google.fhir.stu3.proto.StringOrBuilder getIdOrBuilder() {
      if (idBuilder_ != null) {
        return idBuilder_.getMessageOrBuilder();
      } else {
        return id_ == null ?
            com.google.fhir.stu3.proto.String.getDefaultInstance() : id_;
      }
    }
    /**
     * <pre>
     * xml:id (or equivalent in JSON)
     * </pre>
     *
     * <code>.google.fhir.stu3.proto.String id = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.fhir.stu3.proto.String, com.google.fhir.stu3.proto.String.Builder, com.google.fhir.stu3.proto.StringOrBuilder> 
        getIdFieldBuilder() {
      if (idBuilder_ == null) {
        idBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.fhir.stu3.proto.String, com.google.fhir.stu3.proto.String.Builder, com.google.fhir.stu3.proto.StringOrBuilder>(
                getId(),
                getParentForChildren(),
                isClean());
        id_ = null;
      }
      return idBuilder_;
    }

    private com.google.fhir.stu3.proto.QuestionnaireMinValue.Value value_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.fhir.stu3.proto.QuestionnaireMinValue.Value, com.google.fhir.stu3.proto.QuestionnaireMinValue.Value.Builder, com.google.fhir.stu3.proto.QuestionnaireMinValue.ValueOrBuilder> valueBuilder_;
    /**
     * <code>.google.fhir.stu3.proto.QuestionnaireMinValue.Value value = 3 [(.google.fhir.proto.validation_requirement) = REQUIRED_BY_FHIR];</code>
     * @return Whether the value field is set.
     */
    public boolean hasValue() {
      return valueBuilder_ != null || value_ != null;
    }
    /**
     * <code>.google.fhir.stu3.proto.QuestionnaireMinValue.Value value = 3 [(.google.fhir.proto.validation_requirement) = REQUIRED_BY_FHIR];</code>
     * @return The value.
     */
    public com.google.fhir.stu3.proto.QuestionnaireMinValue.Value getValue() {
      if (valueBuilder_ == null) {
        return value_ == null ? com.google.fhir.stu3.proto.QuestionnaireMinValue.Value.getDefaultInstance() : value_;
      } else {
        return valueBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.fhir.stu3.proto.QuestionnaireMinValue.Value value = 3 [(.google.fhir.proto.validation_requirement) = REQUIRED_BY_FHIR];</code>
     */
    public Builder setValue(com.google.fhir.stu3.proto.QuestionnaireMinValue.Value value) {
      if (valueBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        value_ = value;
        onChanged();
      } else {
        valueBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.fhir.stu3.proto.QuestionnaireMinValue.Value value = 3 [(.google.fhir.proto.validation_requirement) = REQUIRED_BY_FHIR];</code>
     */
    public Builder setValue(
        com.google.fhir.stu3.proto.QuestionnaireMinValue.Value.Builder builderForValue) {
      if (valueBuilder_ == null) {
        value_ = builderForValue.build();
        onChanged();
      } else {
        valueBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.fhir.stu3.proto.QuestionnaireMinValue.Value value = 3 [(.google.fhir.proto.validation_requirement) = REQUIRED_BY_FHIR];</code>
     */
    public Builder mergeValue(com.google.fhir.stu3.proto.QuestionnaireMinValue.Value value) {
      if (valueBuilder_ == null) {
        if (value_ != null) {
          value_ =
            com.google.fhir.stu3.proto.QuestionnaireMinValue.Value.newBuilder(value_).mergeFrom(value).buildPartial();
        } else {
          value_ = value;
        }
        onChanged();
      } else {
        valueBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.fhir.stu3.proto.QuestionnaireMinValue.Value value = 3 [(.google.fhir.proto.validation_requirement) = REQUIRED_BY_FHIR];</code>
     */
    public Builder clearValue() {
      if (valueBuilder_ == null) {
        value_ = null;
        onChanged();
      } else {
        value_ = null;
        valueBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.fhir.stu3.proto.QuestionnaireMinValue.Value value = 3 [(.google.fhir.proto.validation_requirement) = REQUIRED_BY_FHIR];</code>
     */
    public com.google.fhir.stu3.proto.QuestionnaireMinValue.Value.Builder getValueBuilder() {
      
      onChanged();
      return getValueFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.fhir.stu3.proto.QuestionnaireMinValue.Value value = 3 [(.google.fhir.proto.validation_requirement) = REQUIRED_BY_FHIR];</code>
     */
    public com.google.fhir.stu3.proto.QuestionnaireMinValue.ValueOrBuilder getValueOrBuilder() {
      if (valueBuilder_ != null) {
        return valueBuilder_.getMessageOrBuilder();
      } else {
        return value_ == null ?
            com.google.fhir.stu3.proto.QuestionnaireMinValue.Value.getDefaultInstance() : value_;
      }
    }
    /**
     * <code>.google.fhir.stu3.proto.QuestionnaireMinValue.Value value = 3 [(.google.fhir.proto.validation_requirement) = REQUIRED_BY_FHIR];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.fhir.stu3.proto.QuestionnaireMinValue.Value, com.google.fhir.stu3.proto.QuestionnaireMinValue.Value.Builder, com.google.fhir.stu3.proto.QuestionnaireMinValue.ValueOrBuilder> 
        getValueFieldBuilder() {
      if (valueBuilder_ == null) {
        valueBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.fhir.stu3.proto.QuestionnaireMinValue.Value, com.google.fhir.stu3.proto.QuestionnaireMinValue.Value.Builder, com.google.fhir.stu3.proto.QuestionnaireMinValue.ValueOrBuilder>(
                getValue(),
                getParentForChildren(),
                isClean());
        value_ = null;
      }
      return valueBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:google.fhir.stu3.proto.QuestionnaireMinValue)
  }

  // @@protoc_insertion_point(class_scope:google.fhir.stu3.proto.QuestionnaireMinValue)
  private static final com.google.fhir.stu3.proto.QuestionnaireMinValue DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.fhir.stu3.proto.QuestionnaireMinValue();
  }

  public static com.google.fhir.stu3.proto.QuestionnaireMinValue getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<QuestionnaireMinValue>
      PARSER = new com.google.protobuf.AbstractParser<QuestionnaireMinValue>() {
    @java.lang.Override
    public QuestionnaireMinValue parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new QuestionnaireMinValue(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<QuestionnaireMinValue> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<QuestionnaireMinValue> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.fhir.stu3.proto.QuestionnaireMinValue getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

