package com.babylonhealth.lit.usbase_java.codes;

import com.babylonhealth.lit.usbase.CONCEPT_MAP_EQUIVALENCE;

public interface ConceptMapEquivalence {
  public static final CONCEPT_MAP_EQUIVALENCE DISJOINT = CONCEPT_MAP_EQUIVALENCE.DISJOINT$.MODULE$;
  public static final CONCEPT_MAP_EQUIVALENCE EQUAL = CONCEPT_MAP_EQUIVALENCE.EQUAL$.MODULE$;
  public static final CONCEPT_MAP_EQUIVALENCE EQUIVALENT =
      CONCEPT_MAP_EQUIVALENCE.EQUIVALENT$.MODULE$;
  public static final CONCEPT_MAP_EQUIVALENCE INEXACT = CONCEPT_MAP_EQUIVALENCE.INEXACT$.MODULE$;
  public static final CONCEPT_MAP_EQUIVALENCE NARROWER = CONCEPT_MAP_EQUIVALENCE.NARROWER$.MODULE$;
  public static final CONCEPT_MAP_EQUIVALENCE RELATEDTO =
      CONCEPT_MAP_EQUIVALENCE.RELATEDTO$.MODULE$;
  public static final CONCEPT_MAP_EQUIVALENCE SPECIALIZES =
      CONCEPT_MAP_EQUIVALENCE.SPECIALIZES$.MODULE$;
  public static final CONCEPT_MAP_EQUIVALENCE SUBSUMES = CONCEPT_MAP_EQUIVALENCE.SUBSUMES$.MODULE$;
  public static final CONCEPT_MAP_EQUIVALENCE UNMATCHED =
      CONCEPT_MAP_EQUIVALENCE.UNMATCHED$.MODULE$;
  public static final CONCEPT_MAP_EQUIVALENCE WIDER = CONCEPT_MAP_EQUIVALENCE.WIDER$.MODULE$;
}
