package com.babylonhealth.lit.usbase_java.codes;

import com.babylonhealth.lit.usbase.DATA_ABSENT_REASON;

public interface DataAbsentReason {
  public static final DATA_ABSENT_REASON ASKED_BUT_DECLINED =
      DATA_ABSENT_REASON.ASKED_BUT_DECLINED$.MODULE$;
  public static final DATA_ABSENT_REASON ASKED_BUT_UNKNOWN =
      DATA_ABSENT_REASON.ASKED_BUT_UNKNOWN$.MODULE$;
  public static final DATA_ABSENT_REASON AS_TEXT = DATA_ABSENT_REASON.AS_TEXT$.MODULE$;
  public static final DATA_ABSENT_REASON ERROR = DATA_ABSENT_REASON.ERROR$.MODULE$;
  public static final DATA_ABSENT_REASON MASKED = DATA_ABSENT_REASON.MASKED$.MODULE$;
  public static final DATA_ABSENT_REASON NEGATIVE_INFINITY =
      DATA_ABSENT_REASON.NEGATIVE_INFINITY$.MODULE$;
  public static final DATA_ABSENT_REASON NOT_APPLICABLE =
      DATA_ABSENT_REASON.NOT_APPLICABLE$.MODULE$;
  public static final DATA_ABSENT_REASON NOT_ASKED = DATA_ABSENT_REASON.NOT_ASKED$.MODULE$;
  public static final DATA_ABSENT_REASON NOT_A_NUMBER = DATA_ABSENT_REASON.NOT_A_NUMBER$.MODULE$;
  public static final DATA_ABSENT_REASON NOT_PERFORMED = DATA_ABSENT_REASON.NOT_PERFORMED$.MODULE$;
  public static final DATA_ABSENT_REASON NOT_PERMITTED = DATA_ABSENT_REASON.NOT_PERMITTED$.MODULE$;
  public static final DATA_ABSENT_REASON POSITIVE_INFINITY =
      DATA_ABSENT_REASON.POSITIVE_INFINITY$.MODULE$;
  public static final DATA_ABSENT_REASON TEMPORARILY_UNKNOWN =
      DATA_ABSENT_REASON.TEMPORARILY_UNKNOWN$.MODULE$;
  public static final DATA_ABSENT_REASON UNKNOWN = DATA_ABSENT_REASON.UNKNOWN$.MODULE$;
  public static final DATA_ABSENT_REASON UNSUPPORTED = DATA_ABSENT_REASON.UNSUPPORTED$.MODULE$;
}
