package com.babylonhealth.lit.usbase_java.codes;

import com.babylonhealth.lit.usbase.DEVICE_STATEMENT_STATUS;

public interface DeviceStatementStatus {
  public static final DEVICE_STATEMENT_STATUS ACTIVE = DEVICE_STATEMENT_STATUS.ACTIVE$.MODULE$;
  public static final DEVICE_STATEMENT_STATUS COMPLETED =
      DEVICE_STATEMENT_STATUS.COMPLETED$.MODULE$;
  public static final DEVICE_STATEMENT_STATUS ENTERED_IN_ERROR =
      DEVICE_STATEMENT_STATUS.ENTERED_IN_ERROR$.MODULE$;
  public static final DEVICE_STATEMENT_STATUS INTENDED = DEVICE_STATEMENT_STATUS.INTENDED$.MODULE$;
  public static final DEVICE_STATEMENT_STATUS ON_HOLD = DEVICE_STATEMENT_STATUS.ON_HOLD$.MODULE$;
  public static final DEVICE_STATEMENT_STATUS STOPPED = DEVICE_STATEMENT_STATUS.STOPPED$.MODULE$;
}
