package com.babylonhealth.lit.usbase_java.codes;

import com.babylonhealth.lit.usbase.PROBABILITY_DISTRIBUTION_TYPE;

public interface ProbabilityDistributionType {
  public static final PROBABILITY_DISTRIBUTION_TYPE B = PROBABILITY_DISTRIBUTION_TYPE.B$.MODULE$;
  public static final PROBABILITY_DISTRIBUTION_TYPE E = PROBABILITY_DISTRIBUTION_TYPE.E$.MODULE$;
  public static final PROBABILITY_DISTRIBUTION_TYPE F = PROBABILITY_DISTRIBUTION_TYPE.F$.MODULE$;
  public static final PROBABILITY_DISTRIBUTION_TYPE G = PROBABILITY_DISTRIBUTION_TYPE.G$.MODULE$;
  public static final PROBABILITY_DISTRIBUTION_TYPE LN = PROBABILITY_DISTRIBUTION_TYPE.LN$.MODULE$;
  public static final PROBABILITY_DISTRIBUTION_TYPE N = PROBABILITY_DISTRIBUTION_TYPE.N$.MODULE$;
  public static final PROBABILITY_DISTRIBUTION_TYPE T = PROBABILITY_DISTRIBUTION_TYPE.T$.MODULE$;
  public static final PROBABILITY_DISTRIBUTION_TYPE U = PROBABILITY_DISTRIBUTION_TYPE.U$.MODULE$;
  public static final PROBABILITY_DISTRIBUTION_TYPE X2 = PROBABILITY_DISTRIBUTION_TYPE.X2$.MODULE$;
}
