package com.babylonhealth.lit.usbase_java.codes;

import com.babylonhealth.lit.usbase.QUESTIONNAIRE_USAGE_MODE;

public interface QuestionnaireUsageMode {
  public static final QUESTIONNAIRE_USAGE_MODE CAPTURE = QUESTIONNAIRE_USAGE_MODE.CAPTURE$.MODULE$;
  public static final QUESTIONNAIRE_USAGE_MODE CAPTURE_DISPLAY =
      QUESTIONNAIRE_USAGE_MODE.CAPTURE_DISPLAY$.MODULE$;
  public static final QUESTIONNAIRE_USAGE_MODE CAPTURE_DISPLAY_NON_EMPTY =
      QUESTIONNAIRE_USAGE_MODE.CAPTURE_DISPLAY_NON_EMPTY$.MODULE$;
  public static final QUESTIONNAIRE_USAGE_MODE DISPLAY = QUESTIONNAIRE_USAGE_MODE.DISPLAY$.MODULE$;
  public static final QUESTIONNAIRE_USAGE_MODE DISPLAY_WHEN_ANSWERED =
      QUESTIONNAIRE_USAGE_MODE.DISPLAY_WHEN_ANSWERED$.MODULE$;
}
