package com.babylonhealth.lit.usbase_java.codes;

import com.babylonhealth.lit.usbase.RESOURCE_SECURITY_CATEGORY;

public interface ResourceSecurityCategory {
  public static final RESOURCE_SECURITY_CATEGORY ANONYMOUS =
      RESOURCE_SECURITY_CATEGORY.ANONYMOUS$.MODULE$;
  public static final RESOURCE_SECURITY_CATEGORY BUSINESS =
      RESOURCE_SECURITY_CATEGORY.BUSINESS$.MODULE$;
  public static final RESOURCE_SECURITY_CATEGORY INDIVIDUAL =
      RESOURCE_SECURITY_CATEGORY.INDIVIDUAL$.MODULE$;
  public static final RESOURCE_SECURITY_CATEGORY NOT_CLASSIFIED =
      RESOURCE_SECURITY_CATEGORY.NOT_CLASSIFIED$.MODULE$;
  public static final RESOURCE_SECURITY_CATEGORY PATIENT =
      RESOURCE_SECURITY_CATEGORY.PATIENT$.MODULE$;
}
