package com.babylonhealth.lit.usbase_java.codes;

import com.babylonhealth.lit.usbase.SMART_CAPABILITIES;

public interface SmartCapabilities {
  public static final SMART_CAPABILITIES CONFIDENTIAL_CLIENT_PROFILE =
      SMART_CAPABILITIES.CONFIDENTIAL_CLIENT_PROFILE$.MODULE$;
  public static final SMART_CAPABILITIES CONTEXT_EHR_ENCOUNTER =
      SMART_CAPABILITIES.CONTEXT_EHR_ENCOUNTER$.MODULE$;
  public static final SMART_CAPABILITIES CONTEXT_EHR_PATIENT =
      SMART_CAPABILITIES.CONTEXT_EHR_PATIENT$.MODULE$;
  public static final SMART_CAPABILITIES CONTEXT_PASSTHROUGH_BANNER =
      SMART_CAPABILITIES.CONTEXT_PASSTHROUGH_BANNER$.MODULE$;
  public static final SMART_CAPABILITIES CONTEXT_PASSTHROUGH_STYLE =
      SMART_CAPABILITIES.CONTEXT_PASSTHROUGH_STYLE$.MODULE$;
  public static final SMART_CAPABILITIES CONTEXT_STANDALONE_ENCOUNTER =
      SMART_CAPABILITIES.CONTEXT_STANDALONE_ENCOUNTER$.MODULE$;
  public static final SMART_CAPABILITIES CONTEXT_STANDALONE_PATIENT =
      SMART_CAPABILITIES.CONTEXT_STANDALONE_PATIENT$.MODULE$;
  public static final SMART_CAPABILITIES EHR_LAUNCH_MODE =
      SMART_CAPABILITIES.EHR_LAUNCH_MODE$.MODULE$;
  public static final SMART_CAPABILITIES PUBLIC_CLIENT_PROFILE =
      SMART_CAPABILITIES.PUBLIC_CLIENT_PROFILE$.MODULE$;
  public static final SMART_CAPABILITIES STANDALONE_LAUNCH_MODE =
      SMART_CAPABILITIES.STANDALONE_LAUNCH_MODE$.MODULE$;
  public static final SMART_CAPABILITIES SUPPORTS_OPENID_CONNECT =
      SMART_CAPABILITIES.SUPPORTS_OPENID_CONNECT$.MODULE$;
  public static final SMART_CAPABILITIES SUPPORTS_PATIENT_LEVEL_SCOPES =
      SMART_CAPABILITIES.SUPPORTS_PATIENT_LEVEL_SCOPES$.MODULE$;
  public static final SMART_CAPABILITIES SUPPORTS_REFRESH_TOKEN =
      SMART_CAPABILITIES.SUPPORTS_REFRESH_TOKEN$.MODULE$;
  public static final SMART_CAPABILITIES SUPPORTS_USER_LEVEL_SCOPES =
      SMART_CAPABILITIES.SUPPORTS_USER_LEVEL_SCOPES$.MODULE$;
}
