package com.babylonhealth.lit.usbase_java.codes;

import com.babylonhealth.lit.usbase.TEMPLATE_STATUS_CODE;

public interface TemplateStatusCode {
  public static final TEMPLATE_STATUS_CODE ACTIVE = TEMPLATE_STATUS_CODE.ACTIVE$.MODULE$;
  public static final TEMPLATE_STATUS_CODE CANCELLED = TEMPLATE_STATUS_CODE.CANCELLED$.MODULE$;
  public static final TEMPLATE_STATUS_CODE DRAFT = TEMPLATE_STATUS_CODE.DRAFT$.MODULE$;
  public static final TEMPLATE_STATUS_CODE PENDING = TEMPLATE_STATUS_CODE.PENDING$.MODULE$;
  public static final TEMPLATE_STATUS_CODE REJECTED = TEMPLATE_STATUS_CODE.REJECTED$.MODULE$;
  public static final TEMPLATE_STATUS_CODE RETIRED = TEMPLATE_STATUS_CODE.RETIRED$.MODULE$;
  public static final TEMPLATE_STATUS_CODE REVIEW = TEMPLATE_STATUS_CODE.REVIEW$.MODULE$;
  public static final TEMPLATE_STATUS_CODE TERMINATED = TEMPLATE_STATUS_CODE.TERMINATED$.MODULE$;
}
