package com.babylonhealth.lit.usbase_java.codes;

import com.babylonhealth.lit.usbase.V3_ENTITYNAMEUSER2;

public interface V3Entitynameuser2 {
  public static final V3_ENTITYNAMEUSER2 A = V3_ENTITYNAMEUSER2.A$.MODULE$;
  public static final V3_ENTITYNAMEUSER2 ABC = V3_ENTITYNAMEUSER2.ABC$.MODULE$;
  public static final V3_ENTITYNAMEUSER2 ANON = V3_ENTITYNAMEUSER2.ANON$.MODULE$;
  public static final V3_ENTITYNAMEUSER2 ASSUMED = V3_ENTITYNAMEUSER2.ASSUMED$.MODULE$;
  public static final V3_ENTITYNAMEUSER2 C = V3_ENTITYNAMEUSER2.C$.MODULE$;
  public static final V3_ENTITYNAMEUSER2 DN = V3_ENTITYNAMEUSER2.DN$.MODULE$;
  public static final V3_ENTITYNAMEUSER2 I = V3_ENTITYNAMEUSER2.I$.MODULE$;
  public static final V3_ENTITYNAMEUSER2 IDE = V3_ENTITYNAMEUSER2.IDE$.MODULE$;
  public static final V3_ENTITYNAMEUSER2 M = V3_ENTITYNAMEUSER2.M$.MODULE$;
  public static final V3_ENTITYNAMEUSER2 NAMEREPRESENTATIONUSE =
      V3_ENTITYNAMEUSER2.NAMEREPRESENTATIONUSE$.MODULE$;
  public static final V3_ENTITYNAMEUSER2 OLD = V3_ENTITYNAMEUSER2.OLD$.MODULE$;
  public static final V3_ENTITYNAMEUSER2 OR = V3_ENTITYNAMEUSER2.OR$.MODULE$;
  public static final V3_ENTITYNAMEUSER2 P = V3_ENTITYNAMEUSER2.P$.MODULE$;
  public static final V3_ENTITYNAMEUSER2 PHON = V3_ENTITYNAMEUSER2.PHON$.MODULE$;
  public static final V3_ENTITYNAMEUSER2 R = V3_ENTITYNAMEUSER2.R$.MODULE$;
  public static final V3_ENTITYNAMEUSER2 SRCH = V3_ENTITYNAMEUSER2.SRCH$.MODULE$;
  public static final V3_ENTITYNAMEUSER2 SYL = V3_ENTITYNAMEUSER2.SYL$.MODULE$;
  public static final V3_ENTITYNAMEUSER2 T = V3_ENTITYNAMEUSER2.T$.MODULE$;
}
