// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/r4/core/codes.proto

package com.google.fhir.r4.core;

public interface AllergyIntoleranceTypeCodeOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:google.fhir.r4.core.AllergyIntoleranceTypeCode)
    com.google.protobuf.MessageOrBuilder {}
