// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/r4/core/resources/capability_statement.proto

package com.google.fhir.r4.core;

public final class CapabilityStatementOuterClass {
  private CapabilityStatementOuterClass() {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
  }

  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_fhir_r4_core_CapabilityStatement_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_fhir_r4_core_CapabilityStatement_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_fhir_r4_core_CapabilityStatement_StatusCode_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_fhir_r4_core_CapabilityStatement_StatusCode_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_fhir_r4_core_CapabilityStatement_KindCode_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_fhir_r4_core_CapabilityStatement_KindCode_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_fhir_r4_core_CapabilityStatement_Software_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_fhir_r4_core_CapabilityStatement_Software_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_fhir_r4_core_CapabilityStatement_Implementation_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_fhir_r4_core_CapabilityStatement_Implementation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_fhir_r4_core_CapabilityStatement_FhirVersionCode_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_fhir_r4_core_CapabilityStatement_FhirVersionCode_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_fhir_r4_core_CapabilityStatement_FormatCode_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_fhir_r4_core_CapabilityStatement_FormatCode_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_fhir_r4_core_CapabilityStatement_PatchFormatCode_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_fhir_r4_core_CapabilityStatement_PatchFormatCode_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_fhir_r4_core_CapabilityStatement_Rest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_fhir_r4_core_CapabilityStatement_Rest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_fhir_r4_core_CapabilityStatement_Rest_ModeCode_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_fhir_r4_core_CapabilityStatement_Rest_ModeCode_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_fhir_r4_core_CapabilityStatement_Rest_Security_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_fhir_r4_core_CapabilityStatement_Rest_Security_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_fhir_r4_core_CapabilityStatement_Rest_Resource_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_fhir_r4_core_CapabilityStatement_Rest_Resource_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_fhir_r4_core_CapabilityStatement_Rest_Resource_TypeCode_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_fhir_r4_core_CapabilityStatement_Rest_Resource_TypeCode_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_fhir_r4_core_CapabilityStatement_Rest_Resource_ResourceInteraction_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_fhir_r4_core_CapabilityStatement_Rest_Resource_ResourceInteraction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_fhir_r4_core_CapabilityStatement_Rest_Resource_ResourceInteraction_CodeType_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_fhir_r4_core_CapabilityStatement_Rest_Resource_ResourceInteraction_CodeType_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_fhir_r4_core_CapabilityStatement_Rest_Resource_VersioningCode_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_fhir_r4_core_CapabilityStatement_Rest_Resource_VersioningCode_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_fhir_r4_core_CapabilityStatement_Rest_Resource_ConditionalReadCode_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_fhir_r4_core_CapabilityStatement_Rest_Resource_ConditionalReadCode_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_fhir_r4_core_CapabilityStatement_Rest_Resource_ConditionalDeleteCode_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_fhir_r4_core_CapabilityStatement_Rest_Resource_ConditionalDeleteCode_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_fhir_r4_core_CapabilityStatement_Rest_Resource_ReferencePolicyCode_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_fhir_r4_core_CapabilityStatement_Rest_Resource_ReferencePolicyCode_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_fhir_r4_core_CapabilityStatement_Rest_Resource_SearchParam_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_fhir_r4_core_CapabilityStatement_Rest_Resource_SearchParam_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_fhir_r4_core_CapabilityStatement_Rest_Resource_SearchParam_TypeCode_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_fhir_r4_core_CapabilityStatement_Rest_Resource_SearchParam_TypeCode_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_fhir_r4_core_CapabilityStatement_Rest_Resource_Operation_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_fhir_r4_core_CapabilityStatement_Rest_Resource_Operation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_fhir_r4_core_CapabilityStatement_Rest_SystemInteraction_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_fhir_r4_core_CapabilityStatement_Rest_SystemInteraction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_fhir_r4_core_CapabilityStatement_Rest_SystemInteraction_CodeType_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_fhir_r4_core_CapabilityStatement_Rest_SystemInteraction_CodeType_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_fhir_r4_core_CapabilityStatement_Messaging_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_fhir_r4_core_CapabilityStatement_Messaging_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_fhir_r4_core_CapabilityStatement_Messaging_Endpoint_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_fhir_r4_core_CapabilityStatement_Messaging_Endpoint_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_fhir_r4_core_CapabilityStatement_Messaging_SupportedMessage_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_fhir_r4_core_CapabilityStatement_Messaging_SupportedMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_fhir_r4_core_CapabilityStatement_Messaging_SupportedMessage_ModeCode_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_fhir_r4_core_CapabilityStatement_Messaging_SupportedMessage_ModeCode_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_fhir_r4_core_CapabilityStatement_Document_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_fhir_r4_core_CapabilityStatement_Document_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_fhir_r4_core_CapabilityStatement_Document_ModeCode_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_fhir_r4_core_CapabilityStatement_Document_ModeCode_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
    return descriptor;
  }

  private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

  static {
    java.lang.String[] descriptorData = {
      "\n2proto/r4/core/resources/capability_sta"
          + "tement.proto\022\023google.fhir.r4.core\032\031googl"
          + "e/protobuf/any.proto\032\027proto/annotations."
          + "proto\032\031proto/r4/core/codes.proto\032\035proto/"
          + "r4/core/datatypes.proto\032\035proto/r4/core/v"
          + "aluesets.proto\"\215f\n\023CapabilityStatement\022#"
          + "\n\002id\030\001 \001(\0132\027.google.fhir.r4.core.Id\022\'\n\004m"
          + "eta\030\002 \001(\0132\031.google.fhir.r4.core.Meta\0220\n\016"
          + "implicit_rules\030\003 \001(\0132\030.google.fhir.r4.co"
          + "re.Uri\022+\n\010language\030\004 \001(\0132\031.google.fhir.r"
          + "4.core.Code\022,\n\004text\030\005 \001(\0132\036.google.fhir."
          + "r4.core.Narrative\022\'\n\tcontained\030\006 \003(\0132\024.g"
          + "oogle.protobuf.Any\0221\n\textension\030\010 \003(\0132\036."
          + "google.fhir.r4.core.Extension\022:\n\022modifie"
          + "r_extension\030\t \003(\0132\036.google.fhir.r4.core."
          + "Extension\022%\n\003url\030\n \001(\0132\030.google.fhir.r4."
          + "core.Uri\022,\n\007version\030\013 \001(\0132\033.google.fhir."
          + "r4.core.String\022)\n\004name\030\014 \001(\0132\033.google.fh"
          + "ir.r4.core.String\022*\n\005title\030\r \001(\0132\033.googl"
          + "e.fhir.r4.core.String\022K\n\006status\030\016 \001(\01323."
          + "google.fhir.r4.core.CapabilityStatement."
          + "StatusCodeB\006\360\320\207\353\004\001\0222\n\014experimental\030\017 \001(\013"
          + "2\034.google.fhir.r4.core.Boolean\0223\n\004date\030\020"
          + " \001(\0132\035.google.fhir.r4.core.DateTimeB\006\360\320\207"
          + "\353\004\001\022.\n\tpublisher\030\021 \001(\0132\033.google.fhir.r4."
          + "core.String\0223\n\007contact\030\022 \003(\0132\".google.fh"
          + "ir.r4.core.ContactDetail\0222\n\013description\030"
          + "\023 \001(\0132\035.google.fhir.r4.core.Markdown\0226\n\013"
          + "use_context\030\024 \003(\0132!.google.fhir.r4.core."
          + "UsageContext\022:\n\014jurisdiction\030\025 \003(\0132$.goo"
          + "gle.fhir.r4.core.CodeableConcept\022.\n\007purp"
          + "ose\030\026 \001(\0132\035.google.fhir.r4.core.Markdown"
          + "\0220\n\tcopyright\030\027 \001(\0132\035.google.fhir.r4.cor"
          + "e.Markdown\022G\n\004kind\030\030 \001(\01321.google.fhir.r"
          + "4.core.CapabilityStatement.KindCodeB\006\360\320\207"
          + "\353\004\001\0224\n\014instantiates\030\031 \003(\0132\036.google.fhir."
          + "r4.core.Canonical\022/\n\007imports\030\032 \003(\0132\036.goo"
          + "gle.fhir.r4.core.Canonical\022C\n\010software\030\033"
          + " \001(\01321.google.fhir.r4.core.CapabilitySta"
          + "tement.Software\022O\n\016implementation\030\034 \001(\0132"
          + "7.google.fhir.r4.core.CapabilityStatemen"
          + "t.Implementation\022V\n\014fhir_version\030\035 \001(\01328"
          + ".google.fhir.r4.core.CapabilityStatement"
          + ".FhirVersionCodeB\006\360\320\207\353\004\001\022K\n\006format\030\036 \003(\013"
          + "23.google.fhir.r4.core.CapabilityStateme"
          + "nt.FormatCodeB\006\360\320\207\353\004\001\022N\n\014patch_format\030\037 "
          + "\003(\01328.google.fhir.r4.core.CapabilityStat"
          + "ement.PatchFormatCode\022<\n\024implementation_"
          + "guide\030  \003(\0132\036.google.fhir.r4.core.Canoni"
          + "cal\022;\n\004rest\030! \003(\0132-.google.fhir.r4.core."
          + "CapabilityStatement.Rest\022E\n\tmessaging\030\" "
          + "\003(\01322.google.fhir.r4.core.CapabilityStat"
          + "ement.Messaging\022C\n\010document\030# \003(\01321.goog"
          + "le.fhir.r4.core.CapabilityStatement.Docu"
          + "ment\032\230\002\n\nStatusCode\022?\n\005value\030\001 \001(\01620.goo"
          + "gle.fhir.r4.core.PublicationStatusCode.V"
          + "alue\022\'\n\002id\030\002 \001(\0132\033.google.fhir.r4.core.S"
          + "tring\0221\n\textension\030\003 \003(\0132\036.google.fhir.r"
          + "4.core.Extension:m\300\237\343\266\005\001\212\371\203\262\005/http://hl7"
          + ".org/fhir/ValueSet/publication-status\232\265\216"
          + "\223\006,http://hl7.org/fhir/StructureDefiniti"
          + "on/code\032\243\002\n\010KindCode\022E\n\005value\030\001 \001(\01626.go"
          + "ogle.fhir.r4.core.CapabilityStatementKin"
          + "dCode.Value\022\'\n\002id\030\002 \001(\0132\033.google.fhir.r4"
          + ".core.String\0221\n\textension\030\003 \003(\0132\036.google"
          + ".fhir.r4.core.Extension:t\300\237\343\266\005\001\212\371\203\262\0056htt"
          + "p://hl7.org/fhir/ValueSet/capability-sta"
          + "tement-kind\232\265\216\223\006,http://hl7.org/fhir/Str"
          + "uctureDefinition/code\032\270\002\n\010Software\022\'\n\002id"
          + "\030\001 \001(\0132\033.google.fhir.r4.core.String\0221\n\te"
          + "xtension\030\002 \003(\0132\036.google.fhir.r4.core.Ext"
          + "ension\022:\n\022modifier_extension\030\003 \003(\0132\036.goo"
          + "gle.fhir.r4.core.Extension\0221\n\004name\030\004 \001(\013"
          + "2\033.google.fhir.r4.core.StringB\006\360\320\207\353\004\001\022,\n"
          + "\007version\030\005 \001(\0132\033.google.fhir.r4.core.Str"
          + "ing\0223\n\014release_date\030\006 \001(\0132\035.google.fhir."
          + "r4.core.DateTime\032\320\002\n\016Implementation\022\'\n\002i"
          + "d\030\001 \001(\0132\033.google.fhir.r4.core.String\0221\n\t"
          + "extension\030\002 \003(\0132\036.google.fhir.r4.core.Ex"
          + "tension\022:\n\022modifier_extension\030\003 \003(\0132\036.go"
          + "ogle.fhir.r4.core.Extension\0228\n\013descripti"
          + "on\030\004 \001(\0132\033.google.fhir.r4.core.StringB\006\360"
          + "\320\207\353\004\001\022%\n\003url\030\005 \001(\0132\030.google.fhir.r4.core"
          + ".Url\022E\n\tcustodian\030\006 \001(\0132\036.google.fhir.r4"
          + ".core.ReferenceB\022\362\377\374\302\006\014Organization\032\221\002\n\017"
          + "FhirVersionCode\0229\n\005value\030\001 \001(\0162*.google."
          + "fhir.r4.core.FHIRVersionCode.Value\022\'\n\002id"
          + "\030\002 \001(\0132\033.google.fhir.r4.core.String\0221\n\te"
          + "xtension\030\003 \003(\0132\036.google.fhir.r4.core.Ext"
          + "ension:g\300\237\343\266\005\001\212\371\203\262\005)http://hl7.org/fhir/"
          + "ValueSet/FHIR-version\232\265\216\223\006,http://hl7.or"
          + "g/fhir/StructureDefinition/code\032\343\001\n\nForm"
          + "atCode\022\'\n\002id\030\002 \001(\0132\033.google.fhir.r4.core"
          + ".String\0221\n\textension\030\003 \003(\0132\036.google.fhir"
          + ".r4.core.Extension\022\r\n\005value\030\004 \001(\t:d\300\237\343\266\005"
          + "\001\212\371\203\262\005&http://hl7.org/fhir/ValueSet/mime"
          + "types\232\265\216\223\006,http://hl7.org/fhir/Structure"
          + "Definition/codeJ\004\010\001\020\002\032\350\001\n\017PatchFormatCod"
          + "e\022\'\n\002id\030\002 \001(\0132\033.google.fhir.r4.core.Stri"
          + "ng\0221\n\textension\030\003 \003(\0132\036.google.fhir.r4.c"
          + "ore.Extension\022\r\n\005value\030\004 \001(\t:d\300\237\343\266\005\001\212\371\203\262"
          + "\005&http://hl7.org/fhir/ValueSet/mimetypes"
          + "\232\265\216\223\006,http://hl7.org/fhir/StructureDefin"
          + "ition/codeJ\004\010\001\020\002\032\3443\n\004Rest\022\'\n\002id\030\001 \001(\0132\033."
          + "google.fhir.r4.core.String\0221\n\textension\030"
          + "\002 \003(\0132\036.google.fhir.r4.core.Extension\022:\n"
          + "\022modifier_extension\030\003 \003(\0132\036.google.fhir."
          + "r4.core.Extension\022L\n\004mode\030\004 \001(\01326.google"
          + ".fhir.r4.core.CapabilityStatement.Rest.M"
          + "odeCodeB\006\360\320\207\353\004\001\0224\n\rdocumentation\030\005 \001(\0132\035"
          + ".google.fhir.r4.core.Markdown\022H\n\010securit"
          + "y\030\006 \001(\01326.google.fhir.r4.core.Capability"
          + "Statement.Rest.Security\022H\n\010resource\030\007 \003("
          + "\01326.google.fhir.r4.core.CapabilityStatem"
          + "ent.Rest.Resource\022T\n\013interaction\030\010 \003(\0132?"
          + ".google.fhir.r4.core.CapabilityStatement"
          + ".Rest.SystemInteraction\022X\n\014search_param\030"
          + "\t \003(\0132B.google.fhir.r4.core.CapabilitySt"
          + "atement.Rest.Resource.SearchParam\022S\n\tope"
          + "ration\030\n \003(\0132@.google.fhir.r4.core.Capab"
          + "ilityStatement.Rest.Resource.Operation\0223"
          + "\n\013compartment\030\013 \003(\0132\036.google.fhir.r4.cor"
          + "e.Canonical\032\237\002\n\010ModeCode\022C\n\005value\030\001 \001(\0162"
          + "4.google.fhir.r4.core.RestfulCapabilityM"
          + "odeCode.Value\022\'\n\002id\030\002 \001(\0132\033.google.fhir."
          + "r4.core.String\0221\n\textension\030\003 \003(\0132\036.goog"
          + "le.fhir.r4.core.Extension:r\300\237\343\266\005\001\212\371\203\262\0054h"
          + "ttp://hl7.org/fhir/ValueSet/restful-capa"
          + "bility-mode\232\265\216\223\006,http://hl7.org/fhir/Str"
          + "uctureDefinition/code\032\271\002\n\010Security\022\'\n\002id"
          + "\030\001 \001(\0132\033.google.fhir.r4.core.String\0221\n\te"
          + "xtension\030\002 \003(\0132\036.google.fhir.r4.core.Ext"
          + "ension\022:\n\022modifier_extension\030\003 \003(\0132\036.goo"
          + "gle.fhir.r4.core.Extension\022*\n\004cors\030\004 \001(\013"
          + "2\034.google.fhir.r4.core.Boolean\0225\n\007servic"
          + "e\030\005 \003(\0132$.google.fhir.r4.core.CodeableCo"
          + "ncept\0222\n\013description\030\006 \001(\0132\035.google.fhir"
          + ".r4.core.Markdown\032\371#\n\010Resource\022\'\n\002id\030\001 \001"
          + "(\0132\033.google.fhir.r4.core.String\0221\n\texten"
          + "sion\030\002 \003(\0132\036.google.fhir.r4.core.Extensi"
          + "on\022:\n\022modifier_extension\030\003 \003(\0132\036.google."
          + "fhir.r4.core.Extension\022U\n\004type\030\004 \001(\0132?.g"
          + "oogle.fhir.r4.core.CapabilityStatement.R"
          + "est.Resource.TypeCodeB\006\360\320\207\353\004\001\022/\n\007profile"
          + "\030\005 \001(\0132\036.google.fhir.r4.core.Canonical\0229"
          + "\n\021supported_profile\030\006 \003(\0132\036.google.fhir."
          + "r4.core.Canonical\0224\n\rdocumentation\030\007 \001(\013"
          + "2\035.google.fhir.r4.core.Markdown\022_\n\013inter"
          + "action\030\010 \003(\0132J.google.fhir.r4.core.Capab"
          + "ilityStatement.Rest.Resource.ResourceInt"
          + "eraction\022Y\n\nversioning\030\t \001(\0132E.google.fh"
          + "ir.r4.core.CapabilityStatement.Rest.Reso"
          + "urce.VersioningCode\0222\n\014read_history\030\n \001("
          + "\0132\034.google.fhir.r4.core.Boolean\0223\n\rupdat"
          + "e_create\030\013 \001(\0132\034.google.fhir.r4.core.Boo"
          + "lean\0228\n\022conditional_create\030\014 \001(\0132\034.googl"
          + "e.fhir.r4.core.Boolean\022d\n\020conditional_re"
          + "ad\030\r \001(\0132J.google.fhir.r4.core.Capabilit"
          + "yStatement.Rest.Resource.ConditionalRead"
          + "Code\0228\n\022conditional_update\030\016 \001(\0132\034.googl"
          + "e.fhir.r4.core.Boolean\022h\n\022conditional_de"
          + "lete\030\017 \001(\0132L.google.fhir.r4.core.Capabil"
          + "ityStatement.Rest.Resource.ConditionalDe"
          + "leteCode\022d\n\020reference_policy\030\020 \003(\0132J.goo"
          + "gle.fhir.r4.core.CapabilityStatement.Res"
          + "t.Resource.ReferencePolicyCode\0223\n\016search"
          + "_include\030\021 \003(\0132\033.google.fhir.r4.core.Str"
          + "ing\0227\n\022search_rev_include\030\022 \003(\0132\033.google"
          + ".fhir.r4.core.String\022X\n\014search_param\030\023 \003"
          + "(\0132B.google.fhir.r4.core.CapabilityState"
          + "ment.Rest.Resource.SearchParam\022S\n\toperat"
          + "ion\030\024 \003(\0132@.google.fhir.r4.core.Capabili"
          + "tyStatement.Rest.Resource.Operation\032\215\002\n\010"
          + "TypeCode\022:\n\005value\030\001 \001(\0162+.google.fhir.r4"
          + ".core.ResourceTypeCode.Value\022\'\n\002id\030\002 \001(\013"
          + "2\033.google.fhir.r4.core.String\0221\n\textensi"
          + "on\030\003 \003(\0132\036.google.fhir.r4.core.Extension"
          + ":i\300\237\343\266\005\001\212\371\203\262\005+http://hl7.org/fhir/ValueS"
          + "et/resource-types\232\265\216\223\006,http://hl7.org/fh"
          + "ir/StructureDefinition/code\032\366\004\n\023Resource"
          + "Interaction\022\'\n\002id\030\001 \001(\0132\033.google.fhir.r4"
          + ".core.String\0221\n\textension\030\002 \003(\0132\036.google"
          + ".fhir.r4.core.Extension\022:\n\022modifier_exte"
          + "nsion\030\003 \003(\0132\036.google.fhir.r4.core.Extens"
          + "ion\022i\n\004code\030\004 \001(\0132S.google.fhir.r4.core."
          + "CapabilityStatement.Rest.Resource.Resour"
          + "ceInteraction.CodeTypeB\006\360\320\207\353\004\001\0224\n\rdocume"
          + "ntation\030\005 \001(\0132\035.google.fhir.r4.core.Mark"
          + "down\032\245\002\n\010CodeType\022H\n\005value\030\001 \001(\01629.googl"
          + "e.fhir.r4.core.TypeRestfulInteractionVal"
          + "ueSet.Value\022\'\n\002id\030\002 \001(\0132\033.google.fhir.r4"
          + ".core.String\0221\n\textension\030\003 \003(\0132\036.google"
          + ".fhir.r4.core.Extension:s\300\237\343\266\005\001\212\371\203\262\0055htt"
          + "p://hl7.org/fhir/ValueSet/type-restful-i"
          + "nteraction\232\265\216\223\006,http://hl7.org/fhir/Stru"
          + "ctureDefinition/code\032\237\002\n\016VersioningCode\022"
          + "C\n\005value\030\001 \001(\01624.google.fhir.r4.core.Res"
          + "ourceVersionPolicyCode.Value\022\'\n\002id\030\002 \001(\013"
          + "2\033.google.fhir.r4.core.String\0221\n\textensi"
          + "on\030\003 \003(\0132\036.google.fhir.r4.core.Extension"
          + ":l\300\237\343\266\005\001\212\371\203\262\005.http://hl7.org/fhir/ValueS"
          + "et/versioning-policy\232\265\216\223\006,http://hl7.org"
          + "/fhir/StructureDefinition/code\032\252\002\n\023Condi"
          + "tionalReadCode\022C\n\005value\030\001 \001(\01624.google.f"
          + "hir.r4.core.ConditionalReadStatusCode.Va"
          + "lue\022\'\n\002id\030\002 \001(\0132\033.google.fhir.r4.core.St"
          + "ring\0221\n\textension\030\003 \003(\0132\036.google.fhir.r4"
          + ".core.Extension:r\300\237\343\266\005\001\212\371\203\262\0054http://hl7."
          + "org/fhir/ValueSet/conditional-read-statu"
          + "s\232\265\216\223\006,http://hl7.org/fhir/StructureDefi"
          + "nition/code\032\260\002\n\025ConditionalDeleteCode\022E\n"
          + "\005value\030\001 \001(\01626.google.fhir.r4.core.Condi"
          + "tionalDeleteStatusCode.Value\022\'\n\002id\030\002 \001(\013"
          + "2\033.google.fhir.r4.core.String\0221\n\textensi"
          + "on\030\003 \003(\0132\036.google.fhir.r4.core.Extension"
          + ":t\300\237\343\266\005\001\212\371\203\262\0056http://hl7.org/fhir/ValueS"
          + "et/conditional-delete-status\232\265\216\223\006,http:/"
          + "/hl7.org/fhir/StructureDefinition/code\032\256"
          + "\002\n\023ReferencePolicyCode\022E\n\005value\030\001 \001(\01626."
          + "google.fhir.r4.core.ReferenceHandlingPol"
          + "icyCode.Value\022\'\n\002id\030\002 \001(\0132\033.google.fhir."
          + "r4.core.String\0221\n\textension\030\003 \003(\0132\036.goog"
          + "le.fhir.r4.core.Extension:t\300\237\343\266\005\001\212\371\203\262\0056h"
          + "ttp://hl7.org/fhir/ValueSet/reference-ha"
          + "ndling-policy\232\265\216\223\006,http://hl7.org/fhir/S"
          + "tructureDefinition/code\032\273\005\n\013SearchParam\022"
          + "\'\n\002id\030\001 \001(\0132\033.google.fhir.r4.core.String"
          + "\0221\n\textension\030\002 \003(\0132\036.google.fhir.r4.cor"
          + "e.Extension\022:\n\022modifier_extension\030\003 \003(\0132"
          + "\036.google.fhir.r4.core.Extension\0221\n\004name\030"
          + "\004 \001(\0132\033.google.fhir.r4.core.StringB\006\360\320\207\353"
          + "\004\001\0222\n\ndefinition\030\005 \001(\0132\036.google.fhir.r4."
          + "core.Canonical\022a\n\004type\030\006 \001(\0132K.google.fh"
          + "ir.r4.core.CapabilityStatement.Rest.Reso"
          + "urce.SearchParam.TypeCodeB\006\360\320\207\353\004\001\0224\n\rdoc"
          + "umentation\030\007 \001(\0132\035.google.fhir.r4.core.M"
          + "arkdown\032\223\002\n\010TypeCode\022=\n\005value\030\001 \001(\0162..go"
          + "ogle.fhir.r4.core.SearchParamTypeCode.Va"
          + "lue\022\'\n\002id\030\002 \001(\0132\033.google.fhir.r4.core.St"
          + "ring\0221\n\textension\030\003 \003(\0132\036.google.fhir.r4"
          + ".core.Extension:l\300\237\343\266\005\001\212\371\203\262\005.http://hl7."
          + "org/fhir/ValueSet/search-param-type\232\265\216\223\006"
          + ",http://hl7.org/fhir/StructureDefinition"
          + "/code\032\310\002\n\tOperation\022\'\n\002id\030\001 \001(\0132\033.google"
          + ".fhir.r4.core.String\0221\n\textension\030\002 \003(\0132"
          + "\036.google.fhir.r4.core.Extension\022:\n\022modif"
          + "ier_extension\030\003 \003(\0132\036.google.fhir.r4.cor"
          + "e.Extension\0221\n\004name\030\004 \001(\0132\033.google.fhir."
          + "r4.core.StringB\006\360\320\207\353\004\001\022:\n\ndefinition\030\005 \001"
          + "(\0132\036.google.fhir.r4.core.CanonicalB\006\360\320\207\353"
          + "\004\001\0224\n\rdocumentation\030\006 \001(\0132\035.google.fhir."
          + "r4.core.Markdown:+\232\206\223\240\010%searchParam.sele"
          + "ct(name).isDistinct()\032\355\004\n\021SystemInteract"
          + "ion\022\'\n\002id\030\001 \001(\0132\033.google.fhir.r4.core.St"
          + "ring\0221\n\textension\030\002 \003(\0132\036.google.fhir.r4"
          + ".core.Extension\022:\n\022modifier_extension\030\003 "
          + "\003(\0132\036.google.fhir.r4.core.Extension\022^\n\004c"
          + "ode\030\004 \001(\0132H.google.fhir.r4.core.Capabili"
          + "tyStatement.Rest.SystemInteraction.CodeT"
          + "ypeB\006\360\320\207\353\004\001\0224\n\rdocumentation\030\005 \001(\0132\035.goo"
          + "gle.fhir.r4.core.Markdown\032\251\002\n\010CodeType\022J"
          + "\n\005value\030\001 \001(\0162;.google.fhir.r4.core.Syst"
          + "emRestfulInteractionValueSet.Value\022\'\n\002id"
          + "\030\002 \001(\0132\033.google.fhir.r4.core.String\0221\n\te"
          + "xtension\030\003 \003(\0132\036.google.fhir.r4.core.Ext"
          + "ension:u\300\237\343\266\005\001\212\371\203\262\0057http://hl7.org/fhir/"
          + "ValueSet/system-restful-interaction\232\265\216\223\006"
          + ",http://hl7.org/fhir/StructureDefinition"
          + "/code:(\232\206\223\240\010\"resource.select(type).isDis"
          + "tinct()\032\274\n\n\tMessaging\022\'\n\002id\030\001 \001(\0132\033.goog"
          + "le.fhir.r4.core.String\0221\n\textension\030\002 \003("
          + "\0132\036.google.fhir.r4.core.Extension\022:\n\022mod"
          + "ifier_extension\030\003 \003(\0132\036.google.fhir.r4.c"
          + "ore.Extension\022M\n\010endpoint\030\004 \003(\0132;.google"
          + ".fhir.r4.core.CapabilityStatement.Messag"
          + "ing.Endpoint\0228\n\016reliable_cache\030\005 \001(\0132 .g"
          + "oogle.fhir.r4.core.UnsignedInt\0224\n\rdocume"
          + "ntation\030\006 \001(\0132\035.google.fhir.r4.core.Mark"
          + "down\022^\n\021supported_message\030\007 \003(\0132C.google"
          + ".fhir.r4.core.CapabilityStatement.Messag"
          + "ing.SupportedMessage\032\214\002\n\010Endpoint\022\'\n\002id\030"
          + "\001 \001(\0132\033.google.fhir.r4.core.String\0221\n\tex"
          + "tension\030\002 \003(\0132\036.google.fhir.r4.core.Exte"
          + "nsion\022:\n\022modifier_extension\030\003 \003(\0132\036.goog"
          + "le.fhir.r4.core.Extension\0225\n\010protocol\030\004 "
          + "\001(\0132\033.google.fhir.r4.core.CodingB\006\360\320\207\353\004\001"
          + "\0221\n\007address\030\005 \001(\0132\030.google.fhir.r4.core."
          + "UrlB\006\360\320\207\353\004\001\032\350\004\n\020SupportedMessage\022\'\n\002id\030\001"
          + " \001(\0132\033.google.fhir.r4.core.String\0221\n\text"
          + "ension\030\002 \003(\0132\036.google.fhir.r4.core.Exten"
          + "sion\022:\n\022modifier_extension\030\003 \003(\0132\036.googl"
          + "e.fhir.r4.core.Extension\022b\n\004mode\030\004 \001(\0132L"
          + ".google.fhir.r4.core.CapabilityStatement"
          + ".Messaging.SupportedMessage.ModeCodeB\006\360\320"
          + "\207\353\004\001\022:\n\ndefinition\030\005 \001(\0132\036.google.fhir.r"
          + "4.core.CanonicalB\006\360\320\207\353\004\001\032\233\002\n\010ModeCode\022A\n"
          + "\005value\030\001 \001(\01622.google.fhir.r4.core.Event"
          + "CapabilityModeCode.Value\022\'\n\002id\030\002 \001(\0132\033.g"
          + "oogle.fhir.r4.core.String\0221\n\textension\030\003"
          + " \003(\0132\036.google.fhir.r4.core.Extension:p\300\237"
          + "\343\266\005\001\212\371\203\262\0052http://hl7.org/fhir/ValueSet/e"
          + "vent-capability-mode\232\265\216\223\006,http://hl7.org"
          + "/fhir/StructureDefinition/code\032\362\004\n\010Docum"
          + "ent\022\'\n\002id\030\001 \001(\0132\033.google.fhir.r4.core.St"
          + "ring\0221\n\textension\030\002 \003(\0132\036.google.fhir.r4"
          + ".core.Extension\022:\n\022modifier_extension\030\003 "
          + "\003(\0132\036.google.fhir.r4.core.Extension\022P\n\004m"
          + "ode\030\004 \001(\0132:.google.fhir.r4.core.Capabili"
          + "tyStatement.Document.ModeCodeB\006\360\320\207\353\004\001\0224\n"
          + "\rdocumentation\030\005 \001(\0132\035.google.fhir.r4.co"
          + "re.Markdown\0227\n\007profile\030\006 \001(\0132\036.google.fh"
          + "ir.r4.core.CanonicalB\006\360\320\207\353\004\001\032\214\002\n\010ModeCod"
          + "e\022:\n\005value\030\001 \001(\0162+.google.fhir.r4.core.D"
          + "ocumentModeCode.Value\022\'\n\002id\030\002 \001(\0132\033.goog"
          + "le.fhir.r4.core.String\0221\n\textension\030\003 \003("
          + "\0132\036.google.fhir.r4.core.Extension:h\300\237\343\266\005"
          + "\001\212\371\203\262\005*http://hl7.org/fhir/ValueSet/docu"
          + "ment-mode\232\265\216\223\006,http://hl7.org/fhir/Struc"
          + "tureDefinition/code:\232\004\300\237\343\266\005\003\262\376\344\227\006;http:/"
          + "/hl7.org/fhir/StructureDefinition/Capabi"
          + "lityStatement\232\206\223\240\0108rest.exists() or mess"
          + "aging.exists() or document.exists()\232\206\223\240\010"
          + "E(description.count() + software.count()"
          + " + implementation.count()) > 0\232\206\223\240\010/mess"
          + "aging.endpoint.empty() or kind = \'instan"
          + "ce\'\232\206\223\240\010*document.select(profile&mode).i"
          + "sDistinct()\232\206\223\240\010/(kind != \'instance\') or"
          + " implementation.exists()\232\206\223\240\010O(kind != \'"
          + "capability\') or (implementation.exists()"
          + ".not() and software.exists())\232\206\223\240\010U(kind"
          + "!=\'requirements\') or (implementation.exi"
          + "sts().not() and software.exists().not())"
          + "J\004\010\007\020\010B!\n\027com.google.fhir.r4.coreP\001\230\306\260\265\007"
          + "\004b\006proto3"
    };
    descriptor =
        com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(
            descriptorData,
            new com.google.protobuf.Descriptors.FileDescriptor[] {
              com.google.protobuf.AnyProto.getDescriptor(),
              com.google.fhir.proto.Annotations.getDescriptor(),
              com.google.fhir.r4.core.Codes.getDescriptor(),
              com.google.fhir.r4.core.Datatypes.getDescriptor(),
              com.google.fhir.r4.core.Valuesets.getDescriptor(),
            });
    internal_static_google_fhir_r4_core_CapabilityStatement_descriptor =
        getDescriptor().getMessageTypes().get(0);
    internal_static_google_fhir_r4_core_CapabilityStatement_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_fhir_r4_core_CapabilityStatement_descriptor,
            new java.lang.String[] {
              "Id",
              "Meta",
              "ImplicitRules",
              "Language",
              "Text",
              "Contained",
              "Extension",
              "ModifierExtension",
              "Url",
              "Version",
              "Name",
              "Title",
              "Status",
              "Experimental",
              "Date",
              "Publisher",
              "Contact",
              "Description",
              "UseContext",
              "Jurisdiction",
              "Purpose",
              "Copyright",
              "Kind",
              "Instantiates",
              "Imports",
              "Software",
              "Implementation",
              "FhirVersion",
              "Format",
              "PatchFormat",
              "ImplementationGuide",
              "Rest",
              "Messaging",
              "Document",
            });
    internal_static_google_fhir_r4_core_CapabilityStatement_StatusCode_descriptor =
        internal_static_google_fhir_r4_core_CapabilityStatement_descriptor.getNestedTypes().get(0);
    internal_static_google_fhir_r4_core_CapabilityStatement_StatusCode_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_fhir_r4_core_CapabilityStatement_StatusCode_descriptor,
            new java.lang.String[] {
              "Value", "Id", "Extension",
            });
    internal_static_google_fhir_r4_core_CapabilityStatement_KindCode_descriptor =
        internal_static_google_fhir_r4_core_CapabilityStatement_descriptor.getNestedTypes().get(1);
    internal_static_google_fhir_r4_core_CapabilityStatement_KindCode_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_fhir_r4_core_CapabilityStatement_KindCode_descriptor,
            new java.lang.String[] {
              "Value", "Id", "Extension",
            });
    internal_static_google_fhir_r4_core_CapabilityStatement_Software_descriptor =
        internal_static_google_fhir_r4_core_CapabilityStatement_descriptor.getNestedTypes().get(2);
    internal_static_google_fhir_r4_core_CapabilityStatement_Software_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_fhir_r4_core_CapabilityStatement_Software_descriptor,
            new java.lang.String[] {
              "Id", "Extension", "ModifierExtension", "Name", "Version", "ReleaseDate",
            });
    internal_static_google_fhir_r4_core_CapabilityStatement_Implementation_descriptor =
        internal_static_google_fhir_r4_core_CapabilityStatement_descriptor.getNestedTypes().get(3);
    internal_static_google_fhir_r4_core_CapabilityStatement_Implementation_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_fhir_r4_core_CapabilityStatement_Implementation_descriptor,
            new java.lang.String[] {
              "Id", "Extension", "ModifierExtension", "Description", "Url", "Custodian",
            });
    internal_static_google_fhir_r4_core_CapabilityStatement_FhirVersionCode_descriptor =
        internal_static_google_fhir_r4_core_CapabilityStatement_descriptor.getNestedTypes().get(4);
    internal_static_google_fhir_r4_core_CapabilityStatement_FhirVersionCode_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_fhir_r4_core_CapabilityStatement_FhirVersionCode_descriptor,
            new java.lang.String[] {
              "Value", "Id", "Extension",
            });
    internal_static_google_fhir_r4_core_CapabilityStatement_FormatCode_descriptor =
        internal_static_google_fhir_r4_core_CapabilityStatement_descriptor.getNestedTypes().get(5);
    internal_static_google_fhir_r4_core_CapabilityStatement_FormatCode_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_fhir_r4_core_CapabilityStatement_FormatCode_descriptor,
            new java.lang.String[] {
              "Id", "Extension", "Value",
            });
    internal_static_google_fhir_r4_core_CapabilityStatement_PatchFormatCode_descriptor =
        internal_static_google_fhir_r4_core_CapabilityStatement_descriptor.getNestedTypes().get(6);
    internal_static_google_fhir_r4_core_CapabilityStatement_PatchFormatCode_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_fhir_r4_core_CapabilityStatement_PatchFormatCode_descriptor,
            new java.lang.String[] {
              "Id", "Extension", "Value",
            });
    internal_static_google_fhir_r4_core_CapabilityStatement_Rest_descriptor =
        internal_static_google_fhir_r4_core_CapabilityStatement_descriptor.getNestedTypes().get(7);
    internal_static_google_fhir_r4_core_CapabilityStatement_Rest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_fhir_r4_core_CapabilityStatement_Rest_descriptor,
            new java.lang.String[] {
              "Id",
              "Extension",
              "ModifierExtension",
              "Mode",
              "Documentation",
              "Security",
              "Resource",
              "Interaction",
              "SearchParam",
              "Operation",
              "Compartment",
            });
    internal_static_google_fhir_r4_core_CapabilityStatement_Rest_ModeCode_descriptor =
        internal_static_google_fhir_r4_core_CapabilityStatement_Rest_descriptor
            .getNestedTypes()
            .get(0);
    internal_static_google_fhir_r4_core_CapabilityStatement_Rest_ModeCode_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_fhir_r4_core_CapabilityStatement_Rest_ModeCode_descriptor,
            new java.lang.String[] {
              "Value", "Id", "Extension",
            });
    internal_static_google_fhir_r4_core_CapabilityStatement_Rest_Security_descriptor =
        internal_static_google_fhir_r4_core_CapabilityStatement_Rest_descriptor
            .getNestedTypes()
            .get(1);
    internal_static_google_fhir_r4_core_CapabilityStatement_Rest_Security_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_fhir_r4_core_CapabilityStatement_Rest_Security_descriptor,
            new java.lang.String[] {
              "Id", "Extension", "ModifierExtension", "Cors", "Service", "Description",
            });
    internal_static_google_fhir_r4_core_CapabilityStatement_Rest_Resource_descriptor =
        internal_static_google_fhir_r4_core_CapabilityStatement_Rest_descriptor
            .getNestedTypes()
            .get(2);
    internal_static_google_fhir_r4_core_CapabilityStatement_Rest_Resource_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_fhir_r4_core_CapabilityStatement_Rest_Resource_descriptor,
            new java.lang.String[] {
              "Id",
              "Extension",
              "ModifierExtension",
              "Type",
              "Profile",
              "SupportedProfile",
              "Documentation",
              "Interaction",
              "Versioning",
              "ReadHistory",
              "UpdateCreate",
              "ConditionalCreate",
              "ConditionalRead",
              "ConditionalUpdate",
              "ConditionalDelete",
              "ReferencePolicy",
              "SearchInclude",
              "SearchRevInclude",
              "SearchParam",
              "Operation",
            });
    internal_static_google_fhir_r4_core_CapabilityStatement_Rest_Resource_TypeCode_descriptor =
        internal_static_google_fhir_r4_core_CapabilityStatement_Rest_Resource_descriptor
            .getNestedTypes()
            .get(0);
    internal_static_google_fhir_r4_core_CapabilityStatement_Rest_Resource_TypeCode_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_fhir_r4_core_CapabilityStatement_Rest_Resource_TypeCode_descriptor,
            new java.lang.String[] {
              "Value", "Id", "Extension",
            });
    internal_static_google_fhir_r4_core_CapabilityStatement_Rest_Resource_ResourceInteraction_descriptor =
        internal_static_google_fhir_r4_core_CapabilityStatement_Rest_Resource_descriptor
            .getNestedTypes()
            .get(1);
    internal_static_google_fhir_r4_core_CapabilityStatement_Rest_Resource_ResourceInteraction_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_fhir_r4_core_CapabilityStatement_Rest_Resource_ResourceInteraction_descriptor,
            new java.lang.String[] {
              "Id", "Extension", "ModifierExtension", "Code", "Documentation",
            });
    internal_static_google_fhir_r4_core_CapabilityStatement_Rest_Resource_ResourceInteraction_CodeType_descriptor =
        internal_static_google_fhir_r4_core_CapabilityStatement_Rest_Resource_ResourceInteraction_descriptor
            .getNestedTypes()
            .get(0);
    internal_static_google_fhir_r4_core_CapabilityStatement_Rest_Resource_ResourceInteraction_CodeType_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_fhir_r4_core_CapabilityStatement_Rest_Resource_ResourceInteraction_CodeType_descriptor,
            new java.lang.String[] {
              "Value", "Id", "Extension",
            });
    internal_static_google_fhir_r4_core_CapabilityStatement_Rest_Resource_VersioningCode_descriptor =
        internal_static_google_fhir_r4_core_CapabilityStatement_Rest_Resource_descriptor
            .getNestedTypes()
            .get(2);
    internal_static_google_fhir_r4_core_CapabilityStatement_Rest_Resource_VersioningCode_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_fhir_r4_core_CapabilityStatement_Rest_Resource_VersioningCode_descriptor,
            new java.lang.String[] {
              "Value", "Id", "Extension",
            });
    internal_static_google_fhir_r4_core_CapabilityStatement_Rest_Resource_ConditionalReadCode_descriptor =
        internal_static_google_fhir_r4_core_CapabilityStatement_Rest_Resource_descriptor
            .getNestedTypes()
            .get(3);
    internal_static_google_fhir_r4_core_CapabilityStatement_Rest_Resource_ConditionalReadCode_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_fhir_r4_core_CapabilityStatement_Rest_Resource_ConditionalReadCode_descriptor,
            new java.lang.String[] {
              "Value", "Id", "Extension",
            });
    internal_static_google_fhir_r4_core_CapabilityStatement_Rest_Resource_ConditionalDeleteCode_descriptor =
        internal_static_google_fhir_r4_core_CapabilityStatement_Rest_Resource_descriptor
            .getNestedTypes()
            .get(4);
    internal_static_google_fhir_r4_core_CapabilityStatement_Rest_Resource_ConditionalDeleteCode_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_fhir_r4_core_CapabilityStatement_Rest_Resource_ConditionalDeleteCode_descriptor,
            new java.lang.String[] {
              "Value", "Id", "Extension",
            });
    internal_static_google_fhir_r4_core_CapabilityStatement_Rest_Resource_ReferencePolicyCode_descriptor =
        internal_static_google_fhir_r4_core_CapabilityStatement_Rest_Resource_descriptor
            .getNestedTypes()
            .get(5);
    internal_static_google_fhir_r4_core_CapabilityStatement_Rest_Resource_ReferencePolicyCode_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_fhir_r4_core_CapabilityStatement_Rest_Resource_ReferencePolicyCode_descriptor,
            new java.lang.String[] {
              "Value", "Id", "Extension",
            });
    internal_static_google_fhir_r4_core_CapabilityStatement_Rest_Resource_SearchParam_descriptor =
        internal_static_google_fhir_r4_core_CapabilityStatement_Rest_Resource_descriptor
            .getNestedTypes()
            .get(6);
    internal_static_google_fhir_r4_core_CapabilityStatement_Rest_Resource_SearchParam_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_fhir_r4_core_CapabilityStatement_Rest_Resource_SearchParam_descriptor,
            new java.lang.String[] {
              "Id", "Extension", "ModifierExtension", "Name", "Definition", "Type", "Documentation",
            });
    internal_static_google_fhir_r4_core_CapabilityStatement_Rest_Resource_SearchParam_TypeCode_descriptor =
        internal_static_google_fhir_r4_core_CapabilityStatement_Rest_Resource_SearchParam_descriptor
            .getNestedTypes()
            .get(0);
    internal_static_google_fhir_r4_core_CapabilityStatement_Rest_Resource_SearchParam_TypeCode_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_fhir_r4_core_CapabilityStatement_Rest_Resource_SearchParam_TypeCode_descriptor,
            new java.lang.String[] {
              "Value", "Id", "Extension",
            });
    internal_static_google_fhir_r4_core_CapabilityStatement_Rest_Resource_Operation_descriptor =
        internal_static_google_fhir_r4_core_CapabilityStatement_Rest_Resource_descriptor
            .getNestedTypes()
            .get(7);
    internal_static_google_fhir_r4_core_CapabilityStatement_Rest_Resource_Operation_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_fhir_r4_core_CapabilityStatement_Rest_Resource_Operation_descriptor,
            new java.lang.String[] {
              "Id", "Extension", "ModifierExtension", "Name", "Definition", "Documentation",
            });
    internal_static_google_fhir_r4_core_CapabilityStatement_Rest_SystemInteraction_descriptor =
        internal_static_google_fhir_r4_core_CapabilityStatement_Rest_descriptor
            .getNestedTypes()
            .get(3);
    internal_static_google_fhir_r4_core_CapabilityStatement_Rest_SystemInteraction_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_fhir_r4_core_CapabilityStatement_Rest_SystemInteraction_descriptor,
            new java.lang.String[] {
              "Id", "Extension", "ModifierExtension", "Code", "Documentation",
            });
    internal_static_google_fhir_r4_core_CapabilityStatement_Rest_SystemInteraction_CodeType_descriptor =
        internal_static_google_fhir_r4_core_CapabilityStatement_Rest_SystemInteraction_descriptor
            .getNestedTypes()
            .get(0);
    internal_static_google_fhir_r4_core_CapabilityStatement_Rest_SystemInteraction_CodeType_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_fhir_r4_core_CapabilityStatement_Rest_SystemInteraction_CodeType_descriptor,
            new java.lang.String[] {
              "Value", "Id", "Extension",
            });
    internal_static_google_fhir_r4_core_CapabilityStatement_Messaging_descriptor =
        internal_static_google_fhir_r4_core_CapabilityStatement_descriptor.getNestedTypes().get(8);
    internal_static_google_fhir_r4_core_CapabilityStatement_Messaging_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_fhir_r4_core_CapabilityStatement_Messaging_descriptor,
            new java.lang.String[] {
              "Id",
              "Extension",
              "ModifierExtension",
              "Endpoint",
              "ReliableCache",
              "Documentation",
              "SupportedMessage",
            });
    internal_static_google_fhir_r4_core_CapabilityStatement_Messaging_Endpoint_descriptor =
        internal_static_google_fhir_r4_core_CapabilityStatement_Messaging_descriptor
            .getNestedTypes()
            .get(0);
    internal_static_google_fhir_r4_core_CapabilityStatement_Messaging_Endpoint_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_fhir_r4_core_CapabilityStatement_Messaging_Endpoint_descriptor,
            new java.lang.String[] {
              "Id", "Extension", "ModifierExtension", "Protocol", "Address",
            });
    internal_static_google_fhir_r4_core_CapabilityStatement_Messaging_SupportedMessage_descriptor =
        internal_static_google_fhir_r4_core_CapabilityStatement_Messaging_descriptor
            .getNestedTypes()
            .get(1);
    internal_static_google_fhir_r4_core_CapabilityStatement_Messaging_SupportedMessage_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_fhir_r4_core_CapabilityStatement_Messaging_SupportedMessage_descriptor,
            new java.lang.String[] {
              "Id", "Extension", "ModifierExtension", "Mode", "Definition",
            });
    internal_static_google_fhir_r4_core_CapabilityStatement_Messaging_SupportedMessage_ModeCode_descriptor =
        internal_static_google_fhir_r4_core_CapabilityStatement_Messaging_SupportedMessage_descriptor
            .getNestedTypes()
            .get(0);
    internal_static_google_fhir_r4_core_CapabilityStatement_Messaging_SupportedMessage_ModeCode_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_fhir_r4_core_CapabilityStatement_Messaging_SupportedMessage_ModeCode_descriptor,
            new java.lang.String[] {
              "Value", "Id", "Extension",
            });
    internal_static_google_fhir_r4_core_CapabilityStatement_Document_descriptor =
        internal_static_google_fhir_r4_core_CapabilityStatement_descriptor.getNestedTypes().get(9);
    internal_static_google_fhir_r4_core_CapabilityStatement_Document_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_fhir_r4_core_CapabilityStatement_Document_descriptor,
            new java.lang.String[] {
              "Id", "Extension", "ModifierExtension", "Mode", "Documentation", "Profile",
            });
    internal_static_google_fhir_r4_core_CapabilityStatement_Document_ModeCode_descriptor =
        internal_static_google_fhir_r4_core_CapabilityStatement_Document_descriptor
            .getNestedTypes()
            .get(0);
    internal_static_google_fhir_r4_core_CapabilityStatement_Document_ModeCode_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_fhir_r4_core_CapabilityStatement_Document_ModeCode_descriptor,
            new java.lang.String[] {
              "Value", "Id", "Extension",
            });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.fhir.proto.Annotations.fhirPathMessageConstraint);
    registry.add(com.google.fhir.proto.Annotations.fhirProfileBase);
    registry.add(com.google.fhir.proto.Annotations.fhirStructureDefinitionUrl);
    registry.add(com.google.fhir.proto.Annotations.fhirValuesetUrl);
    registry.add(com.google.fhir.proto.Annotations.fhirVersion);
    registry.add(com.google.fhir.proto.Annotations.structureDefinitionKind);
    registry.add(com.google.fhir.proto.Annotations.validReferenceType);
    registry.add(com.google.fhir.proto.Annotations.validationRequirement);
    com.google.protobuf.Descriptors.FileDescriptor.internalUpdateFileDescriptor(
        descriptor, registry);
    com.google.protobuf.AnyProto.getDescriptor();
    com.google.fhir.proto.Annotations.getDescriptor();
    com.google.fhir.r4.core.Codes.getDescriptor();
    com.google.fhir.r4.core.Datatypes.getDescriptor();
    com.google.fhir.r4.core.Valuesets.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
