// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/r4/core/resources/device_request.proto

package com.google.fhir.r4.core;

public final class DeviceRequestOuterClass {
  private DeviceRequestOuterClass() {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
  }

  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_fhir_r4_core_DeviceRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_fhir_r4_core_DeviceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_fhir_r4_core_DeviceRequest_StatusCode_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_fhir_r4_core_DeviceRequest_StatusCode_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_fhir_r4_core_DeviceRequest_IntentCode_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_fhir_r4_core_DeviceRequest_IntentCode_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_fhir_r4_core_DeviceRequest_PriorityCode_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_fhir_r4_core_DeviceRequest_PriorityCode_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_fhir_r4_core_DeviceRequest_CodeX_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_fhir_r4_core_DeviceRequest_CodeX_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_fhir_r4_core_DeviceRequest_Parameter_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_fhir_r4_core_DeviceRequest_Parameter_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_fhir_r4_core_DeviceRequest_Parameter_ValueX_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_fhir_r4_core_DeviceRequest_Parameter_ValueX_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_fhir_r4_core_DeviceRequest_OccurrenceX_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_fhir_r4_core_DeviceRequest_OccurrenceX_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
    return descriptor;
  }

  private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

  static {
    java.lang.String[] descriptorData = {
      "\n,proto/r4/core/resources/device_request"
          + ".proto\022\023google.fhir.r4.core\032\031google/prot"
          + "obuf/any.proto\032\027proto/annotations.proto\032"
          + "\031proto/r4/core/codes.proto\032\035proto/r4/cor"
          + "e/datatypes.proto\"\245\037\n\rDeviceRequest\022#\n\002i"
          + "d\030\001 \001(\0132\027.google.fhir.r4.core.Id\022\'\n\004meta"
          + "\030\002 \001(\0132\031.google.fhir.r4.core.Meta\0220\n\016imp"
          + "licit_rules\030\003 \001(\0132\030.google.fhir.r4.core."
          + "Uri\022+\n\010language\030\004 \001(\0132\031.google.fhir.r4.c"
          + "ore.Code\022,\n\004text\030\005 \001(\0132\036.google.fhir.r4."
          + "core.Narrative\022\'\n\tcontained\030\006 \003(\0132\024.goog"
          + "le.protobuf.Any\0221\n\textension\030\010 \003(\0132\036.goo"
          + "gle.fhir.r4.core.Extension\022:\n\022modifier_e"
          + "xtension\030\t \003(\0132\036.google.fhir.r4.core.Ext"
          + "ension\0223\n\nidentifier\030\n \003(\0132\037.google.fhir"
          + ".r4.core.Identifier\022>\n\026instantiates_cano"
          + "nical\030\013 \003(\0132\036.google.fhir.r4.core.Canoni"
          + "cal\0222\n\020instantiates_uri\030\014 \003(\0132\030.google.f"
          + "hir.r4.core.Uri\022@\n\010based_on\030\r \003(\0132\036.goog"
          + "le.fhir.r4.core.ReferenceB\016\362\377\374\302\006\010Resourc"
          + "e\022E\n\rprior_request\030\016 \003(\0132\036.google.fhir.r"
          + "4.core.ReferenceB\016\362\377\374\302\006\010Resource\0229\n\020grou"
          + "p_identifier\030\017 \001(\0132\037.google.fhir.r4.core"
          + ".Identifier\022=\n\006status\030\020 \001(\0132-.google.fhi"
          + "r.r4.core.DeviceRequest.StatusCode\022E\n\006in"
          + "tent\030\021 \001(\0132-.google.fhir.r4.core.DeviceR"
          + "equest.IntentCodeB\006\360\320\207\353\004\001\022A\n\010priority\030\022 "
          + "\001(\0132/.google.fhir.r4.core.DeviceRequest."
          + "PriorityCode\022>\n\004code\030\023 \001(\0132(.google.fhir"
          + ".r4.core.DeviceRequest.CodeXB\006\360\320\207\353\004\001\022?\n\t"
          + "parameter\030\024 \003(\0132,.google.fhir.r4.core.De"
          + "viceRequest.Parameter\022i\n\007subject\030\025 \001(\0132\036"
          + ".google.fhir.r4.core.ReferenceB8\360\320\207\353\004\001\362\377"
          + "\374\302\006\007Patient\362\377\374\302\006\005Group\362\377\374\302\006\010Location\362\377\374\302"
          + "\006\006Device\022B\n\tencounter\030\026 \001(\0132\036.google.fhi"
          + "r.r4.core.ReferenceB\017\362\377\374\302\006\tEncounter\022B\n\n"
          + "occurrence\030\027 \001(\0132..google.fhir.r4.core.D"
          + "eviceRequest.OccurrenceX\0222\n\013authored_on\030"
          + "\030 \001(\0132\035.google.fhir.r4.core.DateTime\022y\n\t"
          + "requester\030\031 \001(\0132\036.google.fhir.r4.core.Re"
          + "ferenceBF\362\377\374\302\006\006Device\362\377\374\302\006\014Practitioner\362"
          + "\377\374\302\006\020PractitionerRole\362\377\374\302\006\014Organization\022"
          + "<\n\016performer_type\030\032 \001(\0132$.google.fhir.r4"
          + ".core.CodeableConcept\022\277\001\n\tperformer\030\033 \001("
          + "\0132\036.google.fhir.r4.core.ReferenceB\213\001\362\377\374\302"
          + "\006\014Practitioner\362\377\374\302\006\020PractitionerRole\362\377\374\302"
          + "\006\014Organization\362\377\374\302\006\010CareTeam\362\377\374\302\006\021Health"
          + "careService\362\377\374\302\006\007Patient\362\377\374\302\006\006Device\362\377\374\302"
          + "\006\rRelatedPerson\0229\n\013reason_code\030\034 \003(\0132$.g"
          + "oogle.fhir.r4.core.CodeableConcept\022\207\001\n\020r"
          + "eason_reference\030\035 \003(\0132\036.google.fhir.r4.c"
          + "ore.ReferenceBM\362\377\374\302\006\tCondition\362\377\374\302\006\013Obse"
          + "rvation\362\377\374\302\006\020DiagnosticReport\362\377\374\302\006\021Docum"
          + "entReference\022T\n\tinsurance\030\036 \003(\0132\036.google"
          + ".fhir.r4.core.ReferenceB!\362\377\374\302\006\010Coverage\362"
          + "\377\374\302\006\rClaimResponse\022G\n\017supporting_info\030\037 "
          + "\003(\0132\036.google.fhir.r4.core.ReferenceB\016\362\377\374"
          + "\302\006\010Resource\022-\n\004note\030  \003(\0132\037.google.fhir."
          + "r4.core.Annotation\022J\n\020relevant_history\030!"
          + " \003(\0132\036.google.fhir.r4.core.ReferenceB\020\362\377"
          + "\374\302\006\nProvenance\032\220\002\n\nStatusCode\022;\n\005value\030\001"
          + " \001(\0162,.google.fhir.r4.core.RequestStatus"
          + "Code.Value\022\'\n\002id\030\002 \001(\0132\033.google.fhir.r4."
          + "core.String\0221\n\textension\030\003 \003(\0132\036.google."
          + "fhir.r4.core.Extension:i\300\237\343\266\005\001\212\371\203\262\005+http"
          + "://hl7.org/fhir/ValueSet/request-status\232"
          + "\265\216\223\006,http://hl7.org/fhir/StructureDefini"
          + "tion/code\032\220\002\n\nIntentCode\022;\n\005value\030\001 \001(\0162"
          + ",.google.fhir.r4.core.RequestIntentCode."
          + "Value\022\'\n\002id\030\002 \001(\0132\033.google.fhir.r4.core."
          + "String\0221\n\textension\030\003 \003(\0132\036.google.fhir."
          + "r4.core.Extension:i\300\237\343\266\005\001\212\371\203\262\005+http://hl"
          + "7.org/fhir/ValueSet/request-intent\232\265\216\223\006,"
          + "http://hl7.org/fhir/StructureDefinition/"
          + "code\032\226\002\n\014PriorityCode\022=\n\005value\030\001 \001(\0162..g"
          + "oogle.fhir.r4.core.RequestPriorityCode.V"
          + "alue\022\'\n\002id\030\002 \001(\0132\033.google.fhir.r4.core.S"
          + "tring\0221\n\textension\030\003 \003(\0132\036.google.fhir.r"
          + "4.core.Extension:k\300\237\343\266\005\001\212\371\203\262\005-http://hl7"
          + ".org/fhir/ValueSet/request-priority\232\265\216\223\006"
          + ",http://hl7.org/fhir/StructureDefinition"
          + "/code\032\236\001\n\005CodeX\022A\n\treference\030\001 \001(\0132\036.goo"
          + "gle.fhir.r4.core.ReferenceB\014\362\377\374\302\006\006Device"
          + "H\000\022@\n\020codeable_concept\030\002 \001(\0132$.google.fh"
          + "ir.r4.core.CodeableConceptH\000:\006\240\203\203\350\006\001B\010\n\006"
          + "choice\032\213\004\n\tParameter\022\'\n\002id\030\001 \001(\0132\033.googl"
          + "e.fhir.r4.core.String\0221\n\textension\030\002 \003(\013"
          + "2\036.google.fhir.r4.core.Extension\022:\n\022modi"
          + "fier_extension\030\003 \003(\0132\036.google.fhir.r4.co"
          + "re.Extension\0222\n\004code\030\004 \001(\0132$.google.fhir"
          + ".r4.core.CodeableConcept\022B\n\005value\030\005 \001(\0132"
          + "3.google.fhir.r4.core.DeviceRequest.Para"
          + "meter.ValueX\032\355\001\n\006ValueX\022@\n\020codeable_conc"
          + "ept\030\001 \001(\0132$.google.fhir.r4.core.Codeable"
          + "ConceptH\000\0221\n\010quantity\030\002 \001(\0132\035.google.fhi"
          + "r.r4.core.QuantityH\000\022+\n\005range\030\003 \001(\0132\032.go"
          + "ogle.fhir.r4.core.RangeH\000\022/\n\007boolean\030\004 \001"
          + "(\0132\034.google.fhir.r4.core.BooleanH\000:\006\240\203\203\350"
          + "\006\001B\010\n\006choice\032\261\001\n\013OccurrenceX\0222\n\tdate_tim"
          + "e\030\001 \001(\0132\035.google.fhir.r4.core.DateTimeH\000"
          + "\022-\n\006period\030\002 \001(\0132\033.google.fhir.r4.core.P"
          + "eriodH\000\022-\n\006timing\030\003 \001(\0132\033.google.fhir.r4"
          + ".core.TimingH\000:\006\240\203\203\350\006\001B\010\n\006choice:A\300\237\343\266\005\003"
          + "\262\376\344\227\0065http://hl7.org/fhir/StructureDefin"
          + "ition/DeviceRequestJ\004\010\007\020\010B!\n\027com.google."
          + "fhir.r4.coreP\001\230\306\260\265\007\004b\006proto3"
    };
    descriptor =
        com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(
            descriptorData,
            new com.google.protobuf.Descriptors.FileDescriptor[] {
              com.google.protobuf.AnyProto.getDescriptor(),
              com.google.fhir.proto.Annotations.getDescriptor(),
              com.google.fhir.r4.core.Codes.getDescriptor(),
              com.google.fhir.r4.core.Datatypes.getDescriptor(),
            });
    internal_static_google_fhir_r4_core_DeviceRequest_descriptor =
        getDescriptor().getMessageTypes().get(0);
    internal_static_google_fhir_r4_core_DeviceRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_fhir_r4_core_DeviceRequest_descriptor,
            new java.lang.String[] {
              "Id",
              "Meta",
              "ImplicitRules",
              "Language",
              "Text",
              "Contained",
              "Extension",
              "ModifierExtension",
              "Identifier",
              "InstantiatesCanonical",
              "InstantiatesUri",
              "BasedOn",
              "PriorRequest",
              "GroupIdentifier",
              "Status",
              "Intent",
              "Priority",
              "Code",
              "Parameter",
              "Subject",
              "Encounter",
              "Occurrence",
              "AuthoredOn",
              "Requester",
              "PerformerType",
              "Performer",
              "ReasonCode",
              "ReasonReference",
              "Insurance",
              "SupportingInfo",
              "Note",
              "RelevantHistory",
            });
    internal_static_google_fhir_r4_core_DeviceRequest_StatusCode_descriptor =
        internal_static_google_fhir_r4_core_DeviceRequest_descriptor.getNestedTypes().get(0);
    internal_static_google_fhir_r4_core_DeviceRequest_StatusCode_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_fhir_r4_core_DeviceRequest_StatusCode_descriptor,
            new java.lang.String[] {
              "Value", "Id", "Extension",
            });
    internal_static_google_fhir_r4_core_DeviceRequest_IntentCode_descriptor =
        internal_static_google_fhir_r4_core_DeviceRequest_descriptor.getNestedTypes().get(1);
    internal_static_google_fhir_r4_core_DeviceRequest_IntentCode_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_fhir_r4_core_DeviceRequest_IntentCode_descriptor,
            new java.lang.String[] {
              "Value", "Id", "Extension",
            });
    internal_static_google_fhir_r4_core_DeviceRequest_PriorityCode_descriptor =
        internal_static_google_fhir_r4_core_DeviceRequest_descriptor.getNestedTypes().get(2);
    internal_static_google_fhir_r4_core_DeviceRequest_PriorityCode_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_fhir_r4_core_DeviceRequest_PriorityCode_descriptor,
            new java.lang.String[] {
              "Value", "Id", "Extension",
            });
    internal_static_google_fhir_r4_core_DeviceRequest_CodeX_descriptor =
        internal_static_google_fhir_r4_core_DeviceRequest_descriptor.getNestedTypes().get(3);
    internal_static_google_fhir_r4_core_DeviceRequest_CodeX_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_fhir_r4_core_DeviceRequest_CodeX_descriptor,
            new java.lang.String[] {
              "Reference", "CodeableConcept", "Choice",
            });
    internal_static_google_fhir_r4_core_DeviceRequest_Parameter_descriptor =
        internal_static_google_fhir_r4_core_DeviceRequest_descriptor.getNestedTypes().get(4);
    internal_static_google_fhir_r4_core_DeviceRequest_Parameter_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_fhir_r4_core_DeviceRequest_Parameter_descriptor,
            new java.lang.String[] {
              "Id", "Extension", "ModifierExtension", "Code", "Value",
            });
    internal_static_google_fhir_r4_core_DeviceRequest_Parameter_ValueX_descriptor =
        internal_static_google_fhir_r4_core_DeviceRequest_Parameter_descriptor
            .getNestedTypes()
            .get(0);
    internal_static_google_fhir_r4_core_DeviceRequest_Parameter_ValueX_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_fhir_r4_core_DeviceRequest_Parameter_ValueX_descriptor,
            new java.lang.String[] {
              "CodeableConcept", "Quantity", "Range", "Boolean", "Choice",
            });
    internal_static_google_fhir_r4_core_DeviceRequest_OccurrenceX_descriptor =
        internal_static_google_fhir_r4_core_DeviceRequest_descriptor.getNestedTypes().get(5);
    internal_static_google_fhir_r4_core_DeviceRequest_OccurrenceX_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_fhir_r4_core_DeviceRequest_OccurrenceX_descriptor,
            new java.lang.String[] {
              "DateTime", "Period", "Timing", "Choice",
            });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.fhir.proto.Annotations.fhirProfileBase);
    registry.add(com.google.fhir.proto.Annotations.fhirStructureDefinitionUrl);
    registry.add(com.google.fhir.proto.Annotations.fhirValuesetUrl);
    registry.add(com.google.fhir.proto.Annotations.fhirVersion);
    registry.add(com.google.fhir.proto.Annotations.isChoiceType);
    registry.add(com.google.fhir.proto.Annotations.structureDefinitionKind);
    registry.add(com.google.fhir.proto.Annotations.validReferenceType);
    registry.add(com.google.fhir.proto.Annotations.validationRequirement);
    com.google.protobuf.Descriptors.FileDescriptor.internalUpdateFileDescriptor(
        descriptor, registry);
    com.google.protobuf.AnyProto.getDescriptor();
    com.google.fhir.proto.Annotations.getDescriptor();
    com.google.fhir.r4.core.Codes.getDescriptor();
    com.google.fhir.r4.core.Datatypes.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
