// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/google/fhir/proto/r4/core/resources/guidance_response.proto

package com.google.fhir.r4.core;

public final class GuidanceResponseOuterClass {
  private GuidanceResponseOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_fhir_r4_core_GuidanceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_fhir_r4_core_GuidanceResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_fhir_r4_core_GuidanceResponse_ModuleX_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_fhir_r4_core_GuidanceResponse_ModuleX_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_fhir_r4_core_GuidanceResponse_StatusCode_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_fhir_r4_core_GuidanceResponse_StatusCode_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nAproto/google/fhir/proto/r4/core/resour" +
      "ces/guidance_response.proto\022\023google.fhir" +
      ".r4.core\032\031google/protobuf/any.proto\032)pro" +
      "to/google/fhir/proto/annotations.proto\032+" +
      "proto/google/fhir/proto/r4/core/codes.pr" +
      "oto\032/proto/google/fhir/proto/r4/core/dat" +
      "atypes.proto\"\305\021\n\020GuidanceResponse\022#\n\002id\030" +
      "\001 \001(\0132\027.google.fhir.r4.core.Id\022\'\n\004meta\030\002" +
      " \001(\0132\031.google.fhir.r4.core.Meta\0220\n\016impli" +
      "cit_rules\030\003 \001(\0132\030.google.fhir.r4.core.Ur" +
      "i\022+\n\010language\030\004 \001(\0132\031.google.fhir.r4.cor" +
      "e.Code\022,\n\004text\030\005 \001(\0132\036.google.fhir.r4.co" +
      "re.Narrative\022\'\n\tcontained\030\006 \003(\0132\024.google" +
      ".protobuf.Any\0221\n\textension\030\010 \003(\0132\036.googl" +
      "e.fhir.r4.core.Extension\022:\n\022modifier_ext" +
      "ension\030\t \003(\0132\036.google.fhir.r4.core.Exten" +
      "sion\022;\n\022request_identifier\030\n \001(\0132\037.googl" +
      "e.fhir.r4.core.Identifier\0223\n\nidentifier\030" +
      "\013 \003(\0132\037.google.fhir.r4.core.Identifier\022E" +
      "\n\006module\030\014 \001(\0132-.google.fhir.r4.core.Gui" +
      "danceResponse.ModuleXB\006\360\320\207\353\004\001\022H\n\006status\030" +
      "\r \001(\01320.google.fhir.r4.core.GuidanceResp" +
      "onse.StatusCodeB\006\360\320\207\353\004\001\022I\n\007subject\030\016 \001(\013" +
      "2\036.google.fhir.r4.core.ReferenceB\030\362\377\374\302\006\007" +
      "Patient\362\377\374\302\006\005Group\022B\n\tencounter\030\017 \001(\0132\036." +
      "google.fhir.r4.core.ReferenceB\017\362\377\374\302\006\tEnc" +
      "ounter\022;\n\024occurrence_date_time\030\020 \001(\0132\035.g" +
      "oogle.fhir.r4.core.DateTime\022?\n\tperformer" +
      "\030\021 \001(\0132\036.google.fhir.r4.core.ReferenceB\014" +
      "\362\377\374\302\006\006Device\0229\n\013reason_code\030\022 \003(\0132$.goog" +
      "le.fhir.r4.core.CodeableConcept\022\207\001\n\020reas" +
      "on_reference\030\023 \003(\0132\036.google.fhir.r4.core" +
      ".ReferenceBM\362\377\374\302\006\tCondition\362\377\374\302\006\013Observa" +
      "tion\362\377\374\302\006\020DiagnosticReport\362\377\374\302\006\021Document" +
      "Reference\022-\n\004note\030\024 \003(\0132\037.google.fhir.r4" +
      ".core.Annotation\022R\n\022evaluation_message\030\025" +
      " \003(\0132\036.google.fhir.r4.core.ReferenceB\026\362\377" +
      "\374\302\006\020OperationOutcome\022K\n\021output_parameter" +
      "s\030\026 \001(\0132\036.google.fhir.r4.core.ReferenceB" +
      "\020\362\377\374\302\006\nParameters\022P\n\006result\030\027 \001(\0132\036.goog" +
      "le.fhir.r4.core.ReferenceB \362\377\374\302\006\010CarePla" +
      "n\362\377\374\302\006\014RequestGroup\022>\n\020data_requirement\030" +
      "\030 \003(\0132$.google.fhir.r4.core.DataRequirem" +
      "ent\032\273\001\n\007ModuleX\022\'\n\003uri\030\001 \001(\0132\030.google.fh" +
      "ir.r4.core.UriH\000\0223\n\tcanonical\030\002 \001(\0132\036.go" +
      "ogle.fhir.r4.core.CanonicalH\000\022@\n\020codeabl" +
      "e_concept\030\003 \001(\0132$.google.fhir.r4.core.Co" +
      "deableConceptH\000:\006\240\203\203\350\006\001B\010\n\006choice\032\243\002\n\nSt" +
      "atusCode\022D\n\005value\030\001 \001(\01625.google.fhir.r4" +
      ".core.GuidanceResponseStatusCode.Value\022\'" +
      "\n\002id\030\002 \001(\0132\033.google.fhir.r4.core.String\022" +
      "1\n\textension\030\003 \003(\0132\036.google.fhir.r4.core" +
      ".Extension:s\300\237\343\266\005\001\212\371\203\262\0055http://hl7.org/f" +
      "hir/ValueSet/guidance-response-status\232\265\216" +
      "\223\006,http://hl7.org/fhir/StructureDefiniti" +
      "on/code:\234\002\300\237\343\266\005\003\262\376\344\227\0068http://hl7.org/fhi" +
      "r/StructureDefinition/GuidanceResponse\262\365" +
      "\365\327\t+\n\nidentifier\020\004\032\033GuidanceResponse.ide" +
      "ntifier\262\365\365\327\tA\n\007patient\020\005\0324GuidanceRespon" +
      "se.subject.where(resolve() is Patient)\262\365" +
      "\365\327\t/\n\007request\020\004\032\"GuidanceResponse.reques" +
      "tIdentifier\262\365\365\327\t%\n\007subject\020\005\032\030GuidanceRe" +
      "sponse.subjectJ\004\010\007\020\010B!\n\027com.google.fhir." +
      "r4.coreP\001\230\306\260\265\007\004b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
          com.google.fhir.proto.Annotations.getDescriptor(),
          com.google.fhir.r4.core.Codes.getDescriptor(),
          com.google.fhir.r4.core.Datatypes.getDescriptor(),
        });
    internal_static_google_fhir_r4_core_GuidanceResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_google_fhir_r4_core_GuidanceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_fhir_r4_core_GuidanceResponse_descriptor,
        new java.lang.String[] { "Id", "Meta", "ImplicitRules", "Language", "Text", "Contained", "Extension", "ModifierExtension", "RequestIdentifier", "Identifier", "Module", "Status", "Subject", "Encounter", "OccurrenceDateTime", "Performer", "ReasonCode", "ReasonReference", "Note", "EvaluationMessage", "OutputParameters", "Result", "DataRequirement", });
    internal_static_google_fhir_r4_core_GuidanceResponse_ModuleX_descriptor =
      internal_static_google_fhir_r4_core_GuidanceResponse_descriptor.getNestedTypes().get(0);
    internal_static_google_fhir_r4_core_GuidanceResponse_ModuleX_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_fhir_r4_core_GuidanceResponse_ModuleX_descriptor,
        new java.lang.String[] { "Uri", "Canonical", "CodeableConcept", "Choice", });
    internal_static_google_fhir_r4_core_GuidanceResponse_StatusCode_descriptor =
      internal_static_google_fhir_r4_core_GuidanceResponse_descriptor.getNestedTypes().get(1);
    internal_static_google_fhir_r4_core_GuidanceResponse_StatusCode_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_fhir_r4_core_GuidanceResponse_StatusCode_descriptor,
        new java.lang.String[] { "Value", "Id", "Extension", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.fhir.proto.Annotations.fhirProfileBase);
    registry.add(com.google.fhir.proto.Annotations.fhirStructureDefinitionUrl);
    registry.add(com.google.fhir.proto.Annotations.fhirValuesetUrl);
    registry.add(com.google.fhir.proto.Annotations.fhirVersion);
    registry.add(com.google.fhir.proto.Annotations.isChoiceType);
    registry.add(com.google.fhir.proto.Annotations.searchParameter);
    registry.add(com.google.fhir.proto.Annotations.structureDefinitionKind);
    registry.add(com.google.fhir.proto.Annotations.validReferenceType);
    registry.add(com.google.fhir.proto.Annotations.validationRequirement);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.protobuf.AnyProto.getDescriptor();
    com.google.fhir.proto.Annotations.getDescriptor();
    com.google.fhir.r4.core.Codes.getDescriptor();
    com.google.fhir.r4.core.Datatypes.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
