// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/r4/core/resources/metadata_resource.proto

package com.google.fhir.r4.core;

public final class MetadataResourceOuterClass {
  private MetadataResourceOuterClass() {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
  }

  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_fhir_r4_core_MetadataResource_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_fhir_r4_core_MetadataResource_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_fhir_r4_core_MetadataResource_StatusCode_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_fhir_r4_core_MetadataResource_StatusCode_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
    return descriptor;
  }

  private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

  static {
    java.lang.String[] descriptorData = {
      "\n/proto/r4/core/resources/metadata_resou"
          + "rce.proto\022\023google.fhir.r4.core\032\031google/p"
          + "rotobuf/any.proto\032\027proto/annotations.pro"
          + "to\032\031proto/r4/core/codes.proto\032\035proto/r4/"
          + "core/datatypes.proto\"\324\n\n\020MetadataResourc"
          + "e\022\'\n\002id\030\001 \001(\0132\033.google.fhir.r4.core.Stri"
          + "ng\022\'\n\004meta\030\002 \001(\0132\031.google.fhir.r4.core.M"
          + "eta\0220\n\016implicit_rules\030\003 \001(\0132\030.google.fhi"
          + "r.r4.core.Uri\022+\n\010language\030\004 \001(\0132\031.google"
          + ".fhir.r4.core.Code\022,\n\004text\030\005 \001(\0132\036.googl"
          + "e.fhir.r4.core.Narrative\022\'\n\tcontained\030\006 "
          + "\003(\0132\024.google.protobuf.Any\0221\n\textension\030\010"
          + " \003(\0132\036.google.fhir.r4.core.Extension\022:\n\022"
          + "modifier_extension\030\t \003(\0132\036.google.fhir.r"
          + "4.core.Extension\022%\n\003url\030\n \001(\0132\030.google.f"
          + "hir.r4.core.Uri\022,\n\007version\030\013 \001(\0132\033.googl"
          + "e.fhir.r4.core.String\022)\n\004name\030\014 \001(\0132\033.go"
          + "ogle.fhir.r4.core.String\022*\n\005title\030\r \001(\0132"
          + "\033.google.fhir.r4.core.String\022H\n\006status\030\016"
          + " \001(\01320.google.fhir.r4.core.MetadataResou"
          + "rce.StatusCodeB\006\360\320\207\353\004\001\0222\n\014experimental\030\017"
          + " \001(\0132\034.google.fhir.r4.core.Boolean\022+\n\004da"
          + "te\030\020 \001(\0132\035.google.fhir.r4.core.DateTime\022"
          + ".\n\tpublisher\030\021 \001(\0132\033.google.fhir.r4.core"
          + ".String\0223\n\007contact\030\022 \003(\0132\".google.fhir.r"
          + "4.core.ContactDetail\0222\n\013description\030\023 \001("
          + "\0132\035.google.fhir.r4.core.Markdown\0226\n\013use_"
          + "context\030\024 \003(\0132!.google.fhir.r4.core.Usag"
          + "eContext\022:\n\014jurisdiction\030\025 \003(\0132$.google."
          + "fhir.r4.core.CodeableConcept\032\230\002\n\nStatusC"
          + "ode\022?\n\005value\030\001 \001(\01620.google.fhir.r4.core"
          + ".PublicationStatusCode.Value\022\'\n\002id\030\002 \001(\013"
          + "2\033.google.fhir.r4.core.String\0221\n\textensi"
          + "on\030\003 \003(\0132\036.google.fhir.r4.core.Extension"
          + ":m\300\237\343\266\005\001\212\371\203\262\005/http://hl7.org/fhir/ValueS"
          + "et/publication-status\232\265\216\223\006,http://hl7.or"
          + "g/fhir/StructureDefinition/code:D\300\237\343\266\005\004\262"
          + "\376\344\227\0068http://hl7.org/fhir/StructureDefini"
          + "tion/MetadataResourceJ\004\010\007\020\010B!\n\027com.googl"
          + "e.fhir.r4.coreP\001\230\306\260\265\007\004b\006proto3"
    };
    descriptor =
        com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(
            descriptorData,
            new com.google.protobuf.Descriptors.FileDescriptor[] {
              com.google.protobuf.AnyProto.getDescriptor(),
              com.google.fhir.proto.Annotations.getDescriptor(),
              com.google.fhir.r4.core.Codes.getDescriptor(),
              com.google.fhir.r4.core.Datatypes.getDescriptor(),
            });
    internal_static_google_fhir_r4_core_MetadataResource_descriptor =
        getDescriptor().getMessageTypes().get(0);
    internal_static_google_fhir_r4_core_MetadataResource_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_fhir_r4_core_MetadataResource_descriptor,
            new java.lang.String[] {
              "Id",
              "Meta",
              "ImplicitRules",
              "Language",
              "Text",
              "Contained",
              "Extension",
              "ModifierExtension",
              "Url",
              "Version",
              "Name",
              "Title",
              "Status",
              "Experimental",
              "Date",
              "Publisher",
              "Contact",
              "Description",
              "UseContext",
              "Jurisdiction",
            });
    internal_static_google_fhir_r4_core_MetadataResource_StatusCode_descriptor =
        internal_static_google_fhir_r4_core_MetadataResource_descriptor.getNestedTypes().get(0);
    internal_static_google_fhir_r4_core_MetadataResource_StatusCode_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_fhir_r4_core_MetadataResource_StatusCode_descriptor,
            new java.lang.String[] {
              "Value", "Id", "Extension",
            });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.fhir.proto.Annotations.fhirProfileBase);
    registry.add(com.google.fhir.proto.Annotations.fhirStructureDefinitionUrl);
    registry.add(com.google.fhir.proto.Annotations.fhirValuesetUrl);
    registry.add(com.google.fhir.proto.Annotations.fhirVersion);
    registry.add(com.google.fhir.proto.Annotations.structureDefinitionKind);
    registry.add(com.google.fhir.proto.Annotations.validationRequirement);
    com.google.protobuf.Descriptors.FileDescriptor.internalUpdateFileDescriptor(
        descriptor, registry);
    com.google.protobuf.AnyProto.getDescriptor();
    com.google.fhir.proto.Annotations.getDescriptor();
    com.google.fhir.r4.core.Codes.getDescriptor();
    com.google.fhir.r4.core.Datatypes.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
