// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/r4/core/extensions.proto

package com.google.fhir.r4.core;

public interface QuestionnaireConstraintOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:google.fhir.r4.core.QuestionnaireConstraint)
    com.google.protobuf.MessageOrBuilder {

  /**
   *
   *
   * <pre>
   * Unique id for inter-element referencing
   * </pre>
   *
   * <code>.google.fhir.r4.core.String id = 1;</code>
   *
   * @return Whether the id field is set.
   */
  boolean hasId();
  /**
   *
   *
   * <pre>
   * Unique id for inter-element referencing
   * </pre>
   *
   * <code>.google.fhir.r4.core.String id = 1;</code>
   *
   * @return The id.
   */
  com.google.fhir.r4.core.String getId();
  /**
   *
   *
   * <pre>
   * Unique id for inter-element referencing
   * </pre>
   *
   * <code>.google.fhir.r4.core.String id = 1;</code>
   */
  com.google.fhir.r4.core.StringOrBuilder getIdOrBuilder();

  /**
   *
   *
   * <pre>
   * Additional content defined by implementations
   * </pre>
   *
   * <code>repeated .google.fhir.r4.core.Extension extension = 2;</code>
   */
  java.util.List<com.google.fhir.r4.core.Extension> getExtensionList();
  /**
   *
   *
   * <pre>
   * Additional content defined by implementations
   * </pre>
   *
   * <code>repeated .google.fhir.r4.core.Extension extension = 2;</code>
   */
  com.google.fhir.r4.core.Extension getExtension(int index);
  /**
   *
   *
   * <pre>
   * Additional content defined by implementations
   * </pre>
   *
   * <code>repeated .google.fhir.r4.core.Extension extension = 2;</code>
   */
  int getExtensionCount();
  /**
   *
   *
   * <pre>
   * Additional content defined by implementations
   * </pre>
   *
   * <code>repeated .google.fhir.r4.core.Extension extension = 2;</code>
   */
  java.util.List<? extends com.google.fhir.r4.core.ExtensionOrBuilder> getExtensionOrBuilderList();
  /**
   *
   *
   * <pre>
   * Additional content defined by implementations
   * </pre>
   *
   * <code>repeated .google.fhir.r4.core.Extension extension = 2;</code>
   */
  com.google.fhir.r4.core.ExtensionOrBuilder getExtensionOrBuilder(int index);

  /**
   *
   *
   * <pre>
   * Unique identifier
   * </pre>
   *
   * <code>
   * .google.fhir.r4.core.Id key = 4 [(.google.fhir.proto.validation_requirement) = REQUIRED_BY_FHIR];
   * </code>
   *
   * @return Whether the key field is set.
   */
  boolean hasKey();
  /**
   *
   *
   * <pre>
   * Unique identifier
   * </pre>
   *
   * <code>
   * .google.fhir.r4.core.Id key = 4 [(.google.fhir.proto.validation_requirement) = REQUIRED_BY_FHIR];
   * </code>
   *
   * @return The key.
   */
  com.google.fhir.r4.core.Id getKey();
  /**
   *
   *
   * <pre>
   * Unique identifier
   * </pre>
   *
   * <code>
   * .google.fhir.r4.core.Id key = 4 [(.google.fhir.proto.validation_requirement) = REQUIRED_BY_FHIR];
   * </code>
   */
  com.google.fhir.r4.core.IdOrBuilder getKeyOrBuilder();

  /**
   *
   *
   * <pre>
   * Why needed
   * </pre>
   *
   * <code>.google.fhir.r4.core.String requirements = 5;</code>
   *
   * @return Whether the requirements field is set.
   */
  boolean hasRequirements();
  /**
   *
   *
   * <pre>
   * Why needed
   * </pre>
   *
   * <code>.google.fhir.r4.core.String requirements = 5;</code>
   *
   * @return The requirements.
   */
  com.google.fhir.r4.core.String getRequirements();
  /**
   *
   *
   * <pre>
   * Why needed
   * </pre>
   *
   * <code>.google.fhir.r4.core.String requirements = 5;</code>
   */
  com.google.fhir.r4.core.StringOrBuilder getRequirementsOrBuilder();

  /**
   * <code>
   * .google.fhir.r4.core.QuestionnaireConstraint.SeverityCode severity = 6 [(.google.fhir.proto.validation_requirement) = REQUIRED_BY_FHIR];
   * </code>
   *
   * @return Whether the severity field is set.
   */
  boolean hasSeverity();
  /**
   * <code>
   * .google.fhir.r4.core.QuestionnaireConstraint.SeverityCode severity = 6 [(.google.fhir.proto.validation_requirement) = REQUIRED_BY_FHIR];
   * </code>
   *
   * @return The severity.
   */
  com.google.fhir.r4.core.QuestionnaireConstraint.SeverityCode getSeverity();
  /**
   * <code>
   * .google.fhir.r4.core.QuestionnaireConstraint.SeverityCode severity = 6 [(.google.fhir.proto.validation_requirement) = REQUIRED_BY_FHIR];
   * </code>
   */
  com.google.fhir.r4.core.QuestionnaireConstraint.SeverityCodeOrBuilder getSeverityOrBuilder();

  /**
   *
   *
   * <pre>
   * Formal rule
   * </pre>
   *
   * <code>
   * .google.fhir.r4.core.String expression = 7 [(.google.fhir.proto.validation_requirement) = REQUIRED_BY_FHIR];
   * </code>
   *
   * @return Whether the expression field is set.
   */
  boolean hasExpression();
  /**
   *
   *
   * <pre>
   * Formal rule
   * </pre>
   *
   * <code>
   * .google.fhir.r4.core.String expression = 7 [(.google.fhir.proto.validation_requirement) = REQUIRED_BY_FHIR];
   * </code>
   *
   * @return The expression.
   */
  com.google.fhir.r4.core.String getExpression();
  /**
   *
   *
   * <pre>
   * Formal rule
   * </pre>
   *
   * <code>
   * .google.fhir.r4.core.String expression = 7 [(.google.fhir.proto.validation_requirement) = REQUIRED_BY_FHIR];
   * </code>
   */
  com.google.fhir.r4.core.StringOrBuilder getExpressionOrBuilder();

  /**
   *
   *
   * <pre>
   * Human-readable rule
   * </pre>
   *
   * <code>
   * .google.fhir.r4.core.String human = 8 [(.google.fhir.proto.validation_requirement) = REQUIRED_BY_FHIR];
   * </code>
   *
   * @return Whether the human field is set.
   */
  boolean hasHuman();
  /**
   *
   *
   * <pre>
   * Human-readable rule
   * </pre>
   *
   * <code>
   * .google.fhir.r4.core.String human = 8 [(.google.fhir.proto.validation_requirement) = REQUIRED_BY_FHIR];
   * </code>
   *
   * @return The human.
   */
  com.google.fhir.r4.core.String getHuman();
  /**
   *
   *
   * <pre>
   * Human-readable rule
   * </pre>
   *
   * <code>
   * .google.fhir.r4.core.String human = 8 [(.google.fhir.proto.validation_requirement) = REQUIRED_BY_FHIR];
   * </code>
   */
  com.google.fhir.r4.core.StringOrBuilder getHumanOrBuilder();

  /**
   *
   *
   * <pre>
   * Relative path to elements
   * </pre>
   *
   * <code>repeated .google.fhir.r4.core.String location = 9;</code>
   */
  java.util.List<com.google.fhir.r4.core.String> getLocationList();
  /**
   *
   *
   * <pre>
   * Relative path to elements
   * </pre>
   *
   * <code>repeated .google.fhir.r4.core.String location = 9;</code>
   */
  com.google.fhir.r4.core.String getLocation(int index);
  /**
   *
   *
   * <pre>
   * Relative path to elements
   * </pre>
   *
   * <code>repeated .google.fhir.r4.core.String location = 9;</code>
   */
  int getLocationCount();
  /**
   *
   *
   * <pre>
   * Relative path to elements
   * </pre>
   *
   * <code>repeated .google.fhir.r4.core.String location = 9;</code>
   */
  java.util.List<? extends com.google.fhir.r4.core.StringOrBuilder> getLocationOrBuilderList();
  /**
   *
   *
   * <pre>
   * Relative path to elements
   * </pre>
   *
   * <code>repeated .google.fhir.r4.core.String location = 9;</code>
   */
  com.google.fhir.r4.core.StringOrBuilder getLocationOrBuilder(int index);
}
