// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/google/fhir/proto/r4/core/resources/search_parameter.proto

package com.google.fhir.r4.core;

public final class SearchParameterOuterClass {
  private SearchParameterOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_fhir_r4_core_SearchParameter_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_fhir_r4_core_SearchParameter_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_fhir_r4_core_SearchParameter_StatusCode_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_fhir_r4_core_SearchParameter_StatusCode_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_fhir_r4_core_SearchParameter_BaseCode_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_fhir_r4_core_SearchParameter_BaseCode_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_fhir_r4_core_SearchParameter_TypeCode_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_fhir_r4_core_SearchParameter_TypeCode_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_fhir_r4_core_SearchParameter_XpathUsageCode_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_fhir_r4_core_SearchParameter_XpathUsageCode_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_fhir_r4_core_SearchParameter_TargetCode_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_fhir_r4_core_SearchParameter_TargetCode_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_fhir_r4_core_SearchParameter_ComparatorCode_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_fhir_r4_core_SearchParameter_ComparatorCode_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_fhir_r4_core_SearchParameter_ModifierCode_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_fhir_r4_core_SearchParameter_ModifierCode_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_fhir_r4_core_SearchParameter_Component_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_fhir_r4_core_SearchParameter_Component_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n@proto/google/fhir/proto/r4/core/resour" +
      "ces/search_parameter.proto\022\023google.fhir." +
      "r4.core\032\031google/protobuf/any.proto\032)prot" +
      "o/google/fhir/proto/annotations.proto\032+p" +
      "roto/google/fhir/proto/r4/core/codes.pro" +
      "to\032/proto/google/fhir/proto/r4/core/data" +
      "types.proto\"\214W\n\017SearchParameter\022#\n\002id\030\001 " +
      "\001(\0132\027.google.fhir.r4.core.Id\022\'\n\004meta\030\002 \001" +
      "(\0132\031.google.fhir.r4.core.Meta\0220\n\016implici" +
      "t_rules\030\003 \001(\0132\030.google.fhir.r4.core.Uri\022" +
      "+\n\010language\030\004 \001(\0132\031.google.fhir.r4.core." +
      "Code\022,\n\004text\030\005 \001(\0132\036.google.fhir.r4.core" +
      ".Narrative\022\'\n\tcontained\030\006 \003(\0132\024.google.p" +
      "rotobuf.Any\0221\n\textension\030\010 \003(\0132\036.google." +
      "fhir.r4.core.Extension\022:\n\022modifier_exten" +
      "sion\030\t \003(\0132\036.google.fhir.r4.core.Extensi" +
      "on\022-\n\003url\030\n \001(\0132\030.google.fhir.r4.core.Ur" +
      "iB\006\360\320\207\353\004\001\022,\n\007version\030\013 \001(\0132\033.google.fhir" +
      ".r4.core.String\0221\n\004name\030\014 \001(\0132\033.google.f" +
      "hir.r4.core.StringB\006\360\320\207\353\004\001\0224\n\014derived_fr" +
      "om\030\r \001(\0132\036.google.fhir.r4.core.Canonical" +
      "\022G\n\006status\030\016 \001(\0132/.google.fhir.r4.core.S" +
      "earchParameter.StatusCodeB\006\360\320\207\353\004\001\0222\n\014exp" +
      "erimental\030\017 \001(\0132\034.google.fhir.r4.core.Bo" +
      "olean\022+\n\004date\030\020 \001(\0132\035.google.fhir.r4.cor" +
      "e.DateTime\022.\n\tpublisher\030\021 \001(\0132\033.google.f" +
      "hir.r4.core.String\0223\n\007contact\030\022 \003(\0132\".go" +
      "ogle.fhir.r4.core.ContactDetail\022:\n\013descr" +
      "iption\030\023 \001(\0132\035.google.fhir.r4.core.Markd" +
      "ownB\006\360\320\207\353\004\001\0226\n\013use_context\030\024 \003(\0132!.googl" +
      "e.fhir.r4.core.UsageContext\022:\n\014jurisdict" +
      "ion\030\025 \003(\0132$.google.fhir.r4.core.Codeable" +
      "Concept\022.\n\007purpose\030\026 \001(\0132\035.google.fhir.r" +
      "4.core.Markdown\022/\n\004code\030\027 \001(\0132\031.google.f" +
      "hir.r4.core.CodeB\006\360\320\207\353\004\001\022C\n\004base\030\030 \003(\0132-" +
      ".google.fhir.r4.core.SearchParameter.Bas" +
      "eCodeB\006\360\320\207\353\004\001\022C\n\004type\030\031 \001(\0132-.google.fhi" +
      "r.r4.core.SearchParameter.TypeCodeB\006\360\320\207\353" +
      "\004\001\022/\n\nexpression\030\032 \001(\0132\033.google.fhir.r4." +
      "core.String\022*\n\005xpath\030\033 \001(\0132\033.google.fhir" +
      ".r4.core.String\022H\n\013xpath_usage\030\034 \001(\01323.g" +
      "oogle.fhir.r4.core.SearchParameter.Xpath" +
      "UsageCode\022?\n\006target\030\035 \003(\0132/.google.fhir." +
      "r4.core.SearchParameter.TargetCode\0221\n\013mu" +
      "ltiple_or\030\036 \001(\0132\034.google.fhir.r4.core.Bo" +
      "olean\0222\n\014multiple_and\030\037 \001(\0132\034.google.fhi" +
      "r.r4.core.Boolean\022G\n\ncomparator\030  \003(\01323." +
      "google.fhir.r4.core.SearchParameter.Comp" +
      "aratorCode\022C\n\010modifier\030! \003(\01321.google.fh" +
      "ir.r4.core.SearchParameter.ModifierCode\022" +
      "*\n\005chain\030\" \003(\0132\033.google.fhir.r4.core.Str" +
      "ing\022A\n\tcomponent\030# \003(\0132..google.fhir.r4." +
      "core.SearchParameter.Component\032\230\002\n\nStatu" +
      "sCode\022?\n\005value\030\001 \001(\01620.google.fhir.r4.co" +
      "re.PublicationStatusCode.Value\022\'\n\002id\030\002 \001" +
      "(\0132\033.google.fhir.r4.core.String\0221\n\texten" +
      "sion\030\003 \003(\0132\036.google.fhir.r4.core.Extensi" +
      "on:m\300\237\343\266\005\001\212\371\203\262\005/http://hl7.org/fhir/Valu" +
      "eSet/publication-status\232\265\216\223\006,http://hl7." +
      "org/fhir/StructureDefinition/code\032\215\002\n\010Ba" +
      "seCode\022:\n\005value\030\001 \001(\0162+.google.fhir.r4.c" +
      "ore.ResourceTypeCode.Value\022\'\n\002id\030\002 \001(\0132\033" +
      ".google.fhir.r4.core.String\0221\n\textension" +
      "\030\003 \003(\0132\036.google.fhir.r4.core.Extension:i" +
      "\300\237\343\266\005\001\212\371\203\262\005+http://hl7.org/fhir/ValueSet" +
      "/resource-types\232\265\216\223\006,http://hl7.org/fhir" +
      "/StructureDefinition/code\032\223\002\n\010TypeCode\022=" +
      "\n\005value\030\001 \001(\0162..google.fhir.r4.core.Sear" +
      "chParamTypeCode.Value\022\'\n\002id\030\002 \001(\0132\033.goog" +
      "le.fhir.r4.core.String\0221\n\textension\030\003 \003(" +
      "\0132\036.google.fhir.r4.core.Extension:l\300\237\343\266\005" +
      "\001\212\371\203\262\005.http://hl7.org/fhir/ValueSet/sear" +
      "ch-param-type\232\265\216\223\006,http://hl7.org/fhir/S" +
      "tructureDefinition/code\032\231\002\n\016XpathUsageCo" +
      "de\022<\n\005value\030\001 \001(\0162-.google.fhir.r4.core." +
      "XPathUsageTypeCode.Value\022\'\n\002id\030\002 \001(\0132\033.g" +
      "oogle.fhir.r4.core.String\0221\n\textension\030\003" +
      " \003(\0132\036.google.fhir.r4.core.Extension:m\300\237" +
      "\343\266\005\001\212\371\203\262\005/http://hl7.org/fhir/ValueSet/s" +
      "earch-xpath-usage\232\265\216\223\006,http://hl7.org/fh" +
      "ir/StructureDefinition/code\032\217\002\n\nTargetCo" +
      "de\022:\n\005value\030\001 \001(\0162+.google.fhir.r4.core." +
      "ResourceTypeCode.Value\022\'\n\002id\030\002 \001(\0132\033.goo" +
      "gle.fhir.r4.core.String\0221\n\textension\030\003 \003" +
      "(\0132\036.google.fhir.r4.core.Extension:i\300\237\343\266" +
      "\005\001\212\371\203\262\005+http://hl7.org/fhir/ValueSet/res" +
      "ource-types\232\265\216\223\006,http://hl7.org/fhir/Str" +
      "uctureDefinition/code\032\232\002\n\016ComparatorCode" +
      "\022>\n\005value\030\001 \001(\0162/.google.fhir.r4.core.Se" +
      "archComparatorCode.Value\022\'\n\002id\030\002 \001(\0132\033.g" +
      "oogle.fhir.r4.core.String\0221\n\textension\030\003" +
      " \003(\0132\036.google.fhir.r4.core.Extension:l\300\237" +
      "\343\266\005\001\212\371\203\262\005.http://hl7.org/fhir/ValueSet/s" +
      "earch-comparator\232\265\216\223\006,http://hl7.org/fhi" +
      "r/StructureDefinition/code\032\231\002\n\014ModifierC" +
      "ode\022<\n\005value\030\001 \001(\0162-.google.fhir.r4.core" +
      ".SearchModifierCode.Value\022\'\n\002id\030\002 \001(\0132\033." +
      "google.fhir.r4.core.String\0221\n\textension\030" +
      "\003 \003(\0132\036.google.fhir.r4.core.Extension:o\300" +
      "\237\343\266\005\001\212\371\203\262\0051http://hl7.org/fhir/ValueSet/" +
      "search-modifier-code\232\265\216\223\006,http://hl7.org" +
      "/fhir/StructureDefinition/code\032\230\002\n\tCompo" +
      "nent\022\'\n\002id\030\001 \001(\0132\033.google.fhir.r4.core.S" +
      "tring\0221\n\textension\030\002 \003(\0132\036.google.fhir.r" +
      "4.core.Extension\022:\n\022modifier_extension\030\003" +
      " \003(\0132\036.google.fhir.r4.core.Extension\022:\n\n" +
      "definition\030\004 \001(\0132\036.google.fhir.r4.core.C" +
      "anonicalB\006\360\320\207\353\004\001\0227\n\nexpression\030\005 \001(\0132\033.g" +
      "oogle.fhir.r4.core.StringB\006\360\320\207\353\004\001:\2007\300\237\343\266" +
      "\005\003\262\376\344\227\0067http://hl7.org/fhir/StructureDef" +
      "inition/SearchParameter\232\206\223\240\010$xpath.empty" +
      "() or xpathUsage.exists()\232\206\223\240\010#chain.emp" +
      "ty() or type = \'reference\'\262\365\365\327\t\036\n\004base\020\004" +
      "\032\024SearchParameter.base\262\365\365\327\t\036\n\004code\020\004\032\024Se" +
      "archParameter.code\262\365\365\327\t3\n\tcomponent\020\005\032$S" +
      "earchParameter.component.definition\262\365\365\327\t" +
      "\244\006\n\007context\020\004\032\226\006(CapabilityStatement.use" +
      "Context.value as CodeableConcept) | (Cod" +
      "eSystem.useContext.value as CodeableConc" +
      "ept) | (CompartmentDefinition.useContext" +
      ".value as CodeableConcept) | (ConceptMap" +
      ".useContext.value as CodeableConcept) | " +
      "(GraphDefinition.useContext.value as Cod" +
      "eableConcept) | (ImplementationGuide.use" +
      "Context.value as CodeableConcept) | (Mes" +
      "sageDefinition.useContext.value as Codea" +
      "bleConcept) | (NamingSystem.useContext.v" +
      "alue as CodeableConcept) | (OperationDef" +
      "inition.useContext.value as CodeableConc" +
      "ept) | (SearchParameter.useContext.value" +
      " as CodeableConcept) | (StructureDefinit" +
      "ion.useContext.value as CodeableConcept)" +
      " | (StructureMap.useContext.value as Cod" +
      "eableConcept) | (TerminologyCapabilities" +
      ".useContext.value as CodeableConcept) | " +
      "(ValueSet.useContext.value as CodeableCo" +
      "ncept)\262\365\365\327\t\330\n\n\020context-quantity\020\007\032\301\n(Cap" +
      "abilityStatement.useContext.value as Qua" +
      "ntity) | (CapabilityStatement.useContext" +
      ".value as Range) | (CodeSystem.useContex" +
      "t.value as Quantity) | (CodeSystem.useCo" +
      "ntext.value as Range) | (CompartmentDefi" +
      "nition.useContext.value as Quantity) | (" +
      "CompartmentDefinition.useContext.value a" +
      "s Range) | (ConceptMap.useContext.value " +
      "as Quantity) | (ConceptMap.useContext.va" +
      "lue as Range) | (GraphDefinition.useCont" +
      "ext.value as Quantity) | (GraphDefinitio" +
      "n.useContext.value as Range) | (Implemen" +
      "tationGuide.useContext.value as Quantity" +
      ") | (ImplementationGuide.useContext.valu" +
      "e as Range) | (MessageDefinition.useCont" +
      "ext.value as Quantity) | (MessageDefinit" +
      "ion.useContext.value as Range) | (Naming" +
      "System.useContext.value as Quantity) | (" +
      "NamingSystem.useContext.value as Range) " +
      "| (OperationDefinition.useContext.value " +
      "as Quantity) | (OperationDefinition.useC" +
      "ontext.value as Range) | (SearchParamete" +
      "r.useContext.value as Quantity) | (Searc" +
      "hParameter.useContext.value as Range) | " +
      "(StructureDefinition.useContext.value as" +
      " Quantity) | (StructureDefinition.useCon" +
      "text.value as Range) | (StructureMap.use" +
      "Context.value as Quantity) | (StructureM" +
      "ap.useContext.value as Range) | (Termino" +
      "logyCapabilities.useContext.value as Qua" +
      "ntity) | (TerminologyCapabilities.useCon" +
      "text.value as Range) | (ValueSet.useCont" +
      "ext.value as Quantity) | (ValueSet.useCo" +
      "ntext.value as Range)\262\365\365\327\t\365\003\n\014context-ty" +
      "pe\020\004\032\342\003CapabilityStatement.useContext.co" +
      "de | CodeSystem.useContext.code | Compar" +
      "tmentDefinition.useContext.code | Concep" +
      "tMap.useContext.code | GraphDefinition.u" +
      "seContext.code | ImplementationGuide.use" +
      "Context.code | MessageDefinition.useCont" +
      "ext.code | NamingSystem.useContext.code " +
      "| OperationDefinition.useContext.code | " +
      "SearchParameter.useContext.code | Struct" +
      "ureDefinition.useContext.code | Structur" +
      "eMap.useContext.code | TerminologyCapabi" +
      "lities.useContext.code | ValueSet.useCon" +
      "text.code\262\365\365\327\t\270\003\n\025context-type-quantity\020" +
      "\006\032\234\003CapabilityStatement.useContext | Cod" +
      "eSystem.useContext | CompartmentDefiniti" +
      "on.useContext | ConceptMap.useContext | " +
      "GraphDefinition.useContext | Implementat" +
      "ionGuide.useContext | MessageDefinition." +
      "useContext | NamingSystem.useContext | O" +
      "perationDefinition.useContext | SearchPa" +
      "rameter.useContext | StructureDefinition" +
      ".useContext | StructureMap.useContext | " +
      "TerminologyCapabilities.useContext | Val" +
      "ueSet.useContext\262\365\365\327\t\265\003\n\022context-type-va" +
      "lue\020\006\032\234\003CapabilityStatement.useContext |" +
      " CodeSystem.useContext | CompartmentDefi" +
      "nition.useContext | ConceptMap.useContex" +
      "t | GraphDefinition.useContext | Impleme" +
      "ntationGuide.useContext | MessageDefinit" +
      "ion.useContext | NamingSystem.useContext" +
      " | OperationDefinition.useContext | Sear" +
      "chParameter.useContext | StructureDefini" +
      "tion.useContext | StructureMap.useContex" +
      "t | TerminologyCapabilities.useContext |" +
      " ValueSet.useContext\262\365\365\327\t\323\002\n\004date\020\002\032\310\002Ca" +
      "pabilityStatement.date | CodeSystem.date" +
      " | CompartmentDefinition.date | ConceptM" +
      "ap.date | GraphDefinition.date | Impleme" +
      "ntationGuide.date | MessageDefinition.da" +
      "te | NamingSystem.date | OperationDefini" +
      "tion.date | SearchParameter.date | Struc" +
      "tureDefinition.date | StructureMap.date " +
      "| TerminologyCapabilities.date | ValueSe" +
      "t.date\262\365\365\327\t-\n\014derived-from\020\005\032\033SearchPara" +
      "meter.derivedFrom\262\365\365\327\t\274\003\n\013description\020\003\032" +
      "\252\003CapabilityStatement.description | Code" +
      "System.description | CompartmentDefiniti" +
      "on.description | ConceptMap.description " +
      "| GraphDefinition.description | Implemen" +
      "tationGuide.description | MessageDefinit" +
      "ion.description | NamingSystem.descripti" +
      "on | OperationDefinition.description | S" +
      "earchParameter.description | StructureDe" +
      "finition.description | StructureMap.desc" +
      "ription | TerminologyCapabilities.descri" +
      "ption | ValueSet.description\262\365\365\327\t\246\003\n\014jur" +
      "isdiction\020\004\032\223\003CapabilityStatement.jurisd" +
      "iction | CodeSystem.jurisdiction | Conce" +
      "ptMap.jurisdiction | GraphDefinition.jur" +
      "isdiction | ImplementationGuide.jurisdic" +
      "tion | MessageDefinition.jurisdiction | " +
      "NamingSystem.jurisdiction | OperationDef" +
      "inition.jurisdiction | SearchParameter.j" +
      "urisdiction | StructureDefinition.jurisd" +
      "iction | StructureMap.jurisdiction | Ter" +
      "minologyCapabilities.jurisdiction | Valu" +
      "eSet.jurisdiction\262\365\365\327\t\323\002\n\004name\020\003\032\310\002Capab" +
      "ilityStatement.name | CodeSystem.name | " +
      "CompartmentDefinition.name | ConceptMap." +
      "name | GraphDefinition.name | Implementa" +
      "tionGuide.name | MessageDefinition.name " +
      "| NamingSystem.name | OperationDefinitio" +
      "n.name | SearchParameter.name | Structur" +
      "eDefinition.name | StructureMap.name | T" +
      "erminologyCapabilities.name | ValueSet.n" +
      "ame\262\365\365\327\t\236\003\n\tpublisher\020\003\032\216\003CapabilityStat" +
      "ement.publisher | CodeSystem.publisher |" +
      " CompartmentDefinition.publisher | Conce" +
      "ptMap.publisher | GraphDefinition.publis" +
      "her | ImplementationGuide.publisher | Me" +
      "ssageDefinition.publisher | NamingSystem" +
      ".publisher | OperationDefinition.publish" +
      "er | SearchParameter.publisher | Structu" +
      "reDefinition.publisher | StructureMap.pu" +
      "blisher | TerminologyCapabilities.publis" +
      "her | ValueSet.publisher\262\365\365\327\t\361\002\n\006status\020" +
      "\004\032\344\002CapabilityStatement.status | CodeSys" +
      "tem.status | CompartmentDefinition.statu" +
      "s | ConceptMap.status | GraphDefinition." +
      "status | ImplementationGuide.status | Me" +
      "ssageDefinition.status | NamingSystem.st" +
      "atus | OperationDefinition.status | Sear" +
      "chParameter.status | StructureDefinition" +
      ".status | StructureMap.status | Terminol" +
      "ogyCapabilities.status | ValueSet.status" +
      "\262\365\365\327\t\"\n\006target\020\004\032\026SearchParameter.target" +
      "\262\365\365\327\t\036\n\004type\020\004\032\024SearchParameter.type\262\365\365\327" +
      "\t\261\002\n\003url\020\010\032\247\002CapabilityStatement.url | C" +
      "odeSystem.url | CompartmentDefinition.ur" +
      "l | ConceptMap.url | GraphDefinition.url" +
      " | ImplementationGuide.url | MessageDefi" +
      "nition.url | OperationDefinition.url | S" +
      "earchParameter.url | StructureDefinition" +
      ".url | StructureMap.url | TerminologyCap" +
      "abilities.url | ValueSet.url\262\365\365\327\t\351\002\n\007ver" +
      "sion\020\004\032\333\002CapabilityStatement.version | C" +
      "odeSystem.version | CompartmentDefinitio" +
      "n.version | ConceptMap.version | GraphDe" +
      "finition.version | ImplementationGuide.v" +
      "ersion | MessageDefinition.version | Ope" +
      "rationDefinition.version | SearchParamet" +
      "er.version | StructureDefinition.version" +
      " | StructureMap.version | TerminologyCap" +
      "abilities.version | ValueSet.versionJ\004\010\007" +
      "\020\010B!\n\027com.google.fhir.r4.coreP\001\230\306\260\265\007\004b\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
          com.google.fhir.proto.Annotations.getDescriptor(),
          com.google.fhir.r4.core.Codes.getDescriptor(),
          com.google.fhir.r4.core.Datatypes.getDescriptor(),
        });
    internal_static_google_fhir_r4_core_SearchParameter_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_google_fhir_r4_core_SearchParameter_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_fhir_r4_core_SearchParameter_descriptor,
        new java.lang.String[] { "Id", "Meta", "ImplicitRules", "Language", "Text", "Contained", "Extension", "ModifierExtension", "Url", "Version", "Name", "DerivedFrom", "Status", "Experimental", "Date", "Publisher", "Contact", "Description", "UseContext", "Jurisdiction", "Purpose", "Code", "Base", "Type", "Expression", "Xpath", "XpathUsage", "Target", "MultipleOr", "MultipleAnd", "Comparator", "Modifier", "Chain", "Component", });
    internal_static_google_fhir_r4_core_SearchParameter_StatusCode_descriptor =
      internal_static_google_fhir_r4_core_SearchParameter_descriptor.getNestedTypes().get(0);
    internal_static_google_fhir_r4_core_SearchParameter_StatusCode_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_fhir_r4_core_SearchParameter_StatusCode_descriptor,
        new java.lang.String[] { "Value", "Id", "Extension", });
    internal_static_google_fhir_r4_core_SearchParameter_BaseCode_descriptor =
      internal_static_google_fhir_r4_core_SearchParameter_descriptor.getNestedTypes().get(1);
    internal_static_google_fhir_r4_core_SearchParameter_BaseCode_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_fhir_r4_core_SearchParameter_BaseCode_descriptor,
        new java.lang.String[] { "Value", "Id", "Extension", });
    internal_static_google_fhir_r4_core_SearchParameter_TypeCode_descriptor =
      internal_static_google_fhir_r4_core_SearchParameter_descriptor.getNestedTypes().get(2);
    internal_static_google_fhir_r4_core_SearchParameter_TypeCode_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_fhir_r4_core_SearchParameter_TypeCode_descriptor,
        new java.lang.String[] { "Value", "Id", "Extension", });
    internal_static_google_fhir_r4_core_SearchParameter_XpathUsageCode_descriptor =
      internal_static_google_fhir_r4_core_SearchParameter_descriptor.getNestedTypes().get(3);
    internal_static_google_fhir_r4_core_SearchParameter_XpathUsageCode_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_fhir_r4_core_SearchParameter_XpathUsageCode_descriptor,
        new java.lang.String[] { "Value", "Id", "Extension", });
    internal_static_google_fhir_r4_core_SearchParameter_TargetCode_descriptor =
      internal_static_google_fhir_r4_core_SearchParameter_descriptor.getNestedTypes().get(4);
    internal_static_google_fhir_r4_core_SearchParameter_TargetCode_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_fhir_r4_core_SearchParameter_TargetCode_descriptor,
        new java.lang.String[] { "Value", "Id", "Extension", });
    internal_static_google_fhir_r4_core_SearchParameter_ComparatorCode_descriptor =
      internal_static_google_fhir_r4_core_SearchParameter_descriptor.getNestedTypes().get(5);
    internal_static_google_fhir_r4_core_SearchParameter_ComparatorCode_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_fhir_r4_core_SearchParameter_ComparatorCode_descriptor,
        new java.lang.String[] { "Value", "Id", "Extension", });
    internal_static_google_fhir_r4_core_SearchParameter_ModifierCode_descriptor =
      internal_static_google_fhir_r4_core_SearchParameter_descriptor.getNestedTypes().get(6);
    internal_static_google_fhir_r4_core_SearchParameter_ModifierCode_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_fhir_r4_core_SearchParameter_ModifierCode_descriptor,
        new java.lang.String[] { "Value", "Id", "Extension", });
    internal_static_google_fhir_r4_core_SearchParameter_Component_descriptor =
      internal_static_google_fhir_r4_core_SearchParameter_descriptor.getNestedTypes().get(7);
    internal_static_google_fhir_r4_core_SearchParameter_Component_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_fhir_r4_core_SearchParameter_Component_descriptor,
        new java.lang.String[] { "Id", "Extension", "ModifierExtension", "Definition", "Expression", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.fhir.proto.Annotations.fhirPathMessageConstraint);
    registry.add(com.google.fhir.proto.Annotations.fhirProfileBase);
    registry.add(com.google.fhir.proto.Annotations.fhirStructureDefinitionUrl);
    registry.add(com.google.fhir.proto.Annotations.fhirValuesetUrl);
    registry.add(com.google.fhir.proto.Annotations.fhirVersion);
    registry.add(com.google.fhir.proto.Annotations.searchParameter);
    registry.add(com.google.fhir.proto.Annotations.structureDefinitionKind);
    registry.add(com.google.fhir.proto.Annotations.validationRequirement);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.protobuf.AnyProto.getDescriptor();
    com.google.fhir.proto.Annotations.getDescriptor();
    com.google.fhir.r4.core.Codes.getDescriptor();
    com.google.fhir.r4.core.Datatypes.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
