// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/r4/core/resources/test_report.proto

package com.google.fhir.r4.core;

public final class TestReportOuterClass {
  private TestReportOuterClass() {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
  }

  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_fhir_r4_core_TestReport_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_fhir_r4_core_TestReport_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_fhir_r4_core_TestReport_StatusCode_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_fhir_r4_core_TestReport_StatusCode_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_fhir_r4_core_TestReport_ResultCode_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_fhir_r4_core_TestReport_ResultCode_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_fhir_r4_core_TestReport_Participant_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_fhir_r4_core_TestReport_Participant_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_fhir_r4_core_TestReport_Participant_TypeCode_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_fhir_r4_core_TestReport_Participant_TypeCode_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_fhir_r4_core_TestReport_Setup_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_fhir_r4_core_TestReport_Setup_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_fhir_r4_core_TestReport_Setup_SetupAction_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_fhir_r4_core_TestReport_Setup_SetupAction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_fhir_r4_core_TestReport_Setup_SetupAction_Operation_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_fhir_r4_core_TestReport_Setup_SetupAction_Operation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_fhir_r4_core_TestReport_Setup_SetupAction_Operation_ResultCode_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_fhir_r4_core_TestReport_Setup_SetupAction_Operation_ResultCode_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_fhir_r4_core_TestReport_Setup_SetupAction_Assert_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_fhir_r4_core_TestReport_Setup_SetupAction_Assert_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_fhir_r4_core_TestReport_Setup_SetupAction_Assert_ResultCode_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_fhir_r4_core_TestReport_Setup_SetupAction_Assert_ResultCode_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_fhir_r4_core_TestReport_Test_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_fhir_r4_core_TestReport_Test_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_fhir_r4_core_TestReport_Test_TestAction_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_fhir_r4_core_TestReport_Test_TestAction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_fhir_r4_core_TestReport_Teardown_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_fhir_r4_core_TestReport_Teardown_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_fhir_r4_core_TestReport_Teardown_TeardownAction_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_fhir_r4_core_TestReport_Teardown_TeardownAction_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
    return descriptor;
  }

  private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

  static {
    java.lang.String[] descriptorData = {
      "\n)proto/r4/core/resources/test_report.pr"
          + "oto\022\023google.fhir.r4.core\032\031google/protobu"
          + "f/any.proto\032\027proto/annotations.proto\032\031pr"
          + "oto/r4/core/codes.proto\032\035proto/r4/core/d"
          + "atatypes.proto\"\315*\n\nTestReport\022#\n\002id\030\001 \001("
          + "\0132\027.google.fhir.r4.core.Id\022\'\n\004meta\030\002 \001(\013"
          + "2\031.google.fhir.r4.core.Meta\0220\n\016implicit_"
          + "rules\030\003 \001(\0132\030.google.fhir.r4.core.Uri\022+\n"
          + "\010language\030\004 \001(\0132\031.google.fhir.r4.core.Co"
          + "de\022,\n\004text\030\005 \001(\0132\036.google.fhir.r4.core.N"
          + "arrative\022\'\n\tcontained\030\006 \003(\0132\024.google.pro"
          + "tobuf.Any\0221\n\textension\030\010 \003(\0132\036.google.fh"
          + "ir.r4.core.Extension\022:\n\022modifier_extensi"
          + "on\030\t \003(\0132\036.google.fhir.r4.core.Extension"
          + "\0223\n\nidentifier\030\n \001(\0132\037.google.fhir.r4.co"
          + "re.Identifier\022)\n\004name\030\013 \001(\0132\033.google.fhi"
          + "r.r4.core.String\022B\n\006status\030\014 \001(\0132*.googl"
          + "e.fhir.r4.core.TestReport.StatusCodeB\006\360\320"
          + "\207\353\004\001\022K\n\013test_script\030\r \001(\0132\036.google.fhir."
          + "r4.core.ReferenceB\026\360\320\207\353\004\001\362\377\374\302\006\nTestScrip"
          + "t\022B\n\006result\030\016 \001(\0132*.google.fhir.r4.core."
          + "TestReport.ResultCodeB\006\360\320\207\353\004\001\022+\n\005score\030\017"
          + " \001(\0132\034.google.fhir.r4.core.Decimal\022+\n\006te"
          + "ster\030\020 \001(\0132\033.google.fhir.r4.core.String\022"
          + "-\n\006issued\030\021 \001(\0132\035.google.fhir.r4.core.Da"
          + "teTime\022@\n\013participant\030\022 \003(\0132+.google.fhi"
          + "r.r4.core.TestReport.Participant\0224\n\005setu"
          + "p\030\023 \001(\0132%.google.fhir.r4.core.TestReport"
          + ".Setup\0222\n\004test\030\024 \003(\0132$.google.fhir.r4.co"
          + "re.TestReport.Test\022:\n\010teardown\030\025 \001(\0132(.g"
          + "oogle.fhir.r4.core.TestReport.Teardown\032\230"
          + "\002\n\nStatusCode\022>\n\005value\030\001 \001(\0162/.google.fh"
          + "ir.r4.core.TestReportStatusCode.Value\022\'\n"
          + "\002id\030\002 \001(\0132\033.google.fhir.r4.core.String\0221"
          + "\n\textension\030\003 \003(\0132\036.google.fhir.r4.core."
          + "Extension:n\300\237\343\266\005\001\212\371\203\262\0050http://hl7.org/fh"
          + "ir/ValueSet/report-status-codes\232\265\216\223\006,htt"
          + "p://hl7.org/fhir/StructureDefinition/cod"
          + "e\032\230\002\n\nResultCode\022>\n\005value\030\001 \001(\0162/.google"
          + ".fhir.r4.core.TestReportResultCode.Value"
          + "\022\'\n\002id\030\002 \001(\0132\033.google.fhir.r4.core.Strin"
          + "g\0221\n\textension\030\003 \003(\0132\036.google.fhir.r4.co"
          + "re.Extension:n\300\237\343\266\005\001\212\371\203\262\0050http://hl7.org"
          + "/fhir/ValueSet/report-result-codes\232\265\216\223\006,"
          + "http://hl7.org/fhir/StructureDefinition/"
          + "code\032\364\004\n\013Participant\022\'\n\002id\030\001 \001(\0132\033.googl"
          + "e.fhir.r4.core.String\0221\n\textension\030\002 \003(\013"
          + "2\036.google.fhir.r4.core.Extension\022:\n\022modi"
          + "fier_extension\030\003 \003(\0132\036.google.fhir.r4.co"
          + "re.Extension\022J\n\004type\030\004 \001(\01324.google.fhir"
          + ".r4.core.TestReport.Participant.TypeCode"
          + "B\006\360\320\207\353\004\001\022-\n\003uri\030\005 \001(\0132\030.google.fhir.r4.c"
          + "ore.UriB\006\360\320\207\353\004\001\022,\n\007display\030\006 \001(\0132\033.googl"
          + "e.fhir.r4.core.String\032\243\002\n\010TypeCode\022G\n\005va"
          + "lue\030\001 \001(\01628.google.fhir.r4.core.TestRepo"
          + "rtParticipantTypeCode.Value\022\'\n\002id\030\002 \001(\0132"
          + "\033.google.fhir.r4.core.String\0221\n\textensio"
          + "n\030\003 \003(\0132\036.google.fhir.r4.core.Extension:"
          + "r\300\237\343\266\005\001\212\371\203\262\0054http://hl7.org/fhir/ValueSe"
          + "t/report-participant-type\232\265\216\223\006,http://hl"
          + "7.org/fhir/StructureDefinition/code\032\365\016\n\005"
          + "Setup\022\'\n\002id\030\001 \001(\0132\033.google.fhir.r4.core."
          + "String\0221\n\textension\030\002 \003(\0132\036.google.fhir."
          + "r4.core.Extension\022:\n\022modifier_extension\030"
          + "\003 \003(\0132\036.google.fhir.r4.core.Extension\022I\n"
          + "\006action\030\004 \003(\01321.google.fhir.r4.core.Test"
          + "Report.Setup.SetupActionB\006\360\320\207\353\004\001\032\210\r\n\013Set"
          + "upAction\022\'\n\002id\030\001 \001(\0132\033.google.fhir.r4.co"
          + "re.String\0221\n\textension\030\002 \003(\0132\036.google.fh"
          + "ir.r4.core.Extension\022:\n\022modifier_extensi"
          + "on\030\003 \003(\0132\036.google.fhir.r4.core.Extension"
          + "\022N\n\toperation\030\004 \001(\0132;.google.fhir.r4.cor"
          + "e.TestReport.Setup.SetupAction.Operation"
          + "\022V\n\014assert_value\030\005 \001(\01328.google.fhir.r4."
          + "core.TestReport.Setup.SetupAction.Assert"
          + "R\006assert\032\205\005\n\tOperation\022\'\n\002id\030\001 \001(\0132\033.goo"
          + "gle.fhir.r4.core.String\0221\n\textension\030\002 \003"
          + "(\0132\036.google.fhir.r4.core.Extension\022:\n\022mo"
          + "difier_extension\030\003 \003(\0132\036.google.fhir.r4."
          + "core.Extension\022^\n\006result\030\004 \001(\0132F.google."
          + "fhir.r4.core.TestReport.Setup.SetupActio"
          + "n.Operation.ResultCodeB\006\360\320\207\353\004\001\022.\n\007messag"
          + "e\030\005 \001(\0132\035.google.fhir.r4.core.Markdown\022("
          + "\n\006detail\030\006 \001(\0132\030.google.fhir.r4.core.Uri"
          + "\032\245\002\n\nResultCode\022D\n\005value\030\001 \001(\01625.google."
          + "fhir.r4.core.TestReportActionResultCode."
          + "Value\022\'\n\002id\030\002 \001(\0132\033.google.fhir.r4.core."
          + "String\0221\n\textension\030\003 \003(\0132\036.google.fhir."
          + "r4.core.Extension:u\300\237\343\266\005\001\212\371\203\262\0057http://hl"
          + "7.org/fhir/ValueSet/report-action-result"
          + "-codes\232\265\216\223\006,http://hl7.org/fhir/Structur"
          + "eDefinition/code\032\202\005\n\006Assert\022\'\n\002id\030\001 \001(\0132"
          + "\033.google.fhir.r4.core.String\0221\n\textensio"
          + "n\030\002 \003(\0132\036.google.fhir.r4.core.Extension\022"
          + ":\n\022modifier_extension\030\003 \003(\0132\036.google.fhi"
          + "r.r4.core.Extension\022[\n\006result\030\004 \001(\0132C.go"
          + "ogle.fhir.r4.core.TestReport.Setup.Setup"
          + "Action.Assert.ResultCodeB\006\360\320\207\353\004\001\022.\n\007mess"
          + "age\030\005 \001(\0132\035.google.fhir.r4.core.Markdown"
          + "\022+\n\006detail\030\006 \001(\0132\033.google.fhir.r4.core.S"
          + "tring\032\245\002\n\nResultCode\022D\n\005value\030\001 \001(\01625.go"
          + "ogle.fhir.r4.core.TestReportActionResult"
          + "Code.Value\022\'\n\002id\030\002 \001(\0132\033.google.fhir.r4."
          + "core.String\0221\n\textension\030\003 \003(\0132\036.google."
          + "fhir.r4.core.Extension:u\300\237\343\266\005\001\212\371\203\262\0057http"
          + "://hl7.org/fhir/ValueSet/report-action-r"
          + "esult-codes\232\265\216\223\006,http://hl7.org/fhir/Str"
          + "uctureDefinition/code:,\232\206\223\240\010&operation.e"
          + "xists() xor assert.exists()\032\301\005\n\004Test\022\'\n\002"
          + "id\030\001 \001(\0132\033.google.fhir.r4.core.String\0221\n"
          + "\textension\030\002 \003(\0132\036.google.fhir.r4.core.E"
          + "xtension\022:\n\022modifier_extension\030\003 \003(\0132\036.g"
          + "oogle.fhir.r4.core.Extension\022)\n\004name\030\004 \001"
          + "(\0132\033.google.fhir.r4.core.String\0220\n\013descr"
          + "iption\030\005 \001(\0132\033.google.fhir.r4.core.Strin"
          + "g\022G\n\006action\030\006 \003(\0132/.google.fhir.r4.core."
          + "TestReport.Test.TestActionB\006\360\320\207\353\004\001\032\372\002\n\nT"
          + "estAction\022\'\n\002id\030\001 \001(\0132\033.google.fhir.r4.c"
          + "ore.String\0221\n\textension\030\002 \003(\0132\036.google.f"
          + "hir.r4.core.Extension\022:\n\022modifier_extens"
          + "ion\030\003 \003(\0132\036.google.fhir.r4.core.Extensio"
          + "n\022N\n\toperation\030\004 \001(\0132;.google.fhir.r4.co"
          + "re.TestReport.Setup.SetupAction.Operatio"
          + "n\022V\n\014assert_value\030\005 \001(\01328.google.fhir.r4"
          + ".core.TestReport.Setup.SetupAction.Asser"
          + "tR\006assert:,\232\206\223\240\010&operation.exists() xor "
          + "assert.exists()\032\366\003\n\010Teardown\022\'\n\002id\030\001 \001(\013"
          + "2\033.google.fhir.r4.core.String\0221\n\textensi"
          + "on\030\002 \003(\0132\036.google.fhir.r4.core.Extension"
          + "\022:\n\022modifier_extension\030\003 \003(\0132\036.google.fh"
          + "ir.r4.core.Extension\022O\n\006action\030\004 \003(\01327.g"
          + "oogle.fhir.r4.core.TestReport.Teardown.T"
          + "eardownActionB\006\360\320\207\353\004\001\032\200\002\n\016TeardownAction"
          + "\022\'\n\002id\030\001 \001(\0132\033.google.fhir.r4.core.Strin"
          + "g\0221\n\textension\030\002 \003(\0132\036.google.fhir.r4.co"
          + "re.Extension\022:\n\022modifier_extension\030\003 \003(\013"
          + "2\036.google.fhir.r4.core.Extension\022V\n\toper"
          + "ation\030\004 \001(\0132;.google.fhir.r4.core.TestRe"
          + "port.Setup.SetupAction.OperationB\006\360\320\207\353\004\001"
          + ":>\300\237\343\266\005\003\262\376\344\227\0062http://hl7.org/fhir/Struct"
          + "ureDefinition/TestReportJ\004\010\007\020\010B!\n\027com.go"
          + "ogle.fhir.r4.coreP\001\230\306\260\265\007\004b\006proto3"
    };
    descriptor =
        com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(
            descriptorData,
            new com.google.protobuf.Descriptors.FileDescriptor[] {
              com.google.protobuf.AnyProto.getDescriptor(),
              com.google.fhir.proto.Annotations.getDescriptor(),
              com.google.fhir.r4.core.Codes.getDescriptor(),
              com.google.fhir.r4.core.Datatypes.getDescriptor(),
            });
    internal_static_google_fhir_r4_core_TestReport_descriptor =
        getDescriptor().getMessageTypes().get(0);
    internal_static_google_fhir_r4_core_TestReport_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_fhir_r4_core_TestReport_descriptor,
            new java.lang.String[] {
              "Id",
              "Meta",
              "ImplicitRules",
              "Language",
              "Text",
              "Contained",
              "Extension",
              "ModifierExtension",
              "Identifier",
              "Name",
              "Status",
              "TestScript",
              "Result",
              "Score",
              "Tester",
              "Issued",
              "Participant",
              "Setup",
              "Test",
              "Teardown",
            });
    internal_static_google_fhir_r4_core_TestReport_StatusCode_descriptor =
        internal_static_google_fhir_r4_core_TestReport_descriptor.getNestedTypes().get(0);
    internal_static_google_fhir_r4_core_TestReport_StatusCode_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_fhir_r4_core_TestReport_StatusCode_descriptor,
            new java.lang.String[] {
              "Value", "Id", "Extension",
            });
    internal_static_google_fhir_r4_core_TestReport_ResultCode_descriptor =
        internal_static_google_fhir_r4_core_TestReport_descriptor.getNestedTypes().get(1);
    internal_static_google_fhir_r4_core_TestReport_ResultCode_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_fhir_r4_core_TestReport_ResultCode_descriptor,
            new java.lang.String[] {
              "Value", "Id", "Extension",
            });
    internal_static_google_fhir_r4_core_TestReport_Participant_descriptor =
        internal_static_google_fhir_r4_core_TestReport_descriptor.getNestedTypes().get(2);
    internal_static_google_fhir_r4_core_TestReport_Participant_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_fhir_r4_core_TestReport_Participant_descriptor,
            new java.lang.String[] {
              "Id", "Extension", "ModifierExtension", "Type", "Uri", "Display",
            });
    internal_static_google_fhir_r4_core_TestReport_Participant_TypeCode_descriptor =
        internal_static_google_fhir_r4_core_TestReport_Participant_descriptor
            .getNestedTypes()
            .get(0);
    internal_static_google_fhir_r4_core_TestReport_Participant_TypeCode_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_fhir_r4_core_TestReport_Participant_TypeCode_descriptor,
            new java.lang.String[] {
              "Value", "Id", "Extension",
            });
    internal_static_google_fhir_r4_core_TestReport_Setup_descriptor =
        internal_static_google_fhir_r4_core_TestReport_descriptor.getNestedTypes().get(3);
    internal_static_google_fhir_r4_core_TestReport_Setup_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_fhir_r4_core_TestReport_Setup_descriptor,
            new java.lang.String[] {
              "Id", "Extension", "ModifierExtension", "Action",
            });
    internal_static_google_fhir_r4_core_TestReport_Setup_SetupAction_descriptor =
        internal_static_google_fhir_r4_core_TestReport_Setup_descriptor.getNestedTypes().get(0);
    internal_static_google_fhir_r4_core_TestReport_Setup_SetupAction_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_fhir_r4_core_TestReport_Setup_SetupAction_descriptor,
            new java.lang.String[] {
              "Id", "Extension", "ModifierExtension", "Operation", "AssertValue",
            });
    internal_static_google_fhir_r4_core_TestReport_Setup_SetupAction_Operation_descriptor =
        internal_static_google_fhir_r4_core_TestReport_Setup_SetupAction_descriptor
            .getNestedTypes()
            .get(0);
    internal_static_google_fhir_r4_core_TestReport_Setup_SetupAction_Operation_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_fhir_r4_core_TestReport_Setup_SetupAction_Operation_descriptor,
            new java.lang.String[] {
              "Id", "Extension", "ModifierExtension", "Result", "Message", "Detail",
            });
    internal_static_google_fhir_r4_core_TestReport_Setup_SetupAction_Operation_ResultCode_descriptor =
        internal_static_google_fhir_r4_core_TestReport_Setup_SetupAction_Operation_descriptor
            .getNestedTypes()
            .get(0);
    internal_static_google_fhir_r4_core_TestReport_Setup_SetupAction_Operation_ResultCode_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_fhir_r4_core_TestReport_Setup_SetupAction_Operation_ResultCode_descriptor,
            new java.lang.String[] {
              "Value", "Id", "Extension",
            });
    internal_static_google_fhir_r4_core_TestReport_Setup_SetupAction_Assert_descriptor =
        internal_static_google_fhir_r4_core_TestReport_Setup_SetupAction_descriptor
            .getNestedTypes()
            .get(1);
    internal_static_google_fhir_r4_core_TestReport_Setup_SetupAction_Assert_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_fhir_r4_core_TestReport_Setup_SetupAction_Assert_descriptor,
            new java.lang.String[] {
              "Id", "Extension", "ModifierExtension", "Result", "Message", "Detail",
            });
    internal_static_google_fhir_r4_core_TestReport_Setup_SetupAction_Assert_ResultCode_descriptor =
        internal_static_google_fhir_r4_core_TestReport_Setup_SetupAction_Assert_descriptor
            .getNestedTypes()
            .get(0);
    internal_static_google_fhir_r4_core_TestReport_Setup_SetupAction_Assert_ResultCode_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_fhir_r4_core_TestReport_Setup_SetupAction_Assert_ResultCode_descriptor,
            new java.lang.String[] {
              "Value", "Id", "Extension",
            });
    internal_static_google_fhir_r4_core_TestReport_Test_descriptor =
        internal_static_google_fhir_r4_core_TestReport_descriptor.getNestedTypes().get(4);
    internal_static_google_fhir_r4_core_TestReport_Test_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_fhir_r4_core_TestReport_Test_descriptor,
            new java.lang.String[] {
              "Id", "Extension", "ModifierExtension", "Name", "Description", "Action",
            });
    internal_static_google_fhir_r4_core_TestReport_Test_TestAction_descriptor =
        internal_static_google_fhir_r4_core_TestReport_Test_descriptor.getNestedTypes().get(0);
    internal_static_google_fhir_r4_core_TestReport_Test_TestAction_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_fhir_r4_core_TestReport_Test_TestAction_descriptor,
            new java.lang.String[] {
              "Id", "Extension", "ModifierExtension", "Operation", "AssertValue",
            });
    internal_static_google_fhir_r4_core_TestReport_Teardown_descriptor =
        internal_static_google_fhir_r4_core_TestReport_descriptor.getNestedTypes().get(5);
    internal_static_google_fhir_r4_core_TestReport_Teardown_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_fhir_r4_core_TestReport_Teardown_descriptor,
            new java.lang.String[] {
              "Id", "Extension", "ModifierExtension", "Action",
            });
    internal_static_google_fhir_r4_core_TestReport_Teardown_TeardownAction_descriptor =
        internal_static_google_fhir_r4_core_TestReport_Teardown_descriptor.getNestedTypes().get(0);
    internal_static_google_fhir_r4_core_TestReport_Teardown_TeardownAction_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_fhir_r4_core_TestReport_Teardown_TeardownAction_descriptor,
            new java.lang.String[] {
              "Id", "Extension", "ModifierExtension", "Operation",
            });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.fhir.proto.Annotations.fhirPathMessageConstraint);
    registry.add(com.google.fhir.proto.Annotations.fhirProfileBase);
    registry.add(com.google.fhir.proto.Annotations.fhirStructureDefinitionUrl);
    registry.add(com.google.fhir.proto.Annotations.fhirValuesetUrl);
    registry.add(com.google.fhir.proto.Annotations.fhirVersion);
    registry.add(com.google.fhir.proto.Annotations.structureDefinitionKind);
    registry.add(com.google.fhir.proto.Annotations.validReferenceType);
    registry.add(com.google.fhir.proto.Annotations.validationRequirement);
    com.google.protobuf.Descriptors.FileDescriptor.internalUpdateFileDescriptor(
        descriptor, registry);
    com.google.protobuf.AnyProto.getDescriptor();
    com.google.fhir.proto.Annotations.getDescriptor();
    com.google.fhir.r4.core.Codes.getDescriptor();
    com.google.fhir.r4.core.Datatypes.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
