package com.babylonhealth.lit.hl7_java.codes;

import com.babylonhealth.lit.hl7.ACTION_SELECTION_BEHAVIOR;

public interface ActionSelectionBehavior {
  public static final ACTION_SELECTION_BEHAVIOR ALL = ACTION_SELECTION_BEHAVIOR.ALL$.MODULE$;
  public static final ACTION_SELECTION_BEHAVIOR ALL_OR_NONE =
      ACTION_SELECTION_BEHAVIOR.ALL_OR_NONE$.MODULE$;
  public static final ACTION_SELECTION_BEHAVIOR ANY = ACTION_SELECTION_BEHAVIOR.ANY$.MODULE$;
  public static final ACTION_SELECTION_BEHAVIOR AT_MOST_ONE =
      ACTION_SELECTION_BEHAVIOR.AT_MOST_ONE$.MODULE$;
  public static final ACTION_SELECTION_BEHAVIOR EXACTLY_ONE =
      ACTION_SELECTION_BEHAVIOR.EXACTLY_ONE$.MODULE$;
  public static final ACTION_SELECTION_BEHAVIOR ONE_OR_MORE =
      ACTION_SELECTION_BEHAVIOR.ONE_OR_MORE$.MODULE$;
}
