package com.babylonhealth.lit.hl7_java.codes;

import com.babylonhealth.lit.hl7.ACTION_RELATIONSHIP_TYPE;

public interface ActionRelationshipType {
  public static final ACTION_RELATIONSHIP_TYPE AFTER = ACTION_RELATIONSHIP_TYPE.AFTER$.MODULE$;
  public static final ACTION_RELATIONSHIP_TYPE AFTER_END =
      ACTION_RELATIONSHIP_TYPE.AFTER_END$.MODULE$;
  public static final ACTION_RELATIONSHIP_TYPE AFTER_START =
      ACTION_RELATIONSHIP_TYPE.AFTER_START$.MODULE$;
  public static final ACTION_RELATIONSHIP_TYPE BEFORE = ACTION_RELATIONSHIP_TYPE.BEFORE$.MODULE$;
  public static final ACTION_RELATIONSHIP_TYPE BEFORE_END =
      ACTION_RELATIONSHIP_TYPE.BEFORE_END$.MODULE$;
  public static final ACTION_RELATIONSHIP_TYPE BEFORE_START =
      ACTION_RELATIONSHIP_TYPE.BEFORE_START$.MODULE$;
  public static final ACTION_RELATIONSHIP_TYPE CONCURRENT =
      ACTION_RELATIONSHIP_TYPE.CONCURRENT$.MODULE$;
  public static final ACTION_RELATIONSHIP_TYPE CONCURRENT_WITH_END =
      ACTION_RELATIONSHIP_TYPE.CONCURRENT_WITH_END$.MODULE$;
  public static final ACTION_RELATIONSHIP_TYPE CONCURRENT_WITH_START =
      ACTION_RELATIONSHIP_TYPE.CONCURRENT_WITH_START$.MODULE$;
}
