package com.babylonhealth.lit.hl7_java.codes;

import com.babylonhealth.lit.hl7.ALLERGY_INTOLERANCE_CATEGORY;

public interface AllergyIntoleranceCategory {
  public static final ALLERGY_INTOLERANCE_CATEGORY BIOLOGIC =
      ALLERGY_INTOLERANCE_CATEGORY.BIOLOGIC$.MODULE$;
  public static final ALLERGY_INTOLERANCE_CATEGORY ENVIRONMENT =
      ALLERGY_INTOLERANCE_CATEGORY.ENVIRONMENT$.MODULE$;
  public static final ALLERGY_INTOLERANCE_CATEGORY FOOD =
      ALLERGY_INTOLERANCE_CATEGORY.FOOD$.MODULE$;
  public static final ALLERGY_INTOLERANCE_CATEGORY MEDICATION =
      ALLERGY_INTOLERANCE_CATEGORY.MEDICATION$.MODULE$;
}
