package com.babylonhealth.lit.hl7_java.codes;

import com.babylonhealth.lit.hl7.APPOINTMENTSTATUS;

public interface Appointmentstatus {
  public static final APPOINTMENTSTATUS ARRIVED = APPOINTMENTSTATUS.ARRIVED$.MODULE$;
  public static final APPOINTMENTSTATUS BOOKED = APPOINTMENTSTATUS.BOOKED$.MODULE$;
  public static final APPOINTMENTSTATUS CANCELLED = APPOINTMENTSTATUS.CANCELLED$.MODULE$;
  public static final APPOINTMENTSTATUS CHECKED_IN = APPOINTMENTSTATUS.CHECKED_IN$.MODULE$;
  public static final APPOINTMENTSTATUS ENTERED_IN_ERROR =
      APPOINTMENTSTATUS.ENTERED_IN_ERROR$.MODULE$;
  public static final APPOINTMENTSTATUS FULFILLED = APPOINTMENTSTATUS.FULFILLED$.MODULE$;
  public static final APPOINTMENTSTATUS NOSHOW = APPOINTMENTSTATUS.NOSHOW$.MODULE$;
  public static final APPOINTMENTSTATUS PENDING = APPOINTMENTSTATUS.PENDING$.MODULE$;
  public static final APPOINTMENTSTATUS PROPOSED = APPOINTMENTSTATUS.PROPOSED$.MODULE$;
  public static final APPOINTMENTSTATUS WAITLIST = APPOINTMENTSTATUS.WAITLIST$.MODULE$;
}
