package com.babylonhealth.lit.hl7_java.codes;

import com.babylonhealth.lit.hl7.ASSERT_RESPONSE_CODE_TYPES;

public interface AssertResponseCodeTypes {
  public static final ASSERT_RESPONSE_CODE_TYPES BAD = ASSERT_RESPONSE_CODE_TYPES.BAD$.MODULE$;
  public static final ASSERT_RESPONSE_CODE_TYPES CONFLICT =
      ASSERT_RESPONSE_CODE_TYPES.CONFLICT$.MODULE$;
  public static final ASSERT_RESPONSE_CODE_TYPES CREATED =
      ASSERT_RESPONSE_CODE_TYPES.CREATED$.MODULE$;
  public static final ASSERT_RESPONSE_CODE_TYPES FORBIDDEN =
      ASSERT_RESPONSE_CODE_TYPES.FORBIDDEN$.MODULE$;
  public static final ASSERT_RESPONSE_CODE_TYPES GONE = ASSERT_RESPONSE_CODE_TYPES.GONE$.MODULE$;
  public static final ASSERT_RESPONSE_CODE_TYPES METHODNOTALLOWED =
      ASSERT_RESPONSE_CODE_TYPES.METHODNOTALLOWED$.MODULE$;
  public static final ASSERT_RESPONSE_CODE_TYPES NOCONTENT =
      ASSERT_RESPONSE_CODE_TYPES.NOCONTENT$.MODULE$;
  public static final ASSERT_RESPONSE_CODE_TYPES NOTFOUND =
      ASSERT_RESPONSE_CODE_TYPES.NOTFOUND$.MODULE$;
  public static final ASSERT_RESPONSE_CODE_TYPES NOTMODIFIED =
      ASSERT_RESPONSE_CODE_TYPES.NOTMODIFIED$.MODULE$;
  public static final ASSERT_RESPONSE_CODE_TYPES OKAY = ASSERT_RESPONSE_CODE_TYPES.OKAY$.MODULE$;
  public static final ASSERT_RESPONSE_CODE_TYPES PRECONDITIONFAILED =
      ASSERT_RESPONSE_CODE_TYPES.PRECONDITIONFAILED$.MODULE$;
  public static final ASSERT_RESPONSE_CODE_TYPES UNPROCESSABLE =
      ASSERT_RESPONSE_CODE_TYPES.UNPROCESSABLE$.MODULE$;
}
