package com.babylonhealth.lit.hl7_java.codes;

import com.babylonhealth.lit.hl7.ASSERT_OPERATOR_CODES;

public interface AssertOperatorCodes {
  public static final ASSERT_OPERATOR_CODES CONTAINS = ASSERT_OPERATOR_CODES.CONTAINS$.MODULE$;
  public static final ASSERT_OPERATOR_CODES EMPTY = ASSERT_OPERATOR_CODES.EMPTY$.MODULE$;
  public static final ASSERT_OPERATOR_CODES EQUALS = ASSERT_OPERATOR_CODES.EQUALS$.MODULE$;
  public static final ASSERT_OPERATOR_CODES EVAL = ASSERT_OPERATOR_CODES.EVAL$.MODULE$;
  public static final ASSERT_OPERATOR_CODES GREATERTHAN =
      ASSERT_OPERATOR_CODES.GREATERTHAN$.MODULE$;
  public static final ASSERT_OPERATOR_CODES IN = ASSERT_OPERATOR_CODES.IN$.MODULE$;
  public static final ASSERT_OPERATOR_CODES LESSTHAN = ASSERT_OPERATOR_CODES.LESSTHAN$.MODULE$;
  public static final ASSERT_OPERATOR_CODES NOTCONTAINS =
      ASSERT_OPERATOR_CODES.NOTCONTAINS$.MODULE$;
  public static final ASSERT_OPERATOR_CODES NOTEMPTY = ASSERT_OPERATOR_CODES.NOTEMPTY$.MODULE$;
  public static final ASSERT_OPERATOR_CODES NOTEQUALS = ASSERT_OPERATOR_CODES.NOTEQUALS$.MODULE$;
  public static final ASSERT_OPERATOR_CODES NOTIN = ASSERT_OPERATOR_CODES.NOTIN$.MODULE$;
}
