package com.babylonhealth.lit.hl7_java.codes;

import com.babylonhealth.lit.hl7.CARE_PLAN_ACTIVITY_KIND;

public interface CarePlanActivityKind {
  public static final CARE_PLAN_ACTIVITY_KIND APPOINTMENT =
      CARE_PLAN_ACTIVITY_KIND.APPOINTMENT$.MODULE$;
  public static final CARE_PLAN_ACTIVITY_KIND COMMUNICATIONREQUEST =
      CARE_PLAN_ACTIVITY_KIND.COMMUNICATIONREQUEST$.MODULE$;
  public static final CARE_PLAN_ACTIVITY_KIND DEVICEREQUEST =
      CARE_PLAN_ACTIVITY_KIND.DEVICEREQUEST$.MODULE$;
  public static final CARE_PLAN_ACTIVITY_KIND MEDICATIONREQUEST =
      CARE_PLAN_ACTIVITY_KIND.MEDICATIONREQUEST$.MODULE$;
  public static final CARE_PLAN_ACTIVITY_KIND NUTRITIONORDER =
      CARE_PLAN_ACTIVITY_KIND.NUTRITIONORDER$.MODULE$;
  public static final CARE_PLAN_ACTIVITY_KIND SERVICEREQUEST =
      CARE_PLAN_ACTIVITY_KIND.SERVICEREQUEST$.MODULE$;
  public static final CARE_PLAN_ACTIVITY_KIND TASK = CARE_PLAN_ACTIVITY_KIND.TASK$.MODULE$;
  public static final CARE_PLAN_ACTIVITY_KIND VISIONPRESCRIPTION =
      CARE_PLAN_ACTIVITY_KIND.VISIONPRESCRIPTION$.MODULE$;
}
