package com.babylonhealth.lit.hl7_java.codes;

import com.babylonhealth.lit.hl7.CARE_PLAN_ACTIVITY_STATUS;

public interface CarePlanActivityStatus {
  public static final CARE_PLAN_ACTIVITY_STATUS CANCELLED =
      CARE_PLAN_ACTIVITY_STATUS.CANCELLED$.MODULE$;
  public static final CARE_PLAN_ACTIVITY_STATUS COMPLETED =
      CARE_PLAN_ACTIVITY_STATUS.COMPLETED$.MODULE$;
  public static final CARE_PLAN_ACTIVITY_STATUS ENTERED_IN_ERROR =
      CARE_PLAN_ACTIVITY_STATUS.ENTERED_IN_ERROR$.MODULE$;
  public static final CARE_PLAN_ACTIVITY_STATUS IN_PROGRESS =
      CARE_PLAN_ACTIVITY_STATUS.IN_PROGRESS$.MODULE$;
  public static final CARE_PLAN_ACTIVITY_STATUS NOT_STARTED =
      CARE_PLAN_ACTIVITY_STATUS.NOT_STARTED$.MODULE$;
  public static final CARE_PLAN_ACTIVITY_STATUS ON_HOLD =
      CARE_PLAN_ACTIVITY_STATUS.ON_HOLD$.MODULE$;
  public static final CARE_PLAN_ACTIVITY_STATUS SCHEDULED =
      CARE_PLAN_ACTIVITY_STATUS.SCHEDULED$.MODULE$;
  public static final CARE_PLAN_ACTIVITY_STATUS STOPPED =
      CARE_PLAN_ACTIVITY_STATUS.STOPPED$.MODULE$;
  public static final CARE_PLAN_ACTIVITY_STATUS UNKNOWN =
      CARE_PLAN_ACTIVITY_STATUS.UNKNOWN$.MODULE$;
}
