package com.babylonhealth.lit.hl7_java.codes;

import com.babylonhealth.lit.hl7.CHARGEITEM_STATUS;

public interface ChargeitemStatus {
  public static final CHARGEITEM_STATUS ABORTED = CHARGEITEM_STATUS.ABORTED$.MODULE$;
  public static final CHARGEITEM_STATUS BILLABLE = CHARGEITEM_STATUS.BILLABLE$.MODULE$;
  public static final CHARGEITEM_STATUS BILLED = CHARGEITEM_STATUS.BILLED$.MODULE$;
  public static final CHARGEITEM_STATUS ENTERED_IN_ERROR =
      CHARGEITEM_STATUS.ENTERED_IN_ERROR$.MODULE$;
  public static final CHARGEITEM_STATUS NOT_BILLABLE = CHARGEITEM_STATUS.NOT_BILLABLE$.MODULE$;
  public static final CHARGEITEM_STATUS PLANNED = CHARGEITEM_STATUS.PLANNED$.MODULE$;
  public static final CHARGEITEM_STATUS UNKNOWN = CHARGEITEM_STATUS.UNKNOWN$.MODULE$;
}
