package com.babylonhealth.lit.hl7_java.codes;

import com.babylonhealth.lit.hl7.CLINICALIMPRESSION_STATUS;

public interface ClinicalimpressionStatus {
  public static final CLINICALIMPRESSION_STATUS COMPLETED =
      CLINICALIMPRESSION_STATUS.COMPLETED$.MODULE$;
  public static final CLINICALIMPRESSION_STATUS ENTERED_IN_ERROR =
      CLINICALIMPRESSION_STATUS.ENTERED_IN_ERROR$.MODULE$;
  public static final CLINICALIMPRESSION_STATUS IN_PROGRESS =
      CLINICALIMPRESSION_STATUS.IN_PROGRESS$.MODULE$;
}
