package com.babylonhealth.lit.hl7_java.codes;

import com.babylonhealth.lit.hl7.CODESYSTEM_HIERARCHY_MEANING;

public interface CodesystemHierarchyMeaning {
  public static final CODESYSTEM_HIERARCHY_MEANING CLASSIFIED_WITH =
      CODESYSTEM_HIERARCHY_MEANING.CLASSIFIED_WITH$.MODULE$;
  public static final CODESYSTEM_HIERARCHY_MEANING GROUPED_BY =
      CODESYSTEM_HIERARCHY_MEANING.GROUPED_BY$.MODULE$;
  public static final CODESYSTEM_HIERARCHY_MEANING IS_A =
      CODESYSTEM_HIERARCHY_MEANING.IS_A$.MODULE$;
  public static final CODESYSTEM_HIERARCHY_MEANING PART_OF =
      CODESYSTEM_HIERARCHY_MEANING.PART_OF$.MODULE$;
}
