package com.babylonhealth.lit.hl7_java.codes;

import com.babylonhealth.lit.hl7.COMPOSITION_ATTESTATION_MODE;

public interface CompositionAttestationMode {
  public static final COMPOSITION_ATTESTATION_MODE LEGAL =
      COMPOSITION_ATTESTATION_MODE.LEGAL$.MODULE$;
  public static final COMPOSITION_ATTESTATION_MODE OFFICIAL =
      COMPOSITION_ATTESTATION_MODE.OFFICIAL$.MODULE$;
  public static final COMPOSITION_ATTESTATION_MODE PERSONAL =
      COMPOSITION_ATTESTATION_MODE.PERSONAL$.MODULE$;
  public static final COMPOSITION_ATTESTATION_MODE PROFESSIONAL =
      COMPOSITION_ATTESTATION_MODE.PROFESSIONAL$.MODULE$;
}
