package com.babylonhealth.lit.hl7_java.codes;

import com.babylonhealth.lit.hl7.CONCEPT_PROPERTY_TYPE;

public interface ConceptPropertyType {
  public static final CONCEPT_PROPERTY_TYPE BOOLEAN = CONCEPT_PROPERTY_TYPE.BOOLEAN$.MODULE$;
  public static final CONCEPT_PROPERTY_TYPE CODE = CONCEPT_PROPERTY_TYPE.CODE$.MODULE$;
  public static final CONCEPT_PROPERTY_TYPE CODING = CONCEPT_PROPERTY_TYPE.CODING$.MODULE$;
  public static final CONCEPT_PROPERTY_TYPE DATETIME = CONCEPT_PROPERTY_TYPE.DATETIME$.MODULE$;
  public static final CONCEPT_PROPERTY_TYPE DECIMAL = CONCEPT_PROPERTY_TYPE.DECIMAL$.MODULE$;
  public static final CONCEPT_PROPERTY_TYPE INTEGER = CONCEPT_PROPERTY_TYPE.INTEGER$.MODULE$;
  public static final CONCEPT_PROPERTY_TYPE STRING = CONCEPT_PROPERTY_TYPE.STRING$.MODULE$;
}
