package com.babylonhealth.lit.hl7_java.codes;

import com.babylonhealth.lit.hl7.CONTRACT_STATUS;

public interface ContractStatus {
  public static final CONTRACT_STATUS AMENDED = CONTRACT_STATUS.AMENDED$.MODULE$;
  public static final CONTRACT_STATUS APPENDED = CONTRACT_STATUS.APPENDED$.MODULE$;
  public static final CONTRACT_STATUS CANCELLED = CONTRACT_STATUS.CANCELLED$.MODULE$;
  public static final CONTRACT_STATUS DISPUTED = CONTRACT_STATUS.DISPUTED$.MODULE$;
  public static final CONTRACT_STATUS ENTERED_IN_ERROR = CONTRACT_STATUS.ENTERED_IN_ERROR$.MODULE$;
  public static final CONTRACT_STATUS EXECUTABLE = CONTRACT_STATUS.EXECUTABLE$.MODULE$;
  public static final CONTRACT_STATUS EXECUTED = CONTRACT_STATUS.EXECUTED$.MODULE$;
  public static final CONTRACT_STATUS NEGOTIABLE = CONTRACT_STATUS.NEGOTIABLE$.MODULE$;
  public static final CONTRACT_STATUS OFFERED = CONTRACT_STATUS.OFFERED$.MODULE$;
  public static final CONTRACT_STATUS POLICY = CONTRACT_STATUS.POLICY$.MODULE$;
  public static final CONTRACT_STATUS REJECTED = CONTRACT_STATUS.REJECTED$.MODULE$;
  public static final CONTRACT_STATUS RENEWED = CONTRACT_STATUS.RENEWED$.MODULE$;
  public static final CONTRACT_STATUS RESOLVED = CONTRACT_STATUS.RESOLVED$.MODULE$;
  public static final CONTRACT_STATUS REVOKED = CONTRACT_STATUS.REVOKED$.MODULE$;
  public static final CONTRACT_STATUS TERMINATED = CONTRACT_STATUS.TERMINATED$.MODULE$;
}
