package com.babylonhealth.lit.hl7_java.codes;

import com.babylonhealth.lit.hl7.CONTRACT_PUBLICATIONSTATUS;

public interface ContractPublicationstatus {
  public static final CONTRACT_PUBLICATIONSTATUS AMENDED =
      CONTRACT_PUBLICATIONSTATUS.AMENDED$.MODULE$;
  public static final CONTRACT_PUBLICATIONSTATUS APPENDED =
      CONTRACT_PUBLICATIONSTATUS.APPENDED$.MODULE$;
  public static final CONTRACT_PUBLICATIONSTATUS CANCELLED =
      CONTRACT_PUBLICATIONSTATUS.CANCELLED$.MODULE$;
  public static final CONTRACT_PUBLICATIONSTATUS DISPUTED =
      CONTRACT_PUBLICATIONSTATUS.DISPUTED$.MODULE$;
  public static final CONTRACT_PUBLICATIONSTATUS ENTERED_IN_ERROR =
      CONTRACT_PUBLICATIONSTATUS.ENTERED_IN_ERROR$.MODULE$;
  public static final CONTRACT_PUBLICATIONSTATUS EXECUTABLE =
      CONTRACT_PUBLICATIONSTATUS.EXECUTABLE$.MODULE$;
  public static final CONTRACT_PUBLICATIONSTATUS EXECUTED =
      CONTRACT_PUBLICATIONSTATUS.EXECUTED$.MODULE$;
  public static final CONTRACT_PUBLICATIONSTATUS NEGOTIABLE =
      CONTRACT_PUBLICATIONSTATUS.NEGOTIABLE$.MODULE$;
  public static final CONTRACT_PUBLICATIONSTATUS OFFERED =
      CONTRACT_PUBLICATIONSTATUS.OFFERED$.MODULE$;
  public static final CONTRACT_PUBLICATIONSTATUS POLICY =
      CONTRACT_PUBLICATIONSTATUS.POLICY$.MODULE$;
  public static final CONTRACT_PUBLICATIONSTATUS REJECTED =
      CONTRACT_PUBLICATIONSTATUS.REJECTED$.MODULE$;
  public static final CONTRACT_PUBLICATIONSTATUS RENEWED =
      CONTRACT_PUBLICATIONSTATUS.RENEWED$.MODULE$;
  public static final CONTRACT_PUBLICATIONSTATUS RESOLVED =
      CONTRACT_PUBLICATIONSTATUS.RESOLVED$.MODULE$;
  public static final CONTRACT_PUBLICATIONSTATUS REVOKED =
      CONTRACT_PUBLICATIONSTATUS.REVOKED$.MODULE$;
  public static final CONTRACT_PUBLICATIONSTATUS TERMINATED =
      CONTRACT_PUBLICATIONSTATUS.TERMINATED$.MODULE$;
}
