package com.babylonhealth.lit.hl7_java.codes;

import com.babylonhealth.lit.hl7.DEFINED_TYPES;

public interface DefinedTypes {
  public static final DEFINED_TYPES ACCOUNT = DEFINED_TYPES.ACCOUNT$.MODULE$;
  public static final DEFINED_TYPES ACTIVITYDEFINITION = DEFINED_TYPES.ACTIVITYDEFINITION$.MODULE$;
  public static final DEFINED_TYPES ADDRESS = DEFINED_TYPES.ADDRESS$.MODULE$;
  public static final DEFINED_TYPES ADVERSEEVENT = DEFINED_TYPES.ADVERSEEVENT$.MODULE$;
  public static final DEFINED_TYPES AGE = DEFINED_TYPES.AGE$.MODULE$;
  public static final DEFINED_TYPES ALLERGYINTOLERANCE = DEFINED_TYPES.ALLERGYINTOLERANCE$.MODULE$;
  public static final DEFINED_TYPES ANNOTATION = DEFINED_TYPES.ANNOTATION$.MODULE$;
  public static final DEFINED_TYPES APPOINTMENT = DEFINED_TYPES.APPOINTMENT$.MODULE$;
  public static final DEFINED_TYPES APPOINTMENTRESPONSE =
      DEFINED_TYPES.APPOINTMENTRESPONSE$.MODULE$;
  public static final DEFINED_TYPES ATTACHMENT = DEFINED_TYPES.ATTACHMENT$.MODULE$;
  public static final DEFINED_TYPES AUDITEVENT = DEFINED_TYPES.AUDITEVENT$.MODULE$;
  public static final DEFINED_TYPES BACKBONEELEMENT = DEFINED_TYPES.BACKBONEELEMENT$.MODULE$;
  public static final DEFINED_TYPES BASE64BINARY = DEFINED_TYPES.BASE64BINARY$.MODULE$;
  public static final DEFINED_TYPES BASIC = DEFINED_TYPES.BASIC$.MODULE$;
  public static final DEFINED_TYPES BINARY = DEFINED_TYPES.BINARY$.MODULE$;
  public static final DEFINED_TYPES BIOLOGICALLYDERIVEDPRODUCT =
      DEFINED_TYPES.BIOLOGICALLYDERIVEDPRODUCT$.MODULE$;
  public static final DEFINED_TYPES BODYSTRUCTURE = DEFINED_TYPES.BODYSTRUCTURE$.MODULE$;
  public static final DEFINED_TYPES BOOLEAN = DEFINED_TYPES.BOOLEAN$.MODULE$;
  public static final DEFINED_TYPES BUNDLE = DEFINED_TYPES.BUNDLE$.MODULE$;
  public static final DEFINED_TYPES CANONICAL = DEFINED_TYPES.CANONICAL$.MODULE$;
  public static final DEFINED_TYPES CAPABILITYSTATEMENT =
      DEFINED_TYPES.CAPABILITYSTATEMENT$.MODULE$;
  public static final DEFINED_TYPES CAREPLAN = DEFINED_TYPES.CAREPLAN$.MODULE$;
  public static final DEFINED_TYPES CARETEAM = DEFINED_TYPES.CARETEAM$.MODULE$;
  public static final DEFINED_TYPES CATALOGENTRY = DEFINED_TYPES.CATALOGENTRY$.MODULE$;
  public static final DEFINED_TYPES CHARGEITEM = DEFINED_TYPES.CHARGEITEM$.MODULE$;
  public static final DEFINED_TYPES CHARGEITEMDEFINITION =
      DEFINED_TYPES.CHARGEITEMDEFINITION$.MODULE$;
  public static final DEFINED_TYPES CLAIM = DEFINED_TYPES.CLAIM$.MODULE$;
  public static final DEFINED_TYPES CLAIMRESPONSE = DEFINED_TYPES.CLAIMRESPONSE$.MODULE$;
  public static final DEFINED_TYPES CLINICALIMPRESSION = DEFINED_TYPES.CLINICALIMPRESSION$.MODULE$;
  public static final DEFINED_TYPES CODE = DEFINED_TYPES.CODE$.MODULE$;
  public static final DEFINED_TYPES CODEABLECONCEPT = DEFINED_TYPES.CODEABLECONCEPT$.MODULE$;
  public static final DEFINED_TYPES CODESYSTEM = DEFINED_TYPES.CODESYSTEM$.MODULE$;
  public static final DEFINED_TYPES CODING = DEFINED_TYPES.CODING$.MODULE$;
  public static final DEFINED_TYPES COMMUNICATION = DEFINED_TYPES.COMMUNICATION$.MODULE$;
  public static final DEFINED_TYPES COMMUNICATIONREQUEST =
      DEFINED_TYPES.COMMUNICATIONREQUEST$.MODULE$;
  public static final DEFINED_TYPES COMPARTMENTDEFINITION =
      DEFINED_TYPES.COMPARTMENTDEFINITION$.MODULE$;
  public static final DEFINED_TYPES COMPOSITION = DEFINED_TYPES.COMPOSITION$.MODULE$;
  public static final DEFINED_TYPES CONCEPTMAP = DEFINED_TYPES.CONCEPTMAP$.MODULE$;
  public static final DEFINED_TYPES CONDITION = DEFINED_TYPES.CONDITION$.MODULE$;
  public static final DEFINED_TYPES CONSENT = DEFINED_TYPES.CONSENT$.MODULE$;
  public static final DEFINED_TYPES CONTACTDETAIL = DEFINED_TYPES.CONTACTDETAIL$.MODULE$;
  public static final DEFINED_TYPES CONTACTPOINT = DEFINED_TYPES.CONTACTPOINT$.MODULE$;
  public static final DEFINED_TYPES CONTRACT = DEFINED_TYPES.CONTRACT$.MODULE$;
  public static final DEFINED_TYPES CONTRIBUTOR = DEFINED_TYPES.CONTRIBUTOR$.MODULE$;
  public static final DEFINED_TYPES COUNT = DEFINED_TYPES.COUNT$.MODULE$;
  public static final DEFINED_TYPES COVERAGE = DEFINED_TYPES.COVERAGE$.MODULE$;
  public static final DEFINED_TYPES COVERAGEELIGIBILITYREQUEST =
      DEFINED_TYPES.COVERAGEELIGIBILITYREQUEST$.MODULE$;
  public static final DEFINED_TYPES COVERAGEELIGIBILITYRESPONSE =
      DEFINED_TYPES.COVERAGEELIGIBILITYRESPONSE$.MODULE$;
  public static final DEFINED_TYPES DATAREQUIREMENT = DEFINED_TYPES.DATAREQUIREMENT$.MODULE$;
  public static final DEFINED_TYPES DATE = DEFINED_TYPES.DATE$.MODULE$;
  public static final DEFINED_TYPES DATETIME = DEFINED_TYPES.DATETIME$.MODULE$;
  public static final DEFINED_TYPES DECIMAL = DEFINED_TYPES.DECIMAL$.MODULE$;
  public static final DEFINED_TYPES DETECTEDISSUE = DEFINED_TYPES.DETECTEDISSUE$.MODULE$;
  public static final DEFINED_TYPES DEVICE = DEFINED_TYPES.DEVICE$.MODULE$;
  public static final DEFINED_TYPES DEVICEDEFINITION = DEFINED_TYPES.DEVICEDEFINITION$.MODULE$;
  public static final DEFINED_TYPES DEVICEMETRIC = DEFINED_TYPES.DEVICEMETRIC$.MODULE$;
  public static final DEFINED_TYPES DEVICEREQUEST = DEFINED_TYPES.DEVICEREQUEST$.MODULE$;
  public static final DEFINED_TYPES DEVICEUSESTATEMENT = DEFINED_TYPES.DEVICEUSESTATEMENT$.MODULE$;
  public static final DEFINED_TYPES DIAGNOSTICREPORT = DEFINED_TYPES.DIAGNOSTICREPORT$.MODULE$;
  public static final DEFINED_TYPES DISTANCE = DEFINED_TYPES.DISTANCE$.MODULE$;
  public static final DEFINED_TYPES DOCUMENTMANIFEST = DEFINED_TYPES.DOCUMENTMANIFEST$.MODULE$;
  public static final DEFINED_TYPES DOCUMENTREFERENCE = DEFINED_TYPES.DOCUMENTREFERENCE$.MODULE$;
  public static final DEFINED_TYPES DOMAINRESOURCE = DEFINED_TYPES.DOMAINRESOURCE$.MODULE$;
  public static final DEFINED_TYPES DOSAGE = DEFINED_TYPES.DOSAGE$.MODULE$;
  public static final DEFINED_TYPES DURATION = DEFINED_TYPES.DURATION$.MODULE$;
  public static final DEFINED_TYPES EFFECTEVIDENCESYNTHESIS =
      DEFINED_TYPES.EFFECTEVIDENCESYNTHESIS$.MODULE$;
  public static final DEFINED_TYPES ELEMENT = DEFINED_TYPES.ELEMENT$.MODULE$;
  public static final DEFINED_TYPES ELEMENTDEFINITION = DEFINED_TYPES.ELEMENTDEFINITION$.MODULE$;
  public static final DEFINED_TYPES ENCOUNTER = DEFINED_TYPES.ENCOUNTER$.MODULE$;
  public static final DEFINED_TYPES ENDPOINT = DEFINED_TYPES.ENDPOINT$.MODULE$;
  public static final DEFINED_TYPES ENROLLMENTREQUEST = DEFINED_TYPES.ENROLLMENTREQUEST$.MODULE$;
  public static final DEFINED_TYPES ENROLLMENTRESPONSE = DEFINED_TYPES.ENROLLMENTRESPONSE$.MODULE$;
  public static final DEFINED_TYPES EPISODEOFCARE = DEFINED_TYPES.EPISODEOFCARE$.MODULE$;
  public static final DEFINED_TYPES EVENTDEFINITION = DEFINED_TYPES.EVENTDEFINITION$.MODULE$;
  public static final DEFINED_TYPES EVIDENCE = DEFINED_TYPES.EVIDENCE$.MODULE$;
  public static final DEFINED_TYPES EVIDENCEVARIABLE = DEFINED_TYPES.EVIDENCEVARIABLE$.MODULE$;
  public static final DEFINED_TYPES EXAMPLESCENARIO = DEFINED_TYPES.EXAMPLESCENARIO$.MODULE$;
  public static final DEFINED_TYPES EXPLANATIONOFBENEFIT =
      DEFINED_TYPES.EXPLANATIONOFBENEFIT$.MODULE$;
  public static final DEFINED_TYPES EXPRESSION = DEFINED_TYPES.EXPRESSION$.MODULE$;
  public static final DEFINED_TYPES EXTENSION = DEFINED_TYPES.EXTENSION$.MODULE$;
  public static final DEFINED_TYPES FAMILYMEMBERHISTORY =
      DEFINED_TYPES.FAMILYMEMBERHISTORY$.MODULE$;
  public static final DEFINED_TYPES FLAG = DEFINED_TYPES.FLAG$.MODULE$;
  public static final DEFINED_TYPES GOAL = DEFINED_TYPES.GOAL$.MODULE$;
  public static final DEFINED_TYPES GRAPHDEFINITION = DEFINED_TYPES.GRAPHDEFINITION$.MODULE$;
  public static final DEFINED_TYPES GROUP = DEFINED_TYPES.GROUP$.MODULE$;
  public static final DEFINED_TYPES GUIDANCERESPONSE = DEFINED_TYPES.GUIDANCERESPONSE$.MODULE$;
  public static final DEFINED_TYPES HEALTHCARESERVICE = DEFINED_TYPES.HEALTHCARESERVICE$.MODULE$;
  public static final DEFINED_TYPES HUMANNAME = DEFINED_TYPES.HUMANNAME$.MODULE$;
  public static final DEFINED_TYPES ID = DEFINED_TYPES.ID$.MODULE$;
  public static final DEFINED_TYPES IDENTIFIER = DEFINED_TYPES.IDENTIFIER$.MODULE$;
  public static final DEFINED_TYPES IMAGINGSTUDY = DEFINED_TYPES.IMAGINGSTUDY$.MODULE$;
  public static final DEFINED_TYPES IMMUNIZATION = DEFINED_TYPES.IMMUNIZATION$.MODULE$;
  public static final DEFINED_TYPES IMMUNIZATIONEVALUATION =
      DEFINED_TYPES.IMMUNIZATIONEVALUATION$.MODULE$;
  public static final DEFINED_TYPES IMMUNIZATIONRECOMMENDATION =
      DEFINED_TYPES.IMMUNIZATIONRECOMMENDATION$.MODULE$;
  public static final DEFINED_TYPES IMPLEMENTATIONGUIDE =
      DEFINED_TYPES.IMPLEMENTATIONGUIDE$.MODULE$;
  public static final DEFINED_TYPES INSTANT = DEFINED_TYPES.INSTANT$.MODULE$;
  public static final DEFINED_TYPES INSURANCEPLAN = DEFINED_TYPES.INSURANCEPLAN$.MODULE$;
  public static final DEFINED_TYPES INTEGER = DEFINED_TYPES.INTEGER$.MODULE$;
  public static final DEFINED_TYPES INVOICE = DEFINED_TYPES.INVOICE$.MODULE$;
  public static final DEFINED_TYPES LIBRARY = DEFINED_TYPES.LIBRARY$.MODULE$;
  public static final DEFINED_TYPES LINKAGE = DEFINED_TYPES.LINKAGE$.MODULE$;
  public static final DEFINED_TYPES LIST = DEFINED_TYPES.LIST$.MODULE$;
  public static final DEFINED_TYPES LOCATION = DEFINED_TYPES.LOCATION$.MODULE$;
  public static final DEFINED_TYPES MARKDOWN = DEFINED_TYPES.MARKDOWN$.MODULE$;
  public static final DEFINED_TYPES MARKETINGSTATUS = DEFINED_TYPES.MARKETINGSTATUS$.MODULE$;
  public static final DEFINED_TYPES MEASURE = DEFINED_TYPES.MEASURE$.MODULE$;
  public static final DEFINED_TYPES MEASUREREPORT = DEFINED_TYPES.MEASUREREPORT$.MODULE$;
  public static final DEFINED_TYPES MEDIA = DEFINED_TYPES.MEDIA$.MODULE$;
  public static final DEFINED_TYPES MEDICATION = DEFINED_TYPES.MEDICATION$.MODULE$;
  public static final DEFINED_TYPES MEDICATIONADMINISTRATION =
      DEFINED_TYPES.MEDICATIONADMINISTRATION$.MODULE$;
  public static final DEFINED_TYPES MEDICATIONDISPENSE = DEFINED_TYPES.MEDICATIONDISPENSE$.MODULE$;
  public static final DEFINED_TYPES MEDICATIONKNOWLEDGE =
      DEFINED_TYPES.MEDICATIONKNOWLEDGE$.MODULE$;
  public static final DEFINED_TYPES MEDICATIONREQUEST = DEFINED_TYPES.MEDICATIONREQUEST$.MODULE$;
  public static final DEFINED_TYPES MEDICATIONSTATEMENT =
      DEFINED_TYPES.MEDICATIONSTATEMENT$.MODULE$;
  public static final DEFINED_TYPES MEDICINALPRODUCT = DEFINED_TYPES.MEDICINALPRODUCT$.MODULE$;
  public static final DEFINED_TYPES MEDICINALPRODUCTAUTHORIZATION =
      DEFINED_TYPES.MEDICINALPRODUCTAUTHORIZATION$.MODULE$;
  public static final DEFINED_TYPES MEDICINALPRODUCTCONTRAINDICATION =
      DEFINED_TYPES.MEDICINALPRODUCTCONTRAINDICATION$.MODULE$;
  public static final DEFINED_TYPES MEDICINALPRODUCTINDICATION =
      DEFINED_TYPES.MEDICINALPRODUCTINDICATION$.MODULE$;
  public static final DEFINED_TYPES MEDICINALPRODUCTINGREDIENT =
      DEFINED_TYPES.MEDICINALPRODUCTINGREDIENT$.MODULE$;
  public static final DEFINED_TYPES MEDICINALPRODUCTINTERACTION =
      DEFINED_TYPES.MEDICINALPRODUCTINTERACTION$.MODULE$;
  public static final DEFINED_TYPES MEDICINALPRODUCTMANUFACTURED =
      DEFINED_TYPES.MEDICINALPRODUCTMANUFACTURED$.MODULE$;
  public static final DEFINED_TYPES MEDICINALPRODUCTPACKAGED =
      DEFINED_TYPES.MEDICINALPRODUCTPACKAGED$.MODULE$;
  public static final DEFINED_TYPES MEDICINALPRODUCTPHARMACEUTICAL =
      DEFINED_TYPES.MEDICINALPRODUCTPHARMACEUTICAL$.MODULE$;
  public static final DEFINED_TYPES MEDICINALPRODUCTUNDESIRABLEEFFECT =
      DEFINED_TYPES.MEDICINALPRODUCTUNDESIRABLEEFFECT$.MODULE$;
  public static final DEFINED_TYPES MESSAGEDEFINITION = DEFINED_TYPES.MESSAGEDEFINITION$.MODULE$;
  public static final DEFINED_TYPES MESSAGEHEADER = DEFINED_TYPES.MESSAGEHEADER$.MODULE$;
  public static final DEFINED_TYPES META = DEFINED_TYPES.META$.MODULE$;
  public static final DEFINED_TYPES MOLECULARSEQUENCE = DEFINED_TYPES.MOLECULARSEQUENCE$.MODULE$;
  public static final DEFINED_TYPES MONEY = DEFINED_TYPES.MONEY$.MODULE$;
  public static final DEFINED_TYPES MONEYQUANTITY = DEFINED_TYPES.MONEYQUANTITY$.MODULE$;
  public static final DEFINED_TYPES NAMINGSYSTEM = DEFINED_TYPES.NAMINGSYSTEM$.MODULE$;
  public static final DEFINED_TYPES NARRATIVE = DEFINED_TYPES.NARRATIVE$.MODULE$;
  public static final DEFINED_TYPES NUTRITIONORDER = DEFINED_TYPES.NUTRITIONORDER$.MODULE$;
  public static final DEFINED_TYPES OBSERVATION = DEFINED_TYPES.OBSERVATION$.MODULE$;
  public static final DEFINED_TYPES OBSERVATIONDEFINITION =
      DEFINED_TYPES.OBSERVATIONDEFINITION$.MODULE$;
  public static final DEFINED_TYPES OID = DEFINED_TYPES.OID$.MODULE$;
  public static final DEFINED_TYPES OPERATIONDEFINITION =
      DEFINED_TYPES.OPERATIONDEFINITION$.MODULE$;
  public static final DEFINED_TYPES OPERATIONOUTCOME = DEFINED_TYPES.OPERATIONOUTCOME$.MODULE$;
  public static final DEFINED_TYPES ORGANIZATION = DEFINED_TYPES.ORGANIZATION$.MODULE$;
  public static final DEFINED_TYPES ORGANIZATIONAFFILIATION =
      DEFINED_TYPES.ORGANIZATIONAFFILIATION$.MODULE$;
  public static final DEFINED_TYPES PARAMETERDEFINITION =
      DEFINED_TYPES.PARAMETERDEFINITION$.MODULE$;
  public static final DEFINED_TYPES PARAMETERS = DEFINED_TYPES.PARAMETERS$.MODULE$;
  public static final DEFINED_TYPES PATIENT = DEFINED_TYPES.PATIENT$.MODULE$;
  public static final DEFINED_TYPES PAYMENTNOTICE = DEFINED_TYPES.PAYMENTNOTICE$.MODULE$;
  public static final DEFINED_TYPES PAYMENTRECONCILIATION =
      DEFINED_TYPES.PAYMENTRECONCILIATION$.MODULE$;
  public static final DEFINED_TYPES PERIOD = DEFINED_TYPES.PERIOD$.MODULE$;
  public static final DEFINED_TYPES PERSON = DEFINED_TYPES.PERSON$.MODULE$;
  public static final DEFINED_TYPES PLANDEFINITION = DEFINED_TYPES.PLANDEFINITION$.MODULE$;
  public static final DEFINED_TYPES POPULATION = DEFINED_TYPES.POPULATION$.MODULE$;
  public static final DEFINED_TYPES POSITIVEINT = DEFINED_TYPES.POSITIVEINT$.MODULE$;
  public static final DEFINED_TYPES PRACTITIONER = DEFINED_TYPES.PRACTITIONER$.MODULE$;
  public static final DEFINED_TYPES PRACTITIONERROLE = DEFINED_TYPES.PRACTITIONERROLE$.MODULE$;
  public static final DEFINED_TYPES PROCEDURE = DEFINED_TYPES.PROCEDURE$.MODULE$;
  public static final DEFINED_TYPES PRODCHARACTERISTIC = DEFINED_TYPES.PRODCHARACTERISTIC$.MODULE$;
  public static final DEFINED_TYPES PRODUCTSHELFLIFE = DEFINED_TYPES.PRODUCTSHELFLIFE$.MODULE$;
  public static final DEFINED_TYPES PROVENANCE = DEFINED_TYPES.PROVENANCE$.MODULE$;
  public static final DEFINED_TYPES QUANTITY = DEFINED_TYPES.QUANTITY$.MODULE$;
  public static final DEFINED_TYPES QUESTIONNAIRE = DEFINED_TYPES.QUESTIONNAIRE$.MODULE$;
  public static final DEFINED_TYPES QUESTIONNAIRERESPONSE =
      DEFINED_TYPES.QUESTIONNAIRERESPONSE$.MODULE$;
  public static final DEFINED_TYPES RANGE = DEFINED_TYPES.RANGE$.MODULE$;
  public static final DEFINED_TYPES RATIO = DEFINED_TYPES.RATIO$.MODULE$;
  public static final DEFINED_TYPES REFERENCE = DEFINED_TYPES.REFERENCE$.MODULE$;
  public static final DEFINED_TYPES RELATEDARTIFACT = DEFINED_TYPES.RELATEDARTIFACT$.MODULE$;
  public static final DEFINED_TYPES RELATEDPERSON = DEFINED_TYPES.RELATEDPERSON$.MODULE$;
  public static final DEFINED_TYPES REQUESTGROUP = DEFINED_TYPES.REQUESTGROUP$.MODULE$;
  public static final DEFINED_TYPES RESEARCHDEFINITION = DEFINED_TYPES.RESEARCHDEFINITION$.MODULE$;
  public static final DEFINED_TYPES RESEARCHELEMENTDEFINITION =
      DEFINED_TYPES.RESEARCHELEMENTDEFINITION$.MODULE$;
  public static final DEFINED_TYPES RESEARCHSTUDY = DEFINED_TYPES.RESEARCHSTUDY$.MODULE$;
  public static final DEFINED_TYPES RESEARCHSUBJECT = DEFINED_TYPES.RESEARCHSUBJECT$.MODULE$;
  public static final DEFINED_TYPES RESOURCE = DEFINED_TYPES.RESOURCE$.MODULE$;
  public static final DEFINED_TYPES RISKASSESSMENT = DEFINED_TYPES.RISKASSESSMENT$.MODULE$;
  public static final DEFINED_TYPES RISKEVIDENCESYNTHESIS =
      DEFINED_TYPES.RISKEVIDENCESYNTHESIS$.MODULE$;
  public static final DEFINED_TYPES SAMPLEDDATA = DEFINED_TYPES.SAMPLEDDATA$.MODULE$;
  public static final DEFINED_TYPES SCHEDULE = DEFINED_TYPES.SCHEDULE$.MODULE$;
  public static final DEFINED_TYPES SEARCHPARAMETER = DEFINED_TYPES.SEARCHPARAMETER$.MODULE$;
  public static final DEFINED_TYPES SERVICEREQUEST = DEFINED_TYPES.SERVICEREQUEST$.MODULE$;
  public static final DEFINED_TYPES SIGNATURE = DEFINED_TYPES.SIGNATURE$.MODULE$;
  public static final DEFINED_TYPES SIMPLEQUANTITY = DEFINED_TYPES.SIMPLEQUANTITY$.MODULE$;
  public static final DEFINED_TYPES SLOT = DEFINED_TYPES.SLOT$.MODULE$;
  public static final DEFINED_TYPES SPECIMEN = DEFINED_TYPES.SPECIMEN$.MODULE$;
  public static final DEFINED_TYPES SPECIMENDEFINITION = DEFINED_TYPES.SPECIMENDEFINITION$.MODULE$;
  public static final DEFINED_TYPES STRING = DEFINED_TYPES.STRING$.MODULE$;
  public static final DEFINED_TYPES STRUCTUREDEFINITION =
      DEFINED_TYPES.STRUCTUREDEFINITION$.MODULE$;
  public static final DEFINED_TYPES STRUCTUREMAP = DEFINED_TYPES.STRUCTUREMAP$.MODULE$;
  public static final DEFINED_TYPES SUBSCRIPTION = DEFINED_TYPES.SUBSCRIPTION$.MODULE$;
  public static final DEFINED_TYPES SUBSTANCE = DEFINED_TYPES.SUBSTANCE$.MODULE$;
  public static final DEFINED_TYPES SUBSTANCEAMOUNT = DEFINED_TYPES.SUBSTANCEAMOUNT$.MODULE$;
  public static final DEFINED_TYPES SUBSTANCENUCLEICACID =
      DEFINED_TYPES.SUBSTANCENUCLEICACID$.MODULE$;
  public static final DEFINED_TYPES SUBSTANCEPOLYMER = DEFINED_TYPES.SUBSTANCEPOLYMER$.MODULE$;
  public static final DEFINED_TYPES SUBSTANCEPROTEIN = DEFINED_TYPES.SUBSTANCEPROTEIN$.MODULE$;
  public static final DEFINED_TYPES SUBSTANCEREFERENCEINFORMATION =
      DEFINED_TYPES.SUBSTANCEREFERENCEINFORMATION$.MODULE$;
  public static final DEFINED_TYPES SUBSTANCESOURCEMATERIAL =
      DEFINED_TYPES.SUBSTANCESOURCEMATERIAL$.MODULE$;
  public static final DEFINED_TYPES SUBSTANCESPECIFICATION =
      DEFINED_TYPES.SUBSTANCESPECIFICATION$.MODULE$;
  public static final DEFINED_TYPES SUPPLYDELIVERY = DEFINED_TYPES.SUPPLYDELIVERY$.MODULE$;
  public static final DEFINED_TYPES SUPPLYREQUEST = DEFINED_TYPES.SUPPLYREQUEST$.MODULE$;
  public static final DEFINED_TYPES TASK = DEFINED_TYPES.TASK$.MODULE$;
  public static final DEFINED_TYPES TERMINOLOGYCAPABILITIES =
      DEFINED_TYPES.TERMINOLOGYCAPABILITIES$.MODULE$;
  public static final DEFINED_TYPES TESTREPORT = DEFINED_TYPES.TESTREPORT$.MODULE$;
  public static final DEFINED_TYPES TESTSCRIPT = DEFINED_TYPES.TESTSCRIPT$.MODULE$;
  public static final DEFINED_TYPES TIME = DEFINED_TYPES.TIME$.MODULE$;
  public static final DEFINED_TYPES TIMING = DEFINED_TYPES.TIMING$.MODULE$;
  public static final DEFINED_TYPES TRIGGERDEFINITION = DEFINED_TYPES.TRIGGERDEFINITION$.MODULE$;
  public static final DEFINED_TYPES UNSIGNEDINT = DEFINED_TYPES.UNSIGNEDINT$.MODULE$;
  public static final DEFINED_TYPES URI = DEFINED_TYPES.URI$.MODULE$;
  public static final DEFINED_TYPES URL = DEFINED_TYPES.URL$.MODULE$;
  public static final DEFINED_TYPES USAGECONTEXT = DEFINED_TYPES.USAGECONTEXT$.MODULE$;
  public static final DEFINED_TYPES UUID = DEFINED_TYPES.UUID$.MODULE$;
  public static final DEFINED_TYPES VALUESET = DEFINED_TYPES.VALUESET$.MODULE$;
  public static final DEFINED_TYPES VERIFICATIONRESULT = DEFINED_TYPES.VERIFICATIONRESULT$.MODULE$;
  public static final DEFINED_TYPES VISIONPRESCRIPTION = DEFINED_TYPES.VISIONPRESCRIPTION$.MODULE$;
  public static final DEFINED_TYPES XHTML = DEFINED_TYPES.XHTML$.MODULE$;
}
