package com.babylonhealth.lit.hl7_java.codes;

import com.babylonhealth.lit.hl7.DIAGNOSTIC_REPORT_STATUS;

public interface DiagnosticReportStatus {
  public static final DIAGNOSTIC_REPORT_STATUS AMENDED = DIAGNOSTIC_REPORT_STATUS.AMENDED$.MODULE$;
  public static final DIAGNOSTIC_REPORT_STATUS APPENDED =
      DIAGNOSTIC_REPORT_STATUS.APPENDED$.MODULE$;
  public static final DIAGNOSTIC_REPORT_STATUS CANCELLED =
      DIAGNOSTIC_REPORT_STATUS.CANCELLED$.MODULE$;
  public static final DIAGNOSTIC_REPORT_STATUS CORRECTED =
      DIAGNOSTIC_REPORT_STATUS.CORRECTED$.MODULE$;
  public static final DIAGNOSTIC_REPORT_STATUS ENTERED_IN_ERROR =
      DIAGNOSTIC_REPORT_STATUS.ENTERED_IN_ERROR$.MODULE$;
  public static final DIAGNOSTIC_REPORT_STATUS FINAL = DIAGNOSTIC_REPORT_STATUS.FINAL$.MODULE$;
  public static final DIAGNOSTIC_REPORT_STATUS PARTIAL = DIAGNOSTIC_REPORT_STATUS.PARTIAL$.MODULE$;
  public static final DIAGNOSTIC_REPORT_STATUS PRELIMINARY =
      DIAGNOSTIC_REPORT_STATUS.PRELIMINARY$.MODULE$;
  public static final DIAGNOSTIC_REPORT_STATUS REGISTERED =
      DIAGNOSTIC_REPORT_STATUS.REGISTERED$.MODULE$;
  public static final DIAGNOSTIC_REPORT_STATUS UNKNOWN = DIAGNOSTIC_REPORT_STATUS.UNKNOWN$.MODULE$;
}
