package com.babylonhealth.lit.hl7_java.codes;

import com.babylonhealth.lit.hl7.ELIGIBILITYRESPONSE_PURPOSE;

public interface EligibilityresponsePurpose {
  public static final ELIGIBILITYRESPONSE_PURPOSE BENEFITS =
      ELIGIBILITYRESPONSE_PURPOSE.BENEFITS$.MODULE$;
  public static final ELIGIBILITYRESPONSE_PURPOSE COVERAGE_AUTH_REQUIREMENTS =
      ELIGIBILITYRESPONSE_PURPOSE.COVERAGE_AUTH_REQUIREMENTS$.MODULE$;
  public static final ELIGIBILITYRESPONSE_PURPOSE DISCOVERY =
      ELIGIBILITYRESPONSE_PURPOSE.DISCOVERY$.MODULE$;
  public static final ELIGIBILITYRESPONSE_PURPOSE VALIDATION =
      ELIGIBILITYRESPONSE_PURPOSE.VALIDATION$.MODULE$;
}
