package com.babylonhealth.lit.hl7_java.codes;

import com.babylonhealth.lit.hl7.ELIGIBILITYREQUEST_PURPOSE;

public interface EligibilityrequestPurpose {
  public static final ELIGIBILITYREQUEST_PURPOSE BENEFITS =
      ELIGIBILITYREQUEST_PURPOSE.BENEFITS$.MODULE$;
  public static final ELIGIBILITYREQUEST_PURPOSE COVERAGE_AUTH_REQUIREMENTS =
      ELIGIBILITYREQUEST_PURPOSE.COVERAGE_AUTH_REQUIREMENTS$.MODULE$;
  public static final ELIGIBILITYREQUEST_PURPOSE DISCOVERY =
      ELIGIBILITYREQUEST_PURPOSE.DISCOVERY$.MODULE$;
  public static final ELIGIBILITYREQUEST_PURPOSE VALIDATION =
      ELIGIBILITYREQUEST_PURPOSE.VALIDATION$.MODULE$;
}
