package com.babylonhealth.lit.hl7_java.codes;

import com.babylonhealth.lit.hl7.EPISODE_OF_CARE_STATUS;

public interface EpisodeOfCareStatus {
  public static final EPISODE_OF_CARE_STATUS ACTIVE = EPISODE_OF_CARE_STATUS.ACTIVE$.MODULE$;
  public static final EPISODE_OF_CARE_STATUS CANCELLED = EPISODE_OF_CARE_STATUS.CANCELLED$.MODULE$;
  public static final EPISODE_OF_CARE_STATUS ENTERED_IN_ERROR =
      EPISODE_OF_CARE_STATUS.ENTERED_IN_ERROR$.MODULE$;
  public static final EPISODE_OF_CARE_STATUS FINISHED = EPISODE_OF_CARE_STATUS.FINISHED$.MODULE$;
  public static final EPISODE_OF_CARE_STATUS ONHOLD = EPISODE_OF_CARE_STATUS.ONHOLD$.MODULE$;
  public static final EPISODE_OF_CARE_STATUS PLANNED = EPISODE_OF_CARE_STATUS.PLANNED$.MODULE$;
  public static final EPISODE_OF_CARE_STATUS WAITLIST = EPISODE_OF_CARE_STATUS.WAITLIST$.MODULE$;
}
