package com.babylonhealth.lit.hl7_java.codes;

import com.babylonhealth.lit.hl7.EXPLANATIONOFBENEFIT_STATUS;

public interface ExplanationofbenefitStatus {
  public static final EXPLANATIONOFBENEFIT_STATUS ACTIVE =
      EXPLANATIONOFBENEFIT_STATUS.ACTIVE$.MODULE$;
  public static final EXPLANATIONOFBENEFIT_STATUS CANCELLED =
      EXPLANATIONOFBENEFIT_STATUS.CANCELLED$.MODULE$;
  public static final EXPLANATIONOFBENEFIT_STATUS DRAFT =
      EXPLANATIONOFBENEFIT_STATUS.DRAFT$.MODULE$;
  public static final EXPLANATIONOFBENEFIT_STATUS ENTERED_IN_ERROR =
      EXPLANATIONOFBENEFIT_STATUS.ENTERED_IN_ERROR$.MODULE$;
}
