package com.babylonhealth.lit.hl7_java.codes;

import com.babylonhealth.lit.hl7.GRAPH_COMPARTMENT_RULE;

public interface GraphCompartmentRule {
  public static final GRAPH_COMPARTMENT_RULE CUSTOM = GRAPH_COMPARTMENT_RULE.CUSTOM$.MODULE$;
  public static final GRAPH_COMPARTMENT_RULE DIFFERENT = GRAPH_COMPARTMENT_RULE.DIFFERENT$.MODULE$;
  public static final GRAPH_COMPARTMENT_RULE IDENTICAL = GRAPH_COMPARTMENT_RULE.IDENTICAL$.MODULE$;
  public static final GRAPH_COMPARTMENT_RULE MATCHING = GRAPH_COMPARTMENT_RULE.MATCHING$.MODULE$;
}
