package com.babylonhealth.lit.hl7_java.codes;

import com.babylonhealth.lit.hl7.GUIDANCE_RESPONSE_STATUS;

public interface GuidanceResponseStatus {
  public static final GUIDANCE_RESPONSE_STATUS DATA_REQUESTED =
      GUIDANCE_RESPONSE_STATUS.DATA_REQUESTED$.MODULE$;
  public static final GUIDANCE_RESPONSE_STATUS DATA_REQUIRED =
      GUIDANCE_RESPONSE_STATUS.DATA_REQUIRED$.MODULE$;
  public static final GUIDANCE_RESPONSE_STATUS ENTERED_IN_ERROR =
      GUIDANCE_RESPONSE_STATUS.ENTERED_IN_ERROR$.MODULE$;
  public static final GUIDANCE_RESPONSE_STATUS FAILURE = GUIDANCE_RESPONSE_STATUS.FAILURE$.MODULE$;
  public static final GUIDANCE_RESPONSE_STATUS IN_PROGRESS =
      GUIDANCE_RESPONSE_STATUS.IN_PROGRESS$.MODULE$;
  public static final GUIDANCE_RESPONSE_STATUS SUCCESS = GUIDANCE_RESPONSE_STATUS.SUCCESS$.MODULE$;
}
