package com.babylonhealth.lit.hl7_java.codes;

import com.babylonhealth.lit.hl7.GUIDE_PARAMETER_CODE;

public interface GuideParameterCode {
  public static final GUIDE_PARAMETER_CODE APPLY = GUIDE_PARAMETER_CODE.APPLY$.MODULE$;
  public static final GUIDE_PARAMETER_CODE BROKEN_LINKS_RULE =
      GUIDE_PARAMETER_CODE.BROKEN_LINKS_RULE$.MODULE$;
  public static final GUIDE_PARAMETER_CODE EXPANSION_PROFILE =
      GUIDE_PARAMETER_CODE.EXPANSION_PROFILE$.MODULE$;
  public static final GUIDE_PARAMETER_CODE GENERATE_JSON =
      GUIDE_PARAMETER_CODE.GENERATE_JSON$.MODULE$;
  public static final GUIDE_PARAMETER_CODE GENERATE_TURTLE =
      GUIDE_PARAMETER_CODE.GENERATE_TURTLE$.MODULE$;
  public static final GUIDE_PARAMETER_CODE GENERATE_XML =
      GUIDE_PARAMETER_CODE.GENERATE_XML$.MODULE$;
  public static final GUIDE_PARAMETER_CODE HTML_TEMPLATE =
      GUIDE_PARAMETER_CODE.HTML_TEMPLATE$.MODULE$;
  public static final GUIDE_PARAMETER_CODE PAGES_PATH = GUIDE_PARAMETER_CODE.PAGES_PATH$.MODULE$;
  public static final GUIDE_PARAMETER_CODE RESOURCE_PATH =
      GUIDE_PARAMETER_CODE.RESOURCE_PATH$.MODULE$;
  public static final GUIDE_PARAMETER_CODE TERMINOLOGY_CACHE_PATH =
      GUIDE_PARAMETER_CODE.TERMINOLOGY_CACHE_PATH$.MODULE$;
}
