package com.babylonhealth.lit.hl7_java.codes;

import com.babylonhealth.lit.hl7.INVOICE_PRICECOMPONENTTYPE;

public interface InvoicePricecomponenttype {
  public static final INVOICE_PRICECOMPONENTTYPE BASE = INVOICE_PRICECOMPONENTTYPE.BASE$.MODULE$;
  public static final INVOICE_PRICECOMPONENTTYPE DEDUCTION =
      INVOICE_PRICECOMPONENTTYPE.DEDUCTION$.MODULE$;
  public static final INVOICE_PRICECOMPONENTTYPE DISCOUNT =
      INVOICE_PRICECOMPONENTTYPE.DISCOUNT$.MODULE$;
  public static final INVOICE_PRICECOMPONENTTYPE INFORMATIONAL =
      INVOICE_PRICECOMPONENTTYPE.INFORMATIONAL$.MODULE$;
  public static final INVOICE_PRICECOMPONENTTYPE SURCHARGE =
      INVOICE_PRICECOMPONENTTYPE.SURCHARGE$.MODULE$;
  public static final INVOICE_PRICECOMPONENTTYPE TAX = INVOICE_PRICECOMPONENTTYPE.TAX$.MODULE$;
}
