package com.babylonhealth.lit.hl7_java.codes;

import com.babylonhealth.lit.hl7.ISSUE_TYPE;

public interface IssueType {
  public static final ISSUE_TYPE BUSINESS_RULE_VIOLATION =
      ISSUE_TYPE.BUSINESS_RULE_VIOLATION$.MODULE$;
  public static final ISSUE_TYPE CONFLICT = ISSUE_TYPE.CONFLICT$.MODULE$;
  public static final ISSUE_TYPE CONTENT_NOT_SUPPORTED = ISSUE_TYPE.CONTENT_NOT_SUPPORTED$.MODULE$;
  public static final ISSUE_TYPE CONTENT_TOO_LONG = ISSUE_TYPE.CONTENT_TOO_LONG$.MODULE$;
  public static final ISSUE_TYPE DELETED = ISSUE_TYPE.DELETED$.MODULE$;
  public static final ISSUE_TYPE DUPLICATE = ISSUE_TYPE.DUPLICATE$.MODULE$;
  public static final ISSUE_TYPE EXCEPTION = ISSUE_TYPE.EXCEPTION$.MODULE$;
  public static final ISSUE_TYPE EXPIRED = ISSUE_TYPE.EXPIRED$.MODULE$;
  public static final ISSUE_TYPE EXTENSION = ISSUE_TYPE.EXTENSION$.MODULE$;
  public static final ISSUE_TYPE FORBIDDEN = ISSUE_TYPE.FORBIDDEN$.MODULE$;
  public static final ISSUE_TYPE INCOMPLETE = ISSUE_TYPE.INCOMPLETE$.MODULE$;
  public static final ISSUE_TYPE INFORMATIONAL = ISSUE_TYPE.INFORMATIONAL$.MODULE$;
  public static final ISSUE_TYPE INVALID = ISSUE_TYPE.INVALID$.MODULE$;
  public static final ISSUE_TYPE INVALID_CODE = ISSUE_TYPE.INVALID_CODE$.MODULE$;
  public static final ISSUE_TYPE INVARIANT = ISSUE_TYPE.INVARIANT$.MODULE$;
  public static final ISSUE_TYPE LOCK_ERROR = ISSUE_TYPE.LOCK_ERROR$.MODULE$;
  public static final ISSUE_TYPE LOGIN = ISSUE_TYPE.LOGIN$.MODULE$;
  public static final ISSUE_TYPE MULTIPLE_MATCHES = ISSUE_TYPE.MULTIPLE_MATCHES$.MODULE$;
  public static final ISSUE_TYPE NOT_FOUND = ISSUE_TYPE.NOT_FOUND$.MODULE$;
  public static final ISSUE_TYPE NO_STORE_AVAILABLE = ISSUE_TYPE.NO_STORE_AVAILABLE$.MODULE$;
  public static final ISSUE_TYPE OPERATION_TOO_COSTLY = ISSUE_TYPE.OPERATION_TOO_COSTLY$.MODULE$;
  public static final ISSUE_TYPE PROCESSING = ISSUE_TYPE.PROCESSING$.MODULE$;
  public static final ISSUE_TYPE REQUIRED = ISSUE_TYPE.REQUIRED$.MODULE$;
  public static final ISSUE_TYPE SECURITY = ISSUE_TYPE.SECURITY$.MODULE$;
  public static final ISSUE_TYPE STRUCTURE = ISSUE_TYPE.STRUCTURE$.MODULE$;
  public static final ISSUE_TYPE SUPPRESSED = ISSUE_TYPE.SUPPRESSED$.MODULE$;
  public static final ISSUE_TYPE THROTTLED = ISSUE_TYPE.THROTTLED$.MODULE$;
  public static final ISSUE_TYPE TIMEOUT = ISSUE_TYPE.TIMEOUT$.MODULE$;
  public static final ISSUE_TYPE TRANSIENT = ISSUE_TYPE.TRANSIENT$.MODULE$;
  public static final ISSUE_TYPE UNKNOWN = ISSUE_TYPE.UNKNOWN$.MODULE$;
  public static final ISSUE_TYPE VALUE = ISSUE_TYPE.VALUE$.MODULE$;
}
