package com.babylonhealth.lit.hl7_java.codes;

import com.babylonhealth.lit.hl7.MAP_TRANSFORM;

public interface MapTransform {
  public static final MAP_TRANSFORM APPEND = MAP_TRANSFORM.APPEND$.MODULE$;
  public static final MAP_TRANSFORM C = MAP_TRANSFORM.C$.MODULE$;
  public static final MAP_TRANSFORM CAST = MAP_TRANSFORM.CAST$.MODULE$;
  public static final MAP_TRANSFORM CC = MAP_TRANSFORM.CC$.MODULE$;
  public static final MAP_TRANSFORM COPY = MAP_TRANSFORM.COPY$.MODULE$;
  public static final MAP_TRANSFORM CP = MAP_TRANSFORM.CP$.MODULE$;
  public static final MAP_TRANSFORM CREATE = MAP_TRANSFORM.CREATE$.MODULE$;
  public static final MAP_TRANSFORM DATEOP = MAP_TRANSFORM.DATEOP$.MODULE$;
  public static final MAP_TRANSFORM ESCAPE = MAP_TRANSFORM.ESCAPE$.MODULE$;
  public static final MAP_TRANSFORM EVALUATE = MAP_TRANSFORM.EVALUATE$.MODULE$;
  public static final MAP_TRANSFORM ID = MAP_TRANSFORM.ID$.MODULE$;
  public static final MAP_TRANSFORM POINTER = MAP_TRANSFORM.POINTER$.MODULE$;
  public static final MAP_TRANSFORM QTY = MAP_TRANSFORM.QTY$.MODULE$;
  public static final MAP_TRANSFORM REFERENCE = MAP_TRANSFORM.REFERENCE$.MODULE$;
  public static final MAP_TRANSFORM TRANSLATE = MAP_TRANSFORM.TRANSLATE$.MODULE$;
  public static final MAP_TRANSFORM TRUNCATE = MAP_TRANSFORM.TRUNCATE$.MODULE$;
  public static final MAP_TRANSFORM UUID = MAP_TRANSFORM.UUID$.MODULE$;
}
