package com.babylonhealth.lit.hl7_java.codes;

import com.babylonhealth.lit.hl7.MEDICATIONREQUEST_STATUS;

public interface MedicationrequestStatus {
  public static final MEDICATIONREQUEST_STATUS ACTIVE = MEDICATIONREQUEST_STATUS.ACTIVE$.MODULE$;
  public static final MEDICATIONREQUEST_STATUS CANCELLED =
      MEDICATIONREQUEST_STATUS.CANCELLED$.MODULE$;
  public static final MEDICATIONREQUEST_STATUS COMPLETED =
      MEDICATIONREQUEST_STATUS.COMPLETED$.MODULE$;
  public static final MEDICATIONREQUEST_STATUS DRAFT = MEDICATIONREQUEST_STATUS.DRAFT$.MODULE$;
  public static final MEDICATIONREQUEST_STATUS ENTERED_IN_ERROR =
      MEDICATIONREQUEST_STATUS.ENTERED_IN_ERROR$.MODULE$;
  public static final MEDICATIONREQUEST_STATUS ON_HOLD = MEDICATIONREQUEST_STATUS.ON_HOLD$.MODULE$;
  public static final MEDICATIONREQUEST_STATUS STOPPED = MEDICATIONREQUEST_STATUS.STOPPED$.MODULE$;
  public static final MEDICATIONREQUEST_STATUS UNKNOWN = MEDICATIONREQUEST_STATUS.UNKNOWN$.MODULE$;
}
