package com.babylonhealth.lit.hl7_java.codes;

import com.babylonhealth.lit.hl7.MEDICATIONREQUEST_INTENT;

public interface MedicationrequestIntent {
  public static final MEDICATIONREQUEST_INTENT FILLER_ORDER =
      MEDICATIONREQUEST_INTENT.FILLER_ORDER$.MODULE$;
  public static final MEDICATIONREQUEST_INTENT INSTANCE_ORDER =
      MEDICATIONREQUEST_INTENT.INSTANCE_ORDER$.MODULE$;
  public static final MEDICATIONREQUEST_INTENT OPTION = MEDICATIONREQUEST_INTENT.OPTION$.MODULE$;
  public static final MEDICATIONREQUEST_INTENT ORDER = MEDICATIONREQUEST_INTENT.ORDER$.MODULE$;
  public static final MEDICATIONREQUEST_INTENT ORIGINAL_ORDER =
      MEDICATIONREQUEST_INTENT.ORIGINAL_ORDER$.MODULE$;
  public static final MEDICATIONREQUEST_INTENT PLAN = MEDICATIONREQUEST_INTENT.PLAN$.MODULE$;
  public static final MEDICATIONREQUEST_INTENT PROPOSAL =
      MEDICATIONREQUEST_INTENT.PROPOSAL$.MODULE$;
  public static final MEDICATIONREQUEST_INTENT REFLEX_ORDER =
      MEDICATIONREQUEST_INTENT.REFLEX_ORDER$.MODULE$;
}
