package com.babylonhealth.lit.hl7_java.codes;

import com.babylonhealth.lit.hl7.MEDICATIONDISPENSE_STATUS;

public interface MedicationdispenseStatus {
  public static final MEDICATIONDISPENSE_STATUS CANCELLED =
      MEDICATIONDISPENSE_STATUS.CANCELLED$.MODULE$;
  public static final MEDICATIONDISPENSE_STATUS COMPLETED =
      MEDICATIONDISPENSE_STATUS.COMPLETED$.MODULE$;
  public static final MEDICATIONDISPENSE_STATUS DECLINED =
      MEDICATIONDISPENSE_STATUS.DECLINED$.MODULE$;
  public static final MEDICATIONDISPENSE_STATUS ENTERED_IN_ERROR =
      MEDICATIONDISPENSE_STATUS.ENTERED_IN_ERROR$.MODULE$;
  public static final MEDICATIONDISPENSE_STATUS IN_PROGRESS =
      MEDICATIONDISPENSE_STATUS.IN_PROGRESS$.MODULE$;
  public static final MEDICATIONDISPENSE_STATUS ON_HOLD =
      MEDICATIONDISPENSE_STATUS.ON_HOLD$.MODULE$;
  public static final MEDICATIONDISPENSE_STATUS PREPARATION =
      MEDICATIONDISPENSE_STATUS.PREPARATION$.MODULE$;
  public static final MEDICATIONDISPENSE_STATUS STOPPED =
      MEDICATIONDISPENSE_STATUS.STOPPED$.MODULE$;
  public static final MEDICATIONDISPENSE_STATUS UNKNOWN =
      MEDICATIONDISPENSE_STATUS.UNKNOWN$.MODULE$;
}
