package com.babylonhealth.lit.hl7_java.codes;

import com.babylonhealth.lit.hl7.MEDICATION_STATEMENT_STATUS;

public interface MedicationStatementStatus {
  public static final MEDICATION_STATEMENT_STATUS ACTIVE =
      MEDICATION_STATEMENT_STATUS.ACTIVE$.MODULE$;
  public static final MEDICATION_STATEMENT_STATUS COMPLETED =
      MEDICATION_STATEMENT_STATUS.COMPLETED$.MODULE$;
  public static final MEDICATION_STATEMENT_STATUS ENTERED_IN_ERROR =
      MEDICATION_STATEMENT_STATUS.ENTERED_IN_ERROR$.MODULE$;
  public static final MEDICATION_STATEMENT_STATUS INTENDED =
      MEDICATION_STATEMENT_STATUS.INTENDED$.MODULE$;
  public static final MEDICATION_STATEMENT_STATUS NOT_TAKEN =
      MEDICATION_STATEMENT_STATUS.NOT_TAKEN$.MODULE$;
  public static final MEDICATION_STATEMENT_STATUS ON_HOLD =
      MEDICATION_STATEMENT_STATUS.ON_HOLD$.MODULE$;
  public static final MEDICATION_STATEMENT_STATUS STOPPED =
      MEDICATION_STATEMENT_STATUS.STOPPED$.MODULE$;
  public static final MEDICATION_STATEMENT_STATUS UNKNOWN =
      MEDICATION_STATEMENT_STATUS.UNKNOWN$.MODULE$;
}
