package com.babylonhealth.lit.hl7_java.codes;

import com.babylonhealth.lit.hl7.MEDICATION_ADMIN_STATUS;

public interface MedicationAdminStatus {
  public static final MEDICATION_ADMIN_STATUS COMPLETED =
      MEDICATION_ADMIN_STATUS.COMPLETED$.MODULE$;
  public static final MEDICATION_ADMIN_STATUS ENTERED_IN_ERROR =
      MEDICATION_ADMIN_STATUS.ENTERED_IN_ERROR$.MODULE$;
  public static final MEDICATION_ADMIN_STATUS IN_PROGRESS =
      MEDICATION_ADMIN_STATUS.IN_PROGRESS$.MODULE$;
  public static final MEDICATION_ADMIN_STATUS NOT_DONE = MEDICATION_ADMIN_STATUS.NOT_DONE$.MODULE$;
  public static final MEDICATION_ADMIN_STATUS ON_HOLD = MEDICATION_ADMIN_STATUS.ON_HOLD$.MODULE$;
  public static final MEDICATION_ADMIN_STATUS STOPPED = MEDICATION_ADMIN_STATUS.STOPPED$.MODULE$;
  public static final MEDICATION_ADMIN_STATUS UNKNOWN = MEDICATION_ADMIN_STATUS.UNKNOWN$.MODULE$;
}
