package com.babylonhealth.lit.hl7_java.codes;

import com.babylonhealth.lit.hl7.MESSAGEHEADER_RESPONSE_REQUEST;

public interface MessageheaderResponseRequest {
  public static final MESSAGEHEADER_RESPONSE_REQUEST ALWAYS =
      MESSAGEHEADER_RESPONSE_REQUEST.ALWAYS$.MODULE$;
  public static final MESSAGEHEADER_RESPONSE_REQUEST NEVER =
      MESSAGEHEADER_RESPONSE_REQUEST.NEVER$.MODULE$;
  public static final MESSAGEHEADER_RESPONSE_REQUEST ON_ERROR =
      MESSAGEHEADER_RESPONSE_REQUEST.ON_ERROR$.MODULE$;
  public static final MESSAGEHEADER_RESPONSE_REQUEST SUCCESSFUL_COMPLETION_ONLY =
      MESSAGEHEADER_RESPONSE_REQUEST.SUCCESSFUL_COMPLETION_ONLY$.MODULE$;
}
