package com.babylonhealth.lit.hl7_java.codes;

import com.babylonhealth.lit.hl7.METRIC_CALIBRATION_STATE;

public interface MetricCalibrationState {
  public static final METRIC_CALIBRATION_STATE CALIBRATED =
      METRIC_CALIBRATION_STATE.CALIBRATED$.MODULE$;
  public static final METRIC_CALIBRATION_STATE CALIBRATION_REQUIRED =
      METRIC_CALIBRATION_STATE.CALIBRATION_REQUIRED$.MODULE$;
  public static final METRIC_CALIBRATION_STATE NOT_CALIBRATED =
      METRIC_CALIBRATION_STATE.NOT_CALIBRATED$.MODULE$;
  public static final METRIC_CALIBRATION_STATE UNSPECIFIED =
      METRIC_CALIBRATION_STATE.UNSPECIFIED$.MODULE$;
}
