package com.babylonhealth.lit.hl7_java.codes;

import com.babylonhealth.lit.hl7.OBSERVATION_STATUS;

public interface ObservationStatus {
  public static final OBSERVATION_STATUS AMENDED = OBSERVATION_STATUS.AMENDED$.MODULE$;
  public static final OBSERVATION_STATUS CANCELLED = OBSERVATION_STATUS.CANCELLED$.MODULE$;
  public static final OBSERVATION_STATUS CORRECTED = OBSERVATION_STATUS.CORRECTED$.MODULE$;
  public static final OBSERVATION_STATUS ENTERED_IN_ERROR =
      OBSERVATION_STATUS.ENTERED_IN_ERROR$.MODULE$;
  public static final OBSERVATION_STATUS FINAL = OBSERVATION_STATUS.FINAL$.MODULE$;
  public static final OBSERVATION_STATUS PRELIMINARY = OBSERVATION_STATUS.PRELIMINARY$.MODULE$;
  public static final OBSERVATION_STATUS REGISTERED = OBSERVATION_STATUS.REGISTERED$.MODULE$;
  public static final OBSERVATION_STATUS UNKNOWN = OBSERVATION_STATUS.UNKNOWN$.MODULE$;
}
