package com.babylonhealth.lit.hl7_java.codes;

import com.babylonhealth.lit.hl7.PARTICIPATIONSTATUS;

public interface Participationstatus {
  public static final PARTICIPATIONSTATUS ACCEPTED = PARTICIPATIONSTATUS.ACCEPTED$.MODULE$;
  public static final PARTICIPATIONSTATUS DECLINED = PARTICIPATIONSTATUS.DECLINED$.MODULE$;
  public static final PARTICIPATIONSTATUS NEEDS_ACTION = PARTICIPATIONSTATUS.NEEDS_ACTION$.MODULE$;
  public static final PARTICIPATIONSTATUS TENTATIVE = PARTICIPATIONSTATUS.TENTATIVE$.MODULE$;
}
