package com.babylonhealth.lit.hl7_java.codes;

import com.babylonhealth.lit.hl7.PERMITTED_DATA_TYPE;

public interface PermittedDataType {
  public static final PERMITTED_DATA_TYPE BOOLEAN = PERMITTED_DATA_TYPE.BOOLEAN$.MODULE$;
  public static final PERMITTED_DATA_TYPE CODEABLECONCEPT =
      PERMITTED_DATA_TYPE.CODEABLECONCEPT$.MODULE$;
  public static final PERMITTED_DATA_TYPE DATETIME = PERMITTED_DATA_TYPE.DATETIME$.MODULE$;
  public static final PERMITTED_DATA_TYPE INTEGER = PERMITTED_DATA_TYPE.INTEGER$.MODULE$;
  public static final PERMITTED_DATA_TYPE PERIOD = PERMITTED_DATA_TYPE.PERIOD$.MODULE$;
  public static final PERMITTED_DATA_TYPE QUANTITY = PERMITTED_DATA_TYPE.QUANTITY$.MODULE$;
  public static final PERMITTED_DATA_TYPE RANGE = PERMITTED_DATA_TYPE.RANGE$.MODULE$;
  public static final PERMITTED_DATA_TYPE RATIO = PERMITTED_DATA_TYPE.RATIO$.MODULE$;
  public static final PERMITTED_DATA_TYPE SAMPLEDDATA = PERMITTED_DATA_TYPE.SAMPLEDDATA$.MODULE$;
  public static final PERMITTED_DATA_TYPE STRING = PERMITTED_DATA_TYPE.STRING$.MODULE$;
  public static final PERMITTED_DATA_TYPE TIME = PERMITTED_DATA_TYPE.TIME$.MODULE$;
}
