package com.babylonhealth.lit.hl7_java.codes;

import com.babylonhealth.lit.hl7.PROPERTY_REPRESENTATION;

public interface PropertyRepresentation {
  public static final PROPERTY_REPRESENTATION CDATEXT = PROPERTY_REPRESENTATION.CDATEXT$.MODULE$;
  public static final PROPERTY_REPRESENTATION TYPEATTR = PROPERTY_REPRESENTATION.TYPEATTR$.MODULE$;
  public static final PROPERTY_REPRESENTATION XHTML = PROPERTY_REPRESENTATION.XHTML$.MODULE$;
  public static final PROPERTY_REPRESENTATION XMLATTR = PROPERTY_REPRESENTATION.XMLATTR$.MODULE$;
  public static final PROPERTY_REPRESENTATION XMLTEXT = PROPERTY_REPRESENTATION.XMLTEXT$.MODULE$;
}
