package com.babylonhealth.lit.hl7_java.codes;

import com.babylonhealth.lit.hl7.QUESTIONNAIRE_ANSWERS_STATUS;

public interface QuestionnaireAnswersStatus {
  public static final QUESTIONNAIRE_ANSWERS_STATUS AMENDED =
      QUESTIONNAIRE_ANSWERS_STATUS.AMENDED$.MODULE$;
  public static final QUESTIONNAIRE_ANSWERS_STATUS COMPLETED =
      QUESTIONNAIRE_ANSWERS_STATUS.COMPLETED$.MODULE$;
  public static final QUESTIONNAIRE_ANSWERS_STATUS ENTERED_IN_ERROR =
      QUESTIONNAIRE_ANSWERS_STATUS.ENTERED_IN_ERROR$.MODULE$;
  public static final QUESTIONNAIRE_ANSWERS_STATUS IN_PROGRESS =
      QUESTIONNAIRE_ANSWERS_STATUS.IN_PROGRESS$.MODULE$;
  public static final QUESTIONNAIRE_ANSWERS_STATUS STOPPED =
      QUESTIONNAIRE_ANSWERS_STATUS.STOPPED$.MODULE$;
}
