package com.babylonhealth.lit.hl7_java.codes;

import com.babylonhealth.lit.hl7.QUESTIONNAIRE_ENABLE_OPERATOR;

public interface QuestionnaireEnableOperator {
  public static final QUESTIONNAIRE_ENABLE_OPERATOR EQUALS =
      QUESTIONNAIRE_ENABLE_OPERATOR.EQUALS$.MODULE$;
  public static final QUESTIONNAIRE_ENABLE_OPERATOR EXISTS =
      QUESTIONNAIRE_ENABLE_OPERATOR.EXISTS$.MODULE$;
  public static final QUESTIONNAIRE_ENABLE_OPERATOR GREATER_OR_EQUALS =
      QUESTIONNAIRE_ENABLE_OPERATOR.GREATER_OR_EQUALS$.MODULE$;
  public static final QUESTIONNAIRE_ENABLE_OPERATOR GREATER_THAN =
      QUESTIONNAIRE_ENABLE_OPERATOR.GREATER_THAN$.MODULE$;
  public static final QUESTIONNAIRE_ENABLE_OPERATOR LESS_OR_EQUALS =
      QUESTIONNAIRE_ENABLE_OPERATOR.LESS_OR_EQUALS$.MODULE$;
  public static final QUESTIONNAIRE_ENABLE_OPERATOR LESS_THAN =
      QUESTIONNAIRE_ENABLE_OPERATOR.LESS_THAN$.MODULE$;
  public static final QUESTIONNAIRE_ENABLE_OPERATOR NOT_EQUALS =
      QUESTIONNAIRE_ENABLE_OPERATOR.NOT_EQUALS$.MODULE$;
}
