package com.babylonhealth.lit.hl7_java.codes;

import com.babylonhealth.lit.hl7.REFERENCE_HANDLING_POLICY;

public interface ReferenceHandlingPolicy {
  public static final REFERENCE_HANDLING_POLICY ENFORCED =
      REFERENCE_HANDLING_POLICY.ENFORCED$.MODULE$;
  public static final REFERENCE_HANDLING_POLICY LITERAL =
      REFERENCE_HANDLING_POLICY.LITERAL$.MODULE$;
  public static final REFERENCE_HANDLING_POLICY LOCAL = REFERENCE_HANDLING_POLICY.LOCAL$.MODULE$;
  public static final REFERENCE_HANDLING_POLICY LOGICAL =
      REFERENCE_HANDLING_POLICY.LOGICAL$.MODULE$;
  public static final REFERENCE_HANDLING_POLICY RESOLVES =
      REFERENCE_HANDLING_POLICY.RESOLVES$.MODULE$;
}
