package com.babylonhealth.lit.hl7_java.codes;

import com.babylonhealth.lit.hl7.REQUEST_INTENT;

public interface RequestIntent {
  public static final REQUEST_INTENT DIRECTIVE = REQUEST_INTENT.DIRECTIVE$.MODULE$;
  public static final REQUEST_INTENT FILLER_ORDER = REQUEST_INTENT.FILLER_ORDER$.MODULE$;
  public static final REQUEST_INTENT INSTANCE_ORDER = REQUEST_INTENT.INSTANCE_ORDER$.MODULE$;
  public static final REQUEST_INTENT OPTION = REQUEST_INTENT.OPTION$.MODULE$;
  public static final REQUEST_INTENT ORDER = REQUEST_INTENT.ORDER$.MODULE$;
  public static final REQUEST_INTENT ORIGINAL_ORDER = REQUEST_INTENT.ORIGINAL_ORDER$.MODULE$;
  public static final REQUEST_INTENT PLAN = REQUEST_INTENT.PLAN$.MODULE$;
  public static final REQUEST_INTENT PROPOSAL = REQUEST_INTENT.PROPOSAL$.MODULE$;
  public static final REQUEST_INTENT REFLEX_ORDER = REQUEST_INTENT.REFLEX_ORDER$.MODULE$;
}
