package com.babylonhealth.lit.hl7_java.codes;

import com.babylonhealth.lit.hl7.REQUEST_RESOURCE_TYPES;

public interface RequestResourceTypes {
  public static final REQUEST_RESOURCE_TYPES APPOINTMENT =
      REQUEST_RESOURCE_TYPES.APPOINTMENT$.MODULE$;
  public static final REQUEST_RESOURCE_TYPES APPOINTMENTRESPONSE =
      REQUEST_RESOURCE_TYPES.APPOINTMENTRESPONSE$.MODULE$;
  public static final REQUEST_RESOURCE_TYPES CAREPLAN = REQUEST_RESOURCE_TYPES.CAREPLAN$.MODULE$;
  public static final REQUEST_RESOURCE_TYPES CLAIM = REQUEST_RESOURCE_TYPES.CLAIM$.MODULE$;
  public static final REQUEST_RESOURCE_TYPES COMMUNICATIONREQUEST =
      REQUEST_RESOURCE_TYPES.COMMUNICATIONREQUEST$.MODULE$;
  public static final REQUEST_RESOURCE_TYPES CONTRACT = REQUEST_RESOURCE_TYPES.CONTRACT$.MODULE$;
  public static final REQUEST_RESOURCE_TYPES DEVICEREQUEST =
      REQUEST_RESOURCE_TYPES.DEVICEREQUEST$.MODULE$;
  public static final REQUEST_RESOURCE_TYPES ENROLLMENTREQUEST =
      REQUEST_RESOURCE_TYPES.ENROLLMENTREQUEST$.MODULE$;
  public static final REQUEST_RESOURCE_TYPES IMMUNIZATIONRECOMMENDATION =
      REQUEST_RESOURCE_TYPES.IMMUNIZATIONRECOMMENDATION$.MODULE$;
  public static final REQUEST_RESOURCE_TYPES MEDICATIONREQUEST =
      REQUEST_RESOURCE_TYPES.MEDICATIONREQUEST$.MODULE$;
  public static final REQUEST_RESOURCE_TYPES NUTRITIONORDER =
      REQUEST_RESOURCE_TYPES.NUTRITIONORDER$.MODULE$;
  public static final REQUEST_RESOURCE_TYPES SERVICEREQUEST =
      REQUEST_RESOURCE_TYPES.SERVICEREQUEST$.MODULE$;
  public static final REQUEST_RESOURCE_TYPES SUPPLYREQUEST =
      REQUEST_RESOURCE_TYPES.SUPPLYREQUEST$.MODULE$;
  public static final REQUEST_RESOURCE_TYPES TASK = REQUEST_RESOURCE_TYPES.TASK$.MODULE$;
  public static final REQUEST_RESOURCE_TYPES VISIONPRESCRIPTION =
      REQUEST_RESOURCE_TYPES.VISIONPRESCRIPTION$.MODULE$;
}
