package com.babylonhealth.lit.hl7_java.codes;

import com.babylonhealth.lit.hl7.RESEARCH_STUDY_STATUS;

public interface ResearchStudyStatus {
  public static final RESEARCH_STUDY_STATUS ACTIVE = RESEARCH_STUDY_STATUS.ACTIVE$.MODULE$;
  public static final RESEARCH_STUDY_STATUS ADMINISTRATIVELY_COMPLETED =
      RESEARCH_STUDY_STATUS.ADMINISTRATIVELY_COMPLETED$.MODULE$;
  public static final RESEARCH_STUDY_STATUS APPROVED = RESEARCH_STUDY_STATUS.APPROVED$.MODULE$;
  public static final RESEARCH_STUDY_STATUS CLOSED_TO_ACCRUAL =
      RESEARCH_STUDY_STATUS.CLOSED_TO_ACCRUAL$.MODULE$;
  public static final RESEARCH_STUDY_STATUS CLOSED_TO_ACCRUAL_AND_INTERVENTION =
      RESEARCH_STUDY_STATUS.CLOSED_TO_ACCRUAL_AND_INTERVENTION$.MODULE$;
  public static final RESEARCH_STUDY_STATUS COMPLETED = RESEARCH_STUDY_STATUS.COMPLETED$.MODULE$;
  public static final RESEARCH_STUDY_STATUS DISAPPROVED =
      RESEARCH_STUDY_STATUS.DISAPPROVED$.MODULE$;
  public static final RESEARCH_STUDY_STATUS IN_REVIEW = RESEARCH_STUDY_STATUS.IN_REVIEW$.MODULE$;
  public static final RESEARCH_STUDY_STATUS TEMPORARILY_CLOSED_TO_ACCRUAL =
      RESEARCH_STUDY_STATUS.TEMPORARILY_CLOSED_TO_ACCRUAL$.MODULE$;
  public static final RESEARCH_STUDY_STATUS TEMPORARILY_CLOSED_TO_ACCRUAL_AND_INTERVENTION =
      RESEARCH_STUDY_STATUS.TEMPORARILY_CLOSED_TO_ACCRUAL_AND_INTERVENTION$.MODULE$;
  public static final RESEARCH_STUDY_STATUS WITHDRAWN = RESEARCH_STUDY_STATUS.WITHDRAWN$.MODULE$;
}
