package com.babylonhealth.lit.hl7_java.codes;

import com.babylonhealth.lit.hl7.RESEARCH_SUBJECT_STATUS;

public interface ResearchSubjectStatus {
  public static final RESEARCH_SUBJECT_STATUS CANDIDATE =
      RESEARCH_SUBJECT_STATUS.CANDIDATE$.MODULE$;
  public static final RESEARCH_SUBJECT_STATUS ELIGIBLE = RESEARCH_SUBJECT_STATUS.ELIGIBLE$.MODULE$;
  public static final RESEARCH_SUBJECT_STATUS FOLLOW_UP =
      RESEARCH_SUBJECT_STATUS.FOLLOW_UP$.MODULE$;
  public static final RESEARCH_SUBJECT_STATUS INELIGIBLE =
      RESEARCH_SUBJECT_STATUS.INELIGIBLE$.MODULE$;
  public static final RESEARCH_SUBJECT_STATUS NOT_REGISTERED =
      RESEARCH_SUBJECT_STATUS.NOT_REGISTERED$.MODULE$;
  public static final RESEARCH_SUBJECT_STATUS OFF_STUDY =
      RESEARCH_SUBJECT_STATUS.OFF_STUDY$.MODULE$;
  public static final RESEARCH_SUBJECT_STATUS ON_STUDY = RESEARCH_SUBJECT_STATUS.ON_STUDY$.MODULE$;
  public static final RESEARCH_SUBJECT_STATUS ON_STUDY_INTERVENTION =
      RESEARCH_SUBJECT_STATUS.ON_STUDY_INTERVENTION$.MODULE$;
  public static final RESEARCH_SUBJECT_STATUS ON_STUDY_OBSERVATION =
      RESEARCH_SUBJECT_STATUS.ON_STUDY_OBSERVATION$.MODULE$;
  public static final RESEARCH_SUBJECT_STATUS PENDING_ON_STUDY =
      RESEARCH_SUBJECT_STATUS.PENDING_ON_STUDY$.MODULE$;
  public static final RESEARCH_SUBJECT_STATUS POTENTIAL_CANDIDATE =
      RESEARCH_SUBJECT_STATUS.POTENTIAL_CANDIDATE$.MODULE$;
  public static final RESEARCH_SUBJECT_STATUS SCREENING =
      RESEARCH_SUBJECT_STATUS.SCREENING$.MODULE$;
  public static final RESEARCH_SUBJECT_STATUS WITHDRAWN =
      RESEARCH_SUBJECT_STATUS.WITHDRAWN$.MODULE$;
}
