package com.babylonhealth.lit.hl7_java.codes;

import com.babylonhealth.lit.hl7.RESOURCE_TYPES;

public interface ResourceTypes {
  public static final RESOURCE_TYPES ACCOUNT = RESOURCE_TYPES.ACCOUNT$.MODULE$;
  public static final RESOURCE_TYPES ACTIVITYDEFINITION =
      RESOURCE_TYPES.ACTIVITYDEFINITION$.MODULE$;
  public static final RESOURCE_TYPES ADVERSEEVENT = RESOURCE_TYPES.ADVERSEEVENT$.MODULE$;
  public static final RESOURCE_TYPES ALLERGYINTOLERANCE =
      RESOURCE_TYPES.ALLERGYINTOLERANCE$.MODULE$;
  public static final RESOURCE_TYPES APPOINTMENT = RESOURCE_TYPES.APPOINTMENT$.MODULE$;
  public static final RESOURCE_TYPES APPOINTMENTRESPONSE =
      RESOURCE_TYPES.APPOINTMENTRESPONSE$.MODULE$;
  public static final RESOURCE_TYPES AUDITEVENT = RESOURCE_TYPES.AUDITEVENT$.MODULE$;
  public static final RESOURCE_TYPES BASIC = RESOURCE_TYPES.BASIC$.MODULE$;
  public static final RESOURCE_TYPES BINARY = RESOURCE_TYPES.BINARY$.MODULE$;
  public static final RESOURCE_TYPES BIOLOGICALLYDERIVEDPRODUCT =
      RESOURCE_TYPES.BIOLOGICALLYDERIVEDPRODUCT$.MODULE$;
  public static final RESOURCE_TYPES BODYSTRUCTURE = RESOURCE_TYPES.BODYSTRUCTURE$.MODULE$;
  public static final RESOURCE_TYPES BUNDLE = RESOURCE_TYPES.BUNDLE$.MODULE$;
  public static final RESOURCE_TYPES CAPABILITYSTATEMENT =
      RESOURCE_TYPES.CAPABILITYSTATEMENT$.MODULE$;
  public static final RESOURCE_TYPES CAREPLAN = RESOURCE_TYPES.CAREPLAN$.MODULE$;
  public static final RESOURCE_TYPES CARETEAM = RESOURCE_TYPES.CARETEAM$.MODULE$;
  public static final RESOURCE_TYPES CATALOGENTRY = RESOURCE_TYPES.CATALOGENTRY$.MODULE$;
  public static final RESOURCE_TYPES CHARGEITEM = RESOURCE_TYPES.CHARGEITEM$.MODULE$;
  public static final RESOURCE_TYPES CHARGEITEMDEFINITION =
      RESOURCE_TYPES.CHARGEITEMDEFINITION$.MODULE$;
  public static final RESOURCE_TYPES CLAIM = RESOURCE_TYPES.CLAIM$.MODULE$;
  public static final RESOURCE_TYPES CLAIMRESPONSE = RESOURCE_TYPES.CLAIMRESPONSE$.MODULE$;
  public static final RESOURCE_TYPES CLINICALIMPRESSION =
      RESOURCE_TYPES.CLINICALIMPRESSION$.MODULE$;
  public static final RESOURCE_TYPES CODESYSTEM = RESOURCE_TYPES.CODESYSTEM$.MODULE$;
  public static final RESOURCE_TYPES COMMUNICATION = RESOURCE_TYPES.COMMUNICATION$.MODULE$;
  public static final RESOURCE_TYPES COMMUNICATIONREQUEST =
      RESOURCE_TYPES.COMMUNICATIONREQUEST$.MODULE$;
  public static final RESOURCE_TYPES COMPARTMENTDEFINITION =
      RESOURCE_TYPES.COMPARTMENTDEFINITION$.MODULE$;
  public static final RESOURCE_TYPES COMPOSITION = RESOURCE_TYPES.COMPOSITION$.MODULE$;
  public static final RESOURCE_TYPES CONCEPTMAP = RESOURCE_TYPES.CONCEPTMAP$.MODULE$;
  public static final RESOURCE_TYPES CONDITION = RESOURCE_TYPES.CONDITION$.MODULE$;
  public static final RESOURCE_TYPES CONSENT = RESOURCE_TYPES.CONSENT$.MODULE$;
  public static final RESOURCE_TYPES CONTRACT = RESOURCE_TYPES.CONTRACT$.MODULE$;
  public static final RESOURCE_TYPES COVERAGE = RESOURCE_TYPES.COVERAGE$.MODULE$;
  public static final RESOURCE_TYPES COVERAGEELIGIBILITYREQUEST =
      RESOURCE_TYPES.COVERAGEELIGIBILITYREQUEST$.MODULE$;
  public static final RESOURCE_TYPES COVERAGEELIGIBILITYRESPONSE =
      RESOURCE_TYPES.COVERAGEELIGIBILITYRESPONSE$.MODULE$;
  public static final RESOURCE_TYPES DETECTEDISSUE = RESOURCE_TYPES.DETECTEDISSUE$.MODULE$;
  public static final RESOURCE_TYPES DEVICE = RESOURCE_TYPES.DEVICE$.MODULE$;
  public static final RESOURCE_TYPES DEVICEDEFINITION = RESOURCE_TYPES.DEVICEDEFINITION$.MODULE$;
  public static final RESOURCE_TYPES DEVICEMETRIC = RESOURCE_TYPES.DEVICEMETRIC$.MODULE$;
  public static final RESOURCE_TYPES DEVICEREQUEST = RESOURCE_TYPES.DEVICEREQUEST$.MODULE$;
  public static final RESOURCE_TYPES DEVICEUSESTATEMENT =
      RESOURCE_TYPES.DEVICEUSESTATEMENT$.MODULE$;
  public static final RESOURCE_TYPES DIAGNOSTICREPORT = RESOURCE_TYPES.DIAGNOSTICREPORT$.MODULE$;
  public static final RESOURCE_TYPES DOCUMENTMANIFEST = RESOURCE_TYPES.DOCUMENTMANIFEST$.MODULE$;
  public static final RESOURCE_TYPES DOCUMENTREFERENCE = RESOURCE_TYPES.DOCUMENTREFERENCE$.MODULE$;
  public static final RESOURCE_TYPES DOMAINRESOURCE = RESOURCE_TYPES.DOMAINRESOURCE$.MODULE$;
  public static final RESOURCE_TYPES EFFECTEVIDENCESYNTHESIS =
      RESOURCE_TYPES.EFFECTEVIDENCESYNTHESIS$.MODULE$;
  public static final RESOURCE_TYPES ENCOUNTER = RESOURCE_TYPES.ENCOUNTER$.MODULE$;
  public static final RESOURCE_TYPES ENDPOINT = RESOURCE_TYPES.ENDPOINT$.MODULE$;
  public static final RESOURCE_TYPES ENROLLMENTREQUEST = RESOURCE_TYPES.ENROLLMENTREQUEST$.MODULE$;
  public static final RESOURCE_TYPES ENROLLMENTRESPONSE =
      RESOURCE_TYPES.ENROLLMENTRESPONSE$.MODULE$;
  public static final RESOURCE_TYPES EPISODEOFCARE = RESOURCE_TYPES.EPISODEOFCARE$.MODULE$;
  public static final RESOURCE_TYPES EVENTDEFINITION = RESOURCE_TYPES.EVENTDEFINITION$.MODULE$;
  public static final RESOURCE_TYPES EVIDENCE = RESOURCE_TYPES.EVIDENCE$.MODULE$;
  public static final RESOURCE_TYPES EVIDENCEVARIABLE = RESOURCE_TYPES.EVIDENCEVARIABLE$.MODULE$;
  public static final RESOURCE_TYPES EXAMPLESCENARIO = RESOURCE_TYPES.EXAMPLESCENARIO$.MODULE$;
  public static final RESOURCE_TYPES EXPLANATIONOFBENEFIT =
      RESOURCE_TYPES.EXPLANATIONOFBENEFIT$.MODULE$;
  public static final RESOURCE_TYPES FAMILYMEMBERHISTORY =
      RESOURCE_TYPES.FAMILYMEMBERHISTORY$.MODULE$;
  public static final RESOURCE_TYPES FLAG = RESOURCE_TYPES.FLAG$.MODULE$;
  public static final RESOURCE_TYPES GOAL = RESOURCE_TYPES.GOAL$.MODULE$;
  public static final RESOURCE_TYPES GRAPHDEFINITION = RESOURCE_TYPES.GRAPHDEFINITION$.MODULE$;
  public static final RESOURCE_TYPES GROUP = RESOURCE_TYPES.GROUP$.MODULE$;
  public static final RESOURCE_TYPES GUIDANCERESPONSE = RESOURCE_TYPES.GUIDANCERESPONSE$.MODULE$;
  public static final RESOURCE_TYPES HEALTHCARESERVICE = RESOURCE_TYPES.HEALTHCARESERVICE$.MODULE$;
  public static final RESOURCE_TYPES IMAGINGSTUDY = RESOURCE_TYPES.IMAGINGSTUDY$.MODULE$;
  public static final RESOURCE_TYPES IMMUNIZATION = RESOURCE_TYPES.IMMUNIZATION$.MODULE$;
  public static final RESOURCE_TYPES IMMUNIZATIONEVALUATION =
      RESOURCE_TYPES.IMMUNIZATIONEVALUATION$.MODULE$;
  public static final RESOURCE_TYPES IMMUNIZATIONRECOMMENDATION =
      RESOURCE_TYPES.IMMUNIZATIONRECOMMENDATION$.MODULE$;
  public static final RESOURCE_TYPES IMPLEMENTATIONGUIDE =
      RESOURCE_TYPES.IMPLEMENTATIONGUIDE$.MODULE$;
  public static final RESOURCE_TYPES INSURANCEPLAN = RESOURCE_TYPES.INSURANCEPLAN$.MODULE$;
  public static final RESOURCE_TYPES INVOICE = RESOURCE_TYPES.INVOICE$.MODULE$;
  public static final RESOURCE_TYPES LIBRARY = RESOURCE_TYPES.LIBRARY$.MODULE$;
  public static final RESOURCE_TYPES LINKAGE = RESOURCE_TYPES.LINKAGE$.MODULE$;
  public static final RESOURCE_TYPES LIST = RESOURCE_TYPES.LIST$.MODULE$;
  public static final RESOURCE_TYPES LOCATION = RESOURCE_TYPES.LOCATION$.MODULE$;
  public static final RESOURCE_TYPES MEASURE = RESOURCE_TYPES.MEASURE$.MODULE$;
  public static final RESOURCE_TYPES MEASUREREPORT = RESOURCE_TYPES.MEASUREREPORT$.MODULE$;
  public static final RESOURCE_TYPES MEDIA = RESOURCE_TYPES.MEDIA$.MODULE$;
  public static final RESOURCE_TYPES MEDICATION = RESOURCE_TYPES.MEDICATION$.MODULE$;
  public static final RESOURCE_TYPES MEDICATIONADMINISTRATION =
      RESOURCE_TYPES.MEDICATIONADMINISTRATION$.MODULE$;
  public static final RESOURCE_TYPES MEDICATIONDISPENSE =
      RESOURCE_TYPES.MEDICATIONDISPENSE$.MODULE$;
  public static final RESOURCE_TYPES MEDICATIONKNOWLEDGE =
      RESOURCE_TYPES.MEDICATIONKNOWLEDGE$.MODULE$;
  public static final RESOURCE_TYPES MEDICATIONREQUEST = RESOURCE_TYPES.MEDICATIONREQUEST$.MODULE$;
  public static final RESOURCE_TYPES MEDICATIONSTATEMENT =
      RESOURCE_TYPES.MEDICATIONSTATEMENT$.MODULE$;
  public static final RESOURCE_TYPES MEDICINALPRODUCT = RESOURCE_TYPES.MEDICINALPRODUCT$.MODULE$;
  public static final RESOURCE_TYPES MEDICINALPRODUCTAUTHORIZATION =
      RESOURCE_TYPES.MEDICINALPRODUCTAUTHORIZATION$.MODULE$;
  public static final RESOURCE_TYPES MEDICINALPRODUCTCONTRAINDICATION =
      RESOURCE_TYPES.MEDICINALPRODUCTCONTRAINDICATION$.MODULE$;
  public static final RESOURCE_TYPES MEDICINALPRODUCTINDICATION =
      RESOURCE_TYPES.MEDICINALPRODUCTINDICATION$.MODULE$;
  public static final RESOURCE_TYPES MEDICINALPRODUCTINGREDIENT =
      RESOURCE_TYPES.MEDICINALPRODUCTINGREDIENT$.MODULE$;
  public static final RESOURCE_TYPES MEDICINALPRODUCTINTERACTION =
      RESOURCE_TYPES.MEDICINALPRODUCTINTERACTION$.MODULE$;
  public static final RESOURCE_TYPES MEDICINALPRODUCTMANUFACTURED =
      RESOURCE_TYPES.MEDICINALPRODUCTMANUFACTURED$.MODULE$;
  public static final RESOURCE_TYPES MEDICINALPRODUCTPACKAGED =
      RESOURCE_TYPES.MEDICINALPRODUCTPACKAGED$.MODULE$;
  public static final RESOURCE_TYPES MEDICINALPRODUCTPHARMACEUTICAL =
      RESOURCE_TYPES.MEDICINALPRODUCTPHARMACEUTICAL$.MODULE$;
  public static final RESOURCE_TYPES MEDICINALPRODUCTUNDESIRABLEEFFECT =
      RESOURCE_TYPES.MEDICINALPRODUCTUNDESIRABLEEFFECT$.MODULE$;
  public static final RESOURCE_TYPES MESSAGEDEFINITION = RESOURCE_TYPES.MESSAGEDEFINITION$.MODULE$;
  public static final RESOURCE_TYPES MESSAGEHEADER = RESOURCE_TYPES.MESSAGEHEADER$.MODULE$;
  public static final RESOURCE_TYPES MOLECULARSEQUENCE = RESOURCE_TYPES.MOLECULARSEQUENCE$.MODULE$;
  public static final RESOURCE_TYPES NAMINGSYSTEM = RESOURCE_TYPES.NAMINGSYSTEM$.MODULE$;
  public static final RESOURCE_TYPES NUTRITIONORDER = RESOURCE_TYPES.NUTRITIONORDER$.MODULE$;
  public static final RESOURCE_TYPES OBSERVATION = RESOURCE_TYPES.OBSERVATION$.MODULE$;
  public static final RESOURCE_TYPES OBSERVATIONDEFINITION =
      RESOURCE_TYPES.OBSERVATIONDEFINITION$.MODULE$;
  public static final RESOURCE_TYPES OPERATIONDEFINITION =
      RESOURCE_TYPES.OPERATIONDEFINITION$.MODULE$;
  public static final RESOURCE_TYPES OPERATIONOUTCOME = RESOURCE_TYPES.OPERATIONOUTCOME$.MODULE$;
  public static final RESOURCE_TYPES ORGANIZATION = RESOURCE_TYPES.ORGANIZATION$.MODULE$;
  public static final RESOURCE_TYPES ORGANIZATIONAFFILIATION =
      RESOURCE_TYPES.ORGANIZATIONAFFILIATION$.MODULE$;
  public static final RESOURCE_TYPES PARAMETERS = RESOURCE_TYPES.PARAMETERS$.MODULE$;
  public static final RESOURCE_TYPES PATIENT = RESOURCE_TYPES.PATIENT$.MODULE$;
  public static final RESOURCE_TYPES PAYMENTNOTICE = RESOURCE_TYPES.PAYMENTNOTICE$.MODULE$;
  public static final RESOURCE_TYPES PAYMENTRECONCILIATION =
      RESOURCE_TYPES.PAYMENTRECONCILIATION$.MODULE$;
  public static final RESOURCE_TYPES PERSON = RESOURCE_TYPES.PERSON$.MODULE$;
  public static final RESOURCE_TYPES PLANDEFINITION = RESOURCE_TYPES.PLANDEFINITION$.MODULE$;
  public static final RESOURCE_TYPES PRACTITIONER = RESOURCE_TYPES.PRACTITIONER$.MODULE$;
  public static final RESOURCE_TYPES PRACTITIONERROLE = RESOURCE_TYPES.PRACTITIONERROLE$.MODULE$;
  public static final RESOURCE_TYPES PROCEDURE = RESOURCE_TYPES.PROCEDURE$.MODULE$;
  public static final RESOURCE_TYPES PROVENANCE = RESOURCE_TYPES.PROVENANCE$.MODULE$;
  public static final RESOURCE_TYPES QUESTIONNAIRE = RESOURCE_TYPES.QUESTIONNAIRE$.MODULE$;
  public static final RESOURCE_TYPES QUESTIONNAIRERESPONSE =
      RESOURCE_TYPES.QUESTIONNAIRERESPONSE$.MODULE$;
  public static final RESOURCE_TYPES RELATEDPERSON = RESOURCE_TYPES.RELATEDPERSON$.MODULE$;
  public static final RESOURCE_TYPES REQUESTGROUP = RESOURCE_TYPES.REQUESTGROUP$.MODULE$;
  public static final RESOURCE_TYPES RESEARCHDEFINITION =
      RESOURCE_TYPES.RESEARCHDEFINITION$.MODULE$;
  public static final RESOURCE_TYPES RESEARCHELEMENTDEFINITION =
      RESOURCE_TYPES.RESEARCHELEMENTDEFINITION$.MODULE$;
  public static final RESOURCE_TYPES RESEARCHSTUDY = RESOURCE_TYPES.RESEARCHSTUDY$.MODULE$;
  public static final RESOURCE_TYPES RESEARCHSUBJECT = RESOURCE_TYPES.RESEARCHSUBJECT$.MODULE$;
  public static final RESOURCE_TYPES RESOURCE = RESOURCE_TYPES.RESOURCE$.MODULE$;
  public static final RESOURCE_TYPES RISKASSESSMENT = RESOURCE_TYPES.RISKASSESSMENT$.MODULE$;
  public static final RESOURCE_TYPES RISKEVIDENCESYNTHESIS =
      RESOURCE_TYPES.RISKEVIDENCESYNTHESIS$.MODULE$;
  public static final RESOURCE_TYPES SCHEDULE = RESOURCE_TYPES.SCHEDULE$.MODULE$;
  public static final RESOURCE_TYPES SEARCHPARAMETER = RESOURCE_TYPES.SEARCHPARAMETER$.MODULE$;
  public static final RESOURCE_TYPES SERVICEREQUEST = RESOURCE_TYPES.SERVICEREQUEST$.MODULE$;
  public static final RESOURCE_TYPES SLOT = RESOURCE_TYPES.SLOT$.MODULE$;
  public static final RESOURCE_TYPES SPECIMEN = RESOURCE_TYPES.SPECIMEN$.MODULE$;
  public static final RESOURCE_TYPES SPECIMENDEFINITION =
      RESOURCE_TYPES.SPECIMENDEFINITION$.MODULE$;
  public static final RESOURCE_TYPES STRUCTUREDEFINITION =
      RESOURCE_TYPES.STRUCTUREDEFINITION$.MODULE$;
  public static final RESOURCE_TYPES STRUCTUREMAP = RESOURCE_TYPES.STRUCTUREMAP$.MODULE$;
  public static final RESOURCE_TYPES SUBSCRIPTION = RESOURCE_TYPES.SUBSCRIPTION$.MODULE$;
  public static final RESOURCE_TYPES SUBSTANCE = RESOURCE_TYPES.SUBSTANCE$.MODULE$;
  public static final RESOURCE_TYPES SUBSTANCENUCLEICACID =
      RESOURCE_TYPES.SUBSTANCENUCLEICACID$.MODULE$;
  public static final RESOURCE_TYPES SUBSTANCEPOLYMER = RESOURCE_TYPES.SUBSTANCEPOLYMER$.MODULE$;
  public static final RESOURCE_TYPES SUBSTANCEPROTEIN = RESOURCE_TYPES.SUBSTANCEPROTEIN$.MODULE$;
  public static final RESOURCE_TYPES SUBSTANCEREFERENCEINFORMATION =
      RESOURCE_TYPES.SUBSTANCEREFERENCEINFORMATION$.MODULE$;
  public static final RESOURCE_TYPES SUBSTANCESOURCEMATERIAL =
      RESOURCE_TYPES.SUBSTANCESOURCEMATERIAL$.MODULE$;
  public static final RESOURCE_TYPES SUBSTANCESPECIFICATION =
      RESOURCE_TYPES.SUBSTANCESPECIFICATION$.MODULE$;
  public static final RESOURCE_TYPES SUPPLYDELIVERY = RESOURCE_TYPES.SUPPLYDELIVERY$.MODULE$;
  public static final RESOURCE_TYPES SUPPLYREQUEST = RESOURCE_TYPES.SUPPLYREQUEST$.MODULE$;
  public static final RESOURCE_TYPES TASK = RESOURCE_TYPES.TASK$.MODULE$;
  public static final RESOURCE_TYPES TERMINOLOGYCAPABILITIES =
      RESOURCE_TYPES.TERMINOLOGYCAPABILITIES$.MODULE$;
  public static final RESOURCE_TYPES TESTREPORT = RESOURCE_TYPES.TESTREPORT$.MODULE$;
  public static final RESOURCE_TYPES TESTSCRIPT = RESOURCE_TYPES.TESTSCRIPT$.MODULE$;
  public static final RESOURCE_TYPES VALUESET = RESOURCE_TYPES.VALUESET$.MODULE$;
  public static final RESOURCE_TYPES VERIFICATIONRESULT =
      RESOURCE_TYPES.VERIFICATIONRESULT$.MODULE$;
  public static final RESOURCE_TYPES VISIONPRESCRIPTION =
      RESOURCE_TYPES.VISIONPRESCRIPTION$.MODULE$;
}
