package com.babylonhealth.lit.hl7_java.codes;

import com.babylonhealth.lit.hl7.SEARCH_MODIFIER_CODE;

public interface SearchModifierCode {
  public static final SEARCH_MODIFIER_CODE ABOVE = SEARCH_MODIFIER_CODE.ABOVE$.MODULE$;
  public static final SEARCH_MODIFIER_CODE BELOW = SEARCH_MODIFIER_CODE.BELOW$.MODULE$;
  public static final SEARCH_MODIFIER_CODE CONTAINS = SEARCH_MODIFIER_CODE.CONTAINS$.MODULE$;
  public static final SEARCH_MODIFIER_CODE EXACT = SEARCH_MODIFIER_CODE.EXACT$.MODULE$;
  public static final SEARCH_MODIFIER_CODE IDENTIFIER = SEARCH_MODIFIER_CODE.IDENTIFIER$.MODULE$;
  public static final SEARCH_MODIFIER_CODE IN = SEARCH_MODIFIER_CODE.IN$.MODULE$;
  public static final SEARCH_MODIFIER_CODE MISSING = SEARCH_MODIFIER_CODE.MISSING$.MODULE$;
  public static final SEARCH_MODIFIER_CODE NOT = SEARCH_MODIFIER_CODE.NOT$.MODULE$;
  public static final SEARCH_MODIFIER_CODE NOT_IN = SEARCH_MODIFIER_CODE.NOT_IN$.MODULE$;
  public static final SEARCH_MODIFIER_CODE OFTYPE = SEARCH_MODIFIER_CODE.OFTYPE$.MODULE$;
  public static final SEARCH_MODIFIER_CODE TEXT = SEARCH_MODIFIER_CODE.TEXT$.MODULE$;
  public static final SEARCH_MODIFIER_CODE TYPE = SEARCH_MODIFIER_CODE.TYPE$.MODULE$;
}
