package com.babylonhealth.lit.hl7_java.codes;

import com.babylonhealth.lit.hl7.SPDX_LICENSE;

public interface SpdxLicense {
  public static final SPDX_LICENSE AAL = SPDX_LICENSE.AAL$.MODULE$;
  public static final SPDX_LICENSE ABSTYLES = SPDX_LICENSE.ABSTYLES$.MODULE$;
  public static final SPDX_LICENSE ACADEMIC_FREE_LICENSE_V1_1 =
      SPDX_LICENSE.ACADEMIC_FREE_LICENSE_V1_1$.MODULE$;
  public static final SPDX_LICENSE ACADEMIC_FREE_LICENSE_V1_2 =
      SPDX_LICENSE.ACADEMIC_FREE_LICENSE_V1_2$.MODULE$;
  public static final SPDX_LICENSE ACADEMIC_FREE_LICENSE_V2_0 =
      SPDX_LICENSE.ACADEMIC_FREE_LICENSE_V2_0$.MODULE$;
  public static final SPDX_LICENSE ACADEMIC_FREE_LICENSE_V2_1 =
      SPDX_LICENSE.ACADEMIC_FREE_LICENSE_V2_1$.MODULE$;
  public static final SPDX_LICENSE ACADEMIC_FREE_LICENSE_V3_0 =
      SPDX_LICENSE.ACADEMIC_FREE_LICENSE_V3_0$.MODULE$;
  public static final SPDX_LICENSE ADAPTIVE_PUBLIC_LICENSE_1_0 =
      SPDX_LICENSE.ADAPTIVE_PUBLIC_LICENSE_1_0$.MODULE$;
  public static final SPDX_LICENSE ADOBE_GLYPH_LIST_LICENSE =
      SPDX_LICENSE.ADOBE_GLYPH_LIST_LICENSE$.MODULE$;
  public static final SPDX_LICENSE ADOBE_SYSTEMS_INCORPORATED_SOURCE_CODE_LICENSE_AGREEMENT =
      SPDX_LICENSE.ADOBE_SYSTEMS_INCORPORATED_SOURCE_CODE_LICENSE_AGREEMENT$.MODULE$;
  public static final SPDX_LICENSE ADSL = SPDX_LICENSE.ADSL$.MODULE$;
  public static final SPDX_LICENSE AFFERO_GENERAL_PUBLIC_LICENSE_V1_0_ONLY =
      SPDX_LICENSE.AFFERO_GENERAL_PUBLIC_LICENSE_V1_0_ONLY$.MODULE$;
  public static final SPDX_LICENSE AFFERO_GENERAL_PUBLIC_LICENSE_V1_0_OR_LATER =
      SPDX_LICENSE.AFFERO_GENERAL_PUBLIC_LICENSE_V1_0_OR_LATER$.MODULE$;
  public static final SPDX_LICENSE AFMPARSE = SPDX_LICENSE.AFMPARSE$.MODULE$;
  public static final SPDX_LICENSE ALADDIN = SPDX_LICENSE.ALADDIN$.MODULE$;
  public static final SPDX_LICENSE AMDPLPA = SPDX_LICENSE.AMDPLPA$.MODULE$;
  public static final SPDX_LICENSE AML = SPDX_LICENSE.AML$.MODULE$;
  public static final SPDX_LICENSE AMPAS = SPDX_LICENSE.AMPAS$.MODULE$;
  public static final SPDX_LICENSE ANTLR_SOFTWARE_RIGHTS_NOTICE =
      SPDX_LICENSE.ANTLR_SOFTWARE_RIGHTS_NOTICE$.MODULE$;
  public static final SPDX_LICENSE APACHE_LICENSE_1_0 = SPDX_LICENSE.APACHE_LICENSE_1_0$.MODULE$;
  public static final SPDX_LICENSE APACHE_LICENSE_1_1 = SPDX_LICENSE.APACHE_LICENSE_1_1$.MODULE$;
  public static final SPDX_LICENSE APACHE_LICENSE_2_0 = SPDX_LICENSE.APACHE_LICENSE_2_0$.MODULE$;
  public static final SPDX_LICENSE APAFML = SPDX_LICENSE.APAFML$.MODULE$;
  public static final SPDX_LICENSE APPLE_PUBLIC_SOURCE_LICENSE_1_0 =
      SPDX_LICENSE.APPLE_PUBLIC_SOURCE_LICENSE_1_0$.MODULE$;
  public static final SPDX_LICENSE APPLE_PUBLIC_SOURCE_LICENSE_1_1 =
      SPDX_LICENSE.APPLE_PUBLIC_SOURCE_LICENSE_1_1$.MODULE$;
  public static final SPDX_LICENSE APPLE_PUBLIC_SOURCE_LICENSE_1_2 =
      SPDX_LICENSE.APPLE_PUBLIC_SOURCE_LICENSE_1_2$.MODULE$;
  public static final SPDX_LICENSE APPLE_PUBLIC_SOURCE_LICENSE_2_0 =
      SPDX_LICENSE.APPLE_PUBLIC_SOURCE_LICENSE_2_0$.MODULE$;
  public static final SPDX_LICENSE ARTISTIC_10_CL8 = SPDX_LICENSE.ARTISTIC_10_CL8$.MODULE$;
  public static final SPDX_LICENSE ARTISTIC_10_PERL = SPDX_LICENSE.ARTISTIC_10_PERL$.MODULE$;
  public static final SPDX_LICENSE ARTISTIC_LICENSE_1_0 =
      SPDX_LICENSE.ARTISTIC_LICENSE_1_0$.MODULE$;
  public static final SPDX_LICENSE ARTISTIC_LICENSE_2_0 =
      SPDX_LICENSE.ARTISTIC_LICENSE_2_0$.MODULE$;
  public static final SPDX_LICENSE BAHYPH = SPDX_LICENSE.BAHYPH$.MODULE$;
  public static final SPDX_LICENSE BARR = SPDX_LICENSE.BARR$.MODULE$;
  public static final SPDX_LICENSE BEERWARE = SPDX_LICENSE.BEERWARE$.MODULE$;
  public static final SPDX_LICENSE BITTORRENT_OPEN_SOURCE_LICENSE_V1_0 =
      SPDX_LICENSE.BITTORRENT_OPEN_SOURCE_LICENSE_V1_0$.MODULE$;
  public static final SPDX_LICENSE BITTORRENT_OPEN_SOURCE_LICENSE_V1_1 =
      SPDX_LICENSE.BITTORRENT_OPEN_SOURCE_LICENSE_V1_1$.MODULE$;
  public static final SPDX_LICENSE BOOST_SOFTWARE_LICENSE_1_0 =
      SPDX_LICENSE.BOOST_SOFTWARE_LICENSE_1_0$.MODULE$;
  public static final SPDX_LICENSE BORCEUX = SPDX_LICENSE.BORCEUX$.MODULE$;
  public static final SPDX_LICENSE BSD_1_CLAUSE_LICENSE =
      SPDX_LICENSE.BSD_1_CLAUSE_LICENSE$.MODULE$;
  public static final SPDX_LICENSE BSD_2_CLAUSE = SPDX_LICENSE.BSD_2_CLAUSE$.MODULE$;
  public static final SPDX_LICENSE BSD_2_CLAUSE_FREEBSD_LICENSE =
      SPDX_LICENSE.BSD_2_CLAUSE_FREEBSD_LICENSE$.MODULE$;
  public static final SPDX_LICENSE BSD_2_CLAUSE_NETBSD_LICENSE =
      SPDX_LICENSE.BSD_2_CLAUSE_NETBSD_LICENSE$.MODULE$;
  public static final SPDX_LICENSE BSD_2_CLAUSE_PLUS_PATENT_LICENSE =
      SPDX_LICENSE.BSD_2_CLAUSE_PLUS_PATENT_LICENSE$.MODULE$;
  public static final SPDX_LICENSE BSD_3_CLAUSE = SPDX_LICENSE.BSD_3_CLAUSE$.MODULE$;
  public static final SPDX_LICENSE BSD_3_CLAUSE_CLEAR_LICENSE =
      SPDX_LICENSE.BSD_3_CLAUSE_CLEAR_LICENSE$.MODULE$;
  public static final SPDX_LICENSE BSD_3_CLAUSE_NO_NUCLEAR_LICENSE =
      SPDX_LICENSE.BSD_3_CLAUSE_NO_NUCLEAR_LICENSE$.MODULE$;
  public static final SPDX_LICENSE BSD_3_CLAUSE_NO_NUCLEAR_LICENSE_2014 =
      SPDX_LICENSE.BSD_3_CLAUSE_NO_NUCLEAR_LICENSE_2014$.MODULE$;
  public static final SPDX_LICENSE BSD_3_CLAUSE_NO_NUCLEAR_WARRANTY =
      SPDX_LICENSE.BSD_3_CLAUSE_NO_NUCLEAR_WARRANTY$.MODULE$;
  public static final SPDX_LICENSE BSD_4_CLAUSE = SPDX_LICENSE.BSD_4_CLAUSE$.MODULE$;
  public static final SPDX_LICENSE BSD_4_CLAUSE_UC = SPDX_LICENSE.BSD_4_CLAUSE_UC$.MODULE$;
  public static final SPDX_LICENSE BSD_PROTECTION_LICENSE =
      SPDX_LICENSE.BSD_PROTECTION_LICENSE$.MODULE$;
  public static final SPDX_LICENSE BSD_SOURCE_CODE_ATTRIBUTION =
      SPDX_LICENSE.BSD_SOURCE_CODE_ATTRIBUTION$.MODULE$;
  public static final SPDX_LICENSE BSD_WITH_ATTRIBUTION =
      SPDX_LICENSE.BSD_WITH_ATTRIBUTION$.MODULE$;
  public static final SPDX_LICENSE BSD_ZERO_CLAUSE_LICENSE =
      SPDX_LICENSE.BSD_ZERO_CLAUSE_LICENSE$.MODULE$;
  public static final SPDX_LICENSE BZIP2_AND_LIBBZIP2_LICENSE_V1_0_5 =
      SPDX_LICENSE.BZIP2_AND_LIBBZIP2_LICENSE_V1_0_5$.MODULE$;
  public static final SPDX_LICENSE BZIP2_AND_LIBBZIP2_LICENSE_V1_0_6 =
      SPDX_LICENSE.BZIP2_AND_LIBBZIP2_LICENSE_V1_0_6$.MODULE$;
  public static final SPDX_LICENSE CALDERA = SPDX_LICENSE.CALDERA$.MODULE$;
  public static final SPDX_LICENSE CECILL_B_FREE_SOFTWARE_LICENSE_AGREEMENT =
      SPDX_LICENSE.CECILL_B_FREE_SOFTWARE_LICENSE_AGREEMENT$.MODULE$;
  public static final SPDX_LICENSE CECILL_C_FREE_SOFTWARE_LICENSE_AGREEMENT =
      SPDX_LICENSE.CECILL_C_FREE_SOFTWARE_LICENSE_AGREEMENT$.MODULE$;
  public static final SPDX_LICENSE CECILL_FREE_SOFTWARE_LICENSE_AGREEMENT_V1_0 =
      SPDX_LICENSE.CECILL_FREE_SOFTWARE_LICENSE_AGREEMENT_V1_0$.MODULE$;
  public static final SPDX_LICENSE CECILL_FREE_SOFTWARE_LICENSE_AGREEMENT_V1_1 =
      SPDX_LICENSE.CECILL_FREE_SOFTWARE_LICENSE_AGREEMENT_V1_1$.MODULE$;
  public static final SPDX_LICENSE CECILL_FREE_SOFTWARE_LICENSE_AGREEMENT_V2_0 =
      SPDX_LICENSE.CECILL_FREE_SOFTWARE_LICENSE_AGREEMENT_V2_0$.MODULE$;
  public static final SPDX_LICENSE CECILL_FREE_SOFTWARE_LICENSE_AGREEMENT_V2_1 =
      SPDX_LICENSE.CECILL_FREE_SOFTWARE_LICENSE_AGREEMENT_V2_1$.MODULE$;
  public static final SPDX_LICENSE CLARTISTIC = SPDX_LICENSE.CLARTISTIC$.MODULE$;
  public static final SPDX_LICENSE CMU_LICENSE = SPDX_LICENSE.CMU_LICENSE$.MODULE$;
  public static final SPDX_LICENSE CNRI_JYTHON_LICENSE = SPDX_LICENSE.CNRI_JYTHON_LICENSE$.MODULE$;
  public static final SPDX_LICENSE CNRI_PYTHON_LICENSE = SPDX_LICENSE.CNRI_PYTHON_LICENSE$.MODULE$;
  public static final SPDX_LICENSE CNRI_PYTHON_OPEN_SOURCE_GPL_COMPATIBLE_LICENSE_AGREEMENT =
      SPDX_LICENSE.CNRI_PYTHON_OPEN_SOURCE_GPL_COMPATIBLE_LICENSE_AGREEMENT$.MODULE$;
  public static final SPDX_LICENSE CODE_PROJECT_OPEN_LICENSE_1_02 =
      SPDX_LICENSE.CODE_PROJECT_OPEN_LICENSE_1_02$.MODULE$;
  public static final SPDX_LICENSE COMMON_DEVELOPMENT_AND_DISTRIBUTION_LICENSE_1_0 =
      SPDX_LICENSE.COMMON_DEVELOPMENT_AND_DISTRIBUTION_LICENSE_1_0$.MODULE$;
  public static final SPDX_LICENSE COMMON_DEVELOPMENT_AND_DISTRIBUTION_LICENSE_1_1 =
      SPDX_LICENSE.COMMON_DEVELOPMENT_AND_DISTRIBUTION_LICENSE_1_1$.MODULE$;
  public static final SPDX_LICENSE COMMON_PUBLIC_ATTRIBUTION_LICENSE_1_0 =
      SPDX_LICENSE.COMMON_PUBLIC_ATTRIBUTION_LICENSE_1_0$.MODULE$;
  public static final SPDX_LICENSE COMMON_PUBLIC_LICENSE_1_0 =
      SPDX_LICENSE.COMMON_PUBLIC_LICENSE_1_0$.MODULE$;
  public static final SPDX_LICENSE COMMUNITY_DATA_LICENSE_AGREEMENT_PERMISSIVE_1_0 =
      SPDX_LICENSE.COMMUNITY_DATA_LICENSE_AGREEMENT_PERMISSIVE_1_0$.MODULE$;
  public static final SPDX_LICENSE COMMUNITY_DATA_LICENSE_AGREEMENT_SHARING_1_0 =
      SPDX_LICENSE.COMMUNITY_DATA_LICENSE_AGREEMENT_SHARING_1_0$.MODULE$;
  public static final SPDX_LICENSE COMPUTER_ASSOCIATES_TRUSTED_OPEN_SOURCE_LICENSE_1_1 =
      SPDX_LICENSE.COMPUTER_ASSOCIATES_TRUSTED_OPEN_SOURCE_LICENSE_1_1$.MODULE$;
  public static final SPDX_LICENSE CONDOR_PUBLIC_LICENSE_V1_1 =
      SPDX_LICENSE.CONDOR_PUBLIC_LICENSE_V1_1$.MODULE$;
  public static final SPDX_LICENSE CREATIVE_COMMONS_ATTRIBUTION_1_0_GENERIC =
      SPDX_LICENSE.CREATIVE_COMMONS_ATTRIBUTION_1_0_GENERIC$.MODULE$;
  public static final SPDX_LICENSE CREATIVE_COMMONS_ATTRIBUTION_2_0_GENERIC =
      SPDX_LICENSE.CREATIVE_COMMONS_ATTRIBUTION_2_0_GENERIC$.MODULE$;
  public static final SPDX_LICENSE CREATIVE_COMMONS_ATTRIBUTION_2_5_GENERIC =
      SPDX_LICENSE.CREATIVE_COMMONS_ATTRIBUTION_2_5_GENERIC$.MODULE$;
  public static final SPDX_LICENSE CREATIVE_COMMONS_ATTRIBUTION_3_0_UNPORTED =
      SPDX_LICENSE.CREATIVE_COMMONS_ATTRIBUTION_3_0_UNPORTED$.MODULE$;
  public static final SPDX_LICENSE CREATIVE_COMMONS_ATTRIBUTION_4_0_INTERNATIONAL =
      SPDX_LICENSE.CREATIVE_COMMONS_ATTRIBUTION_4_0_INTERNATIONAL$.MODULE$;
  public static final SPDX_LICENSE CREATIVE_COMMONS_ATTRIBUTION_NON_COMMERCIAL_1_0_GENERIC =
      SPDX_LICENSE.CREATIVE_COMMONS_ATTRIBUTION_NON_COMMERCIAL_1_0_GENERIC$.MODULE$;
  public static final SPDX_LICENSE CREATIVE_COMMONS_ATTRIBUTION_NON_COMMERCIAL_2_0_GENERIC =
      SPDX_LICENSE.CREATIVE_COMMONS_ATTRIBUTION_NON_COMMERCIAL_2_0_GENERIC$.MODULE$;
  public static final SPDX_LICENSE CREATIVE_COMMONS_ATTRIBUTION_NON_COMMERCIAL_2_5_GENERIC =
      SPDX_LICENSE.CREATIVE_COMMONS_ATTRIBUTION_NON_COMMERCIAL_2_5_GENERIC$.MODULE$;
  public static final SPDX_LICENSE CREATIVE_COMMONS_ATTRIBUTION_NON_COMMERCIAL_3_0_UNPORTED =
      SPDX_LICENSE.CREATIVE_COMMONS_ATTRIBUTION_NON_COMMERCIAL_3_0_UNPORTED$.MODULE$;
  public static final SPDX_LICENSE CREATIVE_COMMONS_ATTRIBUTION_NON_COMMERCIAL_4_0_INTERNATIONAL =
      SPDX_LICENSE.CREATIVE_COMMONS_ATTRIBUTION_NON_COMMERCIAL_4_0_INTERNATIONAL$.MODULE$;
  public static final SPDX_LICENSE
      CREATIVE_COMMONS_ATTRIBUTION_NON_COMMERCIAL_NO_DERIVATIVES_1_0_GENERIC =
          SPDX_LICENSE
              .CREATIVE_COMMONS_ATTRIBUTION_NON_COMMERCIAL_NO_DERIVATIVES_1_0_GENERIC$
              .MODULE$;
  public static final SPDX_LICENSE
      CREATIVE_COMMONS_ATTRIBUTION_NON_COMMERCIAL_NO_DERIVATIVES_2_0_GENERIC =
          SPDX_LICENSE
              .CREATIVE_COMMONS_ATTRIBUTION_NON_COMMERCIAL_NO_DERIVATIVES_2_0_GENERIC$
              .MODULE$;
  public static final SPDX_LICENSE
      CREATIVE_COMMONS_ATTRIBUTION_NON_COMMERCIAL_NO_DERIVATIVES_2_5_GENERIC =
          SPDX_LICENSE
              .CREATIVE_COMMONS_ATTRIBUTION_NON_COMMERCIAL_NO_DERIVATIVES_2_5_GENERIC$
              .MODULE$;
  public static final SPDX_LICENSE
      CREATIVE_COMMONS_ATTRIBUTION_NON_COMMERCIAL_NO_DERIVATIVES_3_0_UNPORTED =
          SPDX_LICENSE
              .CREATIVE_COMMONS_ATTRIBUTION_NON_COMMERCIAL_NO_DERIVATIVES_3_0_UNPORTED$
              .MODULE$;
  public static final SPDX_LICENSE
      CREATIVE_COMMONS_ATTRIBUTION_NON_COMMERCIAL_NO_DERIVATIVES_4_0_INTERNATIONAL =
          SPDX_LICENSE
              .CREATIVE_COMMONS_ATTRIBUTION_NON_COMMERCIAL_NO_DERIVATIVES_4_0_INTERNATIONAL$
              .MODULE$;
  public static final SPDX_LICENSE
      CREATIVE_COMMONS_ATTRIBUTION_NON_COMMERCIAL_SHARE_ALIKE_1_0_GENERIC =
          SPDX_LICENSE.CREATIVE_COMMONS_ATTRIBUTION_NON_COMMERCIAL_SHARE_ALIKE_1_0_GENERIC$.MODULE$;
  public static final SPDX_LICENSE
      CREATIVE_COMMONS_ATTRIBUTION_NON_COMMERCIAL_SHARE_ALIKE_2_0_GENERIC =
          SPDX_LICENSE.CREATIVE_COMMONS_ATTRIBUTION_NON_COMMERCIAL_SHARE_ALIKE_2_0_GENERIC$.MODULE$;
  public static final SPDX_LICENSE
      CREATIVE_COMMONS_ATTRIBUTION_NON_COMMERCIAL_SHARE_ALIKE_2_5_GENERIC =
          SPDX_LICENSE.CREATIVE_COMMONS_ATTRIBUTION_NON_COMMERCIAL_SHARE_ALIKE_2_5_GENERIC$.MODULE$;
  public static final SPDX_LICENSE
      CREATIVE_COMMONS_ATTRIBUTION_NON_COMMERCIAL_SHARE_ALIKE_3_0_UNPORTED =
          SPDX_LICENSE
              .CREATIVE_COMMONS_ATTRIBUTION_NON_COMMERCIAL_SHARE_ALIKE_3_0_UNPORTED$
              .MODULE$;
  public static final SPDX_LICENSE
      CREATIVE_COMMONS_ATTRIBUTION_NON_COMMERCIAL_SHARE_ALIKE_4_0_INTERNATIONAL =
          SPDX_LICENSE
              .CREATIVE_COMMONS_ATTRIBUTION_NON_COMMERCIAL_SHARE_ALIKE_4_0_INTERNATIONAL$
              .MODULE$;
  public static final SPDX_LICENSE CREATIVE_COMMONS_ATTRIBUTION_NO_DERIVATIVES_1_0_GENERIC =
      SPDX_LICENSE.CREATIVE_COMMONS_ATTRIBUTION_NO_DERIVATIVES_1_0_GENERIC$.MODULE$;
  public static final SPDX_LICENSE CREATIVE_COMMONS_ATTRIBUTION_NO_DERIVATIVES_2_0_GENERIC =
      SPDX_LICENSE.CREATIVE_COMMONS_ATTRIBUTION_NO_DERIVATIVES_2_0_GENERIC$.MODULE$;
  public static final SPDX_LICENSE CREATIVE_COMMONS_ATTRIBUTION_NO_DERIVATIVES_2_5_GENERIC =
      SPDX_LICENSE.CREATIVE_COMMONS_ATTRIBUTION_NO_DERIVATIVES_2_5_GENERIC$.MODULE$;
  public static final SPDX_LICENSE CREATIVE_COMMONS_ATTRIBUTION_NO_DERIVATIVES_3_0_UNPORTED =
      SPDX_LICENSE.CREATIVE_COMMONS_ATTRIBUTION_NO_DERIVATIVES_3_0_UNPORTED$.MODULE$;
  public static final SPDX_LICENSE CREATIVE_COMMONS_ATTRIBUTION_NO_DERIVATIVES_4_0_INTERNATIONAL =
      SPDX_LICENSE.CREATIVE_COMMONS_ATTRIBUTION_NO_DERIVATIVES_4_0_INTERNATIONAL$.MODULE$;
  public static final SPDX_LICENSE CREATIVE_COMMONS_ATTRIBUTION_SHARE_ALIKE_1_0_GENERIC =
      SPDX_LICENSE.CREATIVE_COMMONS_ATTRIBUTION_SHARE_ALIKE_1_0_GENERIC$.MODULE$;
  public static final SPDX_LICENSE CREATIVE_COMMONS_ATTRIBUTION_SHARE_ALIKE_2_0_GENERIC =
      SPDX_LICENSE.CREATIVE_COMMONS_ATTRIBUTION_SHARE_ALIKE_2_0_GENERIC$.MODULE$;
  public static final SPDX_LICENSE CREATIVE_COMMONS_ATTRIBUTION_SHARE_ALIKE_2_5_GENERIC =
      SPDX_LICENSE.CREATIVE_COMMONS_ATTRIBUTION_SHARE_ALIKE_2_5_GENERIC$.MODULE$;
  public static final SPDX_LICENSE CREATIVE_COMMONS_ATTRIBUTION_SHARE_ALIKE_3_0_UNPORTED =
      SPDX_LICENSE.CREATIVE_COMMONS_ATTRIBUTION_SHARE_ALIKE_3_0_UNPORTED$.MODULE$;
  public static final SPDX_LICENSE CREATIVE_COMMONS_ATTRIBUTION_SHARE_ALIKE_4_0_INTERNATIONAL =
      SPDX_LICENSE.CREATIVE_COMMONS_ATTRIBUTION_SHARE_ALIKE_4_0_INTERNATIONAL$.MODULE$;
  public static final SPDX_LICENSE CREATIVE_COMMONS_ZERO_V1_0_UNIVERSAL =
      SPDX_LICENSE.CREATIVE_COMMONS_ZERO_V1_0_UNIVERSAL$.MODULE$;
  public static final SPDX_LICENSE CROSSWORD = SPDX_LICENSE.CROSSWORD$.MODULE$;
  public static final SPDX_LICENSE CRYSTALSTACKER = SPDX_LICENSE.CRYSTALSTACKER$.MODULE$;
  public static final SPDX_LICENSE CUA_OFFICE_PUBLIC_LICENSE_V1_0 =
      SPDX_LICENSE.CUA_OFFICE_PUBLIC_LICENSE_V1_0$.MODULE$;
  public static final SPDX_LICENSE CUBE = SPDX_LICENSE.CUBE$.MODULE$;
  public static final SPDX_LICENSE CURL = SPDX_LICENSE.CURL$.MODULE$;
  public static final SPDX_LICENSE DEUTSCHE_FREIE_SOFTWARE_LIZENZ =
      SPDX_LICENSE.DEUTSCHE_FREIE_SOFTWARE_LIZENZ$.MODULE$;
  public static final SPDX_LICENSE DIFFMARK = SPDX_LICENSE.DIFFMARK$.MODULE$;
  public static final SPDX_LICENSE DOC = SPDX_LICENSE.DOC$.MODULE$;
  public static final SPDX_LICENSE DOTSEQN = SPDX_LICENSE.DOTSEQN$.MODULE$;
  public static final SPDX_LICENSE DSDP = SPDX_LICENSE.DSDP$.MODULE$;
  public static final SPDX_LICENSE DVIPDFM = SPDX_LICENSE.DVIPDFM$.MODULE$;
  public static final SPDX_LICENSE ECLIPSE_PUBLIC_LICENSE_1_0 =
      SPDX_LICENSE.ECLIPSE_PUBLIC_LICENSE_1_0$.MODULE$;
  public static final SPDX_LICENSE ECLIPSE_PUBLIC_LICENSE_2_0 =
      SPDX_LICENSE.ECLIPSE_PUBLIC_LICENSE_2_0$.MODULE$;
  public static final SPDX_LICENSE EDUCATIONAL_COMMUNITY_LICENSE_V1_0 =
      SPDX_LICENSE.EDUCATIONAL_COMMUNITY_LICENSE_V1_0$.MODULE$;
  public static final SPDX_LICENSE EDUCATIONAL_COMMUNITY_LICENSE_V2_0 =
      SPDX_LICENSE.EDUCATIONAL_COMMUNITY_LICENSE_V2_0$.MODULE$;
  public static final SPDX_LICENSE EGENIX = SPDX_LICENSE.EGENIX$.MODULE$;
  public static final SPDX_LICENSE EIFFEL_FORUM_LICENSE_V1_0 =
      SPDX_LICENSE.EIFFEL_FORUM_LICENSE_V1_0$.MODULE$;
  public static final SPDX_LICENSE EIFFEL_FORUM_LICENSE_V2_0 =
      SPDX_LICENSE.EIFFEL_FORUM_LICENSE_V2_0$.MODULE$;
  public static final SPDX_LICENSE ENNA_LICENSE = SPDX_LICENSE.ENNA_LICENSE$.MODULE$;
  public static final SPDX_LICENSE ENTESSA = SPDX_LICENSE.ENTESSA$.MODULE$;
  public static final SPDX_LICENSE ERLANG_PUBLIC_LICENSE_V1_1 =
      SPDX_LICENSE.ERLANG_PUBLIC_LICENSE_V1_1$.MODULE$;
  public static final SPDX_LICENSE EUDATAGRID = SPDX_LICENSE.EUDATAGRID$.MODULE$;
  public static final SPDX_LICENSE EUROPEAN_UNION_PUBLIC_LICENSE_1_0 =
      SPDX_LICENSE.EUROPEAN_UNION_PUBLIC_LICENSE_1_0$.MODULE$;
  public static final SPDX_LICENSE EUROPEAN_UNION_PUBLIC_LICENSE_1_1 =
      SPDX_LICENSE.EUROPEAN_UNION_PUBLIC_LICENSE_1_1$.MODULE$;
  public static final SPDX_LICENSE EUROPEAN_UNION_PUBLIC_LICENSE_1_2 =
      SPDX_LICENSE.EUROPEAN_UNION_PUBLIC_LICENSE_1_2$.MODULE$;
  public static final SPDX_LICENSE EUROSYM = SPDX_LICENSE.EUROSYM$.MODULE$;
  public static final SPDX_LICENSE FAIR = SPDX_LICENSE.FAIR$.MODULE$;
  public static final SPDX_LICENSE FEH_LICENSE = SPDX_LICENSE.FEH_LICENSE$.MODULE$;
  public static final SPDX_LICENSE FRAMEWORX_OPEN_LICENSE_1_0 =
      SPDX_LICENSE.FRAMEWORX_OPEN_LICENSE_1_0$.MODULE$;
  public static final SPDX_LICENSE FREEIMAGE = SPDX_LICENSE.FREEIMAGE$.MODULE$;
  public static final SPDX_LICENSE FSFAP = SPDX_LICENSE.FSFAP$.MODULE$;
  public static final SPDX_LICENSE FSFUL = SPDX_LICENSE.FSFUL$.MODULE$;
  public static final SPDX_LICENSE FSFULLR = SPDX_LICENSE.FSFULLR$.MODULE$;
  public static final SPDX_LICENSE FTL = SPDX_LICENSE.FTL$.MODULE$;
  public static final SPDX_LICENSE GIFTWARE = SPDX_LICENSE.GIFTWARE$.MODULE$;
  public static final SPDX_LICENSE GL2PS = SPDX_LICENSE.GL2PS$.MODULE$;
  public static final SPDX_LICENSE GLIDE = SPDX_LICENSE.GLIDE$.MODULE$;
  public static final SPDX_LICENSE GLULXE = SPDX_LICENSE.GLULXE$.MODULE$;
  public static final SPDX_LICENSE GNUPLOT = SPDX_LICENSE.GNUPLOT$.MODULE$;
  public static final SPDX_LICENSE GNU_AFFERO_GENERAL_PUBLIC_LICENSE_V3_0_ONLY =
      SPDX_LICENSE.GNU_AFFERO_GENERAL_PUBLIC_LICENSE_V3_0_ONLY$.MODULE$;
  public static final SPDX_LICENSE GNU_AFFERO_GENERAL_PUBLIC_LICENSE_V3_0_OR_LATER =
      SPDX_LICENSE.GNU_AFFERO_GENERAL_PUBLIC_LICENSE_V3_0_OR_LATER$.MODULE$;
  public static final SPDX_LICENSE GNU_FREE_DOCUMENTATION_LICENSE_V1_1_ONLY =
      SPDX_LICENSE.GNU_FREE_DOCUMENTATION_LICENSE_V1_1_ONLY$.MODULE$;
  public static final SPDX_LICENSE GNU_FREE_DOCUMENTATION_LICENSE_V1_1_OR_LATER =
      SPDX_LICENSE.GNU_FREE_DOCUMENTATION_LICENSE_V1_1_OR_LATER$.MODULE$;
  public static final SPDX_LICENSE GNU_FREE_DOCUMENTATION_LICENSE_V1_2_ONLY =
      SPDX_LICENSE.GNU_FREE_DOCUMENTATION_LICENSE_V1_2_ONLY$.MODULE$;
  public static final SPDX_LICENSE GNU_FREE_DOCUMENTATION_LICENSE_V1_2_OR_LATER =
      SPDX_LICENSE.GNU_FREE_DOCUMENTATION_LICENSE_V1_2_OR_LATER$.MODULE$;
  public static final SPDX_LICENSE GNU_FREE_DOCUMENTATION_LICENSE_V1_3_ONLY =
      SPDX_LICENSE.GNU_FREE_DOCUMENTATION_LICENSE_V1_3_ONLY$.MODULE$;
  public static final SPDX_LICENSE GNU_FREE_DOCUMENTATION_LICENSE_V1_3_OR_LATER =
      SPDX_LICENSE.GNU_FREE_DOCUMENTATION_LICENSE_V1_3_OR_LATER$.MODULE$;
  public static final SPDX_LICENSE GNU_GENERAL_PUBLIC_LICENSE_V1_0_ONLY =
      SPDX_LICENSE.GNU_GENERAL_PUBLIC_LICENSE_V1_0_ONLY$.MODULE$;
  public static final SPDX_LICENSE GNU_GENERAL_PUBLIC_LICENSE_V1_0_OR_LATER =
      SPDX_LICENSE.GNU_GENERAL_PUBLIC_LICENSE_V1_0_OR_LATER$.MODULE$;
  public static final SPDX_LICENSE GNU_GENERAL_PUBLIC_LICENSE_V2_0_ONLY =
      SPDX_LICENSE.GNU_GENERAL_PUBLIC_LICENSE_V2_0_ONLY$.MODULE$;
  public static final SPDX_LICENSE GNU_GENERAL_PUBLIC_LICENSE_V2_0_OR_LATER =
      SPDX_LICENSE.GNU_GENERAL_PUBLIC_LICENSE_V2_0_OR_LATER$.MODULE$;
  public static final SPDX_LICENSE GNU_GENERAL_PUBLIC_LICENSE_V3_0_ONLY =
      SPDX_LICENSE.GNU_GENERAL_PUBLIC_LICENSE_V3_0_ONLY$.MODULE$;
  public static final SPDX_LICENSE GNU_GENERAL_PUBLIC_LICENSE_V3_0_OR_LATER =
      SPDX_LICENSE.GNU_GENERAL_PUBLIC_LICENSE_V3_0_OR_LATER$.MODULE$;
  public static final SPDX_LICENSE GNU_LESSER_GENERAL_PUBLIC_LICENSE_V2_1_ONLY =
      SPDX_LICENSE.GNU_LESSER_GENERAL_PUBLIC_LICENSE_V2_1_ONLY$.MODULE$;
  public static final SPDX_LICENSE GNU_LESSER_GENERAL_PUBLIC_LICENSE_V2_1_OR_LATER =
      SPDX_LICENSE.GNU_LESSER_GENERAL_PUBLIC_LICENSE_V2_1_OR_LATER$.MODULE$;
  public static final SPDX_LICENSE GNU_LESSER_GENERAL_PUBLIC_LICENSE_V3_0_ONLY =
      SPDX_LICENSE.GNU_LESSER_GENERAL_PUBLIC_LICENSE_V3_0_ONLY$.MODULE$;
  public static final SPDX_LICENSE GNU_LESSER_GENERAL_PUBLIC_LICENSE_V3_0_OR_LATER =
      SPDX_LICENSE.GNU_LESSER_GENERAL_PUBLIC_LICENSE_V3_0_OR_LATER$.MODULE$;
  public static final SPDX_LICENSE GNU_LIBRARY_GENERAL_PUBLIC_LICENSE_V2_ONLY =
      SPDX_LICENSE.GNU_LIBRARY_GENERAL_PUBLIC_LICENSE_V2_ONLY$.MODULE$;
  public static final SPDX_LICENSE GNU_LIBRARY_GENERAL_PUBLIC_LICENSE_V2_OR_LATER =
      SPDX_LICENSE.GNU_LIBRARY_GENERAL_PUBLIC_LICENSE_V2_OR_LATER$.MODULE$;
  public static final SPDX_LICENSE GSOAP_PUBLIC_LICENSE_V1_3B =
      SPDX_LICENSE.GSOAP_PUBLIC_LICENSE_V1_3B$.MODULE$;
  public static final SPDX_LICENSE HASKELLREPORT = SPDX_LICENSE.HASKELLREPORT$.MODULE$;
  public static final SPDX_LICENSE HPND = SPDX_LICENSE.HPND$.MODULE$;
  public static final SPDX_LICENSE IBM_POWERPC_INITIALIZATION_AND_BOOT_SOFTWARE =
      SPDX_LICENSE.IBM_POWERPC_INITIALIZATION_AND_BOOT_SOFTWARE$.MODULE$;
  public static final SPDX_LICENSE IBM_PUBLIC_LICENSE_V1_0 =
      SPDX_LICENSE.IBM_PUBLIC_LICENSE_V1_0$.MODULE$;
  public static final SPDX_LICENSE ICU = SPDX_LICENSE.ICU$.MODULE$;
  public static final SPDX_LICENSE IJG = SPDX_LICENSE.IJG$.MODULE$;
  public static final SPDX_LICENSE IMAGEMAGICK = SPDX_LICENSE.IMAGEMAGICK$.MODULE$;
  public static final SPDX_LICENSE IMATIX = SPDX_LICENSE.IMATIX$.MODULE$;
  public static final SPDX_LICENSE IMLIB2 = SPDX_LICENSE.IMLIB2$.MODULE$;
  public static final SPDX_LICENSE INFO_ZIP_LICENSE = SPDX_LICENSE.INFO_ZIP_LICENSE$.MODULE$;
  public static final SPDX_LICENSE INTEL = SPDX_LICENSE.INTEL$.MODULE$;
  public static final SPDX_LICENSE INTEL_ACPI_SOFTWARE_LICENSE_AGREEMENT =
      SPDX_LICENSE.INTEL_ACPI_SOFTWARE_LICENSE_AGREEMENT$.MODULE$;
  public static final SPDX_LICENSE INTERBASE_PUBLIC_LICENSE_V1_0 =
      SPDX_LICENSE.INTERBASE_PUBLIC_LICENSE_V1_0$.MODULE$;
  public static final SPDX_LICENSE IPA = SPDX_LICENSE.IPA$.MODULE$;
  public static final SPDX_LICENSE ISC = SPDX_LICENSE.ISC$.MODULE$;
  public static final SPDX_LICENSE JASPER_LICENSE = SPDX_LICENSE.JASPER_LICENSE$.MODULE$;
  public static final SPDX_LICENSE JSON = SPDX_LICENSE.JSON$.MODULE$;
  public static final SPDX_LICENSE LATEX2E = SPDX_LICENSE.LATEX2E$.MODULE$;
  public static final SPDX_LICENSE LATEX_PROJECT_PUBLIC_LICENSE_V1_0 =
      SPDX_LICENSE.LATEX_PROJECT_PUBLIC_LICENSE_V1_0$.MODULE$;
  public static final SPDX_LICENSE LATEX_PROJECT_PUBLIC_LICENSE_V1_1 =
      SPDX_LICENSE.LATEX_PROJECT_PUBLIC_LICENSE_V1_1$.MODULE$;
  public static final SPDX_LICENSE LATEX_PROJECT_PUBLIC_LICENSE_V1_2 =
      SPDX_LICENSE.LATEX_PROJECT_PUBLIC_LICENSE_V1_2$.MODULE$;
  public static final SPDX_LICENSE LATEX_PROJECT_PUBLIC_LICENSE_V1_3A =
      SPDX_LICENSE.LATEX_PROJECT_PUBLIC_LICENSE_V1_3A$.MODULE$;
  public static final SPDX_LICENSE LATEX_PROJECT_PUBLIC_LICENSE_V1_3C =
      SPDX_LICENSE.LATEX_PROJECT_PUBLIC_LICENSE_V1_3C$.MODULE$;
  public static final SPDX_LICENSE LAWRENCE_BERKELEY_NATIONAL_LABS_BSD_VARIANT_LICENSE =
      SPDX_LICENSE.LAWRENCE_BERKELEY_NATIONAL_LABS_BSD_VARIANT_LICENSE$.MODULE$;
  public static final SPDX_LICENSE LEPTONICA = SPDX_LICENSE.LEPTONICA$.MODULE$;
  public static final SPDX_LICENSE LGPLLR = SPDX_LICENSE.LGPLLR$.MODULE$;
  public static final SPDX_LICENSE LIBPNG = SPDX_LICENSE.LIBPNG$.MODULE$;
  public static final SPDX_LICENSE LIBTIFF = SPDX_LICENSE.LIBTIFF$.MODULE$;
  public static final SPDX_LICENSE LICENCE_ART_LIBRE_1_2 =
      SPDX_LICENSE.LICENCE_ART_LIBRE_1_2$.MODULE$;
  public static final SPDX_LICENSE LICENCE_ART_LIBRE_1_3 =
      SPDX_LICENSE.LICENCE_ART_LIBRE_1_3$.MODULE$;
  public static final SPDX_LICENSE LILIQ_P_11 = SPDX_LICENSE.LILIQ_P_11$.MODULE$;
  public static final SPDX_LICENSE LILIQ_RPLUS_11 = SPDX_LICENSE.LILIQ_RPLUS_11$.MODULE$;
  public static final SPDX_LICENSE LILIQ_R_11 = SPDX_LICENSE.LILIQ_R_11$.MODULE$;
  public static final SPDX_LICENSE LINUX_KERNEL_VARIANT_OF_OPENIB_ORG_LICENSE =
      SPDX_LICENSE.LINUX_KERNEL_VARIANT_OF_OPENIB_ORG_LICENSE$.MODULE$;
  public static final SPDX_LICENSE LUCENT_PUBLIC_LICENSE_V1_02 =
      SPDX_LICENSE.LUCENT_PUBLIC_LICENSE_V1_02$.MODULE$;
  public static final SPDX_LICENSE LUCENT_PUBLIC_LICENSE_VERSION_1_0 =
      SPDX_LICENSE.LUCENT_PUBLIC_LICENSE_VERSION_1_0$.MODULE$;
  public static final SPDX_LICENSE MAKEINDEX = SPDX_LICENSE.MAKEINDEX$.MODULE$;
  public static final SPDX_LICENSE MICROSOFT_PUBLIC_LICENSE =
      SPDX_LICENSE.MICROSOFT_PUBLIC_LICENSE$.MODULE$;
  public static final SPDX_LICENSE MICROSOFT_RECIPROCAL_LICENSE =
      SPDX_LICENSE.MICROSOFT_RECIPROCAL_LICENSE$.MODULE$;
  public static final SPDX_LICENSE MIROS = SPDX_LICENSE.MIROS$.MODULE$;
  public static final SPDX_LICENSE MIT = SPDX_LICENSE.MIT$.MODULE$;
  public static final SPDX_LICENSE MITNFA = SPDX_LICENSE.MITNFA$.MODULE$;
  public static final SPDX_LICENSE MIT_ADVERTISING = SPDX_LICENSE.MIT_ADVERTISING$.MODULE$;
  public static final SPDX_LICENSE MIT_NO_ATTRIBUTION = SPDX_LICENSE.MIT_NO_ATTRIBUTION$.MODULE$;
  public static final SPDX_LICENSE MOTOSOTO = SPDX_LICENSE.MOTOSOTO$.MODULE$;
  public static final SPDX_LICENSE MOZILLA_PUBLIC_LICENSE_1_0 =
      SPDX_LICENSE.MOZILLA_PUBLIC_LICENSE_1_0$.MODULE$;
  public static final SPDX_LICENSE MOZILLA_PUBLIC_LICENSE_1_1 =
      SPDX_LICENSE.MOZILLA_PUBLIC_LICENSE_1_1$.MODULE$;
  public static final SPDX_LICENSE MOZILLA_PUBLIC_LICENSE_2_0 =
      SPDX_LICENSE.MOZILLA_PUBLIC_LICENSE_2_0$.MODULE$;
  public static final SPDX_LICENSE MPICH2 = SPDX_LICENSE.MPICH2$.MODULE$;
  public static final SPDX_LICENSE MPL_20_NO_COPYLEFT_EXCEPTION =
      SPDX_LICENSE.MPL_20_NO_COPYLEFT_EXCEPTION$.MODULE$;
  public static final SPDX_LICENSE MTLL = SPDX_LICENSE.MTLL$.MODULE$;
  public static final SPDX_LICENSE MULTICS = SPDX_LICENSE.MULTICS$.MODULE$;
  public static final SPDX_LICENSE MUP = SPDX_LICENSE.MUP$.MODULE$;
  public static final SPDX_LICENSE NASA_OPEN_SOURCE_AGREEMENT_1_3 =
      SPDX_LICENSE.NASA_OPEN_SOURCE_AGREEMENT_1_3$.MODULE$;
  public static final SPDX_LICENSE NAUMEN = SPDX_LICENSE.NAUMEN$.MODULE$;
  public static final SPDX_LICENSE NCSA = SPDX_LICENSE.NCSA$.MODULE$;
  public static final SPDX_LICENSE NETCDF = SPDX_LICENSE.NETCDF$.MODULE$;
  public static final SPDX_LICENSE NETSCAPE_PUBLIC_LICENSE_V1_0 =
      SPDX_LICENSE.NETSCAPE_PUBLIC_LICENSE_V1_0$.MODULE$;
  public static final SPDX_LICENSE NETSCAPE_PUBLIC_LICENSE_V1_1 =
      SPDX_LICENSE.NETSCAPE_PUBLIC_LICENSE_V1_1$.MODULE$;
  public static final SPDX_LICENSE NET_BOOLEAN_PUBLIC_LICENSE_V1 =
      SPDX_LICENSE.NET_BOOLEAN_PUBLIC_LICENSE_V1$.MODULE$;
  public static final SPDX_LICENSE NET_SNMP_LICENSE = SPDX_LICENSE.NET_SNMP_LICENSE$.MODULE$;
  public static final SPDX_LICENSE NEWSLETR = SPDX_LICENSE.NEWSLETR$.MODULE$;
  public static final SPDX_LICENSE NGPL = SPDX_LICENSE.NGPL$.MODULE$;
  public static final SPDX_LICENSE NLPL = SPDX_LICENSE.NLPL$.MODULE$;
  public static final SPDX_LICENSE NOKIA = SPDX_LICENSE.NOKIA$.MODULE$;
  public static final SPDX_LICENSE NON_PROFIT_OPEN_SOFTWARE_LICENSE_3_0 =
      SPDX_LICENSE.NON_PROFIT_OPEN_SOFTWARE_LICENSE_3_0$.MODULE$;
  public static final SPDX_LICENSE NORWEGIAN_LICENCE_FOR_OPEN_GOVERNMENT_DATA =
      SPDX_LICENSE.NORWEGIAN_LICENCE_FOR_OPEN_GOVERNMENT_DATA$.MODULE$;
  public static final SPDX_LICENSE NOSL = SPDX_LICENSE.NOSL$.MODULE$;
  public static final SPDX_LICENSE NOT_OPEN_SOURCE = SPDX_LICENSE.NOT_OPEN_SOURCE$.MODULE$;
  public static final SPDX_LICENSE NOWEB = SPDX_LICENSE.NOWEB$.MODULE$;
  public static final SPDX_LICENSE NRL = SPDX_LICENSE.NRL$.MODULE$;
  public static final SPDX_LICENSE NTP = SPDX_LICENSE.NTP$.MODULE$;
  public static final SPDX_LICENSE OCLC_RESEARCH_PUBLIC_LICENSE_2_0 =
      SPDX_LICENSE.OCLC_RESEARCH_PUBLIC_LICENSE_2_0$.MODULE$;
  public static final SPDX_LICENSE ODC_OPEN_DATABASE_LICENSE_V1_0 =
      SPDX_LICENSE.ODC_OPEN_DATABASE_LICENSE_V1_0$.MODULE$;
  public static final SPDX_LICENSE OGTSL = SPDX_LICENSE.OGTSL$.MODULE$;
  public static final SPDX_LICENSE OLDAP_20 = SPDX_LICENSE.OLDAP_20$.MODULE$;
  public static final SPDX_LICENSE OML = SPDX_LICENSE.OML$.MODULE$;
  public static final SPDX_LICENSE OPENSSL = SPDX_LICENSE.OPENSSL$.MODULE$;
  public static final SPDX_LICENSE OPEN_CASCADE_TECHNOLOGY_PUBLIC_LICENSE =
      SPDX_LICENSE.OPEN_CASCADE_TECHNOLOGY_PUBLIC_LICENSE$.MODULE$;
  public static final SPDX_LICENSE OPEN_LDAP_PUBLIC_LICENSE_2_2_2 =
      SPDX_LICENSE.OPEN_LDAP_PUBLIC_LICENSE_2_2_2$.MODULE$;
  public static final SPDX_LICENSE OPEN_LDAP_PUBLIC_LICENSE_V1_1 =
      SPDX_LICENSE.OPEN_LDAP_PUBLIC_LICENSE_V1_1$.MODULE$;
  public static final SPDX_LICENSE OPEN_LDAP_PUBLIC_LICENSE_V1_2 =
      SPDX_LICENSE.OPEN_LDAP_PUBLIC_LICENSE_V1_2$.MODULE$;
  public static final SPDX_LICENSE OPEN_LDAP_PUBLIC_LICENSE_V1_3 =
      SPDX_LICENSE.OPEN_LDAP_PUBLIC_LICENSE_V1_3$.MODULE$;
  public static final SPDX_LICENSE OPEN_LDAP_PUBLIC_LICENSE_V1_4 =
      SPDX_LICENSE.OPEN_LDAP_PUBLIC_LICENSE_V1_4$.MODULE$;
  public static final SPDX_LICENSE OPEN_LDAP_PUBLIC_LICENSE_V2_0_1 =
      SPDX_LICENSE.OPEN_LDAP_PUBLIC_LICENSE_V2_0_1$.MODULE$;
  public static final SPDX_LICENSE OPEN_LDAP_PUBLIC_LICENSE_V2_1 =
      SPDX_LICENSE.OPEN_LDAP_PUBLIC_LICENSE_V2_1$.MODULE$;
  public static final SPDX_LICENSE OPEN_LDAP_PUBLIC_LICENSE_V2_2 =
      SPDX_LICENSE.OPEN_LDAP_PUBLIC_LICENSE_V2_2$.MODULE$;
  public static final SPDX_LICENSE OPEN_LDAP_PUBLIC_LICENSE_V2_2_1 =
      SPDX_LICENSE.OPEN_LDAP_PUBLIC_LICENSE_V2_2_1$.MODULE$;
  public static final SPDX_LICENSE OPEN_LDAP_PUBLIC_LICENSE_V2_3 =
      SPDX_LICENSE.OPEN_LDAP_PUBLIC_LICENSE_V2_3$.MODULE$;
  public static final SPDX_LICENSE OPEN_LDAP_PUBLIC_LICENSE_V2_4 =
      SPDX_LICENSE.OPEN_LDAP_PUBLIC_LICENSE_V2_4$.MODULE$;
  public static final SPDX_LICENSE OPEN_LDAP_PUBLIC_LICENSE_V2_5 =
      SPDX_LICENSE.OPEN_LDAP_PUBLIC_LICENSE_V2_5$.MODULE$;
  public static final SPDX_LICENSE OPEN_LDAP_PUBLIC_LICENSE_V2_6 =
      SPDX_LICENSE.OPEN_LDAP_PUBLIC_LICENSE_V2_6$.MODULE$;
  public static final SPDX_LICENSE OPEN_LDAP_PUBLIC_LICENSE_V2_7 =
      SPDX_LICENSE.OPEN_LDAP_PUBLIC_LICENSE_V2_7$.MODULE$;
  public static final SPDX_LICENSE OPEN_LDAP_PUBLIC_LICENSE_V2_8 =
      SPDX_LICENSE.OPEN_LDAP_PUBLIC_LICENSE_V2_8$.MODULE$;
  public static final SPDX_LICENSE OPEN_PUBLIC_LICENSE_V1_0 =
      SPDX_LICENSE.OPEN_PUBLIC_LICENSE_V1_0$.MODULE$;
  public static final SPDX_LICENSE OPEN_SOFTWARE_LICENSE_1_0 =
      SPDX_LICENSE.OPEN_SOFTWARE_LICENSE_1_0$.MODULE$;
  public static final SPDX_LICENSE OPEN_SOFTWARE_LICENSE_1_1 =
      SPDX_LICENSE.OPEN_SOFTWARE_LICENSE_1_1$.MODULE$;
  public static final SPDX_LICENSE OPEN_SOFTWARE_LICENSE_2_0 =
      SPDX_LICENSE.OPEN_SOFTWARE_LICENSE_2_0$.MODULE$;
  public static final SPDX_LICENSE OPEN_SOFTWARE_LICENSE_2_1 =
      SPDX_LICENSE.OPEN_SOFTWARE_LICENSE_2_1$.MODULE$;
  public static final SPDX_LICENSE OPEN_SOFTWARE_LICENSE_3_0 =
      SPDX_LICENSE.OPEN_SOFTWARE_LICENSE_3_0$.MODULE$;
  public static final SPDX_LICENSE OSET_PUBLIC_LICENSE_VERSION_2_1 =
      SPDX_LICENSE.OSET_PUBLIC_LICENSE_VERSION_2_1$.MODULE$;
  public static final SPDX_LICENSE PDDL_10 = SPDX_LICENSE.PDDL_10$.MODULE$;
  public static final SPDX_LICENSE PHP_LICENSE_V3_0 = SPDX_LICENSE.PHP_LICENSE_V3_0$.MODULE$;
  public static final SPDX_LICENSE PHP_LICENSE_V3_01 = SPDX_LICENSE.PHP_LICENSE_V3_01$.MODULE$;
  public static final SPDX_LICENSE PLEXUS = SPDX_LICENSE.PLEXUS$.MODULE$;
  public static final SPDX_LICENSE POSTGRESQL = SPDX_LICENSE.POSTGRESQL$.MODULE$;
  public static final SPDX_LICENSE PSFRAG = SPDX_LICENSE.PSFRAG$.MODULE$;
  public static final SPDX_LICENSE PSUTILS = SPDX_LICENSE.PSUTILS$.MODULE$;
  public static final SPDX_LICENSE PYTHON_LICENSE_2_0 = SPDX_LICENSE.PYTHON_LICENSE_2_0$.MODULE$;
  public static final SPDX_LICENSE QHULL = SPDX_LICENSE.QHULL$.MODULE$;
  public static final SPDX_LICENSE Q_PUBLIC_LICENSE_1_0 =
      SPDX_LICENSE.Q_PUBLIC_LICENSE_1_0$.MODULE$;
  public static final SPDX_LICENSE RDISC = SPDX_LICENSE.RDISC$.MODULE$;
  public static final SPDX_LICENSE REALNETWORKS_PUBLIC_SOURCE_LICENSE_V1_0 =
      SPDX_LICENSE.REALNETWORKS_PUBLIC_SOURCE_LICENSE_V1_0$.MODULE$;
  public static final SPDX_LICENSE RECIPROCAL_PUBLIC_LICENSE_1_1 =
      SPDX_LICENSE.RECIPROCAL_PUBLIC_LICENSE_1_1$.MODULE$;
  public static final SPDX_LICENSE RECIPROCAL_PUBLIC_LICENSE_1_5 =
      SPDX_LICENSE.RECIPROCAL_PUBLIC_LICENSE_1_5$.MODULE$;
  public static final SPDX_LICENSE RED_HAT_ECOS_PUBLIC_LICENSE_V1_1 =
      SPDX_LICENSE.RED_HAT_ECOS_PUBLIC_LICENSE_V1_1$.MODULE$;
  public static final SPDX_LICENSE RSA_MESSAGE_DIGEST_LICENSE =
      SPDX_LICENSE.RSA_MESSAGE_DIGEST_LICENSE$.MODULE$;
  public static final SPDX_LICENSE RSCPL = SPDX_LICENSE.RSCPL$.MODULE$;
  public static final SPDX_LICENSE RUBY = SPDX_LICENSE.RUBY$.MODULE$;
  public static final SPDX_LICENSE SAXPATH = SPDX_LICENSE.SAXPATH$.MODULE$;
  public static final SPDX_LICENSE SAX_PUBLIC_DOMAIN_NOTICE =
      SPDX_LICENSE.SAX_PUBLIC_DOMAIN_NOTICE$.MODULE$;
  public static final SPDX_LICENSE SCEA = SPDX_LICENSE.SCEA$.MODULE$;
  public static final SPDX_LICENSE SENDMAIL = SPDX_LICENSE.SENDMAIL$.MODULE$;
  public static final SPDX_LICENSE SGI_FREE_SOFTWARE_LICENSE_B_V1_0 =
      SPDX_LICENSE.SGI_FREE_SOFTWARE_LICENSE_B_V1_0$.MODULE$;
  public static final SPDX_LICENSE SGI_FREE_SOFTWARE_LICENSE_B_V1_1 =
      SPDX_LICENSE.SGI_FREE_SOFTWARE_LICENSE_B_V1_1$.MODULE$;
  public static final SPDX_LICENSE SGI_FREE_SOFTWARE_LICENSE_B_V2_0 =
      SPDX_LICENSE.SGI_FREE_SOFTWARE_LICENSE_B_V2_0$.MODULE$;
  public static final SPDX_LICENSE SIL_OPEN_FONT_LICENSE_1_0 =
      SPDX_LICENSE.SIL_OPEN_FONT_LICENSE_1_0$.MODULE$;
  public static final SPDX_LICENSE SIL_OPEN_FONT_LICENSE_1_1 =
      SPDX_LICENSE.SIL_OPEN_FONT_LICENSE_1_1$.MODULE$;
  public static final SPDX_LICENSE SIMPLE_PUBLIC_LICENSE_2_0 =
      SPDX_LICENSE.SIMPLE_PUBLIC_LICENSE_2_0$.MODULE$;
  public static final SPDX_LICENSE SISSL = SPDX_LICENSE.SISSL$.MODULE$;
  public static final SPDX_LICENSE SLEEPYCAT = SPDX_LICENSE.SLEEPYCAT$.MODULE$;
  public static final SPDX_LICENSE SMLNJ = SPDX_LICENSE.SMLNJ$.MODULE$;
  public static final SPDX_LICENSE SMPPL = SPDX_LICENSE.SMPPL$.MODULE$;
  public static final SPDX_LICENSE SNIA = SPDX_LICENSE.SNIA$.MODULE$;
  public static final SPDX_LICENSE SPENCER_LICENSE_86 = SPDX_LICENSE.SPENCER_LICENSE_86$.MODULE$;
  public static final SPDX_LICENSE SPENCER_LICENSE_94 = SPDX_LICENSE.SPENCER_LICENSE_94$.MODULE$;
  public static final SPDX_LICENSE SPENCER_LICENSE_99 = SPDX_LICENSE.SPENCER_LICENSE_99$.MODULE$;
  public static final SPDX_LICENSE SUGARCRM_PUBLIC_LICENSE_V1_1_3 =
      SPDX_LICENSE.SUGARCRM_PUBLIC_LICENSE_V1_1_3$.MODULE$;
  public static final SPDX_LICENSE SUN_INDUSTRY_STANDARDS_SOURCE_LICENSE_V1_2 =
      SPDX_LICENSE.SUN_INDUSTRY_STANDARDS_SOURCE_LICENSE_V1_2$.MODULE$;
  public static final SPDX_LICENSE SUN_PUBLIC_LICENSE_V1_0 =
      SPDX_LICENSE.SUN_PUBLIC_LICENSE_V1_0$.MODULE$;
  public static final SPDX_LICENSE SWL = SPDX_LICENSE.SWL$.MODULE$;
  public static final SPDX_LICENSE SYBASE_OPEN_WATCOM_PUBLIC_LICENSE_1_0 =
      SPDX_LICENSE.SYBASE_OPEN_WATCOM_PUBLIC_LICENSE_1_0$.MODULE$;
  public static final SPDX_LICENSE TCL = SPDX_LICENSE.TCL$.MODULE$;
  public static final SPDX_LICENSE TCP_WRAPPERS_LICENSE =
      SPDX_LICENSE.TCP_WRAPPERS_LICENSE$.MODULE$;
  public static final SPDX_LICENSE TMATE = SPDX_LICENSE.TMATE$.MODULE$;
  public static final SPDX_LICENSE TORQUE_11 = SPDX_LICENSE.TORQUE_11$.MODULE$;
  public static final SPDX_LICENSE TOSL = SPDX_LICENSE.TOSL$.MODULE$;
  public static final SPDX_LICENSE UNICODE_DFS_2015 = SPDX_LICENSE.UNICODE_DFS_2015$.MODULE$;
  public static final SPDX_LICENSE UNICODE_DFS_2016 = SPDX_LICENSE.UNICODE_DFS_2016$.MODULE$;
  public static final SPDX_LICENSE UNICODE_TERMS_OF_USE =
      SPDX_LICENSE.UNICODE_TERMS_OF_USE$.MODULE$;
  public static final SPDX_LICENSE UNIVERSAL_PERMISSIVE_LICENSE_V1_0 =
      SPDX_LICENSE.UNIVERSAL_PERMISSIVE_LICENSE_V1_0$.MODULE$;
  public static final SPDX_LICENSE UNLICENSE = SPDX_LICENSE.UNLICENSE$.MODULE$;
  public static final SPDX_LICENSE VIM = SPDX_LICENSE.VIM$.MODULE$;
  public static final SPDX_LICENSE VOSTROM = SPDX_LICENSE.VOSTROM$.MODULE$;
  public static final SPDX_LICENSE VOVIDA_SOFTWARE_LICENSE_V1_0 =
      SPDX_LICENSE.VOVIDA_SOFTWARE_LICENSE_V1_0$.MODULE$;
  public static final SPDX_LICENSE W3C = SPDX_LICENSE.W3C$.MODULE$;
  public static final SPDX_LICENSE W3C_19980720 = SPDX_LICENSE.W3C_19980720$.MODULE$;
  public static final SPDX_LICENSE W3C_20150513 = SPDX_LICENSE.W3C_20150513$.MODULE$;
  public static final SPDX_LICENSE WSUIPA = SPDX_LICENSE.WSUIPA$.MODULE$;
  public static final SPDX_LICENSE WTFPL = SPDX_LICENSE.WTFPL$.MODULE$;
  public static final SPDX_LICENSE X11 = SPDX_LICENSE.X11$.MODULE$;
  public static final SPDX_LICENSE XEROX = SPDX_LICENSE.XEROX$.MODULE$;
  public static final SPDX_LICENSE XFREE86_LICENSE_1_1 = SPDX_LICENSE.XFREE86_LICENSE_1_1$.MODULE$;
  public static final SPDX_LICENSE XINETD = SPDX_LICENSE.XINETD$.MODULE$;
  public static final SPDX_LICENSE XNET = SPDX_LICENSE.XNET$.MODULE$;
  public static final SPDX_LICENSE XPP = SPDX_LICENSE.XPP$.MODULE$;
  public static final SPDX_LICENSE XSKAT = SPDX_LICENSE.XSKAT$.MODULE$;
  public static final SPDX_LICENSE YPL_10 = SPDX_LICENSE.YPL_10$.MODULE$;
  public static final SPDX_LICENSE YPL_11 = SPDX_LICENSE.YPL_11$.MODULE$;
  public static final SPDX_LICENSE ZED = SPDX_LICENSE.ZED$.MODULE$;
  public static final SPDX_LICENSE ZEND_LICENSE_V2_0 = SPDX_LICENSE.ZEND_LICENSE_V2_0$.MODULE$;
  public static final SPDX_LICENSE ZIMBRA_PUBLIC_LICENSE_V1_3 =
      SPDX_LICENSE.ZIMBRA_PUBLIC_LICENSE_V1_3$.MODULE$;
  public static final SPDX_LICENSE ZIMBRA_PUBLIC_LICENSE_V1_4 =
      SPDX_LICENSE.ZIMBRA_PUBLIC_LICENSE_V1_4$.MODULE$;
  public static final SPDX_LICENSE ZLIB = SPDX_LICENSE.ZLIB$.MODULE$;
  public static final SPDX_LICENSE ZLIB_ACKNOWLEDGEMENT =
      SPDX_LICENSE.ZLIB_ACKNOWLEDGEMENT$.MODULE$;
  public static final SPDX_LICENSE ZOPE_PUBLIC_LICENSE_1_1 =
      SPDX_LICENSE.ZOPE_PUBLIC_LICENSE_1_1$.MODULE$;
  public static final SPDX_LICENSE ZOPE_PUBLIC_LICENSE_2_0 =
      SPDX_LICENSE.ZOPE_PUBLIC_LICENSE_2_0$.MODULE$;
  public static final SPDX_LICENSE ZOPE_PUBLIC_LICENSE_2_1 =
      SPDX_LICENSE.ZOPE_PUBLIC_LICENSE_2_1$.MODULE$;
}
