package com.babylonhealth.lit.hl7_java.codes;

import com.babylonhealth.lit.hl7.STRUCTURE_DEFINITION_KIND;

public interface StructureDefinitionKind {
  public static final STRUCTURE_DEFINITION_KIND COMPLEX_DATA_TYPE =
      STRUCTURE_DEFINITION_KIND.COMPLEX_DATA_TYPE$.MODULE$;
  public static final STRUCTURE_DEFINITION_KIND LOGICAL =
      STRUCTURE_DEFINITION_KIND.LOGICAL$.MODULE$;
  public static final STRUCTURE_DEFINITION_KIND PRIMITIVE_DATA_TYPE =
      STRUCTURE_DEFINITION_KIND.PRIMITIVE_DATA_TYPE$.MODULE$;
  public static final STRUCTURE_DEFINITION_KIND RESOURCE =
      STRUCTURE_DEFINITION_KIND.RESOURCE$.MODULE$;
}
