package com.babylonhealth.lit.hl7_java.codes;

import com.babylonhealth.lit.hl7.SUPPLYREQUEST_STATUS;

public interface SupplyrequestStatus {
  public static final SUPPLYREQUEST_STATUS ACTIVE = SUPPLYREQUEST_STATUS.ACTIVE$.MODULE$;
  public static final SUPPLYREQUEST_STATUS CANCELLED = SUPPLYREQUEST_STATUS.CANCELLED$.MODULE$;
  public static final SUPPLYREQUEST_STATUS COMPLETED = SUPPLYREQUEST_STATUS.COMPLETED$.MODULE$;
  public static final SUPPLYREQUEST_STATUS DRAFT = SUPPLYREQUEST_STATUS.DRAFT$.MODULE$;
  public static final SUPPLYREQUEST_STATUS ENTERED_IN_ERROR =
      SUPPLYREQUEST_STATUS.ENTERED_IN_ERROR$.MODULE$;
  public static final SUPPLYREQUEST_STATUS SUSPENDED = SUPPLYREQUEST_STATUS.SUSPENDED$.MODULE$;
  public static final SUPPLYREQUEST_STATUS UNKNOWN = SUPPLYREQUEST_STATUS.UNKNOWN$.MODULE$;
}
