package com.babylonhealth.lit.hl7_java.codes;

import com.babylonhealth.lit.hl7.SYSTEM_RESTFUL_INTERACTION;

public interface SystemRestfulInteraction {
  public static final SYSTEM_RESTFUL_INTERACTION BATCH = SYSTEM_RESTFUL_INTERACTION.BATCH$.MODULE$;
  public static final SYSTEM_RESTFUL_INTERACTION HISTORY_SYSTEM =
      SYSTEM_RESTFUL_INTERACTION.HISTORY_SYSTEM$.MODULE$;
  public static final SYSTEM_RESTFUL_INTERACTION SEARCH_SYSTEM =
      SYSTEM_RESTFUL_INTERACTION.SEARCH_SYSTEM$.MODULE$;
  public static final SYSTEM_RESTFUL_INTERACTION TRANSACTION =
      SYSTEM_RESTFUL_INTERACTION.TRANSACTION$.MODULE$;
}
