package com.babylonhealth.lit.hl7_java.codes;

import com.babylonhealth.lit.hl7.TYPE_RESTFUL_INTERACTION;

public interface TypeRestfulInteraction {
  public static final TYPE_RESTFUL_INTERACTION CREATE = TYPE_RESTFUL_INTERACTION.CREATE$.MODULE$;
  public static final TYPE_RESTFUL_INTERACTION DELETE = TYPE_RESTFUL_INTERACTION.DELETE$.MODULE$;
  public static final TYPE_RESTFUL_INTERACTION HISTORY_INSTANCE =
      TYPE_RESTFUL_INTERACTION.HISTORY_INSTANCE$.MODULE$;
  public static final TYPE_RESTFUL_INTERACTION HISTORY_TYPE =
      TYPE_RESTFUL_INTERACTION.HISTORY_TYPE$.MODULE$;
  public static final TYPE_RESTFUL_INTERACTION PATCH = TYPE_RESTFUL_INTERACTION.PATCH$.MODULE$;
  public static final TYPE_RESTFUL_INTERACTION READ = TYPE_RESTFUL_INTERACTION.READ$.MODULE$;
  public static final TYPE_RESTFUL_INTERACTION SEARCH_TYPE =
      TYPE_RESTFUL_INTERACTION.SEARCH_TYPE$.MODULE$;
  public static final TYPE_RESTFUL_INTERACTION UPDATE = TYPE_RESTFUL_INTERACTION.UPDATE$.MODULE$;
  public static final TYPE_RESTFUL_INTERACTION VREAD = TYPE_RESTFUL_INTERACTION.VREAD$.MODULE$;
}
