package com.babylonhealth.lit.hl7_java.codes;

import com.babylonhealth.lit.hl7.V3_CONFIDENTIALITYCLASSIFICATION;

public interface V3Confidentialityclassification {
  public static final V3_CONFIDENTIALITYCLASSIFICATION L =
      V3_CONFIDENTIALITYCLASSIFICATION.L$.MODULE$;
  public static final V3_CONFIDENTIALITYCLASSIFICATION M =
      V3_CONFIDENTIALITYCLASSIFICATION.M$.MODULE$;
  public static final V3_CONFIDENTIALITYCLASSIFICATION N =
      V3_CONFIDENTIALITYCLASSIFICATION.N$.MODULE$;
  public static final V3_CONFIDENTIALITYCLASSIFICATION R =
      V3_CONFIDENTIALITYCLASSIFICATION.R$.MODULE$;
  public static final V3_CONFIDENTIALITYCLASSIFICATION U =
      V3_CONFIDENTIALITYCLASSIFICATION.U$.MODULE$;
  public static final V3_CONFIDENTIALITYCLASSIFICATION V =
      V3_CONFIDENTIALITYCLASSIFICATION.V$.MODULE$;
}
