package com.babylonhealth.lit.hl7_java.codes;

import com.babylonhealth.lit.hl7.V3_CONFIDENTIALITY;

public interface V3Confidentiality {
  public static final V3_CONFIDENTIALITY B = V3_CONFIDENTIALITY.B$.MODULE$;
  public static final V3_CONFIDENTIALITY C = V3_CONFIDENTIALITY.C$.MODULE$;
  public static final V3_CONFIDENTIALITY CONFIDENTIALITY =
      V3_CONFIDENTIALITY.CONFIDENTIALITY$.MODULE$;
  public static final V3_CONFIDENTIALITY CONFIDENTIALITYBYACCESSKIND =
      V3_CONFIDENTIALITY.CONFIDENTIALITYBYACCESSKIND$.MODULE$;
  public static final V3_CONFIDENTIALITY CONFIDENTIALITYBYINFOTYPE =
      V3_CONFIDENTIALITY.CONFIDENTIALITYBYINFOTYPE$.MODULE$;
  public static final V3_CONFIDENTIALITY CONFIDENTIALITYMODIFIERS =
      V3_CONFIDENTIALITY.CONFIDENTIALITYMODIFIERS$.MODULE$;
  public static final V3_CONFIDENTIALITY D = V3_CONFIDENTIALITY.D$.MODULE$;
  public static final V3_CONFIDENTIALITY ETH = V3_CONFIDENTIALITY.ETH$.MODULE$;
  public static final V3_CONFIDENTIALITY HIV = V3_CONFIDENTIALITY.HIV$.MODULE$;
  public static final V3_CONFIDENTIALITY I = V3_CONFIDENTIALITY.I$.MODULE$;
  public static final V3_CONFIDENTIALITY L = V3_CONFIDENTIALITY.L$.MODULE$;
  public static final V3_CONFIDENTIALITY M = V3_CONFIDENTIALITY.M$.MODULE$;
  public static final V3_CONFIDENTIALITY N = V3_CONFIDENTIALITY.N$.MODULE$;
  public static final V3_CONFIDENTIALITY PSY = V3_CONFIDENTIALITY.PSY$.MODULE$;
  public static final V3_CONFIDENTIALITY R = V3_CONFIDENTIALITY.R$.MODULE$;
  public static final V3_CONFIDENTIALITY S = V3_CONFIDENTIALITY.S$.MODULE$;
  public static final V3_CONFIDENTIALITY SDV = V3_CONFIDENTIALITY.SDV$.MODULE$;
  public static final V3_CONFIDENTIALITY T = V3_CONFIDENTIALITY.T$.MODULE$;
  public static final V3_CONFIDENTIALITY U = V3_CONFIDENTIALITY.U$.MODULE$;
  public static final V3_CONFIDENTIALITY V = V3_CONFIDENTIALITY.V$.MODULE$;
}
