package com.babylonhealth.lit.hl7_java.codes;

import com.babylonhealth.lit.hl7.VERIFICATIONRESULT_STATUS;

public interface VerificationresultStatus {
  public static final VERIFICATIONRESULT_STATUS ATTESTED =
      VERIFICATIONRESULT_STATUS.ATTESTED$.MODULE$;
  public static final VERIFICATIONRESULT_STATUS IN_PROCESS =
      VERIFICATIONRESULT_STATUS.IN_PROCESS$.MODULE$;
  public static final VERIFICATIONRESULT_STATUS REQUIRES_REVALIDATION =
      VERIFICATIONRESULT_STATUS.REQUIRES_REVALIDATION$.MODULE$;
  public static final VERIFICATIONRESULT_STATUS RE_VALIDATION_FAILED =
      VERIFICATIONRESULT_STATUS.RE_VALIDATION_FAILED$.MODULE$;
  public static final VERIFICATIONRESULT_STATUS VALIDATED =
      VERIFICATIONRESULT_STATUS.VALIDATED$.MODULE$;
  public static final VERIFICATIONRESULT_STATUS VALIDATION_FAILED =
      VERIFICATIONRESULT_STATUS.VALIDATION_FAILED$.MODULE$;
}
