package com.babylonhealth.lit.core_java.codes;

import com.babylonhealth.lit.core.ALL_TYPES;

public interface AllTypes {
  public static final ALL_TYPES ACCOUNT = ALL_TYPES.ACCOUNT$.MODULE$;
  public static final ALL_TYPES ACTIVITYDEFINITION = ALL_TYPES.ACTIVITYDEFINITION$.MODULE$;
  public static final ALL_TYPES ADDRESS = ALL_TYPES.ADDRESS$.MODULE$;
  public static final ALL_TYPES ADVERSEEVENT = ALL_TYPES.ADVERSEEVENT$.MODULE$;
  public static final ALL_TYPES AGE = ALL_TYPES.AGE$.MODULE$;
  public static final ALL_TYPES ALLERGYINTOLERANCE = ALL_TYPES.ALLERGYINTOLERANCE$.MODULE$;
  public static final ALL_TYPES ANNOTATION = ALL_TYPES.ANNOTATION$.MODULE$;
  public static final ALL_TYPES ANY = ALL_TYPES.ANY$.MODULE$;
  public static final ALL_TYPES APPOINTMENT = ALL_TYPES.APPOINTMENT$.MODULE$;
  public static final ALL_TYPES APPOINTMENTRESPONSE = ALL_TYPES.APPOINTMENTRESPONSE$.MODULE$;
  public static final ALL_TYPES ATTACHMENT = ALL_TYPES.ATTACHMENT$.MODULE$;
  public static final ALL_TYPES AUDITEVENT = ALL_TYPES.AUDITEVENT$.MODULE$;
  public static final ALL_TYPES BACKBONEELEMENT = ALL_TYPES.BACKBONEELEMENT$.MODULE$;
  public static final ALL_TYPES BASE64BINARY = ALL_TYPES.BASE64BINARY$.MODULE$;
  public static final ALL_TYPES BASIC = ALL_TYPES.BASIC$.MODULE$;
  public static final ALL_TYPES BINARY = ALL_TYPES.BINARY$.MODULE$;
  public static final ALL_TYPES BIOLOGICALLYDERIVEDPRODUCT =
      ALL_TYPES.BIOLOGICALLYDERIVEDPRODUCT$.MODULE$;
  public static final ALL_TYPES BODYSTRUCTURE = ALL_TYPES.BODYSTRUCTURE$.MODULE$;
  public static final ALL_TYPES BOOLEAN = ALL_TYPES.BOOLEAN$.MODULE$;
  public static final ALL_TYPES BUNDLE = ALL_TYPES.BUNDLE$.MODULE$;
  public static final ALL_TYPES CANONICAL = ALL_TYPES.CANONICAL$.MODULE$;
  public static final ALL_TYPES CAPABILITYSTATEMENT = ALL_TYPES.CAPABILITYSTATEMENT$.MODULE$;
  public static final ALL_TYPES CAREPLAN = ALL_TYPES.CAREPLAN$.MODULE$;
  public static final ALL_TYPES CARETEAM = ALL_TYPES.CARETEAM$.MODULE$;
  public static final ALL_TYPES CATALOGENTRY = ALL_TYPES.CATALOGENTRY$.MODULE$;
  public static final ALL_TYPES CHARGEITEM = ALL_TYPES.CHARGEITEM$.MODULE$;
  public static final ALL_TYPES CHARGEITEMDEFINITION = ALL_TYPES.CHARGEITEMDEFINITION$.MODULE$;
  public static final ALL_TYPES CLAIM = ALL_TYPES.CLAIM$.MODULE$;
  public static final ALL_TYPES CLAIMRESPONSE = ALL_TYPES.CLAIMRESPONSE$.MODULE$;
  public static final ALL_TYPES CLINICALIMPRESSION = ALL_TYPES.CLINICALIMPRESSION$.MODULE$;
  public static final ALL_TYPES CODE = ALL_TYPES.CODE$.MODULE$;
  public static final ALL_TYPES CODEABLECONCEPT = ALL_TYPES.CODEABLECONCEPT$.MODULE$;
  public static final ALL_TYPES CODESYSTEM = ALL_TYPES.CODESYSTEM$.MODULE$;
  public static final ALL_TYPES CODING = ALL_TYPES.CODING$.MODULE$;
  public static final ALL_TYPES COMMUNICATION = ALL_TYPES.COMMUNICATION$.MODULE$;
  public static final ALL_TYPES COMMUNICATIONREQUEST = ALL_TYPES.COMMUNICATIONREQUEST$.MODULE$;
  public static final ALL_TYPES COMPARTMENTDEFINITION = ALL_TYPES.COMPARTMENTDEFINITION$.MODULE$;
  public static final ALL_TYPES COMPOSITION = ALL_TYPES.COMPOSITION$.MODULE$;
  public static final ALL_TYPES CONCEPTMAP = ALL_TYPES.CONCEPTMAP$.MODULE$;
  public static final ALL_TYPES CONDITION = ALL_TYPES.CONDITION$.MODULE$;
  public static final ALL_TYPES CONSENT = ALL_TYPES.CONSENT$.MODULE$;
  public static final ALL_TYPES CONTACTDETAIL = ALL_TYPES.CONTACTDETAIL$.MODULE$;
  public static final ALL_TYPES CONTACTPOINT = ALL_TYPES.CONTACTPOINT$.MODULE$;
  public static final ALL_TYPES CONTRACT = ALL_TYPES.CONTRACT$.MODULE$;
  public static final ALL_TYPES CONTRIBUTOR = ALL_TYPES.CONTRIBUTOR$.MODULE$;
  public static final ALL_TYPES COUNT = ALL_TYPES.COUNT$.MODULE$;
  public static final ALL_TYPES COVERAGE = ALL_TYPES.COVERAGE$.MODULE$;
  public static final ALL_TYPES COVERAGEELIGIBILITYREQUEST =
      ALL_TYPES.COVERAGEELIGIBILITYREQUEST$.MODULE$;
  public static final ALL_TYPES COVERAGEELIGIBILITYRESPONSE =
      ALL_TYPES.COVERAGEELIGIBILITYRESPONSE$.MODULE$;
  public static final ALL_TYPES DATAREQUIREMENT = ALL_TYPES.DATAREQUIREMENT$.MODULE$;
  public static final ALL_TYPES DATE = ALL_TYPES.DATE$.MODULE$;
  public static final ALL_TYPES DATETIME = ALL_TYPES.DATETIME$.MODULE$;
  public static final ALL_TYPES DECIMAL = ALL_TYPES.DECIMAL$.MODULE$;
  public static final ALL_TYPES DETECTEDISSUE = ALL_TYPES.DETECTEDISSUE$.MODULE$;
  public static final ALL_TYPES DEVICE = ALL_TYPES.DEVICE$.MODULE$;
  public static final ALL_TYPES DEVICEDEFINITION = ALL_TYPES.DEVICEDEFINITION$.MODULE$;
  public static final ALL_TYPES DEVICEMETRIC = ALL_TYPES.DEVICEMETRIC$.MODULE$;
  public static final ALL_TYPES DEVICEREQUEST = ALL_TYPES.DEVICEREQUEST$.MODULE$;
  public static final ALL_TYPES DEVICEUSESTATEMENT = ALL_TYPES.DEVICEUSESTATEMENT$.MODULE$;
  public static final ALL_TYPES DIAGNOSTICREPORT = ALL_TYPES.DIAGNOSTICREPORT$.MODULE$;
  public static final ALL_TYPES DISTANCE = ALL_TYPES.DISTANCE$.MODULE$;
  public static final ALL_TYPES DOCUMENTMANIFEST = ALL_TYPES.DOCUMENTMANIFEST$.MODULE$;
  public static final ALL_TYPES DOCUMENTREFERENCE = ALL_TYPES.DOCUMENTREFERENCE$.MODULE$;
  public static final ALL_TYPES DOMAINRESOURCE = ALL_TYPES.DOMAINRESOURCE$.MODULE$;
  public static final ALL_TYPES DOSAGE = ALL_TYPES.DOSAGE$.MODULE$;
  public static final ALL_TYPES DURATION = ALL_TYPES.DURATION$.MODULE$;
  public static final ALL_TYPES EFFECTEVIDENCESYNTHESIS =
      ALL_TYPES.EFFECTEVIDENCESYNTHESIS$.MODULE$;
  public static final ALL_TYPES ELEMENT = ALL_TYPES.ELEMENT$.MODULE$;
  public static final ALL_TYPES ELEMENTDEFINITION = ALL_TYPES.ELEMENTDEFINITION$.MODULE$;
  public static final ALL_TYPES ENCOUNTER = ALL_TYPES.ENCOUNTER$.MODULE$;
  public static final ALL_TYPES ENDPOINT = ALL_TYPES.ENDPOINT$.MODULE$;
  public static final ALL_TYPES ENROLLMENTREQUEST = ALL_TYPES.ENROLLMENTREQUEST$.MODULE$;
  public static final ALL_TYPES ENROLLMENTRESPONSE = ALL_TYPES.ENROLLMENTRESPONSE$.MODULE$;
  public static final ALL_TYPES EPISODEOFCARE = ALL_TYPES.EPISODEOFCARE$.MODULE$;
  public static final ALL_TYPES EVENTDEFINITION = ALL_TYPES.EVENTDEFINITION$.MODULE$;
  public static final ALL_TYPES EVIDENCE = ALL_TYPES.EVIDENCE$.MODULE$;
  public static final ALL_TYPES EVIDENCEVARIABLE = ALL_TYPES.EVIDENCEVARIABLE$.MODULE$;
  public static final ALL_TYPES EXAMPLESCENARIO = ALL_TYPES.EXAMPLESCENARIO$.MODULE$;
  public static final ALL_TYPES EXPLANATIONOFBENEFIT = ALL_TYPES.EXPLANATIONOFBENEFIT$.MODULE$;
  public static final ALL_TYPES EXPRESSION = ALL_TYPES.EXPRESSION$.MODULE$;
  public static final ALL_TYPES EXTENSION = ALL_TYPES.EXTENSION$.MODULE$;
  public static final ALL_TYPES FAMILYMEMBERHISTORY = ALL_TYPES.FAMILYMEMBERHISTORY$.MODULE$;
  public static final ALL_TYPES FLAG = ALL_TYPES.FLAG$.MODULE$;
  public static final ALL_TYPES GOAL = ALL_TYPES.GOAL$.MODULE$;
  public static final ALL_TYPES GRAPHDEFINITION = ALL_TYPES.GRAPHDEFINITION$.MODULE$;
  public static final ALL_TYPES GROUP = ALL_TYPES.GROUP$.MODULE$;
  public static final ALL_TYPES GUIDANCERESPONSE = ALL_TYPES.GUIDANCERESPONSE$.MODULE$;
  public static final ALL_TYPES HEALTHCARESERVICE = ALL_TYPES.HEALTHCARESERVICE$.MODULE$;
  public static final ALL_TYPES HUMANNAME = ALL_TYPES.HUMANNAME$.MODULE$;
  public static final ALL_TYPES ID = ALL_TYPES.ID$.MODULE$;
  public static final ALL_TYPES IDENTIFIER = ALL_TYPES.IDENTIFIER$.MODULE$;
  public static final ALL_TYPES IMAGINGSTUDY = ALL_TYPES.IMAGINGSTUDY$.MODULE$;
  public static final ALL_TYPES IMMUNIZATION = ALL_TYPES.IMMUNIZATION$.MODULE$;
  public static final ALL_TYPES IMMUNIZATIONEVALUATION = ALL_TYPES.IMMUNIZATIONEVALUATION$.MODULE$;
  public static final ALL_TYPES IMMUNIZATIONRECOMMENDATION =
      ALL_TYPES.IMMUNIZATIONRECOMMENDATION$.MODULE$;
  public static final ALL_TYPES IMPLEMENTATIONGUIDE = ALL_TYPES.IMPLEMENTATIONGUIDE$.MODULE$;
  public static final ALL_TYPES INSTANT = ALL_TYPES.INSTANT$.MODULE$;
  public static final ALL_TYPES INSURANCEPLAN = ALL_TYPES.INSURANCEPLAN$.MODULE$;
  public static final ALL_TYPES INTEGER = ALL_TYPES.INTEGER$.MODULE$;
  public static final ALL_TYPES INVOICE = ALL_TYPES.INVOICE$.MODULE$;
  public static final ALL_TYPES LIBRARY = ALL_TYPES.LIBRARY$.MODULE$;
  public static final ALL_TYPES LINKAGE = ALL_TYPES.LINKAGE$.MODULE$;
  public static final ALL_TYPES LIST = ALL_TYPES.LIST$.MODULE$;
  public static final ALL_TYPES LOCATION = ALL_TYPES.LOCATION$.MODULE$;
  public static final ALL_TYPES MARKDOWN = ALL_TYPES.MARKDOWN$.MODULE$;
  public static final ALL_TYPES MARKETINGSTATUS = ALL_TYPES.MARKETINGSTATUS$.MODULE$;
  public static final ALL_TYPES MEASURE = ALL_TYPES.MEASURE$.MODULE$;
  public static final ALL_TYPES MEASUREREPORT = ALL_TYPES.MEASUREREPORT$.MODULE$;
  public static final ALL_TYPES MEDIA = ALL_TYPES.MEDIA$.MODULE$;
  public static final ALL_TYPES MEDICATION = ALL_TYPES.MEDICATION$.MODULE$;
  public static final ALL_TYPES MEDICATIONADMINISTRATION =
      ALL_TYPES.MEDICATIONADMINISTRATION$.MODULE$;
  public static final ALL_TYPES MEDICATIONDISPENSE = ALL_TYPES.MEDICATIONDISPENSE$.MODULE$;
  public static final ALL_TYPES MEDICATIONKNOWLEDGE = ALL_TYPES.MEDICATIONKNOWLEDGE$.MODULE$;
  public static final ALL_TYPES MEDICATIONREQUEST = ALL_TYPES.MEDICATIONREQUEST$.MODULE$;
  public static final ALL_TYPES MEDICATIONSTATEMENT = ALL_TYPES.MEDICATIONSTATEMENT$.MODULE$;
  public static final ALL_TYPES MEDICINALPRODUCT = ALL_TYPES.MEDICINALPRODUCT$.MODULE$;
  public static final ALL_TYPES MEDICINALPRODUCTAUTHORIZATION =
      ALL_TYPES.MEDICINALPRODUCTAUTHORIZATION$.MODULE$;
  public static final ALL_TYPES MEDICINALPRODUCTCONTRAINDICATION =
      ALL_TYPES.MEDICINALPRODUCTCONTRAINDICATION$.MODULE$;
  public static final ALL_TYPES MEDICINALPRODUCTINDICATION =
      ALL_TYPES.MEDICINALPRODUCTINDICATION$.MODULE$;
  public static final ALL_TYPES MEDICINALPRODUCTINGREDIENT =
      ALL_TYPES.MEDICINALPRODUCTINGREDIENT$.MODULE$;
  public static final ALL_TYPES MEDICINALPRODUCTINTERACTION =
      ALL_TYPES.MEDICINALPRODUCTINTERACTION$.MODULE$;
  public static final ALL_TYPES MEDICINALPRODUCTMANUFACTURED =
      ALL_TYPES.MEDICINALPRODUCTMANUFACTURED$.MODULE$;
  public static final ALL_TYPES MEDICINALPRODUCTPACKAGED =
      ALL_TYPES.MEDICINALPRODUCTPACKAGED$.MODULE$;
  public static final ALL_TYPES MEDICINALPRODUCTPHARMACEUTICAL =
      ALL_TYPES.MEDICINALPRODUCTPHARMACEUTICAL$.MODULE$;
  public static final ALL_TYPES MEDICINALPRODUCTUNDESIRABLEEFFECT =
      ALL_TYPES.MEDICINALPRODUCTUNDESIRABLEEFFECT$.MODULE$;
  public static final ALL_TYPES MESSAGEDEFINITION = ALL_TYPES.MESSAGEDEFINITION$.MODULE$;
  public static final ALL_TYPES MESSAGEHEADER = ALL_TYPES.MESSAGEHEADER$.MODULE$;
  public static final ALL_TYPES META = ALL_TYPES.META$.MODULE$;
  public static final ALL_TYPES MOLECULARSEQUENCE = ALL_TYPES.MOLECULARSEQUENCE$.MODULE$;
  public static final ALL_TYPES MONEY = ALL_TYPES.MONEY$.MODULE$;
  public static final ALL_TYPES MONEYQUANTITY = ALL_TYPES.MONEYQUANTITY$.MODULE$;
  public static final ALL_TYPES NAMINGSYSTEM = ALL_TYPES.NAMINGSYSTEM$.MODULE$;
  public static final ALL_TYPES NARRATIVE = ALL_TYPES.NARRATIVE$.MODULE$;
  public static final ALL_TYPES NUTRITIONORDER = ALL_TYPES.NUTRITIONORDER$.MODULE$;
  public static final ALL_TYPES OBSERVATION = ALL_TYPES.OBSERVATION$.MODULE$;
  public static final ALL_TYPES OBSERVATIONDEFINITION = ALL_TYPES.OBSERVATIONDEFINITION$.MODULE$;
  public static final ALL_TYPES OID = ALL_TYPES.OID$.MODULE$;
  public static final ALL_TYPES OPERATIONDEFINITION = ALL_TYPES.OPERATIONDEFINITION$.MODULE$;
  public static final ALL_TYPES OPERATIONOUTCOME = ALL_TYPES.OPERATIONOUTCOME$.MODULE$;
  public static final ALL_TYPES ORGANIZATION = ALL_TYPES.ORGANIZATION$.MODULE$;
  public static final ALL_TYPES ORGANIZATIONAFFILIATION =
      ALL_TYPES.ORGANIZATIONAFFILIATION$.MODULE$;
  public static final ALL_TYPES PARAMETERDEFINITION = ALL_TYPES.PARAMETERDEFINITION$.MODULE$;
  public static final ALL_TYPES PARAMETERS = ALL_TYPES.PARAMETERS$.MODULE$;
  public static final ALL_TYPES PATIENT = ALL_TYPES.PATIENT$.MODULE$;
  public static final ALL_TYPES PAYMENTNOTICE = ALL_TYPES.PAYMENTNOTICE$.MODULE$;
  public static final ALL_TYPES PAYMENTRECONCILIATION = ALL_TYPES.PAYMENTRECONCILIATION$.MODULE$;
  public static final ALL_TYPES PERIOD = ALL_TYPES.PERIOD$.MODULE$;
  public static final ALL_TYPES PERSON = ALL_TYPES.PERSON$.MODULE$;
  public static final ALL_TYPES PLANDEFINITION = ALL_TYPES.PLANDEFINITION$.MODULE$;
  public static final ALL_TYPES POPULATION = ALL_TYPES.POPULATION$.MODULE$;
  public static final ALL_TYPES POSITIVEINT = ALL_TYPES.POSITIVEINT$.MODULE$;
  public static final ALL_TYPES PRACTITIONER = ALL_TYPES.PRACTITIONER$.MODULE$;
  public static final ALL_TYPES PRACTITIONERROLE = ALL_TYPES.PRACTITIONERROLE$.MODULE$;
  public static final ALL_TYPES PROCEDURE = ALL_TYPES.PROCEDURE$.MODULE$;
  public static final ALL_TYPES PRODCHARACTERISTIC = ALL_TYPES.PRODCHARACTERISTIC$.MODULE$;
  public static final ALL_TYPES PRODUCTSHELFLIFE = ALL_TYPES.PRODUCTSHELFLIFE$.MODULE$;
  public static final ALL_TYPES PROVENANCE = ALL_TYPES.PROVENANCE$.MODULE$;
  public static final ALL_TYPES QUANTITY = ALL_TYPES.QUANTITY$.MODULE$;
  public static final ALL_TYPES QUESTIONNAIRE = ALL_TYPES.QUESTIONNAIRE$.MODULE$;
  public static final ALL_TYPES QUESTIONNAIRERESPONSE = ALL_TYPES.QUESTIONNAIRERESPONSE$.MODULE$;
  public static final ALL_TYPES RANGE = ALL_TYPES.RANGE$.MODULE$;
  public static final ALL_TYPES RATIO = ALL_TYPES.RATIO$.MODULE$;
  public static final ALL_TYPES REFERENCE = ALL_TYPES.REFERENCE$.MODULE$;
  public static final ALL_TYPES RELATEDARTIFACT = ALL_TYPES.RELATEDARTIFACT$.MODULE$;
  public static final ALL_TYPES RELATEDPERSON = ALL_TYPES.RELATEDPERSON$.MODULE$;
  public static final ALL_TYPES REQUESTGROUP = ALL_TYPES.REQUESTGROUP$.MODULE$;
  public static final ALL_TYPES RESEARCHDEFINITION = ALL_TYPES.RESEARCHDEFINITION$.MODULE$;
  public static final ALL_TYPES RESEARCHELEMENTDEFINITION =
      ALL_TYPES.RESEARCHELEMENTDEFINITION$.MODULE$;
  public static final ALL_TYPES RESEARCHSTUDY = ALL_TYPES.RESEARCHSTUDY$.MODULE$;
  public static final ALL_TYPES RESEARCHSUBJECT = ALL_TYPES.RESEARCHSUBJECT$.MODULE$;
  public static final ALL_TYPES RESOURCE = ALL_TYPES.RESOURCE$.MODULE$;
  public static final ALL_TYPES RISKASSESSMENT = ALL_TYPES.RISKASSESSMENT$.MODULE$;
  public static final ALL_TYPES RISKEVIDENCESYNTHESIS = ALL_TYPES.RISKEVIDENCESYNTHESIS$.MODULE$;
  public static final ALL_TYPES SAMPLEDDATA = ALL_TYPES.SAMPLEDDATA$.MODULE$;
  public static final ALL_TYPES SCHEDULE = ALL_TYPES.SCHEDULE$.MODULE$;
  public static final ALL_TYPES SEARCHPARAMETER = ALL_TYPES.SEARCHPARAMETER$.MODULE$;
  public static final ALL_TYPES SERVICEREQUEST = ALL_TYPES.SERVICEREQUEST$.MODULE$;
  public static final ALL_TYPES SIGNATURE = ALL_TYPES.SIGNATURE$.MODULE$;
  public static final ALL_TYPES SIMPLEQUANTITY = ALL_TYPES.SIMPLEQUANTITY$.MODULE$;
  public static final ALL_TYPES SLOT = ALL_TYPES.SLOT$.MODULE$;
  public static final ALL_TYPES SPECIMEN = ALL_TYPES.SPECIMEN$.MODULE$;
  public static final ALL_TYPES SPECIMENDEFINITION = ALL_TYPES.SPECIMENDEFINITION$.MODULE$;
  public static final ALL_TYPES STRING = ALL_TYPES.STRING$.MODULE$;
  public static final ALL_TYPES STRUCTUREDEFINITION = ALL_TYPES.STRUCTUREDEFINITION$.MODULE$;
  public static final ALL_TYPES STRUCTUREMAP = ALL_TYPES.STRUCTUREMAP$.MODULE$;
  public static final ALL_TYPES SUBSCRIPTION = ALL_TYPES.SUBSCRIPTION$.MODULE$;
  public static final ALL_TYPES SUBSTANCE = ALL_TYPES.SUBSTANCE$.MODULE$;
  public static final ALL_TYPES SUBSTANCEAMOUNT = ALL_TYPES.SUBSTANCEAMOUNT$.MODULE$;
  public static final ALL_TYPES SUBSTANCENUCLEICACID = ALL_TYPES.SUBSTANCENUCLEICACID$.MODULE$;
  public static final ALL_TYPES SUBSTANCEPOLYMER = ALL_TYPES.SUBSTANCEPOLYMER$.MODULE$;
  public static final ALL_TYPES SUBSTANCEPROTEIN = ALL_TYPES.SUBSTANCEPROTEIN$.MODULE$;
  public static final ALL_TYPES SUBSTANCEREFERENCEINFORMATION =
      ALL_TYPES.SUBSTANCEREFERENCEINFORMATION$.MODULE$;
  public static final ALL_TYPES SUBSTANCESOURCEMATERIAL =
      ALL_TYPES.SUBSTANCESOURCEMATERIAL$.MODULE$;
  public static final ALL_TYPES SUBSTANCESPECIFICATION = ALL_TYPES.SUBSTANCESPECIFICATION$.MODULE$;
  public static final ALL_TYPES SUPPLYDELIVERY = ALL_TYPES.SUPPLYDELIVERY$.MODULE$;
  public static final ALL_TYPES SUPPLYREQUEST = ALL_TYPES.SUPPLYREQUEST$.MODULE$;
  public static final ALL_TYPES TASK = ALL_TYPES.TASK$.MODULE$;
  public static final ALL_TYPES TERMINOLOGYCAPABILITIES =
      ALL_TYPES.TERMINOLOGYCAPABILITIES$.MODULE$;
  public static final ALL_TYPES TESTREPORT = ALL_TYPES.TESTREPORT$.MODULE$;
  public static final ALL_TYPES TESTSCRIPT = ALL_TYPES.TESTSCRIPT$.MODULE$;
  public static final ALL_TYPES TIME = ALL_TYPES.TIME$.MODULE$;
  public static final ALL_TYPES TIMING = ALL_TYPES.TIMING$.MODULE$;
  public static final ALL_TYPES TRIGGERDEFINITION = ALL_TYPES.TRIGGERDEFINITION$.MODULE$;
  public static final ALL_TYPES TYPE = ALL_TYPES.TYPE$.MODULE$;
  public static final ALL_TYPES UNSIGNEDINT = ALL_TYPES.UNSIGNEDINT$.MODULE$;
  public static final ALL_TYPES URI = ALL_TYPES.URI$.MODULE$;
  public static final ALL_TYPES URL = ALL_TYPES.URL$.MODULE$;
  public static final ALL_TYPES USAGECONTEXT = ALL_TYPES.USAGECONTEXT$.MODULE$;
  public static final ALL_TYPES UUID = ALL_TYPES.UUID$.MODULE$;
  public static final ALL_TYPES VALUESET = ALL_TYPES.VALUESET$.MODULE$;
  public static final ALL_TYPES VERIFICATIONRESULT = ALL_TYPES.VERIFICATIONRESULT$.MODULE$;
  public static final ALL_TYPES VISIONPRESCRIPTION = ALL_TYPES.VISIONPRESCRIPTION$.MODULE$;
  public static final ALL_TYPES XHTML = ALL_TYPES.XHTML$.MODULE$;
}
