package com.babylonhealth.lit.core_java.codes;

import com.babylonhealth.lit.core.LANGUAGES;

public interface Languages {
  public static final LANGUAGES AR = LANGUAGES.AR$.MODULE$;
  public static final LANGUAGES BN = LANGUAGES.BN$.MODULE$;
  public static final LANGUAGES CS = LANGUAGES.CS$.MODULE$;
  public static final LANGUAGES DA = LANGUAGES.DA$.MODULE$;
  public static final LANGUAGES DE = LANGUAGES.DE$.MODULE$;
  public static final LANGUAGES DE_AT = LANGUAGES.DE_AT$.MODULE$;
  public static final LANGUAGES DE_CH = LANGUAGES.DE_CH$.MODULE$;
  public static final LANGUAGES DE_DE = LANGUAGES.DE_DE$.MODULE$;
  public static final LANGUAGES EL = LANGUAGES.EL$.MODULE$;
  public static final LANGUAGES EN = LANGUAGES.EN$.MODULE$;
  public static final LANGUAGES EN_AU = LANGUAGES.EN_AU$.MODULE$;
  public static final LANGUAGES EN_CA = LANGUAGES.EN_CA$.MODULE$;
  public static final LANGUAGES EN_GB = LANGUAGES.EN_GB$.MODULE$;
  public static final LANGUAGES EN_IN = LANGUAGES.EN_IN$.MODULE$;
  public static final LANGUAGES EN_NZ = LANGUAGES.EN_NZ$.MODULE$;
  public static final LANGUAGES EN_SG = LANGUAGES.EN_SG$.MODULE$;
  public static final LANGUAGES EN_US = LANGUAGES.EN_US$.MODULE$;
  public static final LANGUAGES ES = LANGUAGES.ES$.MODULE$;
  public static final LANGUAGES ES_AR = LANGUAGES.ES_AR$.MODULE$;
  public static final LANGUAGES ES_ES = LANGUAGES.ES_ES$.MODULE$;
  public static final LANGUAGES ES_UY = LANGUAGES.ES_UY$.MODULE$;
  public static final LANGUAGES FI = LANGUAGES.FI$.MODULE$;
  public static final LANGUAGES FR = LANGUAGES.FR$.MODULE$;
  public static final LANGUAGES FR_BE = LANGUAGES.FR_BE$.MODULE$;
  public static final LANGUAGES FR_CH = LANGUAGES.FR_CH$.MODULE$;
  public static final LANGUAGES FR_FR = LANGUAGES.FR_FR$.MODULE$;
  public static final LANGUAGES FY = LANGUAGES.FY$.MODULE$;
  public static final LANGUAGES FY_NL = LANGUAGES.FY_NL$.MODULE$;
  public static final LANGUAGES HI = LANGUAGES.HI$.MODULE$;
  public static final LANGUAGES HR = LANGUAGES.HR$.MODULE$;
  public static final LANGUAGES IT = LANGUAGES.IT$.MODULE$;
  public static final LANGUAGES IT_CH = LANGUAGES.IT_CH$.MODULE$;
  public static final LANGUAGES IT_IT = LANGUAGES.IT_IT$.MODULE$;
  public static final LANGUAGES JA = LANGUAGES.JA$.MODULE$;
  public static final LANGUAGES KO = LANGUAGES.KO$.MODULE$;
  public static final LANGUAGES NL = LANGUAGES.NL$.MODULE$;
  public static final LANGUAGES NL_BE = LANGUAGES.NL_BE$.MODULE$;
  public static final LANGUAGES NL_NL = LANGUAGES.NL_NL$.MODULE$;
  public static final LANGUAGES NO = LANGUAGES.NO$.MODULE$;
  public static final LANGUAGES NO_NO = LANGUAGES.NO_NO$.MODULE$;
  public static final LANGUAGES PA = LANGUAGES.PA$.MODULE$;
  public static final LANGUAGES PL = LANGUAGES.PL$.MODULE$;
  public static final LANGUAGES PT = LANGUAGES.PT$.MODULE$;
  public static final LANGUAGES PT_BR = LANGUAGES.PT_BR$.MODULE$;
  public static final LANGUAGES RU = LANGUAGES.RU$.MODULE$;
  public static final LANGUAGES RU_RU = LANGUAGES.RU_RU$.MODULE$;
  public static final LANGUAGES SR = LANGUAGES.SR$.MODULE$;
  public static final LANGUAGES SR_RS = LANGUAGES.SR_RS$.MODULE$;
  public static final LANGUAGES SV = LANGUAGES.SV$.MODULE$;
  public static final LANGUAGES SV_SE = LANGUAGES.SV_SE$.MODULE$;
  public static final LANGUAGES TE = LANGUAGES.TE$.MODULE$;
  public static final LANGUAGES ZH = LANGUAGES.ZH$.MODULE$;
  public static final LANGUAGES ZH_CN = LANGUAGES.ZH_CN$.MODULE$;
  public static final LANGUAGES ZH_HK = LANGUAGES.ZH_HK$.MODULE$;
  public static final LANGUAGES ZH_SG = LANGUAGES.ZH_SG$.MODULE$;
  public static final LANGUAGES ZH_TW = LANGUAGES.ZH_TW$.MODULE$;
}
