package com.babylonhealth.lit.core_java.codes;

import com.babylonhealth.lit.core.RELATED_ARTIFACT_TYPE;

public interface RelatedArtifactType {
  public static final RELATED_ARTIFACT_TYPE CITATION = RELATED_ARTIFACT_TYPE.CITATION$.MODULE$;
  public static final RELATED_ARTIFACT_TYPE COMPOSED_OF =
      RELATED_ARTIFACT_TYPE.COMPOSED_OF$.MODULE$;
  public static final RELATED_ARTIFACT_TYPE DEPENDS_ON = RELATED_ARTIFACT_TYPE.DEPENDS_ON$.MODULE$;
  public static final RELATED_ARTIFACT_TYPE DERIVED_FROM =
      RELATED_ARTIFACT_TYPE.DERIVED_FROM$.MODULE$;
  public static final RELATED_ARTIFACT_TYPE DOCUMENTATION =
      RELATED_ARTIFACT_TYPE.DOCUMENTATION$.MODULE$;
  public static final RELATED_ARTIFACT_TYPE JUSTIFICATION =
      RELATED_ARTIFACT_TYPE.JUSTIFICATION$.MODULE$;
  public static final RELATED_ARTIFACT_TYPE PREDECESSOR =
      RELATED_ARTIFACT_TYPE.PREDECESSOR$.MODULE$;
  public static final RELATED_ARTIFACT_TYPE SUCCESSOR = RELATED_ARTIFACT_TYPE.SUCCESSOR$.MODULE$;
}
