name: Build and run tests

on:
  pull_request:
    branches: [ master ]

jobs:
  fetch-deps:
    name: Fetch dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Try restore deps cache
        run: echo TODO
      - name: Build Dependencies
        run: make download-deps
      - name: Store deps cache
        uses: actions/upload-artifact@v2
        with:
          name: dependencies
          path: ~/.cache/coursier
  build-modules:
    name: Build generated modules
    needs: fetch-deps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Restore deps cache
        uses: actions/download-artifact@v2
        with:
          name: dependencies
      - name: Try restore build cache
        run: echo TODO
      - name: Build Dependencies
        run: make compile
      - name: Make build cache
        run: find -name target -exec tar -zcf targets.tar.gz -H posix {} + && find -name target -exec rm -r {} +
      - name: Store build cache
        uses: actions/upload-artifact@v2
        with:
          name: buildtarget
          path: ~/project/targets.tar.gz
  test-modules:
    name: Test generated modules
    needs: build-modules
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Restore build cache
        uses: actions/download-artifact@v2
        with:
          name: buildtarget
      - name: Extract build cache
        run: tar --skip-old-files -xf targets.tar.gz
      - name: Try restore test cache
        run: echo TODO
      - name: Build Dependencies
        run: make test
      - name: Make test cache
        run: find -name target -exec tar -zcf test-targets.tar.gz -H posix {} + && find -name target -exec rm -r {} +
      - name: Store test cache
        uses: actions/upload-artifact@v2
        with:
          name: buildtarget
          path: ~/project/test-targets.tar.gz
