name: Build and run tests

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Fetch dependencies
        run: make download-deps
      - name: Compile
        run: make compile
      - name: Test
        run: make test
      - name: Make test cache
        run: find -name target -exec tar -zcf test-targets.tar.gz -H posix {} + && find -name target -exec rm -r {} +
      - name: Store test cache
        uses: actions/upload-artifact@v2
        with:
          name: buildtarget
          path: ~/project/test-targets.tar.gz
