name: Release snapshot

on:
  push:
#    branches: [master]
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
      - name: Fetch dependencies
        run: |
          GITHUB_TAG="${{steps.tag.outputs.tag}}"
          if [ "${GITHUB_TAG::1}" = g ]; then sbt +generator/update; else make download-deps; fi
      - name: Compile
        run: |
          GITHUB_TAG="${{steps.tag.outputs.tag}}"
          if [ "${GITHUB_TAG::1}" = g ]; then sbt +generator/compile; else make compile; fi
      - run: |
          GITHUB_TAG="${{steps.tag.outputs.tag}}"
          if [ "${GITHUB_TAG::1}" = g ]; then sbt generator/ci-release; else sbt ci-release; fi
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
